"""Emit tests/system/v8t_card.v: the multimesh_v8t block design as one Verilog
top for simulation -- the BD's own modules (ktpu_node_v8t x4, kx_pbd_4x4,
sb_bd_line4, xcvu13p_rst_tree) with the vendor IP replaced by the repo's
behavioural stand-ins (axi_ram for each DDR4, axil_ram for the two register
endpoints per die, axi_up32to64 for the width converter, kh_rst_sync for the
proc_sys_reset blocks) and the three host managers (JTAG 64-bit, XDMA 512-bit,
XDMA Lite) brought to the boundary for a harness to drive. Every clock of the
image is a port: the harness owns the fifteen domains at their real periods.

    python scripts/py/gen_v8t_card.py -o tests/system/v8t_card.v

The station map is v8t's (scripts/tcl/v8/50_addr_lit.tcl), computed here the
same way and emitted as the sized literals sb_bd_line4 takes.
"""

import argparse
from pathlib import Path

AW = 43
FULL = (1 << AW) - 1
NQ = 4
MESHES = 4
MESH_WIN = 1 << 40
CTRL_BASE, WIZ_BASE, DDR_WIN = 0x800000, 0x900000, 0x100000

# the Xache's 16 KB rotation: pairs (i, i+2) for i = 14..31, byte k of the
# 256-bit wrapper parameter is pair k
KX_ILV_LG, KX_HOME_LSB = 14, 32


def seg_tables():
    base, mask, xlt, dst, dprt = [], [], [], [], []
    for m in range(MESHES):
        base.append((m + 1) * MESH_WIN)
        mask.append(7 * MESH_WIN)
        xlt.append(0)
        dst.append(m)
        dprt.append(0)
        b = CTRL_BASE + m * 0x10000
        base.append(b)
        mask.append(FULL ^ 0xFFFF)
        xlt.append(b)
        dst.append(m)
        dprt.append(1)
        b = m * DDR_WIN
        base.append(b)
        mask.append(FULL ^ 0xFFFFF)
        xlt.append(b)
        dst.append(m)
        dprt.append(2)
        b = WIZ_BASE + m * 0x10000
        base.append(b)
        mask.append(FULL ^ 0xFFFF)
        xlt.append(b)
        dst.append(m)
        dprt.append(3)
    return base, mask, xlt, dst, dprt


def cat(vals, width):
    """Segment k at bits [k*width +: width], as v8_cat packs it."""
    v = 0
    for k, x in enumerate(vals):
        v |= (x & ((1 << width) - 1)) << (k * width)
    n = len(vals) * width
    return f"{n}'h{v:0{(n + 3) // 4}x}"


def swap_literal(offset):
    v = 0
    for k in range(KX_HOME_LSB - KX_ILV_LG):
        v |= (KX_ILV_LG + offset + k) << (8 * k)
    return f"256'h{v:064x}"


# (name, width, direction from the STATION's point of view for an M port)
AXI4_FULL = [
    ("awid", "IDW", "o"),
    ("awaddr", 43, "o"),
    ("awlen", 8, "o"),
    ("awsize", 3, "o"),
    ("awburst", 2, "o"),
    ("awvalid", 1, "o"),
    ("awready", 1, "i"),
    ("wdata", "DW", "o"),
    ("wstrb", "SW", "o"),
    ("wlast", 1, "o"),
    ("wvalid", 1, "o"),
    ("wready", 1, "i"),
    ("bid", "IDW", "i"),
    ("bresp", 2, "i"),
    ("bvalid", 1, "i"),
    ("bready", 1, "o"),
    ("arid", "IDW", "o"),
    ("araddr", 43, "o"),
    ("arlen", 8, "o"),
    ("arsize", 3, "o"),
    ("arburst", 2, "o"),
    ("arvalid", 1, "o"),
    ("arready", 1, "i"),
    ("rid", "IDW", "i"),
    ("rdata", "DW", "i"),
    ("rresp", 2, "i"),
    ("rlast", 1, "i"),
    ("rvalid", 1, "i"),
    ("rready", 1, "o"),
]
AXI_LITE = [
    ("awaddr", 43, "o"),
    ("awvalid", 1, "o"),
    ("awready", 1, "i"),
    ("wdata", 32, "o"),
    ("wstrb", 4, "o"),
    ("wvalid", 1, "o"),
    ("wready", 1, "i"),
    ("bresp", 2, "i"),
    ("bvalid", 1, "i"),
    ("bready", 1, "o"),
    ("araddr", 43, "o"),
    ("arvalid", 1, "o"),
    ("arready", 1, "i"),
    ("rdata", 32, "i"),
    ("rresp", 2, "i"),
    ("rvalid", 1, "i"),
    ("rready", 1, "o"),
]


def w(width, dw, idw):
    if width == "DW":
        return dw
    if width == "SW":
        return dw // 8
    if width == "IDW":
        return idw
    return width


def port_decl(prefix, fields, dw, idw, master_is_host):
    """Top-level ports for one host manager: the host DRIVES the station's S
    side, so an 'o' field of the station's M list is an INPUT here."""
    out = []
    for name, width, d in fields:
        n = w(width, dw, idw)
        dirn = "input " if (d == "o") == master_is_host else "output"
        vec = f"[{n - 1}:0] " if n > 1 else ""
        out.append(f"    {dirn} wire {vec}{prefix}_{name},")
    return out


def wire_decl(prefix, fields, dw, idw):
    out = []
    for name, width, _ in fields:
        n = w(width, dw, idw)
        vec = f"[{n - 1}:0] " if n > 1 else ""
        out.append(f"    wire {vec}{prefix}_{name};")
    return out


def conn(port_prefix, sig_prefix, fields):
    return [f".{port_prefix}_{name}({sig_prefix}_{name})" for name, _, _ in fields]


def emit(banks_default=8, dram_words=1 << 16):
    base, mask, xlt, dst, dprt = seg_tables()
    L = []
    L += [
        "// v8t_card -- GENERATED by scripts/py/gen_v8t_card.py. Do not edit by hand.",
        "//",
        "// multimesh_v8t as one simulation top: the block design's own modules with",
        "// the vendor IP replaced by behavioural stand-ins and the three host managers",
        "// at the boundary. Fifteen clocks are ports; the harness runs each at its",
        "// period. One asynchronous reset in; every domain releases it on its own",
        "// clock through kh_rst_sync, the sysnode copies through xcvu13p_rst_tree.",
        "",
        "`default_nettype none",
        "",
        "module v8t_card #(",
        f"    parameter integer BANKS      = {banks_default},   // kx_carray banks: 1 = v8t, 8 = v8t2",
        f"    parameter integer DRAM_WORDS = {dram_words},      // 512-bit words modelled per channel",
        "    parameter integer WIZ_LOCKED = 1",
        ")(",
        "    input  wire clk_ctrl,    // 100 MHz: JTAG manager, station port 3, the wizards' Lite",
        "    input  wire clk_xdma,    // 250 MHz: the XDMA managers",
        "    input  wire clk_sys,     // 300 MHz: every node, the Xache, station ports 0/1, the converters",
        "    input  wire bus_clk0, input wire bus_clk1, input wire bus_clk2, input wire bus_clk3,   // 200 MHz per die",
        "    input  wire clk_ddr0, input wire clk_ddr1, input wire clk_ddr2, input wire clk_ddr3,   // MIG ui per die",
        "    input  wire rstn,",
        "",
        "    // host manager 0: the JTAG-to-AXI master, 64-bit, on clk_ctrl",
    ]
    L += port_decl("h0", AXI4_FULL, 64, 4, True)
    L += ["", "    // host manager 1: XDMA M_AXI, 512-bit, on clk_xdma"]
    L += port_decl("h1", AXI4_FULL, 512, 4, True)
    L += ["", "    // host manager 2: XDMA M_AXI_LITE, 32-bit, on clk_xdma"]
    L += port_decl("h2", AXI_LITE, 32, 4, True)
    L += [
        "",
        "    // DRAM backdoors, one per channel (channel c = the MIG behind home c)",
        "    input  wire [3:0]      bd_we,",
        "    input  wire [4*16-1:0] bd_addr,",
        "    input  wire [4*512-1:0] bd_wdata,",
        "    output wire [4*512-1:0] bd_rdata,",
        "",
        "    output wire [31:0]     stat_decerr,",
        "    output wire [3:0]      d_rstn_o     // the four sysnode reset copies, for the harness to wait on",
        ");",
        "",
        "    // ---- resets: one per clock, released on that clock ----------------",
        "    wire rstn_ctrl, rstn_xdma, rstn_sys;",
        "    wire [3:0] rstn_bus, rstn_ddr, d_rstn;",
        "    kh_rst_sync u_rs_ctrl (.clk(clk_ctrl), .arstn(rstn), .rstn(rstn_ctrl));",
        "    kh_rst_sync u_rs_xdma (.clk(clk_xdma), .arstn(rstn), .rstn(rstn_xdma));",
        "    kh_rst_sync u_rs_sys  (.clk(clk_sys),  .arstn(rstn), .rstn(rstn_sys));",
        "    xcvu13p_rst_tree u_tree (.clk(clk_sys), .rstn_in(rstn_sys),",
        "        .rstn_o0(d_rstn[0]), .rstn_o1(d_rstn[1]), .rstn_o2(d_rstn[2]), .rstn_o3(d_rstn[3]));",
        "    assign d_rstn_o = d_rstn;",
        "    wire [3:0] bus_clk = {bus_clk3, bus_clk2, bus_clk1, bus_clk0};",
        "    wire [3:0] clk_ddr = {clk_ddr3, clk_ddr2, clk_ddr1, clk_ddr0};",
        "    genvar gi;",
        "    generate for (gi = 0; gi < 4; gi = gi + 1) begin : g_rs",
        "        kh_rst_sync u_rs_bus (.clk(bus_clk[gi]), .arstn(rstn), .rstn(rstn_bus[gi]));",
        "        kh_rst_sync u_rs_ddr (.clk(clk_ddr[gi]), .arstn(rstn), .rstn(rstn_ddr[gi]));",
        "    end endgenerate",
        "",
        "    // ---- the station map, as 50_addr_lit.tcl builds it -----------------",
        f"    localparam [16*43-1:0] SEG_BASE  = {cat(base, AW)};",
        f"    localparam [16*43-1:0] SEG_MASK  = {cat(mask, AW)};",
        f"    localparam [16*43-1:0] SEG_XLT   = {cat(xlt, AW)};",
        f"    localparam [16*2-1:0]  SEG_DST   = {cat(dst, 2)};",
        f"    localparam [16*2-1:0]  SEG_DPORT = {cat(dprt, 2)};",
        "",
        "    // ---- station endpoints: 16 ports, 4 per die -------------------------",
    ]
    for m in range(MESHES):
        for q in range(NQ):
            k = m * NQ + q
            p = f"M{k:02d}"
            if q == 0:
                L += wire_decl(p, AXI4_FULL, 256, 4)
            elif q == 1:
                L += wire_decl(p, AXI4_FULL, 32, 4)
            else:
                L += wire_decl(p, AXI_LITE, 32, 4)
    L += [
        "",
        "    sb_bd_line4 #(.FW(256), .OST(4), .STORE_FWD(1), .LUT_PER_BRAM(0), .TIMEOUT(0),",
        "                  .LINK_CDC(1), .LINK_FULL(0), .CRED(16), .PIPE(4),",
        "                  .SEG_OVERRIDE(1), .SEG_BASE_P(SEG_BASE), .SEG_MASK_P(SEG_MASK),",
        "                  .SEG_XLT_P(SEG_XLT), .SEG_DST_P(SEG_DST), .SEG_DPORT_P(SEG_DPORT),",
        "                  .SEG_VLD_P(16'hFFFF)) u_bus (",
        "        .bus_clk0(bus_clk[0]), .bus_rst0(!rstn_bus[0]), .bus_clk1(bus_clk[1]), .bus_rst1(!rstn_bus[1]),",
        "        .bus_clk2(bus_clk[2]), .bus_rst2(!rstn_bus[2]), .bus_clk3(bus_clk[3]), .bus_rst3(!rstn_bus[3]),",
        "        .clk_ctrl(clk_ctrl), .aresetn_ctrl(rstn_ctrl), .clk_xdma(clk_xdma), .aresetn_xdma(rstn_xdma),",
        "        .clk_s0(clk_sys), .aresetn_s0(d_rstn[0]), .clk_s1(clk_sys), .aresetn_s1(d_rstn[1]),",
        "        .clk_s2(clk_sys), .aresetn_s2(d_rstn[2]), .clk_s3(clk_sys), .aresetn_s3(d_rstn[3]),",
        "        .clk_ddr0(clk_ddr[0]), .aresetn_ddr0(rstn_ddr[0]), .clk_ddr1(clk_ddr[1]), .aresetn_ddr1(rstn_ddr[1]),",
        "        .clk_ddr2(clk_ddr[2]), .aresetn_ddr2(rstn_ddr[2]), .clk_ddr3(clk_ddr[3]), .aresetn_ddr3(rstn_ddr[3]),",
    ]
    c = []
    c += conn("S00_AXI", "h0", AXI4_FULL)
    c += conn("S01_AXI", "h1", AXI4_FULL)
    c += conn("S02_AXI", "h2", AXI_LITE)
    for m in range(MESHES):
        for q in range(NQ):
            k = m * NQ + q
            c += conn(f"M{k:02d}_AXI", f"M{k:02d}", AXI4_FULL if q < 2 else AXI_LITE)
    c.append(".stat_decerr(stat_decerr)")
    for i in range(0, len(c), 4):
        L.append("        " + ", ".join(c[i : i + 4]) + ("," if i + 4 < len(c) else ""))
    L += ["    );", ""]

    # ---- per die: node, converter, two Lite RAMs, DRAM
    L += [
        "    // ---- per die: node, control converter, register stand-ins, DRAM -----"
    ]
    for m in range(MESHES):
        p0, p1, p2, p3 = (f"M{m * NQ + q:02d}" for q in range(NQ))
        L += [
            f"    // die {m}",
            f"    wire [3:0]  c{m}_awid, c{m}_arid, c{m}_bid, c{m}_rid;",
            f"    wire [31:0] c{m}_awaddr, c{m}_araddr;",
            f"    wire [7:0]  c{m}_awlen, c{m}_arlen;",
            f"    wire [2:0]  c{m}_awsize, c{m}_arsize;",
            f"    wire [1:0]  c{m}_awburst, c{m}_arburst, c{m}_bresp, c{m}_rresp;",
            f"    wire        c{m}_awvalid, c{m}_awready, c{m}_wvalid, c{m}_wready, c{m}_wlast;",
            f"    wire        c{m}_bvalid, c{m}_bready, c{m}_arvalid, c{m}_arready, c{m}_rvalid, c{m}_rready, c{m}_rlast;",
            f"    wire [63:0] c{m}_wdata, c{m}_rdata;",
            f"    wire [7:0]  c{m}_wstrb;",
            "    // the BD's axi_dwidth_converter SI 32 -> MI 64 on the sysnode clock; the",
            "    // low 32 address bits reach the node exactly as the IP's M_AXI carries them",
            f"    axi_up32to64 #(.AW(32), .IDW(4)) u_dwc{m} (",
            f"        .clk(clk_sys), .resetn(d_rstn[{m}]),",
            f"        .s_awid({p1}_awid), .s_awaddr({p1}_awaddr[31:0]), .s_awlen({p1}_awlen), .s_awsize({p1}_awsize),",
            f"        .s_awburst({p1}_awburst), .s_awvalid({p1}_awvalid), .s_awready({p1}_awready),",
            f"        .s_wdata({p1}_wdata), .s_wstrb({p1}_wstrb), .s_wlast({p1}_wlast), .s_wvalid({p1}_wvalid), .s_wready({p1}_wready),",
            f"        .s_bid({p1}_bid), .s_bresp({p1}_bresp), .s_bvalid({p1}_bvalid), .s_bready({p1}_bready),",
            f"        .s_arid({p1}_arid), .s_araddr({p1}_araddr[31:0]), .s_arlen({p1}_arlen), .s_arsize({p1}_arsize),",
            f"        .s_arburst({p1}_arburst), .s_arvalid({p1}_arvalid), .s_arready({p1}_arready),",
            f"        .s_rid({p1}_rid), .s_rdata({p1}_rdata), .s_rresp({p1}_rresp), .s_rlast({p1}_rlast), .s_rvalid({p1}_rvalid), .s_rready({p1}_rready),",
            f"        .m_awid(c{m}_awid), .m_awaddr(c{m}_awaddr), .m_awlen(c{m}_awlen), .m_awsize(c{m}_awsize), .m_awburst(c{m}_awburst),",
            f"        .m_awvalid(c{m}_awvalid), .m_awready(c{m}_awready),",
            f"        .m_wdata(c{m}_wdata), .m_wstrb(c{m}_wstrb), .m_wlast(c{m}_wlast), .m_wvalid(c{m}_wvalid), .m_wready(c{m}_wready),",
            f"        .m_bid(c{m}_bid), .m_bresp(c{m}_bresp), .m_bvalid(c{m}_bvalid), .m_bready(c{m}_bready),",
            f"        .m_arid(c{m}_arid), .m_araddr(c{m}_araddr), .m_arlen(c{m}_arlen), .m_arsize(c{m}_arsize), .m_arburst(c{m}_arburst),",
            f"        .m_arvalid(c{m}_arvalid), .m_arready(c{m}_arready),",
            f"        .m_rid(c{m}_rid), .m_rdata(c{m}_rdata), .m_rresp(c{m}_rresp), .m_rlast(c{m}_rlast), .m_rvalid(c{m}_rvalid), .m_rready(c{m}_rready));",
            "",
            f"    wire [3:0]   x{m}_awid, x{m}_arid, x{m}_bid, x{m}_rid;",
            f"    wire [39:0]  x{m}_awaddr, x{m}_araddr;",
            f"    wire [7:0]   x{m}_awlen, x{m}_arlen;",
            f"    wire [2:0]   x{m}_awsize, x{m}_arsize;",
            f"    wire [1:0]   x{m}_awburst, x{m}_arburst, x{m}_bresp, x{m}_rresp;",
            f"    wire         x{m}_awvalid, x{m}_awready, x{m}_wvalid, x{m}_wready, x{m}_wlast;",
            f"    wire         x{m}_bvalid, x{m}_bready, x{m}_arvalid, x{m}_arready, x{m}_rvalid, x{m}_rready, x{m}_rlast;",
            f"    wire [511:0] x{m}_wdata, x{m}_rdata;",
            f"    wire [63:0]  x{m}_wstrb;",
            f"    ktpu_node_v8t #(.MESH_ID({m}), .PORTS(2), .L2_MAG_BANKS(4), .L2_MAG_ENTRIES(16384),",
            f"                   .DRAM_CDC(0)) u_node{m} (",
            f"        .axi_aclk(clk_sys), .axi_aresetn(d_rstn[{m}]), .dram_aclk(clk_sys), .dram_aresetn(d_rstn[{m}]),",
            f"        .S_AXI_MEM_awid({p0}_awid), .S_AXI_MEM_awaddr({p0}_awaddr[39:0]), .S_AXI_MEM_awlen({p0}_awlen),",
            f"        .S_AXI_MEM_awvalid({p0}_awvalid), .S_AXI_MEM_awready({p0}_awready),",
            f"        .S_AXI_MEM_wdata({p0}_wdata), .S_AXI_MEM_wstrb({p0}_wstrb), .S_AXI_MEM_wlast({p0}_wlast),",
            f"        .S_AXI_MEM_wvalid({p0}_wvalid), .S_AXI_MEM_wready({p0}_wready),",
            f"        .S_AXI_MEM_bid({p0}_bid), .S_AXI_MEM_bresp({p0}_bresp), .S_AXI_MEM_bvalid({p0}_bvalid), .S_AXI_MEM_bready({p0}_bready),",
            f"        .S_AXI_MEM_arid({p0}_arid), .S_AXI_MEM_araddr({p0}_araddr[39:0]), .S_AXI_MEM_arlen({p0}_arlen),",
            f"        .S_AXI_MEM_arvalid({p0}_arvalid), .S_AXI_MEM_arready({p0}_arready),",
            f"        .S_AXI_MEM_rid({p0}_rid), .S_AXI_MEM_rdata({p0}_rdata), .S_AXI_MEM_rresp({p0}_rresp), .S_AXI_MEM_rlast({p0}_rlast),",
            f"        .S_AXI_MEM_rvalid({p0}_rvalid), .S_AXI_MEM_rready({p0}_rready),",
            f"        .S_AXI_CTRL_awid(c{m}_awid), .S_AXI_CTRL_awaddr(c{m}_awaddr), .S_AXI_CTRL_awlen(c{m}_awlen),",
            f"        .S_AXI_CTRL_awvalid(c{m}_awvalid), .S_AXI_CTRL_awready(c{m}_awready),",
            f"        .S_AXI_CTRL_wdata(c{m}_wdata), .S_AXI_CTRL_wstrb(c{m}_wstrb), .S_AXI_CTRL_wlast(c{m}_wlast),",
            f"        .S_AXI_CTRL_wvalid(c{m}_wvalid), .S_AXI_CTRL_wready(c{m}_wready),",
            f"        .S_AXI_CTRL_bid(c{m}_bid), .S_AXI_CTRL_bresp(c{m}_bresp), .S_AXI_CTRL_bvalid(c{m}_bvalid), .S_AXI_CTRL_bready(c{m}_bready),",
            f"        .S_AXI_CTRL_arid(c{m}_arid), .S_AXI_CTRL_araddr(c{m}_araddr), .S_AXI_CTRL_arlen(c{m}_arlen),",
            f"        .S_AXI_CTRL_arvalid(c{m}_arvalid), .S_AXI_CTRL_arready(c{m}_arready),",
            f"        .S_AXI_CTRL_rid(c{m}_rid), .S_AXI_CTRL_rdata(c{m}_rdata), .S_AXI_CTRL_rresp(c{m}_rresp), .S_AXI_CTRL_rlast(c{m}_rlast),",
            f"        .S_AXI_CTRL_rvalid(c{m}_rvalid), .S_AXI_CTRL_rready(c{m}_rready),",
            f"        .M_AXI_DRAM_awid(x{m}_awid), .M_AXI_DRAM_awaddr(x{m}_awaddr), .M_AXI_DRAM_awlen(x{m}_awlen),",
            f"        .M_AXI_DRAM_awsize(x{m}_awsize), .M_AXI_DRAM_awburst(x{m}_awburst),",
            f"        .M_AXI_DRAM_awvalid(x{m}_awvalid), .M_AXI_DRAM_awready(x{m}_awready),",
            f"        .M_AXI_DRAM_wdata(x{m}_wdata), .M_AXI_DRAM_wstrb(x{m}_wstrb), .M_AXI_DRAM_wlast(x{m}_wlast),",
            f"        .M_AXI_DRAM_wvalid(x{m}_wvalid), .M_AXI_DRAM_wready(x{m}_wready),",
            f"        .M_AXI_DRAM_bid(x{m}_bid), .M_AXI_DRAM_bresp(x{m}_bresp), .M_AXI_DRAM_bvalid(x{m}_bvalid), .M_AXI_DRAM_bready(x{m}_bready),",
            f"        .M_AXI_DRAM_arid(x{m}_arid), .M_AXI_DRAM_araddr(x{m}_araddr), .M_AXI_DRAM_arlen(x{m}_arlen),",
            f"        .M_AXI_DRAM_arsize(x{m}_arsize), .M_AXI_DRAM_arburst(x{m}_arburst),",
            f"        .M_AXI_DRAM_arvalid(x{m}_arvalid), .M_AXI_DRAM_arready(x{m}_arready),",
            f"        .M_AXI_DRAM_rid(x{m}_rid), .M_AXI_DRAM_rdata(x{m}_rdata), .M_AXI_DRAM_rresp(x{m}_rresp), .M_AXI_DRAM_rlast(x{m}_rlast),",
            f"        .M_AXI_DRAM_rvalid(x{m}_rvalid), .M_AXI_DRAM_rready(x{m}_rready));",
            "",
            "    // port 2: the DDR4 controller's register window; port 3: the die's clock",
            "    // wizard, STATUS = LOCKED so the driver's load() returns on its first poll",
            f"    axil_ram #(.AW(43), .WORDS(256)) u_ddrctl{m} (.clk(clk_ddr[{m}]), .resetn(rstn_ddr[{m}]),",
            f"        .s_awaddr({p2}_awaddr), .s_awvalid({p2}_awvalid), .s_awready({p2}_awready),",
            f"        .s_wdata({p2}_wdata), .s_wstrb({p2}_wstrb), .s_wvalid({p2}_wvalid), .s_wready({p2}_wready),",
            f"        .s_bresp({p2}_bresp), .s_bvalid({p2}_bvalid), .s_bready({p2}_bready),",
            f"        .s_araddr({p2}_araddr), .s_arvalid({p2}_arvalid), .s_arready({p2}_arready),",
            f"        .s_rdata({p2}_rdata), .s_rresp({p2}_rresp), .s_rvalid({p2}_rvalid), .s_rready({p2}_rready));",
            f"    axil_ram #(.AW(43), .WORDS(256), .INIT_IDX(1), .INIT_VAL(WIZ_LOCKED)) u_wiz{m} (.clk(clk_ctrl), .resetn(rstn_ctrl),",
            f"        .s_awaddr({p3}_awaddr), .s_awvalid({p3}_awvalid), .s_awready({p3}_awready),",
            f"        .s_wdata({p3}_wdata), .s_wstrb({p3}_wstrb), .s_wvalid({p3}_wvalid), .s_wready({p3}_wready),",
            f"        .s_bresp({p3}_bresp), .s_bvalid({p3}_bvalid), .s_bready({p3}_bready),",
            f"        .s_araddr({p3}_araddr), .s_arvalid({p3}_arvalid), .s_arready({p3}_arready),",
            f"        .s_rdata({p3}_rdata), .s_rresp({p3}_rresp), .s_rvalid({p3}_rvalid), .s_rready({p3}_rready));",
            "",
        ]

    # ---- the Xache
    L += [
        "    // ---- the Xache: master m = node m, home h -> DRAM channel h on clk_ddr[h] ----",
        "    wire [4*6-1:0]   d_awid, d_arid, d_bid, d_rid;",
        "    wire [4*40-1:0]  d_awaddr, d_araddr;",
        "    wire [4*8-1:0]   d_awlen, d_arlen;",
        "    wire [4*3-1:0]   d_awsize, d_arsize;",
        "    wire [4*2-1:0]   d_awburst, d_arburst, d_bresp, d_rresp;",
        "    wire [3:0]       d_awvalid, d_awready, d_wvalid, d_wready, d_wlast;",
        "    wire [3:0]       d_bvalid, d_bready, d_arvalid, d_arready, d_rvalid, d_rready, d_rlast;",
        "    wire [4*512-1:0] d_wdata, d_rdata;",
        "    wire [4*64-1:0]  d_wstrb;",
        f"    localparam [255:0] SWAP_A = {swap_literal(0)};",
        f"    localparam [255:0] SWAP_B = {swap_literal(2)};",
        '    kx_pbd_4x4 #(.SETS(32768), .SET_W(15), .K(1), .RAM_STYLE("ultra"), .BANKS(BANKS),',
        "                 .CDC_DEPTH(16), .NSWAP(18), .SWAP_A(SWAP_A), .SWAP_B(SWAP_B),",
        '                 .RD_OUTQ(4), .WR_OUTQ(4), .HOP_DEPTH(16), .HOP_BUF("lean"), .HOP_RXREG(0)) u_xache (',
        "        .aclk(clk_sys), .d_rstn0(d_rstn[0]), .d_rstn1(d_rstn[1]), .d_rstn2(d_rstn[2]), .d_rstn3(d_rstn[3]),",
        "        .h_clk0(clk_ddr[0]), .h_rstn0(rstn_ddr[0]), .h_clk1(clk_ddr[1]), .h_rstn1(rstn_ddr[1]),",
        "        .h_clk2(clk_ddr[2]), .h_rstn2(rstn_ddr[2]), .h_clk3(clk_ddr[3]), .h_rstn3(rstn_ddr[3]),",
    ]
    sconn = []
    for m in range(MESHES):
        s = f"S{m:02d}_AXI"
        x = f"x{m}"
        sconn += [
            f".{s}_awid({x}_awid), .{s}_awaddr({x}_awaddr), .{s}_awlen({x}_awlen), .{s}_awsize({x}_awsize), .{s}_awburst({x}_awburst)",
            f".{s}_awvalid({x}_awvalid), .{s}_awready({x}_awready), .{s}_wdata({x}_wdata), .{s}_wstrb({x}_wstrb), .{s}_wlast({x}_wlast)",
            f".{s}_wvalid({x}_wvalid), .{s}_wready({x}_wready), .{s}_bid({x}_bid), .{s}_bresp({x}_bresp), .{s}_bvalid({x}_bvalid), .{s}_bready({x}_bready)",
            f".{s}_arid({x}_arid), .{s}_araddr({x}_araddr), .{s}_arlen({x}_arlen), .{s}_arsize({x}_arsize), .{s}_arburst({x}_arburst)",
            f".{s}_arvalid({x}_arvalid), .{s}_arready({x}_arready), .{s}_rid({x}_rid), .{s}_rdata({x}_rdata), .{s}_rresp({x}_rresp), .{s}_rlast({x}_rlast)",
            f".{s}_rvalid({x}_rvalid), .{s}_rready({x}_rready)",
        ]
    for h in range(MESHES):
        s = f"M{h:02d}_AXI"
        sconn += [
            f".{s}_awid(d_awid[{h}*6 +: 6]), .{s}_awaddr(d_awaddr[{h}*40 +: 40]), .{s}_awlen(d_awlen[{h}*8 +: 8]), .{s}_awsize(d_awsize[{h}*3 +: 3]), .{s}_awburst(d_awburst[{h}*2 +: 2])",
            f".{s}_awvalid(d_awvalid[{h}]), .{s}_awready(d_awready[{h}]), .{s}_wdata(d_wdata[{h}*512 +: 512]), .{s}_wstrb(d_wstrb[{h}*64 +: 64]), .{s}_wlast(d_wlast[{h}])",
            f".{s}_wvalid(d_wvalid[{h}]), .{s}_wready(d_wready[{h}]), .{s}_bid(d_bid[{h}*6 +: 6]), .{s}_bresp(d_bresp[{h}*2 +: 2]), .{s}_bvalid(d_bvalid[{h}]), .{s}_bready(d_bready[{h}])",
            f".{s}_arid(d_arid[{h}*6 +: 6]), .{s}_araddr(d_araddr[{h}*40 +: 40]), .{s}_arlen(d_arlen[{h}*8 +: 8]), .{s}_arsize(d_arsize[{h}*3 +: 3]), .{s}_arburst(d_arburst[{h}*2 +: 2])",
            f".{s}_arvalid(d_arvalid[{h}]), .{s}_arready(d_arready[{h}]), .{s}_rid(d_rid[{h}*6 +: 6]), .{s}_rdata(d_rdata[{h}*512 +: 512]), .{s}_rresp(d_rresp[{h}*2 +: 2]), .{s}_rlast(d_rlast[{h}])",
            f".{s}_rvalid(d_rvalid[{h}]), .{s}_rready(d_rready[{h}])",
        ]
    for i, line in enumerate(sconn):
        L.append("        " + line + ("," if i + 1 < len(sconn) else ""))
    L += ["    );", ""]

    L += [
        "    // ---- DRAM: one axi_ram per channel on that channel's ui clock -------",
        "    generate for (gi = 0; gi < 4; gi = gi + 1) begin : g_dram",
        "        axi_ram #(.DATA_W(512), .ADDR_W(40), .ID_W(6), .WORDS(DRAM_WORDS), .PORTS(1)) u_ram (",
        "            .clk(clk_ddr[gi]), .resetn(rstn_ddr[gi]),",
        "            .s_awid(d_awid[gi*6 +: 6]), .s_awaddr(d_awaddr[gi*40 +: 40]), .s_awlen(d_awlen[gi*8 +: 8]),",
        "            .s_awsize(d_awsize[gi*3 +: 3]), .s_awburst(d_awburst[gi*2 +: 2]),",
        "            .s_awvalid(d_awvalid[gi]), .s_awready(d_awready[gi]),",
        "            .s_wdata(d_wdata[gi*512 +: 512]), .s_wstrb(d_wstrb[gi*64 +: 64]), .s_wlast(d_wlast[gi]),",
        "            .s_wvalid(d_wvalid[gi]), .s_wready(d_wready[gi]),",
        "            .s_bid(d_bid[gi*6 +: 6]), .s_bresp(d_bresp[gi*2 +: 2]), .s_bvalid(d_bvalid[gi]), .s_bready(d_bready[gi]),",
        "            .s_arid(d_arid[gi*6 +: 6]), .s_araddr(d_araddr[gi*40 +: 40]), .s_arlen(d_arlen[gi*8 +: 8]),",
        "            .s_arsize(d_arsize[gi*3 +: 3]), .s_arburst(d_arburst[gi*2 +: 2]),",
        "            .s_arvalid(d_arvalid[gi]), .s_arready(d_arready[gi]),",
        "            .s_rid(d_rid[gi*6 +: 6]), .s_rdata(d_rdata[gi*512 +: 512]), .s_rresp(d_rresp[gi*2 +: 2]),",
        "            .s_rlast(d_rlast[gi]), .s_rvalid(d_rvalid[gi]), .s_rready(d_rready[gi]),",
        "            .bd_we(bd_we[gi]), .bd_addr(bd_addr[gi*16 +: 16]), .bd_wdata(bd_wdata[gi*512 +: 512]),",
        "            .bd_rdata(bd_rdata[gi*512 +: 512]));",
        "    end endgenerate",
        "endmodule",
        "",
        "`default_nettype wire",
        "",
    ]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default="tests/system/v8t_card.v")
    ap.add_argument("--banks", type=int, default=8)
    ap.add_argument("--dram-words", type=int, default=1 << 16)
    a = ap.parse_args()
    text = emit(a.banks, a.dram_words)
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text(text, encoding="utf-8")
    print(f"wrote {a.out}: {text.count(chr(10))} lines")


if __name__ == "__main__":
    main()
