#!/usr/bin/env python3
"""Emit the block-design wrapper around kx_xache (Kohaku Xache).

    python scripts/py/gen_kx_wrap.py --m 4 --n 4 -o xilinx-fpga/xcvu13p/bd/kx_bd_4x4.v

kx_xache carries its M masters and N homes as packed vectors, which a block
design sees as loose wires. Every named S<m>_AXI / M<h>_AXI port here becomes
one inferred AXI4 interface; the fabric clock/reset carry the master ports
(MCDC is forced 0 -- every master is on the fabric clock in this wrapper) and
each home's DRAM clock/reset carries its M<h>_AXI (HCDC forced all ones).

The DRAM-side address has its home field cleared, so a 4 GB channel sees its
own range at 0 whatever the home field selected.
"""

import argparse
from pathlib import Path

#: (signal, width or None, direction on a SLAVE port)
FIELDS = [
    ("awid", "ID", "i"),
    ("awaddr", "AW", "i"),
    ("awlen", "8", "i"),
    ("awsize", "3", "i"),
    ("awburst", "2", "i"),
    ("awvalid", None, "i"),
    ("awready", None, "o"),
    ("wdata", "W", "i"),
    ("wstrb", "W/8", "i"),
    ("wlast", None, "i"),
    ("wvalid", None, "i"),
    ("wready", None, "o"),
    ("bid", "ID", "o"),
    ("bresp", "2", "o"),
    ("bvalid", None, "o"),
    ("bready", None, "i"),
    ("arid", "ID", "i"),
    ("araddr", "AW", "i"),
    ("arlen", "8", "i"),
    ("arsize", "3", "i"),
    ("arburst", "2", "i"),
    ("arvalid", None, "i"),
    ("arready", None, "o"),
    ("rid", "ID", "o"),
    ("rdata", "W", "o"),
    ("rresp", "2", "o"),
    ("rlast", None, "o"),
    ("rvalid", None, "o"),
    ("rready", None, "i"),
]

#: kx_xache port name per AXI signal, on the master (s_) and DRAM (d_) side
KX = {
    "awid": "awid",
    "awaddr": "awaddr",
    "awlen": "awlen",
    "awsize": "awsize",
    "awburst": "awburst",
    "awvalid": "awvalid",
    "awready": "awready",
    "wdata": "wdata",
    "wstrb": "wstrb",
    "wlast": "wlast",
    "wvalid": "wvalid",
    "wready": "wready",
    "bid": "bid",
    "bresp": "bresp",
    "bvalid": "bvalid",
    "bready": "bready",
    "arid": "arid",
    "araddr": "araddr",
    "arlen": "arlen",
    "arsize": "arsize",
    "arburst": "arburst",
    "arvalid": "arvalid",
    "arready": "arready",
    "rid": "rid",
    "rdata": "rdata",
    "rresp": "rresp",
    "rlast": "rlast",
    "rvalid": "rvalid",
    "rready": "rready",
}


def width(expr, idw, aw, w):
    return eval(
        expr.replace("ID", str(idw))
        .replace("AW", str(aw))
        .replace("W/8", str(w // 8))
        .replace("W", str(w))
    )


def decls(prefix, mirror, idw, aw, w):
    out = []
    for sig, wd, d in FIELDS:
        kind = d if not mirror else ("o" if d == "i" else "i")
        word = "output wire" if kind == "o" else "input  wire"
        ws = f"[{width(wd, idw, aw, w)}-1:0] " if wd else ""
        out.append(f"    {word} {ws}{prefix}_{sig},")
    return "\n".join(out)


def glue(i, prefix, mirror, side, idw, aw, w, home_lsb, hidx_w):
    """Wire named port `prefix` into kx_xache's packed `side` (s_ or d_) at index i."""
    out = []
    for sig, wd, d in FIELDS:
        n = width(wd, idw, aw, w) if wd else 1
        kx = f"{side}{KX[sig]}"
        sl = f"[{i}*{n} +: {n}]" if wd else f"[{i}]"
        drives_kx = (d == "i") if not mirror else (d == "o")
        if drives_kx:
            out.append(f"    assign {kx}{sl} = {prefix}_{sig};")
        else:
            src = f"{kx}{sl}"
            if mirror and sig in ("awaddr", "araddr"):
                # the home field cleared: a 4 GB channel sees its range at 0
                hi, lo = home_lsb + hidx_w, home_lsb
                src = (
                    f"{{{kx}[{i}*{n} + {n} - 1 : {i}*{n} + {hi}], {hidx_w}'b0, "
                    f"{kx}[{i}*{n} + {lo} - 1 : {i}*{n}]}}"
                )
            out.append(f"    assign {prefix}_{sig} = {src};")
    return "\n".join(out)


def emit(m, n, w, aw, idw, home_lsb, pxache=False):
    """`pxache`: wrap kx_pxache instead -- P = n partitions, master i and home
    i in partition i (the die that holds node i and MIG i), a reset per
    partition, lanes of kx_hop across every boundary."""
    hidx_w = max(1, (n - 1).bit_length())
    midx_w = max(1, (m - 1).bit_length())
    didw = idw + midx_w
    mod = f"kx_pbd_{m}x{n}" if pxache else f"kx_bd_{m}x{n}"
    s_busif = ":".join(f"S{i:02d}_AXI" for i in range(m))
    lines = [
        f"// {mod} -- GENERATED by scripts/py/gen_kx_wrap.py. Do not edit by hand.",
        "//",
        f"// Kohaku Xache with {m} master ports and {n} homes named for a block design.",
        "// Every master is on the fabric clock (MCDC = 0); every home's DRAM side crosses",
        "// to its own clock (HCDC = 1). The DRAM-side address carries the home field cleared.",
        "",
        "`default_nettype none",
        "",
        f"module {mod} #(",
        "    parameter integer SETS      = 16384,",
        "    parameter integer SET_W     = 14,",
        "    parameter integer K         = 2,",
        '    parameter         RAM_STYLE = "ultra",',
        "    parameter integer BANKS     = 1,",
        "    parameter integer RSAMD     = 1,",
        "    parameter integer WSAMD     = 1,",
        "    parameter integer CDC_DEPTH = 16,",
        "    parameter integer NSWAP     = 0,",
        "    // IPI types a parameter from its default: a fixed width and a sized zero",
        "    // make these bit-strings (0b...); a width in NSWAP made them integers.",
        "    // Room for 32 pairs; pair k is byte k.",
        "    parameter [255:0] SWAP_A    = 256'h0,",
        "    parameter [255:0] SWAP_B    = 256'h0,",
    ]
    if pxache:
        lines += [
            "    parameter integer RD_OUTQ   = 4,",
            "    parameter integer WR_OUTQ   = 4,",
            "    parameter integer RB_BEATS  = 0,",
            "    parameter integer HOP_DEPTH = 16,",
            '    parameter         HOP_BUF   = "lean",',
            "    parameter integer HOP_RXREG = 0,",
            "    parameter integer BND_TRUNK  = 0,",
            "    parameter integer PCLK       = 0,",
            '    parameter         MEM_TRUNK  = "block",',
            '    parameter         MEM_RB     = "block",',
            '    parameter         MEM_HRD    = "block",',
            '    parameter         MEM_HWR    = "block",',
            "    parameter integer TRUNK_SLOT = 0",
        ]
    else:
        lines += [
            "    parameter integer RD_PIPE   = 1,",
            "    parameter integer RD_OUTQ   = 4,",
            "    parameter integer SLRX      = 1",
        ]
    # A master port rides its partition's clock, so under pxache the slave
    # interfaces belong to p_clk<i> and there is no aclk left to own anything.
    # IPI gives a clock pin with no ASSOCIATED_BUSIF EVERY interface in the
    # module, which collides with each h_clk and fails validation (BD 41-1732).
    lines += [")("]
    if not pxache:
        lines += [
            '    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 aclk CLK" *)',
            (
                f'    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF {s_busif},'
                f' ASSOCIATED_RESET d_rstn0" *)'
            ),
            "    input  wire aclk,",
        ]
    # One reset per die, all on aclk: die i's copy resets home slice i and
    # master slice i (the die that owns MIG i and node i). This wrapper is the
    # only place where a die meets a slice; the fabric knows slices only.
    assert m == n, "per-die resets assume master i and home i share die i"
    for i in range(n):
        lines += [
            f'    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 d_rstn{i} RST" *)',
            '    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)',
            f"    input  wire d_rstn{i},",
        ]
    # Partition i's fabric clock: aclk at PCLK 0, die i's own clock at PCLK 1
    # (where every boundary trunk is then the crossing).
    if pxache:
        for i in range(n):
            lines += [
                f'    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 p_clk{i} CLK" *)',
                (
                    f'    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S{i:02d}_AXI,'
                    f' ASSOCIATED_RESET d_rstn{i}" *)'
                ),
                f"    input  wire p_clk{i},",
            ]
    for h in range(n):
        lines += [
            f'    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 h_clk{h} CLK" *)',
            f'    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M{h:02d}_AXI, ASSOCIATED_RESET h_rstn{h}" *)',
            f"    input  wire h_clk{h},",
            f'    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 h_rstn{h} RST" *)',
            '    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)',
            f"    input  wire h_rstn{h},",
        ]
    lines.append("")
    for i in range(m):
        lines.append(decls(f"S{i:02d}_AXI", False, idw, aw, w))
        lines.append("")
    for h in range(n):
        lines.append(decls(f"M{h:02d}_AXI", True, didw, aw, w))
        lines.append("")
    # drop the trailing comma of the last port
    last = lines[-2].rstrip(",")
    lines[-2] = last
    lines += [
        ");",
        f"    localparam integer M = {m}, N = {n}, W = {w}, AW = {aw}, ID_W = {idw}, IDW = {didw};",
        f"    localparam integer HOME_LSB = {home_lsb}, HIDX_W = {hidx_w};",
        "",
        "    wire [M*ID_W-1:0] s_awid, s_arid, s_bid, s_rid;",
        "    wire [M*AW-1:0]   s_awaddr, s_araddr;",
        "    wire [M*8-1:0]    s_awlen, s_arlen;",
        "    wire [M*3-1:0]    s_awsize, s_arsize;",
        "    wire [M*2-1:0]    s_awburst, s_arburst, s_bresp, s_rresp;",
        "    wire [M-1:0]      s_awvalid, s_awready, s_wvalid, s_wready, s_wlast;",
        "    wire [M-1:0]      s_bvalid, s_bready, s_arvalid, s_arready, s_rvalid, s_rready, s_rlast;",
        "    wire [M*W-1:0]    s_wdata, s_rdata;",
        "    wire [M*W/8-1:0]  s_wstrb;",
        "    wire [N*IDW-1:0]  d_awid, d_arid, d_bid, d_rid;",
        "    wire [N*AW-1:0]   d_awaddr, d_araddr;",
        "    wire [N*8-1:0]    d_awlen, d_arlen;",
        "    wire [N*3-1:0]    d_awsize, d_arsize;",
        "    wire [N*2-1:0]    d_awburst, d_arburst, d_bresp, d_rresp;",
        "    wire [N-1:0]      d_awvalid, d_awready, d_wvalid, d_wready, d_wlast;",
        "    wire [N-1:0]      d_bvalid, d_bready, d_arvalid, d_arready, d_rvalid, d_rready, d_rlast;",
        "    wire [N*W-1:0]    d_wdata, d_rdata;",
        "    wire [N*W/8-1:0]  d_wstrb;",
        "",
    ]
    for i in range(m):
        lines.append(
            glue(i, f"S{i:02d}_AXI", False, "s_", idw, aw, w, home_lsb, hidx_w)
        )
        lines.append("")
    for h in range(n):
        lines.append(
            glue(h, f"M{h:02d}_AXI", True, "d_", didw, aw, w, home_lsb, hidx_w)
        )
        lines.append("")
    hclk = ", ".join(f"h_clk{h}" for h in reversed(range(n)))
    hrst = ", ".join(f"h_rstn{h}" for h in reversed(range(n)))
    drst = ", ".join(f"d_rstn{i}" for i in reversed(range(n)))
    pclk = ", ".join(f"p_clk{i}" for i in reversed(range(n)))
    if pxache:
        pw = max(1, (n - 1).bit_length())
        ident = ", ".join(f"{pw}'d{i}" for i in reversed(range(n)))
        lines += [
            f"    localparam integer P = N, PW = {pw};",
            "    // partition i = die i: master i (node i) and home i (MIG i) sit there",
            f"    localparam [M*PW-1:0] MP = {{{ident}}};",
            f"    localparam [N*PW-1:0] HP = {{{ident}}};",
            "    kx_pxache #(.P(P), .M(M), .N_HOME(N), .PW(PW), .MP(MP), .HP(HP),",
            "                .AW(AW), .W(W), .ID_W(ID_W), .HOME_LSB(HOME_LSB),",
            "                .SETS(SETS), .SET_W(SET_W), .K(K), .RAM_STYLE(RAM_STYLE), .BANKS(BANKS),",
            "                .MCDC({M{1'b0}}), .HCDC({N{1'b1}}),",
            "                .CDC_DEPTH(CDC_DEPTH), .NSWAP(NSWAP),",
            "                .SWAP_A(SWAP_A[((NSWAP < 1) ? 1 : NSWAP)*8-1:0]),",
            "                .SWAP_B(SWAP_B[((NSWAP < 1) ? 1 : NSWAP)*8-1:0]),",
            "                .RD_OUTQ(RD_OUTQ), .WR_OUTQ(WR_OUTQ), .RB_BEATS(RB_BEATS),",
            "                .HOP_DEPTH(HOP_DEPTH),",
            "                .HOP_BUF(HOP_BUF), .HOP_RXREG(HOP_RXREG),",
            "                .BND_TRUNK(BND_TRUNK), .TRUNK_SLOT(TRUNK_SLOT),",
            "                .MEM_TRUNK(MEM_TRUNK), .MEM_RB(MEM_RB),",
            "                .MEM_HRD(MEM_HRD), .MEM_HWR(MEM_HWR),",
            "                .PCLK(PCLK)) u_kx (",
            f"        .clk(p_clk0), .clk_p({{{pclk}}}), .rstn_p({{{drst}}}),",
            f"        .m_clk({{{pclk}}}), .m_rstn({{{drst}}}),",
            f"        .h_clk({{{hclk}}}), .h_rstn({{{hrst}}}),",
        ]
    else:
        lines += [
            "    kx_xache #(.M(M), .N_HOME(N), .AW(AW), .W(W), .ID_W(ID_W), .HOME_LSB(HOME_LSB),",
            "               .SETS(SETS), .SET_W(SET_W), .K(K), .RAM_STYLE(RAM_STYLE), .BANKS(BANKS),",
            "               .MCDC({M{1'b0}}), .HCDC({N{1'b1}}), .RSAMD(RSAMD), .WSAMD(WSAMD),",
            "               .CDC_DEPTH(CDC_DEPTH), .NSWAP(NSWAP),",
            "               .SWAP_A(SWAP_A[((NSWAP < 1) ? 1 : NSWAP)*8-1:0]),",
            "               .SWAP_B(SWAP_B[((NSWAP < 1) ? 1 : NSWAP)*8-1:0]),",
            "               .RD_PIPE(RD_PIPE), .RD_OUTQ(RD_OUTQ), .SLRX(SLRX)) u_kx (",
            f"        .clk(aclk), .rstn_h({{{drst}}}), .rstn_m({{{drst}}}),",
            f"        .m_clk({{M{{aclk}}}}), .m_rstn({{{drst}}}),",
            f"        .h_clk({{{hclk}}}), .h_rstn({{{hrst}}}),",
        ]
    conn = []
    for side, sigs in (
        ("s_", [f for f, _, _ in FIELDS]),
        ("d_", [f for f, _, _ in FIELDS]),
    ):
        for sig in sigs:
            conn.append(f".{side}{KX[sig]}({side}{KX[sig]})")
    for k in range(0, len(conn), 5):
        lines.append(
            "        " + ", ".join(conn[k : k + 5]) + ("," if k + 5 < len(conn) else "")
        )
    lines += ["    );", "endmodule", "", "`default_nettype wire", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--m", type=int, default=4)
    ap.add_argument("--n", type=int, default=4)
    ap.add_argument("--w", type=int, default=512)
    ap.add_argument("--aw", type=int, default=40)
    ap.add_argument("--idw", type=int, default=4)
    ap.add_argument("--home-lsb", type=int, default=32)
    ap.add_argument(
        "--pxache",
        action="store_true",
        help="wrap kx_pxache (kx_pbd_MxN): a partition per die, lanes of hops",
    )
    ap.add_argument("-o", "--out")
    a = ap.parse_args()
    text = emit(a.m, a.n, a.w, a.aw, a.idw, a.home_lsb, pxache=a.pxache)
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")
    else:
        print(text)


if __name__ == "__main__":
    main()
