# Floorplan, clock groups and board pins, written out as XDC. Nothing here can
# check itself: XDC rejects `if`, so every assertion lives in 70_analyze.tcl.

file mkdir $root/build
set top ${design_name}_i

# ---- board pins ----------------------------------------------------------
proc v8_board {name} {
    global BOARD_DIR
    if {![file exists $BOARD_DIR/$name]} { error "missing board XDC: $BOARD_DIR/$name" }
    return $BOARD_DIR/$name
}
# import_files COPIES into the project, so a rebuild adds a SECOND copy of each
# board file every time unless the one already there is found first.
proc v8_import {name} {
    if {[llength [get_files -quiet -of_objects [get_filesets constrs_1] *$name]]} {
        return
    }
    import_files -fileset constrs_1 -norecurse [v8_board $name]
}
foreach i {0 1 2 3} { v8_import ddr4_c${i}.xdc }
v8_import pcie.xdc

# ---- pblocks -------------------------------------------------------------
# Every line has ONE shape, `add_cells_to_pblock [get_pblocks PB] [get_cells
# -quiet ARGS]`, and 70_analyze re-evaluates ARGS on the netlist; a cell in
# two lines is a fault there, so the sets below are disjoint by construction.
set xdc $root/build/${design_name}_pblocks.xdc
set fh [open $xdc w]
puts $fh "# GENERATED by scripts/tcl/v8t3/60_constraints.tcl"
set ::V8_PB {}
proc v8_pin {fh pb cell} {
    puts $fh "add_cells_to_pblock \[get_pblocks $pb\] \[get_cells -quiet \{$cell\}\]"
    lappend ::V8_PB [list $pb "{$cell}"]
}
# A generate scope minus the lanes inside it. `?` stands for each bracket:
# a bracket in a =~ pattern is a character class, not a bracket.
proc v8_pin_scope {fh pb scope excl} {
    set f "NAME =~ \"$scope.*\""
    foreach e $excl { append f " && NAME !~ \"$scope.$e.*\"" }
    puts $fh "add_cells_to_pblock \[get_pblocks $pb\] \[get_cells -quiet -hier -filter \{$f\}\]"
    lappend ::V8_PB [list $pb "-hier -filter {$f}"]
}
# The Xache is one module whose slices live on four dies. Partition i = die i
# holds master i's edge, routing, reorder ring and slot logic (g_m[i]), home
# i's DRAM edge, array, engines and taps (g_hedge[i], g_home[i]), and the
# sending or landing half of each boundary trunk (below). g_medge and g_route
# are wires at MCDC 0 and leave no cell.
set KX $top/xache/inst/u_kx
set NP [expr {[llength $MESHES] / 2}]
set ncmp 0
foreach {mid mod} $MESHES {
    lassign [dict get $SLR_ROWS $mid] ylo yhi
    puts $fh "create_pblock pb_slr$mid"
    puts $fh "resize_pblock \[get_pblocks pb_slr$mid\] -add \{CLOCKREGION_X0${ylo}:CLOCKREGION_X7${yhi}\}"
    # CMP_COLS: the compute half of the die gets a narrower pblock, and the node,
    # its Xache partition and (CMP_STN) its station go in THAT one instead -- a
    # cell may sit in only one pblock, and 70_analyze fails a cell that sits in
    # two. {xlo xhi} spans the die's rows; {xlo xhi ylo yhi} names the rows.
    set pbc pb_slr$mid
    if {[dict exists $CMP_COLS $mid]} {
        lassign [dict get $CMP_COLS $mid] xlo xhi cylo cyhi
        if {$cylo eq ""} { set cylo $ylo ; set cyhi $yhi }
        set pbc pb_cmp$mid
        puts $fh "create_pblock $pbc"
        puts $fh "resize_pblock \[get_pblocks $pbc\] -add\
 \{CLOCKREGION_${xlo}${cylo}:CLOCKREGION_${xhi}${cyhi}\}"
        puts $fh "set_property CONTAIN_ROUTING false \[get_pblocks $pbc\]"
        incr ncmp
    }
    set pbs [expr {[lsearch $CMP_STN $mid] >= 0 ? $pbc : "pb_slr$mid"}]
    # g_link is deliberately absent -- its pipeline registers ARE the die
    # crossing and must be free to place across it. Everything else in die i
    # carries the SLR index by construction.
    v8_pin $fh $pbs $top/station_bus/inst/u_line/g_stn\[$mid\].*
    v8_pin $fh $pbc $top/mesh_$mid
    foreach c [list clk_wiz_mesh$mid bus_rst_inv$mid \
                    ddr4_$mid rst_ddr4_$mid dwc_ctrl$mid] {
        v8_pin $fh pb_slr$mid $top/$c
    }
    v8_pin_scope $fh pb_slr$mid "$KX/g_hedge?$mid?" {}
    # A die half holds 128 URAM; the node's 65 and the home's 64 are 129, so
    # CMP_HOME says which dies' homes share the box at all.
    set pbh [expr {[lsearch $CMP_HOME $mid] >= 0 ? $pbc : "pb_slr$mid"}]
    v8_pin_scope $fh $pbh "$KX/g_home?$mid?" {g_up g_dn}
    v8_pin_scope $fh $pbc "$KX/g_m?$mid?" {g_up g_dn}
    # die i's copies of the sysnode and bus resets: at PER_DIE_CLK 1 they are
    # generated here, otherwise the tree's landing and fan-out registers are.
    if {$PER_DIE_CLK} {
        foreach t [list rst_sys$mid rst_bus$mid] { v8_pin $fh pb_slr$mid $top/$t }
    } else {
        foreach t {rst_tree rst_tree_bus} {
            v8_pin $fh pb_slr$mid $top/$t/inst/land_reg\[$mid\]
            v8_pin $fh pb_slr$mid $top/$t/inst/fan_reg\[$mid\]
        }
    }
    puts $fh "set_property CONTAIN_ROUTING false \[get_pblocks pb_slr$mid\]"
}
# BND_TRUNK: ONE crossing per boundary and direction, not a lane per source.
# u_tk holds both halves -- rx_*, the landing rings and the return registers
# belong to the receiving die, everything else to the sending one. The g_p glue
# belongs to its own partition.
set nhop 0
proc v8_pin_filter {fh pb f} {
    puts $fh "add_cells_to_pblock \[get_pblocks $pb\] \[get_cells -quiet -hier -filter \{$f\}\]"
    lappend ::V8_PB [list $pb "-hier -filter {$f}"]
}
for {set b 0} {$b < $NP - 1} {incr b} {
    foreach d {0 1} {
        set src  [expr {$d ? $b : $b + 1}]
        set dst  [expr {$d ? $b + 1 : $b}]
        set base "$KX/g_chain.g_b?$b?.g_d?$d?.u_tk"
        # Every m_clk register belongs to the receiving die. At KX_PCLK 1 the
        # return counters pb/pg and fok_m are on m_clk too -- left with the
        # sender they put a combinational path across THREE dies (measured
        # -4.382 at v8t4 synthesis, 6.881 ns of 7.427 in route) -- and the ring
        # becomes an async FIFO whose write half is the sender's and read half
        # the receiver's, so it belongs to neither pblock.
        set rxpat [list rx_* pp_tx* fok_tx*]
        if {$KX_PCLK} {
            lappend rxpat g_ret_a.fok_m_reg* g_ret_a.g_pc*.pb_reg* g_ret_a.g_pc*.pg_reg*
        } else {
            lappend rxpat g_ring*
        }
        set ors {} ; set ands {}
        foreach p $rxpat {
            lappend ors  "NAME =~ \"$base/$p\""
            lappend ands "NAME !~ \"$base/$p\""
        }
        if {$KX_PCLK} { lappend ands "NAME !~ \"$base/g_ring*\"" }
        v8_pin_filter $fh pb_slr$dst [join $ors " || "]
        v8_pin_filter $fh pb_slr$src "NAME =~ \"$base/*\" && [join $ands " && "]"
        incr nhop 2
    }
}
foreach {p mod} $MESHES {
    v8_pin_filter $fh pb_slr$p "NAME =~ \"$KX/g_chain.g_p?$p?.*\" && IS_PRIMITIVE"
}
# The interlink pipes: u_tx with the die the hop leaves, u_rx with the die it
# lands on; every register of a half has exactly one load in the other half,
# so each pair is a Laguna crossing.
set npipe 0
foreach hop {{0 1} {1 2} {2 3}} {
    lassign $hop lo hi
    v8_pin $fh pb_slr$lo $top/pipe_${lo}_to_${hi}/inst/u_tx
    v8_pin $fh pb_slr$hi $top/pipe_${lo}_to_${hi}/inst/u_rx
    v8_pin $fh pb_slr$hi $top/pipe_${hi}_to_${lo}/inst/u_tx
    v8_pin $fh pb_slr$lo $top/pipe_${hi}_to_${lo}/inst/u_rx
    incr npipe 4
    # At IL_ASYNC 1 the crossing is kts_cdc. Its two FIFOs each hold registers
    # of BOTH clocks, so neither belongs to a die and both are left unpinned;
    # everything else in it is on the receiving clock except the credit output.
    if {$IL_ASYNC} {
        foreach {tx rx} [list $lo $hi $hi $lo] {
            set cdc $top/pipe_${tx}_to_${rx}/inst/g_async.u_x
            v8_pin_filter $fh pb_slr$rx "NAME =~ \"$cdc/*\" && NAME !~ \"$cdc/u_f/*\"\
                 && NAME !~ \"$cdc/u_b/*\" && NAME !~ \"$cdc/o_crd_*\""
            v8_pin_filter $fh pb_slr$tx "NAME =~ \"$cdc/o_crd_*\""
            incr npipe 2
        }
    }
}
# Only at IL_ASYNC 0 is a pipe half's register the TX flop of an SLL pair. With
# a kts_cdc between them the crossing is inside a FIFO, which cannot use Laguna.
if {!$IL_ASYNC} {
    puts $fh "set_property USER_SLL_REG TRUE \[get_cells -quiet -hier -filter \{NAME =~ \"$top/pipe_*/inst/u_?x/*\" && IS_SEQUENTIAL\}\]"
}
# Each die-spanning reset lives with its generator, and so do its tree's four
# sending registers; each pair is a Laguna crossing where it crosses. At
# PER_DIE_CLK 1 no reset spans a die and there is nothing here to place.
if {!$PER_DIE_CLK} {
    v8_pin $fh pb_slr$SYS_WIZ $top/rst_sys
    v8_pin $fh pb_slr1 $top/rst_bus
    foreach {t home} [list rst_tree $SYS_WIZ rst_tree_bus 1] {
        foreach {mid mod} $MESHES {
            v8_pin $fh pb_slr$home $top/$t/inst/q_reg\[$mid\]
            if {$mid != $home} {
                puts $fh "set_property USER_SLL_REG TRUE \[get_cells -quiet \{$top/$t/inst/q_reg\[$mid\] $top/$t/inst/land_reg\[$mid\]\}\]"
            }
        }
    }
}
# PCIE40E4_X0Y1 and the AY23 reference are both in SLR1, so the fabric half of
# XDMA and the clock root belong there too. The constants are NOT pinned:
# synthesis dissolves them into tie-offs and the path resolves empty.
foreach c {xdma_0 jtag_ctrl clk_wiz_ctrl rst_ctrl \
           util_ds_buf_bufg util_ds_buf_sys util_ds_buf_pcie} {
    v8_pin $fh pb_slr1 $top/$c
}
close $fh
if {![llength [get_files -quiet -of_objects [get_filesets constrs_1] $xdc]]} {
    add_files -fileset constrs_1 -norecurse $xdc
}

# ---- clocks --------------------------------------------------------------
set clk $root/build/${design_name}_clocks.xdc
set fh [open $clk w]
puts $fh "# GENERATED by scripts/tcl/v8t3/60_constraints.tcl"
puts $fh "create_clock -name sys_clk -period 10.000 \[get_ports system_clk_p\]"
puts $fh "set_property IOSTANDARD DIFF_SSTL12 \[get_ports system_clk_p\]"
puts $fh "set_property IOSTANDARD DIFF_SSTL12 \[get_ports system_clk_n\]"
puts $fh "set_property PACKAGE_PIN AY23 \[get_ports system_clk_p\]"
puts $fh "set_property PACKAGE_PIN BD20 \[get_ports user_lnk_up\]"
puts $fh "set_property IOSTANDARD LVCMOS12 \[get_ports user_lnk_up\]"
# Five MMCMs on one reference; rule_bufg_mmcm_3loads caps a BUFGCE at three.
puts $fh "set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN \[get_nets -of \[get_pins $top/clk_wiz_ctrl/clk_in1\]\]"

# Groups: per die {noc, vec} and {mat 2x} (the units reach the NoC through
# async FIFOs at UNIT_CDC=1); the sysnode clock alone (MAG_CDC=1 crosses NoC
# <-> node, kx_scdc crosses Xache <-> MIG); the system clock (every station
# port and the JTAG NMU cross inside sb_nsu/sb_nmu); ctrl; each MIG; XDMA.
set ::V8_CLKPINS {}
proc v8_group {wiz outs} {
    set pins {}
    foreach o $outs { lappend pins "$::top/$wiz/$o" }
    lappend ::V8_CLKPINS {*}$pins
    return " \\\n    -group \[get_clocks -include_generated_clocks -of_objects\
 \[get_pins \{$pins\}\]\]"
}
# No mesh, so no mesh, vector or matmul clock group: the sysnode clock, the
# two control clocks, the four MIG UI clocks and XDMA are all that run.
set grp {}
if {$PER_DIE_CLK} {
    # Four sysnode clocks and four bus clocks, each its own group: every path
    # between two of them goes through a crossing (KX_PCLK, IL_ASYNC, LINK_CDC).
    foreach {mid mod} $MESHES { append grp [v8_group clk_wiz_mesh$mid {clk_out4}] }
    append grp [v8_group clk_wiz_ctrl {clk_out1}]
    foreach {mid mod} $MESHES {
        append grp [v8_group clk_wiz_ctrl [list clk_out[expr {$mid + 2}]]]
    }
} else {
    append grp [v8_group clk_wiz_mesh$SYS_WIZ {clk_out4}]
    append grp [v8_group clk_wiz_ctrl {clk_out1}]
    append grp [v8_group clk_wiz_ctrl {clk_out2}]
}
foreach i {0 1 2 3} { append grp [v8_group ddr4_$i {c0_ddr4_ui_clk}] }
# No group of its own for xdma_0/axi_aclk: it is a generated clock of
# pcie_refclk and the reference's group carries it (XDCB-3, TIMING-47).
append grp " \\\n    -group \[get_clocks -include_generated_clocks pcie_refclk\]"
puts $fh "set_clock_groups -asynchronous$grp"
close $fh
if {![llength [get_files -quiet -of_objects [get_filesets constrs_1] $clk]]} {
    add_files -fileset constrs_1 -norecurse $clk
}
# LATE, or the clk_wiz generated clocks do not exist yet and every group
# matches nothing.
set_property PROCESSING_ORDER LATE \
    [get_files -of_objects [get_filesets constrs_1] */${design_name}_clocks.xdc]

# Vivado parses EVERY enabled xdc and they ADD rather than replace.
foreach pat {*multimesh_v*_clocks.xdc *multimesh_v*_pblocks.xdc
             */JTAG-DMA-test/pblocks.xdc *sysytem.xdc} {
    foreach f [get_files -quiet -of_objects [get_filesets constrs_1] $pat] {
        if {[string match ${design_name}_* [file tail $f]]} { continue }
        if {[get_property is_enabled $f]} {
            set_property is_enabled false $f
            puts "@@@ disabled stale constraint: [file tail $f]"
        }
    }
}
puts "@@@ constraints: [llength $::V8_PB] pblock lines ($nhop hop halves,\
 $npipe pipe halves, $ncmp compute-half pblocks), [llength $::V8_CLKPINS] clock pins"
