// sb_bd_leaf -- GENERATED by scripts/py/gen_station_wrap.py. Do not edit by hand.
//
// A leaf station with every interface named so a block design infers it: one
// AXIS link in, one AXIS link out, 2 local AXI4 masters on one clock.

`default_nettype none

module sb_bd_leaf #(
    parameter integer OST          = 4,
    parameter integer LUT_PER_BRAM = 0,
    parameter integer TIMEOUT      = 0
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 bus_clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF L_REQ:L_RSP, ASSOCIATED_RESET bus_rst" *)
    input  wire bus_clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 bus_rst RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_HIGH" *)
    input  wire bus_rst,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_loc CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M00_AXI:M01_AXI, ASSOCIATED_RESET aresetn_loc" *)
    input  wire clk_loc,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_loc RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_loc,

    input  wire [632-1:0] L_REQ_tdata,
    input  wire L_REQ_tvalid,
    output wire L_REQ_tready,
    output wire [528-1:0] L_RSP_tdata,
    output wire L_RSP_tvalid,
    input  wire L_RSP_tready,

    output wire [4-1:0] M00_AXI_awid,
    output wire [32-1:0] M00_AXI_awaddr,
    output wire [8-1:0] M00_AXI_awlen,
    output wire [3-1:0] M00_AXI_awsize,
    output wire [2-1:0] M00_AXI_awburst,
    output wire M00_AXI_awvalid,
    input  wire M00_AXI_awready,
    output wire [512-1:0] M00_AXI_wdata,
    output wire [64-1:0] M00_AXI_wstrb,
    output wire M00_AXI_wlast,
    output wire M00_AXI_wvalid,
    input  wire M00_AXI_wready,
    input  wire [4-1:0] M00_AXI_bid,
    input  wire [2-1:0] M00_AXI_bresp,
    input  wire M00_AXI_bvalid,
    output wire M00_AXI_bready,
    output wire [4-1:0] M00_AXI_arid,
    output wire [32-1:0] M00_AXI_araddr,
    output wire [8-1:0] M00_AXI_arlen,
    output wire [3-1:0] M00_AXI_arsize,
    output wire [2-1:0] M00_AXI_arburst,
    output wire M00_AXI_arvalid,
    input  wire M00_AXI_arready,
    input  wire [4-1:0] M00_AXI_rid,
    input  wire [512-1:0] M00_AXI_rdata,
    input  wire [2-1:0] M00_AXI_rresp,
    input  wire M00_AXI_rlast,
    input  wire M00_AXI_rvalid,
    output wire M00_AXI_rready,

    output wire [4-1:0] M01_AXI_awid,
    output wire [32-1:0] M01_AXI_awaddr,
    output wire [8-1:0] M01_AXI_awlen,
    output wire [3-1:0] M01_AXI_awsize,
    output wire [2-1:0] M01_AXI_awburst,
    output wire M01_AXI_awvalid,
    input  wire M01_AXI_awready,
    output wire [32-1:0] M01_AXI_wdata,
    output wire [4-1:0] M01_AXI_wstrb,
    output wire M01_AXI_wlast,
    output wire M01_AXI_wvalid,
    input  wire M01_AXI_wready,
    input  wire [4-1:0] M01_AXI_bid,
    input  wire [2-1:0] M01_AXI_bresp,
    input  wire M01_AXI_bvalid,
    output wire M01_AXI_bready,
    output wire [4-1:0] M01_AXI_arid,
    output wire [32-1:0] M01_AXI_araddr,
    output wire [8-1:0] M01_AXI_arlen,
    output wire [3-1:0] M01_AXI_arsize,
    output wire [2-1:0] M01_AXI_arburst,
    output wire M01_AXI_arvalid,
    input  wire M01_AXI_arready,
    input  wire [4-1:0] M01_AXI_rid,
    input  wire [32-1:0] M01_AXI_rdata,
    input  wire [2-1:0] M01_AXI_rresp,
    input  wire M01_AXI_rlast,
    input  wire M01_AXI_rvalid,
    output wire M01_AXI_rready
);
    localparam integer NS   = 2;
    localparam integer AW   = 32;
    localparam integer MAXW = 512;
    localparam integer MAXID = 4;
    localparam integer FW   = 512;

    wire [NS*MAXID-1:0]    sp_awid, sp_arid, sp_bid, sp_rid;
    wire [NS*AW-1:0]       sp_awaddr, sp_araddr;
    wire [NS*8-1:0]        sp_awlen, sp_arlen;
    wire [NS*3-1:0]        sp_awsize, sp_arsize;
    wire [NS*2-1:0]        sp_awburst, sp_arburst, sp_bresp, sp_rresp;
    wire [NS-1:0]          sp_awvalid, sp_awready, sp_wvalid, sp_wready;
    wire [NS-1:0]          sp_wlast, sp_bvalid, sp_bready;
    wire [NS-1:0]          sp_arvalid, sp_arready, sp_rvalid, sp_rready, sp_rlast;
    wire [NS*MAXW-1:0]     sp_wdata, sp_rdata;
    wire [NS*(MAXW/8)-1:0] sp_wstrb;

    assign M00_AXI_awid = sp_awid[0*4 +: 4];
    assign M00_AXI_awaddr = sp_awaddr[0*32 +: 32];
    assign M00_AXI_awlen = sp_awlen[0*8 +: 8];
    assign M00_AXI_awsize = sp_awsize[0*3 +: 3];
    assign M00_AXI_awburst = sp_awburst[0*2 +: 2];
    assign M00_AXI_awvalid = sp_awvalid[0];
    assign sp_awready[0] = M00_AXI_awready;
    assign M00_AXI_wdata = sp_wdata[0*512 +: 512];
    assign M00_AXI_wstrb = sp_wstrb[0*64 +: 64];
    assign M00_AXI_wlast = sp_wlast[0];
    assign M00_AXI_wvalid = sp_wvalid[0];
    assign sp_wready[0] = M00_AXI_wready;
    assign sp_bid[0*4 +: 4] = M00_AXI_bid;
    assign sp_bresp[0*2 +: 2] = M00_AXI_bresp;
    assign sp_bvalid[0] = M00_AXI_bvalid;
    assign M00_AXI_bready = sp_bready[0];
    assign M00_AXI_arid = sp_arid[0*4 +: 4];
    assign M00_AXI_araddr = sp_araddr[0*32 +: 32];
    assign M00_AXI_arlen = sp_arlen[0*8 +: 8];
    assign M00_AXI_arsize = sp_arsize[0*3 +: 3];
    assign M00_AXI_arburst = sp_arburst[0*2 +: 2];
    assign M00_AXI_arvalid = sp_arvalid[0];
    assign sp_arready[0] = M00_AXI_arready;
    assign sp_rid[0*4 +: 4] = M00_AXI_rid;
    assign sp_rdata[0*512 +: 512] = M00_AXI_rdata;
    assign sp_rresp[0*2 +: 2] = M00_AXI_rresp;
    assign sp_rlast[0] = M00_AXI_rlast;
    assign sp_rvalid[0] = M00_AXI_rvalid;
    assign M00_AXI_rready = sp_rready[0];

    assign M01_AXI_awid = sp_awid[1*4 +: 4];
    assign M01_AXI_awaddr = sp_awaddr[1*32 +: 32];
    assign M01_AXI_awlen = sp_awlen[1*8 +: 8];
    assign M01_AXI_awsize = sp_awsize[1*3 +: 3];
    assign M01_AXI_awburst = sp_awburst[1*2 +: 2];
    assign M01_AXI_awvalid = sp_awvalid[1];
    assign sp_awready[1] = M01_AXI_awready;
    assign M01_AXI_wdata = sp_wdata[1*512 +: 32];
    assign M01_AXI_wstrb = sp_wstrb[1*64 +: 4];
    assign M01_AXI_wlast = sp_wlast[1];
    assign M01_AXI_wvalid = sp_wvalid[1];
    assign sp_wready[1] = M01_AXI_wready;
    assign sp_bid[1*4 +: 4] = M01_AXI_bid;
    assign sp_bresp[1*2 +: 2] = M01_AXI_bresp;
    assign sp_bvalid[1] = M01_AXI_bvalid;
    assign M01_AXI_bready = sp_bready[1];
    assign M01_AXI_arid = sp_arid[1*4 +: 4];
    assign M01_AXI_araddr = sp_araddr[1*32 +: 32];
    assign M01_AXI_arlen = sp_arlen[1*8 +: 8];
    assign M01_AXI_arsize = sp_arsize[1*3 +: 3];
    assign M01_AXI_arburst = sp_arburst[1*2 +: 2];
    assign M01_AXI_arvalid = sp_arvalid[1];
    assign sp_arready[1] = M01_AXI_arready;
    assign sp_rid[1*4 +: 4] = M01_AXI_rid;
    assign sp_rdata[1*512 +: 32] = M01_AXI_rdata;
    assign sp_rresp[1*2 +: 2] = M01_AXI_rresp;
    assign sp_rlast[1] = M01_AXI_rlast;
    assign sp_rvalid[1] = M01_AXI_rvalid;
    assign M01_AXI_rready = sp_rready[1];

    wire [1:0]      lq_src;
    wire [2:0]      lq_dpt;
    wire [3:0]      lq_tag;
    wire            lq_wr, lq_head, lq_last;
    wire [AW-1:0]   lq_addr;
    wire [7:0]      lq_len;
    wire [2:0]      lq_size;
    wire [FW-1:0]   lq_data;
    wire [FW/8-1:0] lq_strb;

    assign {lq_src, lq_dpt, lq_tag, lq_wr, lq_head, lq_last, lq_addr, lq_len,
            lq_size, lq_data, lq_strb} = L_REQ_tdata[631-1:0];

    wire [1:0]    ls_dst;
    wire [3:0]    ls_tag;
    wire          ls_wr, ls_last;
    wire [1:0]    ls_resp;
    wire [FW-1:0] ls_data;

    assign L_RSP_tdata = {6'd0, ls_dst, ls_tag, ls_wr, ls_last,
                         ls_resp, ls_data};

    sb_stn_leaf #(.FW(FW), .AW(AW), .MAXW(MAXW), .MAXID(MAXID), .NS(NS),
                  .TAGW(4), .DSTW(3), .SRCW(2), .OST(OST),
                  .TIMEOUT(TIMEOUT), .LUT_PER_BRAM(LUT_PER_BRAM),
                  .LOC_W(32'h00000001)) u_stn (
        .bus_clk(bus_clk), .bus_rst(bus_rst),
        .clk_loc(clk_loc), .aresetn_loc(aresetn_loc),
        .lk_req_valid(L_REQ_tvalid), .lk_req_ready(L_REQ_tready),
        .lk_req_dport(lq_dpt), .lk_req_src(lq_src), .lk_req_tag(lq_tag),
        .lk_req_wr(lq_wr), .lk_req_head(lq_head), .lk_req_last(lq_last),
        .lk_req_addr(lq_addr), .lk_req_len(lq_len), .lk_req_size(lq_size),
        .lk_req_data(lq_data), .lk_req_strb(lq_strb),
        .lk_rsp_valid(L_RSP_tvalid), .lk_rsp_ready(L_RSP_tready),
        .lk_rsp_dst(ls_dst), .lk_rsp_tag(ls_tag), .lk_rsp_wr(ls_wr),
        .lk_rsp_last(ls_last), .lk_rsp_resp(ls_resp), .lk_rsp_data(ls_data),
        .sp_awid(sp_awid), .sp_awaddr(sp_awaddr), .sp_awlen(sp_awlen),
        .sp_awsize(sp_awsize), .sp_awburst(sp_awburst),
        .sp_awvalid(sp_awvalid), .sp_awready(sp_awready),
        .sp_wdata(sp_wdata), .sp_wstrb(sp_wstrb), .sp_wlast(sp_wlast),
        .sp_wvalid(sp_wvalid), .sp_wready(sp_wready),
        .sp_bid(sp_bid), .sp_bresp(sp_bresp), .sp_bvalid(sp_bvalid),
        .sp_bready(sp_bready),
        .sp_arid(sp_arid), .sp_araddr(sp_araddr), .sp_arlen(sp_arlen),
        .sp_arsize(sp_arsize), .sp_arburst(sp_arburst),
        .sp_arvalid(sp_arvalid), .sp_arready(sp_arready),
        .sp_rid(sp_rid), .sp_rdata(sp_rdata), .sp_rresp(sp_rresp),
        .sp_rlast(sp_rlast), .sp_rvalid(sp_rvalid), .sp_rready(sp_rready)
    );
endmodule

`default_nettype wire
