# Floorplan, clock groups and board pins, written out as XDC. Nothing here can
# check itself: XDC rejects `if`, so every assertion lives in 70_analyze.tcl.

file mkdir $root/build
set top ${design_name}_i

# ---- board pins ----------------------------------------------------------
# Required: without them the DDR4 and PCIe pins are unconstrained and the run
# dies at placement, one synthesis later.
proc v6_board {name} {
    global BOARD_DIR
    if {![file exists $BOARD_DIR/$name]} { error "missing board XDC: $BOARD_DIR/$name" }
    return $BOARD_DIR/$name
}
# import_files COPIES into the project, so a rebuild adds a SECOND copy of each
# board file every time unless the one already there is found first.
proc v6_import {name} {
    if {[llength [get_files -quiet -of_objects [get_filesets constrs_1] *$name]]} {
        return
    }
    import_files -fileset constrs_1 -norecurse [v6_board $name]
}
foreach i {0 1 2 3} { v6_import ddr4_c${i}.xdc }
v6_import pcie.xdc

# The DDR4 <-> SLR check needs an open design for get_slrs, so it lives in
# 70_analyze.tcl. ddr4_0's pins are in SLR3: the index says nothing about the die.

# ---- pblocks -------------------------------------------------------------
set xdc $root/build/${design_name}_pblocks.xdc
set fh [open $xdc w]
puts $fh "# GENERATED by scripts/tcl/v6/60_constraints.tcl"
set ::V6_PB {}
proc v6_pin {fh pb cell} {
    puts $fh "add_cells_to_pblock \[get_pblocks $pb\] \[get_cells -quiet \{$cell\}\]"
    lappend ::V6_PB [list $pb $cell]
}
foreach {mid mod} $MESHES {
    set ddr [dict get $DDR_OF_SLR $mid]
    lassign [dict get $SLR_ROWS $mid] ylo yhi
    puts $fh "create_pblock pb_slr$mid"
    puts $fh "resize_pblock \[get_pblocks pb_slr$mid\] -add \{CLOCKREGION_X0${ylo}:CLOCKREGION_X7${yhi}\}"
    # g_link is deliberately absent -- its pipeline registers ARE the die
    # crossing and must be free to place across it.
    foreach c [list station_bus/inst/u_line/g_stn\[$mid\].* \
                    mesh_$mid ddr4_$ddr rst_ddr4_$ddr \
                    clk_wiz_mesh$mid rst_mesh$mid div2_mesh$mid dclr_mesh$mid \
                    clk_wiz_bus$mid rst_bus$mid bus_rst_inv$mid dwc_ctrl$mid] {
        v6_pin $fh pb_slr$mid $top/$c
    }
    puts $fh "set_property CONTAIN_ROUTING false \[get_pblocks pb_slr$mid\]"
}
# Each SLR owns the FIFOs for links LEAVING it, so an SLL crossing starts at a
# registered output.
foreach hop {{0 1} {1 2} {2 3}} {
    lassign $hop lo hi
    v6_pin $fh pb_slr$lo $top/cdc_${lo}_to_${hi}
    v6_pin $fh pb_slr$hi $top/cdc_${hi}_to_${lo}
}
# PCIE40E4_X0Y1 and the AY23 reference are both in SLR1, so the fabric half of
# XDMA and the clock root belong there too.
foreach c {xdma_0 jtag_ctrl clk_wiz_ctrl rst_ctrl \
           util_ds_buf_bufg util_ds_buf_sys util_ds_buf_pcie xlconstant_irq} {
    v6_pin $fh pb_slr1 $top/$c
}
close $fh
add_files -fileset constrs_1 -norecurse $xdc

# ---- clocks --------------------------------------------------------------
set clk $root/build/${design_name}_clocks.xdc
set fh [open $clk w]
puts $fh "# GENERATED by scripts/tcl/v6/60_constraints.tcl"
# WITHOUT THIS NOTHING DERIVES: no board part declares the reference, so every
# MMCM output would carry no clock and the design would route UNTIMED.
puts $fh "create_clock -name sys_clk -period 10.000 \[get_ports system_clk_p\]"
puts $fh "set_property IOSTANDARD DIFF_SSTL12 \[get_ports system_clk_p\]"
puts $fh "set_property IOSTANDARD DIFF_SSTL12 \[get_ports system_clk_n\]"
puts $fh "set_property PACKAGE_PIN AY23 \[get_ports system_clk_p\]"
# Only sysytem.xdc pinned user_lnk_up and it is disabled below; an output with
# no location is UCIO-1, an ERROR at implementation.
puts $fh "set_property PACKAGE_PIN BD20 \[get_ports user_lnk_up\]"
puts $fh "set_property IOSTANDARD LVCMOS12 \[get_ports user_lnk_up\]"
# Ten MMCMs on one reference; rule_bufg_mmcm_3loads caps a BUFGCE at three.
# Named by a LOAD pin: an auto-inserted BUFG has no name until opt_design.
puts $fh "set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN \[get_nets -of \[get_pins $top/clk_wiz_ctrl/clk_in1\]\]"

# The matmul pair is its OWN group: at UNIT_CDC=1 the units reach the NoC
# through async FIFOs, so grouping clk_out2 with clk_out1 times what they break.
set ::V6_CLKPINS {}
proc v6_group {wiz outs} {
    set pins {}
    foreach o $outs { lappend pins "$::top/$wiz/$o" }
    lappend ::V6_CLKPINS {*}$pins
    return " \\\n    -group \[get_clocks -include_generated_clocks -of_objects\
 \[get_pins \{$pins\}\]\]"
}
set grp {}
foreach {mid mod} $MESHES {
    append grp [v6_group clk_wiz_mesh$mid {clk_out1 clk_out3 clk_out4}]
    append grp [v6_group clk_wiz_mesh$mid {clk_out2}]
    append grp [v6_group clk_wiz_bus$mid  {clk_out1}]
}
append grp [v6_group clk_wiz_ctrl {clk_out1}]
# By PIN and by LITERAL PATH: `get_pins -hier -filter NAME` resolves EMPTY here,
# which makes the whole -group a silent no-op and times every MIG crossing.
foreach i {0 1 2 3} { append grp [v6_group ddr4_$i {c0_ddr4_ui_clk}] }
append grp [v6_group xdma_0 {axi_aclk}]
append grp " \\\n    -group \[get_clocks -include_generated_clocks pcie_refclk\]"
puts $fh "set_clock_groups -asynchronous$grp"
close $fh
add_files -fileset constrs_1 -norecurse $clk
# LATE, or the clk_wiz generated clocks do not exist yet and every group
# matches nothing.
set_property PROCESSING_ORDER LATE \
    [get_files -of_objects [get_filesets constrs_1] */${design_name}_clocks.xdc]

# Vivado parses EVERY enabled xdc and they ADD rather than replace, so an older
# grouping of the same clock silently conflicts with this one.
# EVERY older version, clocks AND pblocks: create_pblock is not idempotent, so
# v5's pb_slr0..3 collide with ours rather than being overridden by them.
foreach pat {*multimesh_v*_clocks.xdc *multimesh_v*_pblocks.xdc
             */JTAG-DMA-test/pblocks.xdc *sysytem.xdc} {
    foreach f [get_files -quiet -of_objects [get_filesets constrs_1] $pat] {
        if {[string match ${design_name}_* [file tail $f]]} { continue }
        if {[get_property is_enabled $f]} {
            set_property is_enabled false $f
            puts "@@@ disabled stale constraint: [file tail $f]"
        }
    }
}
puts "@@@ v6 constraints: [llength $::V6_PB] pblock cells, [llength $::V6_CLKPINS] clock pins"
