"""The register map, the flit codec, and the control program.

Everything a host needs to talk to a KohakuAccel machine without knowing what
any of its compute units compute.
"""

from kohakuaccel.device.discovery import (
    AgentCaps,
    Endpoint,
    agent_status,
    answers_at,
    by_type,
    control_exchange,
    control_read,
    drain_mailbox,
    enumerate_mesh,
    find_control_window,
    find_control_windows,
    read_agent_caps,
)
from kohakuaccel.device.flit import (
    ctrl_reply,
    ctrl_request,
    cu_data_flits,
    decode_caps,
    decode_counters,
    decode_status,
    encode_caps,
    field,
    header,
)
from kohakuaccel.device.program import Command, Program
from kohakuaccel.device.registers import (
    CU_CAPS,
    CU_COUNTERS,
    CU_DBG,
    CU_STATUS,
    INST_DEPTH,
    MAG_BASE,
    ORC_BASE,
    SIG_BATCH_COMPLETE,
    SIG_DATA_RECEIVED,
    SIG_FAULT,
    SIG_INST_COMPLETE,
    T_CU_CTRL,
    T_CU_DATA,
    T_CU_INST,
    node_index,
    node_status_addr,
    type_code,
)

__all__ = [
    "CU_CAPS",
    "CU_COUNTERS",
    "CU_DBG",
    "CU_STATUS",
    "INST_DEPTH",
    "MAG_BASE",
    "ORC_BASE",
    "SIG_BATCH_COMPLETE",
    "SIG_DATA_RECEIVED",
    "SIG_FAULT",
    "SIG_INST_COMPLETE",
    "T_CU_CTRL",
    "T_CU_DATA",
    "T_CU_INST",
    "AgentCaps",
    "Command",
    "Endpoint",
    "Program",
    "agent_status",
    "answers_at",
    "by_type",
    "control_exchange",
    "control_read",
    "ctrl_reply",
    "ctrl_request",
    "cu_data_flits",
    "decode_caps",
    "decode_counters",
    "decode_status",
    "drain_mailbox",
    "encode_caps",
    "enumerate_mesh",
    "field",
    "find_control_window",
    "find_control_windows",
    "header",
    "node_index",
    "node_status_addr",
    "read_agent_caps",
    "type_code",
]
