// kx_bd_4x4 -- GENERATED by scripts/py/gen_kx_wrap.py. Do not edit by hand.
//
// Kohaku Xache with 4 master ports and 4 homes named for a block design.
// Every master is on the fabric clock (MCDC = 0); every home's DRAM side crosses
// to its own clock (HCDC = 1). The DRAM-side address carries the home field cleared.

`default_nettype none

module kx_bd_4x4 #(
    parameter integer SETS      = 32768,
    parameter integer SET_W     = 15,
    parameter integer K         = 1,
    parameter         RAM_STYLE = "ultra",
    parameter integer BANKS     = 8,
    parameter integer RSAMD     = 1,
    parameter integer WSAMD     = 1,
    parameter integer CDC_DEPTH = 16,
    parameter integer NSWAP     = 0,
    // IPI types a parameter from its default: a fixed width and a sized zero
    // make these bit-strings (0b...); a width in NSWAP made them integers.
    // Room for 32 pairs; pair k is byte k.
    parameter [255:0] SWAP_A    = 256'h0,
    parameter [255:0] SWAP_B    = 256'h0,
    parameter integer RD_PIPE   = 1,
    parameter integer RD_OUTQ   = 4,
    parameter integer SLRX      = 1
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S00_AXI:S01_AXI:S02_AXI:S03_AXI, ASSOCIATED_RESET d_rstn0" *)
    input  wire aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 d_rstn0 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire d_rstn0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 d_rstn1 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire d_rstn1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 d_rstn2 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire d_rstn2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 d_rstn3 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire d_rstn3,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 h_clk0 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M00_AXI, ASSOCIATED_RESET h_rstn0" *)
    input  wire h_clk0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 h_rstn0 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire h_rstn0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 h_clk1 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M01_AXI, ASSOCIATED_RESET h_rstn1" *)
    input  wire h_clk1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 h_rstn1 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire h_rstn1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 h_clk2 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M02_AXI, ASSOCIATED_RESET h_rstn2" *)
    input  wire h_clk2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 h_rstn2 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire h_rstn2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 h_clk3 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M03_AXI, ASSOCIATED_RESET h_rstn3" *)
    input  wire h_clk3,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 h_rstn3 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire h_rstn3,

    input  wire [4-1:0] S00_AXI_awid,
    input  wire [40-1:0] S00_AXI_awaddr,
    input  wire [8-1:0] S00_AXI_awlen,
    input  wire [3-1:0] S00_AXI_awsize,
    input  wire [2-1:0] S00_AXI_awburst,
    input  wire S00_AXI_awvalid,
    output wire S00_AXI_awready,
    input  wire [512-1:0] S00_AXI_wdata,
    input  wire [64-1:0] S00_AXI_wstrb,
    input  wire S00_AXI_wlast,
    input  wire S00_AXI_wvalid,
    output wire S00_AXI_wready,
    output wire [4-1:0] S00_AXI_bid,
    output wire [2-1:0] S00_AXI_bresp,
    output wire S00_AXI_bvalid,
    input  wire S00_AXI_bready,
    input  wire [4-1:0] S00_AXI_arid,
    input  wire [40-1:0] S00_AXI_araddr,
    input  wire [8-1:0] S00_AXI_arlen,
    input  wire [3-1:0] S00_AXI_arsize,
    input  wire [2-1:0] S00_AXI_arburst,
    input  wire S00_AXI_arvalid,
    output wire S00_AXI_arready,
    output wire [4-1:0] S00_AXI_rid,
    output wire [512-1:0] S00_AXI_rdata,
    output wire [2-1:0] S00_AXI_rresp,
    output wire S00_AXI_rlast,
    output wire S00_AXI_rvalid,
    input  wire S00_AXI_rready,

    input  wire [4-1:0] S01_AXI_awid,
    input  wire [40-1:0] S01_AXI_awaddr,
    input  wire [8-1:0] S01_AXI_awlen,
    input  wire [3-1:0] S01_AXI_awsize,
    input  wire [2-1:0] S01_AXI_awburst,
    input  wire S01_AXI_awvalid,
    output wire S01_AXI_awready,
    input  wire [512-1:0] S01_AXI_wdata,
    input  wire [64-1:0] S01_AXI_wstrb,
    input  wire S01_AXI_wlast,
    input  wire S01_AXI_wvalid,
    output wire S01_AXI_wready,
    output wire [4-1:0] S01_AXI_bid,
    output wire [2-1:0] S01_AXI_bresp,
    output wire S01_AXI_bvalid,
    input  wire S01_AXI_bready,
    input  wire [4-1:0] S01_AXI_arid,
    input  wire [40-1:0] S01_AXI_araddr,
    input  wire [8-1:0] S01_AXI_arlen,
    input  wire [3-1:0] S01_AXI_arsize,
    input  wire [2-1:0] S01_AXI_arburst,
    input  wire S01_AXI_arvalid,
    output wire S01_AXI_arready,
    output wire [4-1:0] S01_AXI_rid,
    output wire [512-1:0] S01_AXI_rdata,
    output wire [2-1:0] S01_AXI_rresp,
    output wire S01_AXI_rlast,
    output wire S01_AXI_rvalid,
    input  wire S01_AXI_rready,

    input  wire [4-1:0] S02_AXI_awid,
    input  wire [40-1:0] S02_AXI_awaddr,
    input  wire [8-1:0] S02_AXI_awlen,
    input  wire [3-1:0] S02_AXI_awsize,
    input  wire [2-1:0] S02_AXI_awburst,
    input  wire S02_AXI_awvalid,
    output wire S02_AXI_awready,
    input  wire [512-1:0] S02_AXI_wdata,
    input  wire [64-1:0] S02_AXI_wstrb,
    input  wire S02_AXI_wlast,
    input  wire S02_AXI_wvalid,
    output wire S02_AXI_wready,
    output wire [4-1:0] S02_AXI_bid,
    output wire [2-1:0] S02_AXI_bresp,
    output wire S02_AXI_bvalid,
    input  wire S02_AXI_bready,
    input  wire [4-1:0] S02_AXI_arid,
    input  wire [40-1:0] S02_AXI_araddr,
    input  wire [8-1:0] S02_AXI_arlen,
    input  wire [3-1:0] S02_AXI_arsize,
    input  wire [2-1:0] S02_AXI_arburst,
    input  wire S02_AXI_arvalid,
    output wire S02_AXI_arready,
    output wire [4-1:0] S02_AXI_rid,
    output wire [512-1:0] S02_AXI_rdata,
    output wire [2-1:0] S02_AXI_rresp,
    output wire S02_AXI_rlast,
    output wire S02_AXI_rvalid,
    input  wire S02_AXI_rready,

    input  wire [4-1:0] S03_AXI_awid,
    input  wire [40-1:0] S03_AXI_awaddr,
    input  wire [8-1:0] S03_AXI_awlen,
    input  wire [3-1:0] S03_AXI_awsize,
    input  wire [2-1:0] S03_AXI_awburst,
    input  wire S03_AXI_awvalid,
    output wire S03_AXI_awready,
    input  wire [512-1:0] S03_AXI_wdata,
    input  wire [64-1:0] S03_AXI_wstrb,
    input  wire S03_AXI_wlast,
    input  wire S03_AXI_wvalid,
    output wire S03_AXI_wready,
    output wire [4-1:0] S03_AXI_bid,
    output wire [2-1:0] S03_AXI_bresp,
    output wire S03_AXI_bvalid,
    input  wire S03_AXI_bready,
    input  wire [4-1:0] S03_AXI_arid,
    input  wire [40-1:0] S03_AXI_araddr,
    input  wire [8-1:0] S03_AXI_arlen,
    input  wire [3-1:0] S03_AXI_arsize,
    input  wire [2-1:0] S03_AXI_arburst,
    input  wire S03_AXI_arvalid,
    output wire S03_AXI_arready,
    output wire [4-1:0] S03_AXI_rid,
    output wire [512-1:0] S03_AXI_rdata,
    output wire [2-1:0] S03_AXI_rresp,
    output wire S03_AXI_rlast,
    output wire S03_AXI_rvalid,
    input  wire S03_AXI_rready,

    output wire [6-1:0] M00_AXI_awid,
    output wire [40-1:0] M00_AXI_awaddr,
    output wire [8-1:0] M00_AXI_awlen,
    output wire [3-1:0] M00_AXI_awsize,
    output wire [2-1:0] M00_AXI_awburst,
    output wire M00_AXI_awvalid,
    input  wire M00_AXI_awready,
    output wire [512-1:0] M00_AXI_wdata,
    output wire [64-1:0] M00_AXI_wstrb,
    output wire M00_AXI_wlast,
    output wire M00_AXI_wvalid,
    input  wire M00_AXI_wready,
    input  wire [6-1:0] M00_AXI_bid,
    input  wire [2-1:0] M00_AXI_bresp,
    input  wire M00_AXI_bvalid,
    output wire M00_AXI_bready,
    output wire [6-1:0] M00_AXI_arid,
    output wire [40-1:0] M00_AXI_araddr,
    output wire [8-1:0] M00_AXI_arlen,
    output wire [3-1:0] M00_AXI_arsize,
    output wire [2-1:0] M00_AXI_arburst,
    output wire M00_AXI_arvalid,
    input  wire M00_AXI_arready,
    input  wire [6-1:0] M00_AXI_rid,
    input  wire [512-1:0] M00_AXI_rdata,
    input  wire [2-1:0] M00_AXI_rresp,
    input  wire M00_AXI_rlast,
    input  wire M00_AXI_rvalid,
    output wire M00_AXI_rready,

    output wire [6-1:0] M01_AXI_awid,
    output wire [40-1:0] M01_AXI_awaddr,
    output wire [8-1:0] M01_AXI_awlen,
    output wire [3-1:0] M01_AXI_awsize,
    output wire [2-1:0] M01_AXI_awburst,
    output wire M01_AXI_awvalid,
    input  wire M01_AXI_awready,
    output wire [512-1:0] M01_AXI_wdata,
    output wire [64-1:0] M01_AXI_wstrb,
    output wire M01_AXI_wlast,
    output wire M01_AXI_wvalid,
    input  wire M01_AXI_wready,
    input  wire [6-1:0] M01_AXI_bid,
    input  wire [2-1:0] M01_AXI_bresp,
    input  wire M01_AXI_bvalid,
    output wire M01_AXI_bready,
    output wire [6-1:0] M01_AXI_arid,
    output wire [40-1:0] M01_AXI_araddr,
    output wire [8-1:0] M01_AXI_arlen,
    output wire [3-1:0] M01_AXI_arsize,
    output wire [2-1:0] M01_AXI_arburst,
    output wire M01_AXI_arvalid,
    input  wire M01_AXI_arready,
    input  wire [6-1:0] M01_AXI_rid,
    input  wire [512-1:0] M01_AXI_rdata,
    input  wire [2-1:0] M01_AXI_rresp,
    input  wire M01_AXI_rlast,
    input  wire M01_AXI_rvalid,
    output wire M01_AXI_rready,

    output wire [6-1:0] M02_AXI_awid,
    output wire [40-1:0] M02_AXI_awaddr,
    output wire [8-1:0] M02_AXI_awlen,
    output wire [3-1:0] M02_AXI_awsize,
    output wire [2-1:0] M02_AXI_awburst,
    output wire M02_AXI_awvalid,
    input  wire M02_AXI_awready,
    output wire [512-1:0] M02_AXI_wdata,
    output wire [64-1:0] M02_AXI_wstrb,
    output wire M02_AXI_wlast,
    output wire M02_AXI_wvalid,
    input  wire M02_AXI_wready,
    input  wire [6-1:0] M02_AXI_bid,
    input  wire [2-1:0] M02_AXI_bresp,
    input  wire M02_AXI_bvalid,
    output wire M02_AXI_bready,
    output wire [6-1:0] M02_AXI_arid,
    output wire [40-1:0] M02_AXI_araddr,
    output wire [8-1:0] M02_AXI_arlen,
    output wire [3-1:0] M02_AXI_arsize,
    output wire [2-1:0] M02_AXI_arburst,
    output wire M02_AXI_arvalid,
    input  wire M02_AXI_arready,
    input  wire [6-1:0] M02_AXI_rid,
    input  wire [512-1:0] M02_AXI_rdata,
    input  wire [2-1:0] M02_AXI_rresp,
    input  wire M02_AXI_rlast,
    input  wire M02_AXI_rvalid,
    output wire M02_AXI_rready,

    output wire [6-1:0] M03_AXI_awid,
    output wire [40-1:0] M03_AXI_awaddr,
    output wire [8-1:0] M03_AXI_awlen,
    output wire [3-1:0] M03_AXI_awsize,
    output wire [2-1:0] M03_AXI_awburst,
    output wire M03_AXI_awvalid,
    input  wire M03_AXI_awready,
    output wire [512-1:0] M03_AXI_wdata,
    output wire [64-1:0] M03_AXI_wstrb,
    output wire M03_AXI_wlast,
    output wire M03_AXI_wvalid,
    input  wire M03_AXI_wready,
    input  wire [6-1:0] M03_AXI_bid,
    input  wire [2-1:0] M03_AXI_bresp,
    input  wire M03_AXI_bvalid,
    output wire M03_AXI_bready,
    output wire [6-1:0] M03_AXI_arid,
    output wire [40-1:0] M03_AXI_araddr,
    output wire [8-1:0] M03_AXI_arlen,
    output wire [3-1:0] M03_AXI_arsize,
    output wire [2-1:0] M03_AXI_arburst,
    output wire M03_AXI_arvalid,
    input  wire M03_AXI_arready,
    input  wire [6-1:0] M03_AXI_rid,
    input  wire [512-1:0] M03_AXI_rdata,
    input  wire [2-1:0] M03_AXI_rresp,
    input  wire M03_AXI_rlast,
    input  wire M03_AXI_rvalid,
    output wire M03_AXI_rready

);
    localparam integer M = 4, N = 4, W = 512, AW = 40, ID_W = 4, IDW = 6;
    localparam integer HOME_LSB = 32, HIDX_W = 2;

    wire [M*ID_W-1:0] s_awid, s_arid, s_bid, s_rid;
    wire [M*AW-1:0]   s_awaddr, s_araddr;
    wire [M*8-1:0]    s_awlen, s_arlen;
    wire [M*3-1:0]    s_awsize, s_arsize;
    wire [M*2-1:0]    s_awburst, s_arburst, s_bresp, s_rresp;
    wire [M-1:0]      s_awvalid, s_awready, s_wvalid, s_wready, s_wlast;
    wire [M-1:0]      s_bvalid, s_bready, s_arvalid, s_arready, s_rvalid, s_rready, s_rlast;
    wire [M*W-1:0]    s_wdata, s_rdata;
    wire [M*W/8-1:0]  s_wstrb;
    wire [N*IDW-1:0]  d_awid, d_arid, d_bid, d_rid;
    wire [N*AW-1:0]   d_awaddr, d_araddr;
    wire [N*8-1:0]    d_awlen, d_arlen;
    wire [N*3-1:0]    d_awsize, d_arsize;
    wire [N*2-1:0]    d_awburst, d_arburst, d_bresp, d_rresp;
    wire [N-1:0]      d_awvalid, d_awready, d_wvalid, d_wready, d_wlast;
    wire [N-1:0]      d_bvalid, d_bready, d_arvalid, d_arready, d_rvalid, d_rready, d_rlast;
    wire [N*W-1:0]    d_wdata, d_rdata;
    wire [N*W/8-1:0]  d_wstrb;

    assign s_awid[0*4 +: 4] = S00_AXI_awid;
    assign s_awaddr[0*40 +: 40] = S00_AXI_awaddr;
    assign s_awlen[0*8 +: 8] = S00_AXI_awlen;
    assign s_awsize[0*3 +: 3] = S00_AXI_awsize;
    assign s_awburst[0*2 +: 2] = S00_AXI_awburst;
    assign s_awvalid[0] = S00_AXI_awvalid;
    assign S00_AXI_awready = s_awready[0];
    assign s_wdata[0*512 +: 512] = S00_AXI_wdata;
    assign s_wstrb[0*64 +: 64] = S00_AXI_wstrb;
    assign s_wlast[0] = S00_AXI_wlast;
    assign s_wvalid[0] = S00_AXI_wvalid;
    assign S00_AXI_wready = s_wready[0];
    assign S00_AXI_bid = s_bid[0*4 +: 4];
    assign S00_AXI_bresp = s_bresp[0*2 +: 2];
    assign S00_AXI_bvalid = s_bvalid[0];
    assign s_bready[0] = S00_AXI_bready;
    assign s_arid[0*4 +: 4] = S00_AXI_arid;
    assign s_araddr[0*40 +: 40] = S00_AXI_araddr;
    assign s_arlen[0*8 +: 8] = S00_AXI_arlen;
    assign s_arsize[0*3 +: 3] = S00_AXI_arsize;
    assign s_arburst[0*2 +: 2] = S00_AXI_arburst;
    assign s_arvalid[0] = S00_AXI_arvalid;
    assign S00_AXI_arready = s_arready[0];
    assign S00_AXI_rid = s_rid[0*4 +: 4];
    assign S00_AXI_rdata = s_rdata[0*512 +: 512];
    assign S00_AXI_rresp = s_rresp[0*2 +: 2];
    assign S00_AXI_rlast = s_rlast[0];
    assign S00_AXI_rvalid = s_rvalid[0];
    assign s_rready[0] = S00_AXI_rready;

    assign s_awid[1*4 +: 4] = S01_AXI_awid;
    assign s_awaddr[1*40 +: 40] = S01_AXI_awaddr;
    assign s_awlen[1*8 +: 8] = S01_AXI_awlen;
    assign s_awsize[1*3 +: 3] = S01_AXI_awsize;
    assign s_awburst[1*2 +: 2] = S01_AXI_awburst;
    assign s_awvalid[1] = S01_AXI_awvalid;
    assign S01_AXI_awready = s_awready[1];
    assign s_wdata[1*512 +: 512] = S01_AXI_wdata;
    assign s_wstrb[1*64 +: 64] = S01_AXI_wstrb;
    assign s_wlast[1] = S01_AXI_wlast;
    assign s_wvalid[1] = S01_AXI_wvalid;
    assign S01_AXI_wready = s_wready[1];
    assign S01_AXI_bid = s_bid[1*4 +: 4];
    assign S01_AXI_bresp = s_bresp[1*2 +: 2];
    assign S01_AXI_bvalid = s_bvalid[1];
    assign s_bready[1] = S01_AXI_bready;
    assign s_arid[1*4 +: 4] = S01_AXI_arid;
    assign s_araddr[1*40 +: 40] = S01_AXI_araddr;
    assign s_arlen[1*8 +: 8] = S01_AXI_arlen;
    assign s_arsize[1*3 +: 3] = S01_AXI_arsize;
    assign s_arburst[1*2 +: 2] = S01_AXI_arburst;
    assign s_arvalid[1] = S01_AXI_arvalid;
    assign S01_AXI_arready = s_arready[1];
    assign S01_AXI_rid = s_rid[1*4 +: 4];
    assign S01_AXI_rdata = s_rdata[1*512 +: 512];
    assign S01_AXI_rresp = s_rresp[1*2 +: 2];
    assign S01_AXI_rlast = s_rlast[1];
    assign S01_AXI_rvalid = s_rvalid[1];
    assign s_rready[1] = S01_AXI_rready;

    assign s_awid[2*4 +: 4] = S02_AXI_awid;
    assign s_awaddr[2*40 +: 40] = S02_AXI_awaddr;
    assign s_awlen[2*8 +: 8] = S02_AXI_awlen;
    assign s_awsize[2*3 +: 3] = S02_AXI_awsize;
    assign s_awburst[2*2 +: 2] = S02_AXI_awburst;
    assign s_awvalid[2] = S02_AXI_awvalid;
    assign S02_AXI_awready = s_awready[2];
    assign s_wdata[2*512 +: 512] = S02_AXI_wdata;
    assign s_wstrb[2*64 +: 64] = S02_AXI_wstrb;
    assign s_wlast[2] = S02_AXI_wlast;
    assign s_wvalid[2] = S02_AXI_wvalid;
    assign S02_AXI_wready = s_wready[2];
    assign S02_AXI_bid = s_bid[2*4 +: 4];
    assign S02_AXI_bresp = s_bresp[2*2 +: 2];
    assign S02_AXI_bvalid = s_bvalid[2];
    assign s_bready[2] = S02_AXI_bready;
    assign s_arid[2*4 +: 4] = S02_AXI_arid;
    assign s_araddr[2*40 +: 40] = S02_AXI_araddr;
    assign s_arlen[2*8 +: 8] = S02_AXI_arlen;
    assign s_arsize[2*3 +: 3] = S02_AXI_arsize;
    assign s_arburst[2*2 +: 2] = S02_AXI_arburst;
    assign s_arvalid[2] = S02_AXI_arvalid;
    assign S02_AXI_arready = s_arready[2];
    assign S02_AXI_rid = s_rid[2*4 +: 4];
    assign S02_AXI_rdata = s_rdata[2*512 +: 512];
    assign S02_AXI_rresp = s_rresp[2*2 +: 2];
    assign S02_AXI_rlast = s_rlast[2];
    assign S02_AXI_rvalid = s_rvalid[2];
    assign s_rready[2] = S02_AXI_rready;

    assign s_awid[3*4 +: 4] = S03_AXI_awid;
    assign s_awaddr[3*40 +: 40] = S03_AXI_awaddr;
    assign s_awlen[3*8 +: 8] = S03_AXI_awlen;
    assign s_awsize[3*3 +: 3] = S03_AXI_awsize;
    assign s_awburst[3*2 +: 2] = S03_AXI_awburst;
    assign s_awvalid[3] = S03_AXI_awvalid;
    assign S03_AXI_awready = s_awready[3];
    assign s_wdata[3*512 +: 512] = S03_AXI_wdata;
    assign s_wstrb[3*64 +: 64] = S03_AXI_wstrb;
    assign s_wlast[3] = S03_AXI_wlast;
    assign s_wvalid[3] = S03_AXI_wvalid;
    assign S03_AXI_wready = s_wready[3];
    assign S03_AXI_bid = s_bid[3*4 +: 4];
    assign S03_AXI_bresp = s_bresp[3*2 +: 2];
    assign S03_AXI_bvalid = s_bvalid[3];
    assign s_bready[3] = S03_AXI_bready;
    assign s_arid[3*4 +: 4] = S03_AXI_arid;
    assign s_araddr[3*40 +: 40] = S03_AXI_araddr;
    assign s_arlen[3*8 +: 8] = S03_AXI_arlen;
    assign s_arsize[3*3 +: 3] = S03_AXI_arsize;
    assign s_arburst[3*2 +: 2] = S03_AXI_arburst;
    assign s_arvalid[3] = S03_AXI_arvalid;
    assign S03_AXI_arready = s_arready[3];
    assign S03_AXI_rid = s_rid[3*4 +: 4];
    assign S03_AXI_rdata = s_rdata[3*512 +: 512];
    assign S03_AXI_rresp = s_rresp[3*2 +: 2];
    assign S03_AXI_rlast = s_rlast[3];
    assign S03_AXI_rvalid = s_rvalid[3];
    assign s_rready[3] = S03_AXI_rready;

    assign M00_AXI_awid = d_awid[0*6 +: 6];
    assign M00_AXI_awaddr = {d_awaddr[0*40 + 40 - 1 : 0*40 + 34], 2'b0, d_awaddr[0*40 + 32 - 1 : 0*40]};
    assign M00_AXI_awlen = d_awlen[0*8 +: 8];
    assign M00_AXI_awsize = d_awsize[0*3 +: 3];
    assign M00_AXI_awburst = d_awburst[0*2 +: 2];
    assign M00_AXI_awvalid = d_awvalid[0];
    assign d_awready[0] = M00_AXI_awready;
    assign M00_AXI_wdata = d_wdata[0*512 +: 512];
    assign M00_AXI_wstrb = d_wstrb[0*64 +: 64];
    assign M00_AXI_wlast = d_wlast[0];
    assign M00_AXI_wvalid = d_wvalid[0];
    assign d_wready[0] = M00_AXI_wready;
    assign d_bid[0*6 +: 6] = M00_AXI_bid;
    assign d_bresp[0*2 +: 2] = M00_AXI_bresp;
    assign d_bvalid[0] = M00_AXI_bvalid;
    assign M00_AXI_bready = d_bready[0];
    assign M00_AXI_arid = d_arid[0*6 +: 6];
    assign M00_AXI_araddr = {d_araddr[0*40 + 40 - 1 : 0*40 + 34], 2'b0, d_araddr[0*40 + 32 - 1 : 0*40]};
    assign M00_AXI_arlen = d_arlen[0*8 +: 8];
    assign M00_AXI_arsize = d_arsize[0*3 +: 3];
    assign M00_AXI_arburst = d_arburst[0*2 +: 2];
    assign M00_AXI_arvalid = d_arvalid[0];
    assign d_arready[0] = M00_AXI_arready;
    assign d_rid[0*6 +: 6] = M00_AXI_rid;
    assign d_rdata[0*512 +: 512] = M00_AXI_rdata;
    assign d_rresp[0*2 +: 2] = M00_AXI_rresp;
    assign d_rlast[0] = M00_AXI_rlast;
    assign d_rvalid[0] = M00_AXI_rvalid;
    assign M00_AXI_rready = d_rready[0];

    assign M01_AXI_awid = d_awid[1*6 +: 6];
    assign M01_AXI_awaddr = {d_awaddr[1*40 + 40 - 1 : 1*40 + 34], 2'b0, d_awaddr[1*40 + 32 - 1 : 1*40]};
    assign M01_AXI_awlen = d_awlen[1*8 +: 8];
    assign M01_AXI_awsize = d_awsize[1*3 +: 3];
    assign M01_AXI_awburst = d_awburst[1*2 +: 2];
    assign M01_AXI_awvalid = d_awvalid[1];
    assign d_awready[1] = M01_AXI_awready;
    assign M01_AXI_wdata = d_wdata[1*512 +: 512];
    assign M01_AXI_wstrb = d_wstrb[1*64 +: 64];
    assign M01_AXI_wlast = d_wlast[1];
    assign M01_AXI_wvalid = d_wvalid[1];
    assign d_wready[1] = M01_AXI_wready;
    assign d_bid[1*6 +: 6] = M01_AXI_bid;
    assign d_bresp[1*2 +: 2] = M01_AXI_bresp;
    assign d_bvalid[1] = M01_AXI_bvalid;
    assign M01_AXI_bready = d_bready[1];
    assign M01_AXI_arid = d_arid[1*6 +: 6];
    assign M01_AXI_araddr = {d_araddr[1*40 + 40 - 1 : 1*40 + 34], 2'b0, d_araddr[1*40 + 32 - 1 : 1*40]};
    assign M01_AXI_arlen = d_arlen[1*8 +: 8];
    assign M01_AXI_arsize = d_arsize[1*3 +: 3];
    assign M01_AXI_arburst = d_arburst[1*2 +: 2];
    assign M01_AXI_arvalid = d_arvalid[1];
    assign d_arready[1] = M01_AXI_arready;
    assign d_rid[1*6 +: 6] = M01_AXI_rid;
    assign d_rdata[1*512 +: 512] = M01_AXI_rdata;
    assign d_rresp[1*2 +: 2] = M01_AXI_rresp;
    assign d_rlast[1] = M01_AXI_rlast;
    assign d_rvalid[1] = M01_AXI_rvalid;
    assign M01_AXI_rready = d_rready[1];

    assign M02_AXI_awid = d_awid[2*6 +: 6];
    assign M02_AXI_awaddr = {d_awaddr[2*40 + 40 - 1 : 2*40 + 34], 2'b0, d_awaddr[2*40 + 32 - 1 : 2*40]};
    assign M02_AXI_awlen = d_awlen[2*8 +: 8];
    assign M02_AXI_awsize = d_awsize[2*3 +: 3];
    assign M02_AXI_awburst = d_awburst[2*2 +: 2];
    assign M02_AXI_awvalid = d_awvalid[2];
    assign d_awready[2] = M02_AXI_awready;
    assign M02_AXI_wdata = d_wdata[2*512 +: 512];
    assign M02_AXI_wstrb = d_wstrb[2*64 +: 64];
    assign M02_AXI_wlast = d_wlast[2];
    assign M02_AXI_wvalid = d_wvalid[2];
    assign d_wready[2] = M02_AXI_wready;
    assign d_bid[2*6 +: 6] = M02_AXI_bid;
    assign d_bresp[2*2 +: 2] = M02_AXI_bresp;
    assign d_bvalid[2] = M02_AXI_bvalid;
    assign M02_AXI_bready = d_bready[2];
    assign M02_AXI_arid = d_arid[2*6 +: 6];
    assign M02_AXI_araddr = {d_araddr[2*40 + 40 - 1 : 2*40 + 34], 2'b0, d_araddr[2*40 + 32 - 1 : 2*40]};
    assign M02_AXI_arlen = d_arlen[2*8 +: 8];
    assign M02_AXI_arsize = d_arsize[2*3 +: 3];
    assign M02_AXI_arburst = d_arburst[2*2 +: 2];
    assign M02_AXI_arvalid = d_arvalid[2];
    assign d_arready[2] = M02_AXI_arready;
    assign d_rid[2*6 +: 6] = M02_AXI_rid;
    assign d_rdata[2*512 +: 512] = M02_AXI_rdata;
    assign d_rresp[2*2 +: 2] = M02_AXI_rresp;
    assign d_rlast[2] = M02_AXI_rlast;
    assign d_rvalid[2] = M02_AXI_rvalid;
    assign M02_AXI_rready = d_rready[2];

    assign M03_AXI_awid = d_awid[3*6 +: 6];
    assign M03_AXI_awaddr = {d_awaddr[3*40 + 40 - 1 : 3*40 + 34], 2'b0, d_awaddr[3*40 + 32 - 1 : 3*40]};
    assign M03_AXI_awlen = d_awlen[3*8 +: 8];
    assign M03_AXI_awsize = d_awsize[3*3 +: 3];
    assign M03_AXI_awburst = d_awburst[3*2 +: 2];
    assign M03_AXI_awvalid = d_awvalid[3];
    assign d_awready[3] = M03_AXI_awready;
    assign M03_AXI_wdata = d_wdata[3*512 +: 512];
    assign M03_AXI_wstrb = d_wstrb[3*64 +: 64];
    assign M03_AXI_wlast = d_wlast[3];
    assign M03_AXI_wvalid = d_wvalid[3];
    assign d_wready[3] = M03_AXI_wready;
    assign d_bid[3*6 +: 6] = M03_AXI_bid;
    assign d_bresp[3*2 +: 2] = M03_AXI_bresp;
    assign d_bvalid[3] = M03_AXI_bvalid;
    assign M03_AXI_bready = d_bready[3];
    assign M03_AXI_arid = d_arid[3*6 +: 6];
    assign M03_AXI_araddr = {d_araddr[3*40 + 40 - 1 : 3*40 + 34], 2'b0, d_araddr[3*40 + 32 - 1 : 3*40]};
    assign M03_AXI_arlen = d_arlen[3*8 +: 8];
    assign M03_AXI_arsize = d_arsize[3*3 +: 3];
    assign M03_AXI_arburst = d_arburst[3*2 +: 2];
    assign M03_AXI_arvalid = d_arvalid[3];
    assign d_arready[3] = M03_AXI_arready;
    assign d_rid[3*6 +: 6] = M03_AXI_rid;
    assign d_rdata[3*512 +: 512] = M03_AXI_rdata;
    assign d_rresp[3*2 +: 2] = M03_AXI_rresp;
    assign d_rlast[3] = M03_AXI_rlast;
    assign d_rvalid[3] = M03_AXI_rvalid;
    assign M03_AXI_rready = d_rready[3];

    kx_xache #(.M(M), .N_HOME(N), .AW(AW), .W(W), .ID_W(ID_W), .HOME_LSB(HOME_LSB),
               .SETS(SETS), .SET_W(SET_W), .K(K), .RAM_STYLE(RAM_STYLE), .BANKS(BANKS),
               .MCDC({M{1'b0}}), .HCDC({N{1'b1}}), .RSAMD(RSAMD), .WSAMD(WSAMD),
               .CDC_DEPTH(CDC_DEPTH), .NSWAP(NSWAP),
               .SWAP_A(SWAP_A[((NSWAP < 1) ? 1 : NSWAP)*8-1:0]),
               .SWAP_B(SWAP_B[((NSWAP < 1) ? 1 : NSWAP)*8-1:0]),
               .RD_PIPE(RD_PIPE), .RD_OUTQ(RD_OUTQ), .SLRX(SLRX)) u_kx (
        .clk(aclk), .rstn_h({d_rstn3, d_rstn2, d_rstn1, d_rstn0}), .rstn_m({d_rstn3, d_rstn2, d_rstn1, d_rstn0}),
        .m_clk({M{aclk}}), .m_rstn({d_rstn3, d_rstn2, d_rstn1, d_rstn0}),
        .h_clk({h_clk3, h_clk2, h_clk1, h_clk0}), .h_rstn({h_rstn3, h_rstn2, h_rstn1, h_rstn0}),
        .s_awid(s_awid), .s_awaddr(s_awaddr), .s_awlen(s_awlen), .s_awsize(s_awsize), .s_awburst(s_awburst),
        .s_awvalid(s_awvalid), .s_awready(s_awready), .s_wdata(s_wdata), .s_wstrb(s_wstrb), .s_wlast(s_wlast),
        .s_wvalid(s_wvalid), .s_wready(s_wready), .s_bid(s_bid), .s_bresp(s_bresp), .s_bvalid(s_bvalid),
        .s_bready(s_bready), .s_arid(s_arid), .s_araddr(s_araddr), .s_arlen(s_arlen), .s_arsize(s_arsize),
        .s_arburst(s_arburst), .s_arvalid(s_arvalid), .s_arready(s_arready), .s_rid(s_rid), .s_rdata(s_rdata),
        .s_rresp(s_rresp), .s_rlast(s_rlast), .s_rvalid(s_rvalid), .s_rready(s_rready), .d_awid(d_awid),
        .d_awaddr(d_awaddr), .d_awlen(d_awlen), .d_awsize(d_awsize), .d_awburst(d_awburst), .d_awvalid(d_awvalid),
        .d_awready(d_awready), .d_wdata(d_wdata), .d_wstrb(d_wstrb), .d_wlast(d_wlast), .d_wvalid(d_wvalid),
        .d_wready(d_wready), .d_bid(d_bid), .d_bresp(d_bresp), .d_bvalid(d_bvalid), .d_bready(d_bready),
        .d_arid(d_arid), .d_araddr(d_araddr), .d_arlen(d_arlen), .d_arsize(d_arsize), .d_arburst(d_arburst),
        .d_arvalid(d_arvalid), .d_arready(d_arready), .d_rid(d_rid), .d_rdata(d_rdata), .d_rresp(d_rresp),
        .d_rlast(d_rlast), .d_rvalid(d_rvalid), .d_rready(d_rready)
    );
endmodule

`default_nettype wire
