# Floorplan, clock groups and board pins, written out as XDC. Nothing here can
# check itself: XDC rejects `if`, so every assertion lives in 70_analyze.tcl.

file mkdir $root/build
set top ${design_name}_i

# ---- board pins ----------------------------------------------------------
proc v8_board {name} {
    global BOARD_DIR
    if {![file exists $BOARD_DIR/$name]} { error "missing board XDC: $BOARD_DIR/$name" }
    return $BOARD_DIR/$name
}
# import_files COPIES into the project, so a rebuild adds a SECOND copy of each
# board file every time unless the one already there is found first.
proc v8_import {name} {
    if {[llength [get_files -quiet -of_objects [get_filesets constrs_1] *$name]]} {
        return
    }
    import_files -fileset constrs_1 -norecurse [v8_board $name]
}
foreach i {0 1 2 3} { v8_import ddr4_c${i}.xdc }
v8_import pcie.xdc

# ---- pblocks -------------------------------------------------------------
set xdc $root/build/${design_name}_pblocks.xdc
set fh [open $xdc w]
puts $fh "# GENERATED by scripts/tcl/v8/60_constraints.tcl"
set ::V8_PB {}
proc v8_pin {fh pb cell} {
    puts $fh "add_cells_to_pblock \[get_pblocks $pb\] \[get_cells -quiet \{$cell\}\]"
    lappend ::V8_PB [list $pb $cell]
}
# The Xache is one module whose slices live on four dies: home h's array,
# engines, W select, DRAM edge and the receiving half of every crossing INTO
# it sit in SLR h; master m's edge, aggregation, permutation and the sending
# half of every crossing FROM it sit in SLR m. A kx_slrx spans two dies by
# design, so its u_tx and u_rx are pinned separately.
set KX $top/xache/inst/u_kx
foreach {mid mod} $MESHES {
    set ddr [dict get $DDR_OF_SLR $mid]
    lassign [dict get $SLR_ROWS $mid] ylo yhi
    puts $fh "create_pblock pb_slr$mid"
    puts $fh "resize_pblock \[get_pblocks pb_slr$mid\] -add \{CLOCKREGION_X0${ylo}:CLOCKREGION_X7${yhi}\}"
    # g_link is deliberately absent -- its pipeline registers ARE the die
    # crossing and must be free to place across it; so are the interlink pipes.
    set cells [list station_bus/inst/u_line/g_stn\[$mid\].* \
                    clk_wiz_mesh$mid \
                    clk_wiz_bus$mid rst_bus$mid bus_rst_inv$mid \
                    mesh_$mid ddr4_$ddr rst_ddr4_$ddr \
                    div2_mesh$mid dclr_mesh$mid dwc_ctrl$mid]
    foreach c $cells { v8_pin $fh pb_slr$mid $top/$c }
    # the Xache, home side. Not listed because synthesis leaves no cell for
    # them: turn_q (constant under SLRX), g_medge (MCDC 0: wires), g_route
    # (kx_perm: wires); g_wsel's LUTs dissolve into u_kx and are claimed below.
    foreach c [list g_carray\[$mid\].* g_rd\[$mid\].g_pipe.* \
                    g_wr\[$mid\].u_we g_hedge\[$mid\].*] {
        v8_pin $fh pb_slr$mid $KX/$c
    }
    # the Xache, master side
    foreach c [list g_agg\[$mid\].* g_wh\[$mid\].*] {
        v8_pin $fh pb_slr$mid $KX/$c
    }
    # crossings: requests m -> h send from m, land in h; responses the reverse
    foreach {h2 m2} $MESHES {
        v8_pin $fh pb_slr$mid $KX/g_slot\[*\].g_m\[$mid\].g_x.u_*/u_tx
        v8_pin $fh pb_slr$mid $KX/g_slot\[$mid\].g_m\[*\].g_x.u_*/u_rx
        v8_pin $fh pb_slr$mid $KX/g_rd\[$mid\].g_rtx.g_m\[*\].u_r/u_tx
        v8_pin $fh pb_slr$mid $KX/g_rd\[*\].g_rtx.g_m\[$mid\].u_r/u_rx
        v8_pin $fh pb_slr$mid $KX/g_wr\[$mid\].g_btx.g_m\[*\].u_b/u_tx
        v8_pin $fh pb_slr$mid $KX/g_wr\[*\].g_btx.g_m\[$mid\].u_b/u_rx
        break
    }
    # die i's copy of the sysnode reset: landing and fan-out registers here,
    # the sending register with the source (below)
    v8_pin $fh pb_slr$mid $top/rst_tree/inst/land_reg\[$mid\]
    v8_pin $fh pb_slr$mid $top/rst_tree/inst/fan_reg\[$mid\]
    puts $fh "set_property CONTAIN_ROUTING false \[get_pblocks pb_slr$mid\]"
}
# The sysnode clock's reset lives with its generator, and so do the tree's
# four sending registers; each pair is a Laguna crossing where it crosses.
v8_pin $fh pb_slr$SYS_WIZ $top/rst_sys
foreach {mid mod} $MESHES {
    v8_pin $fh pb_slr$SYS_WIZ $top/rst_tree/inst/q_reg\[$mid\]
    if {$mid != $SYS_WIZ} {
        puts $fh "set_property USER_SLL_REG TRUE \[get_cells -quiet \{$top/rst_tree/inst/q_reg\[$mid\] $top/rst_tree/inst/land_reg\[$mid\]\}\]"
    }
}
# PCIE40E4_X0Y1 and the AY23 reference are both in SLR1, so the fabric half of
# XDMA and the clock root belong there too. xlconstant_irq is NOT pinned:
# synthesis dissolves a constant into a tie-off and the path resolves empty.
foreach c {xdma_0 jtag_ctrl clk_wiz_ctrl rst_ctrl \
           util_ds_buf_bufg util_ds_buf_sys util_ds_buf_pcie} {
    v8_pin $fh pb_slr1 $top/$c
}
close $fh
if {![llength [get_files -quiet -of_objects [get_filesets constrs_1] $xdc]]} {
    add_files -fileset constrs_1 -norecurse $xdc
}

# ---- clocks --------------------------------------------------------------
set clk $root/build/${design_name}_clocks.xdc
set fh [open $clk w]
puts $fh "# GENERATED by scripts/tcl/v8/60_constraints.tcl"
puts $fh "create_clock -name sys_clk -period 10.000 \[get_ports system_clk_p\]"
puts $fh "set_property IOSTANDARD DIFF_SSTL12 \[get_ports system_clk_p\]"
puts $fh "set_property IOSTANDARD DIFF_SSTL12 \[get_ports system_clk_n\]"
puts $fh "set_property PACKAGE_PIN AY23 \[get_ports system_clk_p\]"
puts $fh "set_property PACKAGE_PIN BD20 \[get_ports user_lnk_up\]"
puts $fh "set_property IOSTANDARD LVCMOS12 \[get_ports user_lnk_up\]"
# Ten MMCMs on one reference; rule_bufg_mmcm_3loads caps a BUFGCE at three.
puts $fh "set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN \[get_nets -of \[get_pins $top/clk_wiz_ctrl/clk_in1\]\]"

# Groups: per die {noc, vec} and {mat 2x} (the units reach the NoC through
# async FIFOs at UNIT_CDC=1); the sysnode clock alone (MAG_CDC=1 crosses NoC
# <-> node, kx_scdc crosses Xache <-> MIG); each bus; ctrl; each MIG; XDMA.
set ::V8_CLKPINS {}
proc v8_group {wiz outs} {
    set pins {}
    foreach o $outs { lappend pins "$::top/$wiz/$o" }
    lappend ::V8_CLKPINS {*}$pins
    return " \\\n    -group \[get_clocks -include_generated_clocks -of_objects\
 \[get_pins \{$pins\}\]\]"
}
set grp {}
foreach {mid mod} $MESHES {
    append grp [v8_group clk_wiz_mesh$mid {clk_out1 clk_out3}]
    append grp [v8_group clk_wiz_mesh$mid {clk_out2}]
    append grp [v8_group clk_wiz_bus$mid  {clk_out1}]
}
append grp [v8_group clk_wiz_mesh$SYS_WIZ {clk_out4}]
append grp [v8_group clk_wiz_ctrl {clk_out1}]
foreach i {0 1 2 3} { append grp [v8_group ddr4_$i {c0_ddr4_ui_clk}] }
append grp [v8_group xdma_0 {axi_aclk}]
append grp " \\\n    -group \[get_clocks -include_generated_clocks pcie_refclk\]"
puts $fh "set_clock_groups -asynchronous$grp"
close $fh
if {![llength [get_files -quiet -of_objects [get_filesets constrs_1] $clk]]} {
    add_files -fileset constrs_1 -norecurse $clk
}
# LATE, or the clk_wiz generated clocks do not exist yet and every group
# matches nothing.
set_property PROCESSING_ORDER LATE \
    [get_files -of_objects [get_filesets constrs_1] */${design_name}_clocks.xdc]

# Vivado parses EVERY enabled xdc and they ADD rather than replace.
foreach pat {*multimesh_v*_clocks.xdc *multimesh_v*_pblocks.xdc
             */JTAG-DMA-test/pblocks.xdc *sysytem.xdc} {
    foreach f [get_files -quiet -of_objects [get_filesets constrs_1] $pat] {
        if {[string match ${design_name}_* [file tail $f]]} { continue }
        if {[get_property is_enabled $f]} {
            set_property is_enabled false $f
            puts "@@@ disabled stale constraint: [file tail $f]"
        }
    }
}
puts "@@@ v8 constraints: [llength $::V8_PB] pblock cells, [llength $::V8_CLKPINS] clock pins"
