kohakumpe/simd/generated/khs_isa.vh
kohakumpe/simd/generated/khs_seed_tab.v
kohakumpe/simd/khs_facc.v
kohakumpe/simd/khs_fcvt.v
kohakumpe/simd/khs_ffold.v
kohakumpe/simd/khs_fp32_alu.v
kohakumpe/simd/khs_fp32_sfu.v
kohakumpe/simd/khs_lane.v
kohakumpe/simd/khs_lead1.v
kohakumpe/simd/khs_mul.v
kohakumpe/simd/khs_padd32.v
kohakumpe/simd/khs_perm.v
kohakumpe/simd/khs_pshift32.v
kohakumpe/simd/khs_reduce.v
kohakumpe/simd/khs_scalar_decode.v
kohakumpe/simd/khs_unit.v
kohakumpe/simd/khs_vregfile.v
kohakumpe/simd/khs_vspad.v
