// khs_fp32_sfu -- exp2, log2, rcp and rsqrt over IEEE binary32.
//
// KOHAKUMPE'S OWN AND FP32 THROUGHOUT. `vec_alu`'s HAS_POLY path computes the
// same four functions in E8M15 with 15 mantissa bits, which is 256x coarser
// than binary32 and cannot serve a D3D11 rcp/rsq at 1 ULP. Nothing here is
// shared with the vector core and the vector core is not modified.
//
// ONE BACKEND FOR FOUR FUNCTIONS. Each produces a fixed-point magnitude in a
// 40-bit field at 32 fraction bits plus a signed exponent base, so
// `biased_exp = lead1(mag) + ebase` closes for all of them and the unit holds
// one leading-one search, one normalising shift and one rounder:
//
//     exp2    mag = 2^frac(x) * 2^32        ebase =  95 + floor(x)
//     log2    mag = |(E << 32) + L|         ebase =  95
//     rcp     mag = (1/1.m) * 2^32          ebase = 222 - e
//     rsqrt   mag = 2^(-r/2)/sqrt(1.m)*2^32 ebase =  95 - floor((e-127)/2)
//
// THE POLYNOMIAL IS INTEGER AND THE MODEL RUNS THE SAME EXPRESSION:
//
//     Q = C0 + (((C1 + ((C2 * U) >> 22)) * U) >> 20)
//
// with `t = U * 2^-30` in every function, which is what keeps those two shifts
// constants. 512 segments each, 1024 for rsqrt's two octaves. The table is
// generated by tests/pe/tools/khs_seed_emit.py, which also measures the ULP
// error; C0 is the exact value at each segment's origin, so exp2(k),
// log2(2^k), rcp(2^k) and rsqrt(2^2k) come out exact.
//
// LATENCY 10, against rv_fpu's 6. khs_fp32_alu pads the FMA path by 4 when seed
// units are built and by nothing when they are not.

`default_nettype none

module khs_fp32_sfu (
    input  wire        clk,
    input  wire        rst,
    input  wire        in_valid,
    // 0 exp2, 1 log2, 2 rcp, 3 rsqrt -- the FSFU opcode's low two bits in both
    // ISAs, so neither caller needs a translation.
    input  wire [1:0]  fsel,
    input  wire [31:0] a,
    output wire        out_valid,
    output wire [31:0] y
);
    localparam [1:0] F_EXP2 = 2'd0, F_LOG2 = 2'd1;
    localparam [1:0] F_INV = 2'd2, F_RSQRT = 2'd3;

    localparam [31:0] F32_QNAN = 32'h7FC0_0000;

    // ---- stage 1: capture ---------------------------------------------------
    reg [31:0] s1_a;
    reg [1:0]  s1_f;
    reg        s1_v;
    always @(posedge clk) begin
        s1_v <= !rst && in_valid;
        s1_a <= a;
        s1_f <= fsel;
    end

    // ---- cycle 1: unpack, classify, exp2 range reduction --------------------
    wire        sa  = s1_a[31];
    wire [7:0]  ea  = s1_a[30:23];
    wire [22:0] ma  = s1_a[22:0];
    wire [23:0] sga = (ea == 8'd0) ? 24'd0 : {1'b1, ma};

    wire a_nan = (ea == 8'hFF) && (ma != 23'd0);
    wire a_inf = (ea == 8'hFF) && (ma == 23'd0);
    wire a_zro = (ea == 8'd0);
    wire a_neg = sa && !a_zro;              // -0 is NOT negative here

    // R = x * 2^30 as ONE right shift: the bias absorbs the direction, and
    // e >= 134 cannot reach here because it is a special.
    wire [7:0]  rr_raw = 8'd133 - ea;
    wire [5:0]  rr_sh  = (ea >= 8'd133) ? 6'd0
                       : (rr_raw > 8'd38) ? 6'd38 : rr_raw[5:0];
    wire [37:0] rr_fld = {sga, 14'b0} >> rr_sh;

    // K = floor((e-127)/2). An arithmetic shift is floor for both signs, which
    // is what makes odd and even exponents one expression.
    wire signed [9:0] rs_k = ($signed({2'b0, ea}) - 10'sd127) >>> 1;

    reg s_nan, s_inf, s_zro, s_sgn;
    always @(*) begin
        case (s1_f)
            F_EXP2: begin
                s_nan = a_nan;
                s_inf = !a_nan && !sa && (a_inf || (ea >= 8'd134));
                s_zro = !a_nan &&  sa && (a_inf || (ea >= 8'd134));
                s_sgn = 1'b0;
            end
            F_LOG2: begin
                s_nan = a_nan || a_neg;
                s_inf = !(a_nan || a_neg) && (a_inf || a_zro);
                s_zro = 1'b0;
                s_sgn = a_zro;
            end
            F_INV: begin
                s_nan = a_nan;
                s_inf = !a_nan && a_zro;
                s_zro = !a_nan && a_inf;
                s_sgn = sa;
            end
            default: begin
                // rsqrt(-0) IS -inf: IEEE gives sqrt(+-0) = +-0, so 1/sqrt(-0)
                // is 1/-0. Only -0 reaches `s_sgn` here.
                s_nan = a_nan || a_neg;
                s_inf = !(a_nan || a_neg) && a_zro;
                s_zro = !(a_nan || a_neg) && a_inf;
                s_sgn = sa && a_zro;
            end
        endcase
    end

    reg [37:0] s2_fld;
    reg [22:0] s2_ma;
    reg [7:0]  s2_ea;
    reg [1:0]  s2_f;
    reg        s2_v, s2_sa;
    reg        s2_nan, s2_inf, s2_zro, s2_sgn;
    reg signed [9:0] s2_k;
    always @(posedge clk) begin
        s2_v   <= !rst && s1_v;
        s2_fld <= rr_fld;
        s2_ma  <= ma;
        s2_ea  <= ea;
        s2_sa  <= sa;
        s2_f   <= s1_f;
        s2_k   <= rs_k;
        s2_nan <= s_nan;
        s2_inf <= s_inf;
        s2_zro <= s_zro;
        s2_sgn <= s_sgn;
    end

    // ---- cycle 2: finish the reduction, form the table address --------------
    // Round to 30 fraction bits, then negate: -(R+g) is what turns
    // 2^x = 2^floor(x) * 2^frac(x) into one two's complement, with frac in
    // [0,1) for a negative argument and no separate compare.
    wire [37:0] rr_pos = {1'b0, s2_fld[37:1]} + {37'b0, s2_fld[0]};
    wire signed [38:0] rr_v = s2_sa ? -$signed({1'b0, rr_pos})
                                    :  $signed({1'b0, rr_pos});
    wire signed [8:0]  ex_k = rr_v[38:30];
    wire [29:0]        ex_f = rr_v[29:0];

    // 512 SEGMENTS, not 256: the quadratic's error falls with the cube of the
    // segment width, and at 256 rcp and rsqrt measured 1.98 and 1.84 ULP
    // against D3D11's 1 ULP bar. Halving the segment is 8x and costs BRAM only.
    // `u_c` keeps its 22-bit port with the top bit zero, so every product and
    // shift below is the width it was.
    wire       par = ~s2_ea[0];
    wire [9:0] idx_c = (s2_f == F_EXP2)  ? {1'b0, ex_f[29:21]}
                     : (s2_f == F_RSQRT) ? {par,  s2_ma[22:14]}
                                         : {1'b0, s2_ma[22:14]};
    wire [21:0] u_c = (s2_f == F_EXP2) ? {1'b0, ex_f[20:0]}
                                       : {1'b0, s2_ma[13:0], 7'b0};

    wire signed [11:0] eb_exp2 = 12'sd95 + $signed({{3{ex_k[8]}}, ex_k});
    wire signed [11:0] eb_inv  = 12'sd222 - $signed({4'b0, s2_ea});
    wire signed [11:0] eb_rsq  = 12'sd95 - $signed({{2{s2_k[9]}}, s2_k});
    wire signed [11:0] ebase_c = (s2_f == F_EXP2) ? eb_exp2
                               : (s2_f == F_LOG2) ? 12'sd95
                               : (s2_f == F_INV)  ? eb_inv : eb_rsq;

    wire signed [8:0] e_int_c = $signed({1'b0, s2_ea}) - 9'sd127;
    wire              sign_c  = (s2_f == F_INV) ? s2_sa : 1'b0;

    wire signed [33:0] c0;
    wire signed [23:0] c1;
    wire signed [15:0] c2;
    khs_seed_tab u_tab (
        .clk(clk), .fsel(s2_f), .idx(idx_c), .c0(c0), .c1(c1), .c2(c2)
    );

    reg [21:0] s3_u;
    reg [1:0]  s3_f;
    reg        s3_v, s3_sign;
    reg        s3_nan, s3_inf, s3_zro, s3_sgn;
    reg signed [11:0] s3_eb;
    reg signed [8:0]  s3_ei;
    always @(posedge clk) begin
        s3_v    <= !rst && s2_v;
        s3_u    <= u_c;
        s3_f    <= s2_f;
        s3_eb   <= ebase_c;
        s3_ei   <= e_int_c;
        s3_sign <= sign_c;
        s3_nan  <= s2_nan;
        s3_inf  <= s2_inf;
        s3_zro  <= s2_zro;
        s3_sgn  <= s2_sgn;
    end

    // ---- cycles 3..6: the quadratic ----------------------------------------
    (* use_dsp = "yes" *)
    wire signed [38:0] p1_c = c2 * $signed({1'b0, s3_u});

    reg signed [38:0] s4_p1;
    reg signed [33:0] s4_c0;
    reg signed [23:0] s4_c1;
    reg [21:0] s4_u;
    reg [1:0]  s4_f;
    reg        s4_v, s4_sign, s4_nan, s4_inf, s4_zro, s4_sgn;
    reg signed [11:0] s4_eb;
    reg signed [8:0]  s4_ei;
    always @(posedge clk) begin
        s4_v    <= !rst && s3_v;
        s4_p1   <= p1_c;
        s4_c0   <= c0;
        s4_c1   <= c1;
        s4_u    <= s3_u;
        s4_f    <= s3_f;
        s4_eb   <= s3_eb;
        s4_ei   <= s3_ei;
        s4_sign <= s3_sign;
        s4_nan  <= s3_nan;
        s4_inf  <= s3_inf;
        s4_zro  <= s3_zro;
        s4_sgn  <= s3_sgn;
    end

    wire signed [24:0] h_c = ({{1{s4_c1[23]}}, s4_c1}
                              + {{8{s4_p1[38]}}, s4_p1[38:22]});

    reg signed [24:0] s5_h;
    reg signed [33:0] s5_c0;
    reg [21:0] s5_u;
    reg [1:0]  s5_f;
    reg        s5_v, s5_sign, s5_nan, s5_inf, s5_zro, s5_sgn;
    reg signed [11:0] s5_eb;
    reg signed [8:0]  s5_ei;
    always @(posedge clk) begin
        s5_v    <= !rst && s4_v;
        s5_h    <= h_c;
        s5_c0   <= s4_c0;
        s5_u    <= s4_u;
        s5_f    <= s4_f;
        s5_eb   <= s4_eb;
        s5_ei   <= s4_ei;
        s5_sign <= s4_sign;
        s5_nan  <= s4_nan;
        s5_inf  <= s4_inf;
        s5_zro  <= s4_zro;
        s5_sgn  <= s4_sgn;
    end

    (* use_dsp = "yes" *)
    wire signed [47:0] p2_c = s5_h * $signed({1'b0, s5_u});

    reg signed [47:0] s6_p2;
    reg signed [33:0] s6_c0;
    reg [1:0]  s6_f;
    reg        s6_v, s6_sign, s6_nan, s6_inf, s6_zro, s6_sgn;
    reg signed [11:0] s6_eb;
    reg signed [8:0]  s6_ei;
    always @(posedge clk) begin
        s6_v    <= !rst && s5_v;
        s6_p2   <= p2_c;
        s6_c0   <= s5_c0;
        s6_f    <= s5_f;
        s6_eb   <= s5_eb;
        s6_ei   <= s5_ei;
        s6_sign <= s5_sign;
        s6_nan  <= s5_nan;
        s6_inf  <= s5_inf;
        s6_zro  <= s5_zro;
        s6_sgn  <= s5_sgn;
    end

    // ---- cycle 6: the value, and log2's integer part ------------------------
    wire signed [35:0] q_c = ({{2{s6_c0[33]}}, s6_c0}
                              + {{8{s6_p2[47]}}, s6_p2[47:20]});
    wire signed [40:0] q_ext = {{5{q_c[35]}}, q_c};
    wire signed [40:0] e_sh  = {s6_ei, 32'b0};
    wire signed [40:0] w_c   = (s6_f == F_LOG2) ? (e_sh + q_ext) : q_ext;
    wire        w_neg = w_c[40];
    wire [39:0] mag_c = w_neg ? (~w_c[39:0] + 40'd1) : w_c[39:0];
    wire        sgn_c = (s6_f == F_LOG2) ? w_neg : s6_sign;

    reg [39:0] s7_mag;
    reg        s7_v, s7_sign, s7_nan, s7_inf, s7_zro, s7_sgn;
    reg signed [11:0] s7_eb;
    always @(posedge clk) begin
        s7_v    <= !rst && s6_v;
        s7_mag  <= mag_c;
        s7_eb   <= s6_eb;
        s7_sign <= sgn_c;
        s7_nan  <= s6_nan;
        s7_inf  <= s6_inf;
        s7_zro  <= s6_zro;
        s7_sgn  <= s6_sgn;
    end

    // ---- cycles 7..9: normalise, round, pack --------------------------------
    wire [5:0] lz_pos;
    wire       lz_nz;
    khs_lead1 #(.W(40)) u_l1 (.x(s7_mag), .pos(lz_pos), .nz(lz_nz));

    reg [39:0] s8_mag;
    reg [5:0]  s8_pos;
    reg        s8_v, s8_nz, s8_sign, s8_nan, s8_inf, s8_zro, s8_sgn;
    reg signed [11:0] s8_eb;
    always @(posedge clk) begin
        s8_v    <= !rst && s7_v;
        s8_mag  <= s7_mag;
        s8_pos  <= lz_pos;
        s8_nz   <= lz_nz;
        s8_eb   <= s7_eb;
        s8_sign <= s7_sign;
        s8_nan  <= s7_nan;
        s8_inf  <= s7_inf;
        s8_zro  <= s7_zro;
        s8_sgn  <= s7_sgn;
    end

    wire [39:0] nrm_c = s8_mag << (6'd39 - s8_pos);

    reg [39:0] s9_nrm;
    reg [5:0]  s9_pos;
    reg        s9_v, s9_nz, s9_sign, s9_nan, s9_inf, s9_zro, s9_sgn;
    reg signed [11:0] s9_eb;
    always @(posedge clk) begin
        s9_v    <= !rst && s8_v;
        s9_nrm  <= nrm_c;
        s9_pos  <= s8_pos;
        s9_nz   <= s8_nz;
        s9_eb   <= s8_eb;
        s9_sign <= s8_sign;
        s9_nan  <= s8_nan;
        s9_inf  <= s8_inf;
        s9_zro  <= s8_zro;
        s9_sgn  <= s8_sgn;
    end

    // ---- cycle 10: round and pack ------------------------------------------
    // REGISTERED, AND THAT IS A TIMING FIX. Left downstream of s9 this tail was
    // the SIMT PE's binding path -- 16 logic levels and 7 CARRY8 from s9_nrm to
    // the vector file's write port for -0.347 ns, holding a 387 MHz core to
    // 271.7 -- because the 25-bit round, the 12-bit exponent add and both range
    // compares all landed after the last register.
    wire [23:0] keep  = s9_nrm[39:16];
    wire        guard = s9_nrm[15];
    wire        stick = |s9_nrm[14:0];
    wire        rnd_up = guard & (stick | keep[0]);
    wire [24:0] sig_r  = {1'b0, keep} + {24'b0, rnd_up};
    wire        carry  = sig_r[24];
    wire [22:0] frac   = carry ? sig_r[23:1] : sig_r[22:0];

    wire signed [11:0] e_fin = (s9_eb + $signed({6'b0, s9_pos})
                               + (carry ? 12'sd1 : 12'sd0));

    reg [22:0] sa_frac;
    reg [7:0]  sa_exp;
    reg        sa_v, sa_sign, sa_nan, sa_inf, sa_zro, sa_nz, sa_sgn;
    reg        sa_ovf, sa_unf;
    always @(posedge clk) begin
        sa_v    <= !rst && s9_v;
        sa_frac <= frac;
        sa_exp  <= e_fin[7:0];
        sa_ovf  <= (e_fin >= 12'sd255);
        sa_unf  <= (e_fin <= 12'sd0);
        sa_sign <= s9_sign;
        sa_nan  <= s9_nan;
        sa_inf  <= s9_inf;
        sa_zro  <= s9_zro;
        sa_nz   <= s9_nz;
        sa_sgn  <= s9_sgn;
    end

    assign y = sa_nan  ? F32_QNAN
             : sa_inf  ? {sa_sgn, 8'hFF, 23'd0}
             : sa_zro  ? {sa_sgn, 31'd0}
             : !sa_nz  ? {sa_sign, 31'd0}
             : sa_ovf  ? {sa_sign, 8'hFF, 23'd0}
             : sa_unf  ? {sa_sign, 31'd0}
                       : {sa_sign, sa_exp, sa_frac};
    assign out_valid = sa_v;
endmodule

`default_nettype wire
