// sb_p6x9f512 -- GENERATED by scripts/py/gen_station_wrap.py. Do not edit by hand.
//   gen_station_wrap.py --kind root --nk 6 --mgr-w 512,512,512,512,512,512 --loc-w 512,512,512,512,512,512,512,512,512 --fw 512 --aw 43 -o C:\Users\apoll\Desktop\code\Project\KohakuTPU\src\synth_top\sb_p6x9f512.v -m sb_p6x9f512
//
// The root station with every interface named so a block design infers it:
// 6 AXI4 slaves, 9 local AXI4 masters, 6 AXIS links to other stations.
// The logic is all in sb_stn_root.v; this file is declarations and assigns.

`default_nettype none

module sb_p6x9f512 #(
    parameter integer OST          = 4,
    parameter integer STORE_FWD    = 1,
    parameter integer LUT_PER_BRAM = 0,
    parameter integer TIMEOUT      = 0
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 bus_clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF L0_REQ:L0_RSP:L1_REQ:L1_RSP:L2_REQ:L2_RSP:L3_REQ:L3_RSP:L4_REQ:L4_RSP:L5_REQ:L5_RSP, ASSOCIATED_RESET bus_rst" *)
    input  wire bus_clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 bus_rst RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_HIGH" *)
    input  wire bus_rst,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_ctrl CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S00_AXI, ASSOCIATED_RESET aresetn_ctrl" *)
    input  wire clk_ctrl,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_ctrl RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_ctrl,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_xdma CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S01_AXI:S02_AXI:S03_AXI:S04_AXI:S05_AXI, ASSOCIATED_RESET aresetn_xdma" *)
    input  wire clk_xdma,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_xdma RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_xdma,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_loc CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M00_AXI:M01_AXI:M02_AXI:M03_AXI:M04_AXI:M05_AXI:M06_AXI:M07_AXI:M08_AXI, ASSOCIATED_RESET aresetn_loc" *)
    input  wire clk_loc,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_loc RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_loc,

    input  wire [4-1:0] S00_AXI_awid,
    input  wire [43-1:0] S00_AXI_awaddr,
    input  wire [8-1:0] S00_AXI_awlen,
    input  wire [3-1:0] S00_AXI_awsize,
    input  wire [2-1:0] S00_AXI_awburst,
    input  wire S00_AXI_awvalid,
    output wire S00_AXI_awready,
    input  wire [512-1:0] S00_AXI_wdata,
    input  wire [64-1:0] S00_AXI_wstrb,
    input  wire S00_AXI_wlast,
    input  wire S00_AXI_wvalid,
    output wire S00_AXI_wready,
    output wire [4-1:0] S00_AXI_bid,
    output wire [2-1:0] S00_AXI_bresp,
    output wire S00_AXI_bvalid,
    input  wire S00_AXI_bready,
    input  wire [4-1:0] S00_AXI_arid,
    input  wire [43-1:0] S00_AXI_araddr,
    input  wire [8-1:0] S00_AXI_arlen,
    input  wire [3-1:0] S00_AXI_arsize,
    input  wire [2-1:0] S00_AXI_arburst,
    input  wire S00_AXI_arvalid,
    output wire S00_AXI_arready,
    output wire [4-1:0] S00_AXI_rid,
    output wire [512-1:0] S00_AXI_rdata,
    output wire [2-1:0] S00_AXI_rresp,
    output wire S00_AXI_rlast,
    output wire S00_AXI_rvalid,
    input  wire S00_AXI_rready,

    input  wire [4-1:0] S01_AXI_awid,
    input  wire [43-1:0] S01_AXI_awaddr,
    input  wire [8-1:0] S01_AXI_awlen,
    input  wire [3-1:0] S01_AXI_awsize,
    input  wire [2-1:0] S01_AXI_awburst,
    input  wire S01_AXI_awvalid,
    output wire S01_AXI_awready,
    input  wire [512-1:0] S01_AXI_wdata,
    input  wire [64-1:0] S01_AXI_wstrb,
    input  wire S01_AXI_wlast,
    input  wire S01_AXI_wvalid,
    output wire S01_AXI_wready,
    output wire [4-1:0] S01_AXI_bid,
    output wire [2-1:0] S01_AXI_bresp,
    output wire S01_AXI_bvalid,
    input  wire S01_AXI_bready,
    input  wire [4-1:0] S01_AXI_arid,
    input  wire [43-1:0] S01_AXI_araddr,
    input  wire [8-1:0] S01_AXI_arlen,
    input  wire [3-1:0] S01_AXI_arsize,
    input  wire [2-1:0] S01_AXI_arburst,
    input  wire S01_AXI_arvalid,
    output wire S01_AXI_arready,
    output wire [4-1:0] S01_AXI_rid,
    output wire [512-1:0] S01_AXI_rdata,
    output wire [2-1:0] S01_AXI_rresp,
    output wire S01_AXI_rlast,
    output wire S01_AXI_rvalid,
    input  wire S01_AXI_rready,

    input  wire [4-1:0] S02_AXI_awid,
    input  wire [43-1:0] S02_AXI_awaddr,
    input  wire [8-1:0] S02_AXI_awlen,
    input  wire [3-1:0] S02_AXI_awsize,
    input  wire [2-1:0] S02_AXI_awburst,
    input  wire S02_AXI_awvalid,
    output wire S02_AXI_awready,
    input  wire [512-1:0] S02_AXI_wdata,
    input  wire [64-1:0] S02_AXI_wstrb,
    input  wire S02_AXI_wlast,
    input  wire S02_AXI_wvalid,
    output wire S02_AXI_wready,
    output wire [4-1:0] S02_AXI_bid,
    output wire [2-1:0] S02_AXI_bresp,
    output wire S02_AXI_bvalid,
    input  wire S02_AXI_bready,
    input  wire [4-1:0] S02_AXI_arid,
    input  wire [43-1:0] S02_AXI_araddr,
    input  wire [8-1:0] S02_AXI_arlen,
    input  wire [3-1:0] S02_AXI_arsize,
    input  wire [2-1:0] S02_AXI_arburst,
    input  wire S02_AXI_arvalid,
    output wire S02_AXI_arready,
    output wire [4-1:0] S02_AXI_rid,
    output wire [512-1:0] S02_AXI_rdata,
    output wire [2-1:0] S02_AXI_rresp,
    output wire S02_AXI_rlast,
    output wire S02_AXI_rvalid,
    input  wire S02_AXI_rready,

    input  wire [4-1:0] S03_AXI_awid,
    input  wire [43-1:0] S03_AXI_awaddr,
    input  wire [8-1:0] S03_AXI_awlen,
    input  wire [3-1:0] S03_AXI_awsize,
    input  wire [2-1:0] S03_AXI_awburst,
    input  wire S03_AXI_awvalid,
    output wire S03_AXI_awready,
    input  wire [512-1:0] S03_AXI_wdata,
    input  wire [64-1:0] S03_AXI_wstrb,
    input  wire S03_AXI_wlast,
    input  wire S03_AXI_wvalid,
    output wire S03_AXI_wready,
    output wire [4-1:0] S03_AXI_bid,
    output wire [2-1:0] S03_AXI_bresp,
    output wire S03_AXI_bvalid,
    input  wire S03_AXI_bready,
    input  wire [4-1:0] S03_AXI_arid,
    input  wire [43-1:0] S03_AXI_araddr,
    input  wire [8-1:0] S03_AXI_arlen,
    input  wire [3-1:0] S03_AXI_arsize,
    input  wire [2-1:0] S03_AXI_arburst,
    input  wire S03_AXI_arvalid,
    output wire S03_AXI_arready,
    output wire [4-1:0] S03_AXI_rid,
    output wire [512-1:0] S03_AXI_rdata,
    output wire [2-1:0] S03_AXI_rresp,
    output wire S03_AXI_rlast,
    output wire S03_AXI_rvalid,
    input  wire S03_AXI_rready,

    input  wire [4-1:0] S04_AXI_awid,
    input  wire [43-1:0] S04_AXI_awaddr,
    input  wire [8-1:0] S04_AXI_awlen,
    input  wire [3-1:0] S04_AXI_awsize,
    input  wire [2-1:0] S04_AXI_awburst,
    input  wire S04_AXI_awvalid,
    output wire S04_AXI_awready,
    input  wire [512-1:0] S04_AXI_wdata,
    input  wire [64-1:0] S04_AXI_wstrb,
    input  wire S04_AXI_wlast,
    input  wire S04_AXI_wvalid,
    output wire S04_AXI_wready,
    output wire [4-1:0] S04_AXI_bid,
    output wire [2-1:0] S04_AXI_bresp,
    output wire S04_AXI_bvalid,
    input  wire S04_AXI_bready,
    input  wire [4-1:0] S04_AXI_arid,
    input  wire [43-1:0] S04_AXI_araddr,
    input  wire [8-1:0] S04_AXI_arlen,
    input  wire [3-1:0] S04_AXI_arsize,
    input  wire [2-1:0] S04_AXI_arburst,
    input  wire S04_AXI_arvalid,
    output wire S04_AXI_arready,
    output wire [4-1:0] S04_AXI_rid,
    output wire [512-1:0] S04_AXI_rdata,
    output wire [2-1:0] S04_AXI_rresp,
    output wire S04_AXI_rlast,
    output wire S04_AXI_rvalid,
    input  wire S04_AXI_rready,

    input  wire [4-1:0] S05_AXI_awid,
    input  wire [43-1:0] S05_AXI_awaddr,
    input  wire [8-1:0] S05_AXI_awlen,
    input  wire [3-1:0] S05_AXI_awsize,
    input  wire [2-1:0] S05_AXI_awburst,
    input  wire S05_AXI_awvalid,
    output wire S05_AXI_awready,
    input  wire [512-1:0] S05_AXI_wdata,
    input  wire [64-1:0] S05_AXI_wstrb,
    input  wire S05_AXI_wlast,
    input  wire S05_AXI_wvalid,
    output wire S05_AXI_wready,
    output wire [4-1:0] S05_AXI_bid,
    output wire [2-1:0] S05_AXI_bresp,
    output wire S05_AXI_bvalid,
    input  wire S05_AXI_bready,
    input  wire [4-1:0] S05_AXI_arid,
    input  wire [43-1:0] S05_AXI_araddr,
    input  wire [8-1:0] S05_AXI_arlen,
    input  wire [3-1:0] S05_AXI_arsize,
    input  wire [2-1:0] S05_AXI_arburst,
    input  wire S05_AXI_arvalid,
    output wire S05_AXI_arready,
    output wire [4-1:0] S05_AXI_rid,
    output wire [512-1:0] S05_AXI_rdata,
    output wire [2-1:0] S05_AXI_rresp,
    output wire S05_AXI_rlast,
    output wire S05_AXI_rvalid,
    input  wire S05_AXI_rready,

    output wire [4-1:0] M00_AXI_awid,
    output wire [43-1:0] M00_AXI_awaddr,
    output wire [8-1:0] M00_AXI_awlen,
    output wire [3-1:0] M00_AXI_awsize,
    output wire [2-1:0] M00_AXI_awburst,
    output wire M00_AXI_awvalid,
    input  wire M00_AXI_awready,
    output wire [512-1:0] M00_AXI_wdata,
    output wire [64-1:0] M00_AXI_wstrb,
    output wire M00_AXI_wlast,
    output wire M00_AXI_wvalid,
    input  wire M00_AXI_wready,
    input  wire [4-1:0] M00_AXI_bid,
    input  wire [2-1:0] M00_AXI_bresp,
    input  wire M00_AXI_bvalid,
    output wire M00_AXI_bready,
    output wire [4-1:0] M00_AXI_arid,
    output wire [43-1:0] M00_AXI_araddr,
    output wire [8-1:0] M00_AXI_arlen,
    output wire [3-1:0] M00_AXI_arsize,
    output wire [2-1:0] M00_AXI_arburst,
    output wire M00_AXI_arvalid,
    input  wire M00_AXI_arready,
    input  wire [4-1:0] M00_AXI_rid,
    input  wire [512-1:0] M00_AXI_rdata,
    input  wire [2-1:0] M00_AXI_rresp,
    input  wire M00_AXI_rlast,
    input  wire M00_AXI_rvalid,
    output wire M00_AXI_rready,

    output wire [4-1:0] M01_AXI_awid,
    output wire [43-1:0] M01_AXI_awaddr,
    output wire [8-1:0] M01_AXI_awlen,
    output wire [3-1:0] M01_AXI_awsize,
    output wire [2-1:0] M01_AXI_awburst,
    output wire M01_AXI_awvalid,
    input  wire M01_AXI_awready,
    output wire [512-1:0] M01_AXI_wdata,
    output wire [64-1:0] M01_AXI_wstrb,
    output wire M01_AXI_wlast,
    output wire M01_AXI_wvalid,
    input  wire M01_AXI_wready,
    input  wire [4-1:0] M01_AXI_bid,
    input  wire [2-1:0] M01_AXI_bresp,
    input  wire M01_AXI_bvalid,
    output wire M01_AXI_bready,
    output wire [4-1:0] M01_AXI_arid,
    output wire [43-1:0] M01_AXI_araddr,
    output wire [8-1:0] M01_AXI_arlen,
    output wire [3-1:0] M01_AXI_arsize,
    output wire [2-1:0] M01_AXI_arburst,
    output wire M01_AXI_arvalid,
    input  wire M01_AXI_arready,
    input  wire [4-1:0] M01_AXI_rid,
    input  wire [512-1:0] M01_AXI_rdata,
    input  wire [2-1:0] M01_AXI_rresp,
    input  wire M01_AXI_rlast,
    input  wire M01_AXI_rvalid,
    output wire M01_AXI_rready,

    output wire [4-1:0] M02_AXI_awid,
    output wire [43-1:0] M02_AXI_awaddr,
    output wire [8-1:0] M02_AXI_awlen,
    output wire [3-1:0] M02_AXI_awsize,
    output wire [2-1:0] M02_AXI_awburst,
    output wire M02_AXI_awvalid,
    input  wire M02_AXI_awready,
    output wire [512-1:0] M02_AXI_wdata,
    output wire [64-1:0] M02_AXI_wstrb,
    output wire M02_AXI_wlast,
    output wire M02_AXI_wvalid,
    input  wire M02_AXI_wready,
    input  wire [4-1:0] M02_AXI_bid,
    input  wire [2-1:0] M02_AXI_bresp,
    input  wire M02_AXI_bvalid,
    output wire M02_AXI_bready,
    output wire [4-1:0] M02_AXI_arid,
    output wire [43-1:0] M02_AXI_araddr,
    output wire [8-1:0] M02_AXI_arlen,
    output wire [3-1:0] M02_AXI_arsize,
    output wire [2-1:0] M02_AXI_arburst,
    output wire M02_AXI_arvalid,
    input  wire M02_AXI_arready,
    input  wire [4-1:0] M02_AXI_rid,
    input  wire [512-1:0] M02_AXI_rdata,
    input  wire [2-1:0] M02_AXI_rresp,
    input  wire M02_AXI_rlast,
    input  wire M02_AXI_rvalid,
    output wire M02_AXI_rready,

    output wire [4-1:0] M03_AXI_awid,
    output wire [43-1:0] M03_AXI_awaddr,
    output wire [8-1:0] M03_AXI_awlen,
    output wire [3-1:0] M03_AXI_awsize,
    output wire [2-1:0] M03_AXI_awburst,
    output wire M03_AXI_awvalid,
    input  wire M03_AXI_awready,
    output wire [512-1:0] M03_AXI_wdata,
    output wire [64-1:0] M03_AXI_wstrb,
    output wire M03_AXI_wlast,
    output wire M03_AXI_wvalid,
    input  wire M03_AXI_wready,
    input  wire [4-1:0] M03_AXI_bid,
    input  wire [2-1:0] M03_AXI_bresp,
    input  wire M03_AXI_bvalid,
    output wire M03_AXI_bready,
    output wire [4-1:0] M03_AXI_arid,
    output wire [43-1:0] M03_AXI_araddr,
    output wire [8-1:0] M03_AXI_arlen,
    output wire [3-1:0] M03_AXI_arsize,
    output wire [2-1:0] M03_AXI_arburst,
    output wire M03_AXI_arvalid,
    input  wire M03_AXI_arready,
    input  wire [4-1:0] M03_AXI_rid,
    input  wire [512-1:0] M03_AXI_rdata,
    input  wire [2-1:0] M03_AXI_rresp,
    input  wire M03_AXI_rlast,
    input  wire M03_AXI_rvalid,
    output wire M03_AXI_rready,

    output wire [4-1:0] M04_AXI_awid,
    output wire [43-1:0] M04_AXI_awaddr,
    output wire [8-1:0] M04_AXI_awlen,
    output wire [3-1:0] M04_AXI_awsize,
    output wire [2-1:0] M04_AXI_awburst,
    output wire M04_AXI_awvalid,
    input  wire M04_AXI_awready,
    output wire [512-1:0] M04_AXI_wdata,
    output wire [64-1:0] M04_AXI_wstrb,
    output wire M04_AXI_wlast,
    output wire M04_AXI_wvalid,
    input  wire M04_AXI_wready,
    input  wire [4-1:0] M04_AXI_bid,
    input  wire [2-1:0] M04_AXI_bresp,
    input  wire M04_AXI_bvalid,
    output wire M04_AXI_bready,
    output wire [4-1:0] M04_AXI_arid,
    output wire [43-1:0] M04_AXI_araddr,
    output wire [8-1:0] M04_AXI_arlen,
    output wire [3-1:0] M04_AXI_arsize,
    output wire [2-1:0] M04_AXI_arburst,
    output wire M04_AXI_arvalid,
    input  wire M04_AXI_arready,
    input  wire [4-1:0] M04_AXI_rid,
    input  wire [512-1:0] M04_AXI_rdata,
    input  wire [2-1:0] M04_AXI_rresp,
    input  wire M04_AXI_rlast,
    input  wire M04_AXI_rvalid,
    output wire M04_AXI_rready,

    output wire [4-1:0] M05_AXI_awid,
    output wire [43-1:0] M05_AXI_awaddr,
    output wire [8-1:0] M05_AXI_awlen,
    output wire [3-1:0] M05_AXI_awsize,
    output wire [2-1:0] M05_AXI_awburst,
    output wire M05_AXI_awvalid,
    input  wire M05_AXI_awready,
    output wire [512-1:0] M05_AXI_wdata,
    output wire [64-1:0] M05_AXI_wstrb,
    output wire M05_AXI_wlast,
    output wire M05_AXI_wvalid,
    input  wire M05_AXI_wready,
    input  wire [4-1:0] M05_AXI_bid,
    input  wire [2-1:0] M05_AXI_bresp,
    input  wire M05_AXI_bvalid,
    output wire M05_AXI_bready,
    output wire [4-1:0] M05_AXI_arid,
    output wire [43-1:0] M05_AXI_araddr,
    output wire [8-1:0] M05_AXI_arlen,
    output wire [3-1:0] M05_AXI_arsize,
    output wire [2-1:0] M05_AXI_arburst,
    output wire M05_AXI_arvalid,
    input  wire M05_AXI_arready,
    input  wire [4-1:0] M05_AXI_rid,
    input  wire [512-1:0] M05_AXI_rdata,
    input  wire [2-1:0] M05_AXI_rresp,
    input  wire M05_AXI_rlast,
    input  wire M05_AXI_rvalid,
    output wire M05_AXI_rready,

    output wire [4-1:0] M06_AXI_awid,
    output wire [43-1:0] M06_AXI_awaddr,
    output wire [8-1:0] M06_AXI_awlen,
    output wire [3-1:0] M06_AXI_awsize,
    output wire [2-1:0] M06_AXI_awburst,
    output wire M06_AXI_awvalid,
    input  wire M06_AXI_awready,
    output wire [512-1:0] M06_AXI_wdata,
    output wire [64-1:0] M06_AXI_wstrb,
    output wire M06_AXI_wlast,
    output wire M06_AXI_wvalid,
    input  wire M06_AXI_wready,
    input  wire [4-1:0] M06_AXI_bid,
    input  wire [2-1:0] M06_AXI_bresp,
    input  wire M06_AXI_bvalid,
    output wire M06_AXI_bready,
    output wire [4-1:0] M06_AXI_arid,
    output wire [43-1:0] M06_AXI_araddr,
    output wire [8-1:0] M06_AXI_arlen,
    output wire [3-1:0] M06_AXI_arsize,
    output wire [2-1:0] M06_AXI_arburst,
    output wire M06_AXI_arvalid,
    input  wire M06_AXI_arready,
    input  wire [4-1:0] M06_AXI_rid,
    input  wire [512-1:0] M06_AXI_rdata,
    input  wire [2-1:0] M06_AXI_rresp,
    input  wire M06_AXI_rlast,
    input  wire M06_AXI_rvalid,
    output wire M06_AXI_rready,

    output wire [4-1:0] M07_AXI_awid,
    output wire [43-1:0] M07_AXI_awaddr,
    output wire [8-1:0] M07_AXI_awlen,
    output wire [3-1:0] M07_AXI_awsize,
    output wire [2-1:0] M07_AXI_awburst,
    output wire M07_AXI_awvalid,
    input  wire M07_AXI_awready,
    output wire [512-1:0] M07_AXI_wdata,
    output wire [64-1:0] M07_AXI_wstrb,
    output wire M07_AXI_wlast,
    output wire M07_AXI_wvalid,
    input  wire M07_AXI_wready,
    input  wire [4-1:0] M07_AXI_bid,
    input  wire [2-1:0] M07_AXI_bresp,
    input  wire M07_AXI_bvalid,
    output wire M07_AXI_bready,
    output wire [4-1:0] M07_AXI_arid,
    output wire [43-1:0] M07_AXI_araddr,
    output wire [8-1:0] M07_AXI_arlen,
    output wire [3-1:0] M07_AXI_arsize,
    output wire [2-1:0] M07_AXI_arburst,
    output wire M07_AXI_arvalid,
    input  wire M07_AXI_arready,
    input  wire [4-1:0] M07_AXI_rid,
    input  wire [512-1:0] M07_AXI_rdata,
    input  wire [2-1:0] M07_AXI_rresp,
    input  wire M07_AXI_rlast,
    input  wire M07_AXI_rvalid,
    output wire M07_AXI_rready,

    output wire [4-1:0] M08_AXI_awid,
    output wire [43-1:0] M08_AXI_awaddr,
    output wire [8-1:0] M08_AXI_awlen,
    output wire [3-1:0] M08_AXI_awsize,
    output wire [2-1:0] M08_AXI_awburst,
    output wire M08_AXI_awvalid,
    input  wire M08_AXI_awready,
    output wire [512-1:0] M08_AXI_wdata,
    output wire [64-1:0] M08_AXI_wstrb,
    output wire M08_AXI_wlast,
    output wire M08_AXI_wvalid,
    input  wire M08_AXI_wready,
    input  wire [4-1:0] M08_AXI_bid,
    input  wire [2-1:0] M08_AXI_bresp,
    input  wire M08_AXI_bvalid,
    output wire M08_AXI_bready,
    output wire [4-1:0] M08_AXI_arid,
    output wire [43-1:0] M08_AXI_araddr,
    output wire [8-1:0] M08_AXI_arlen,
    output wire [3-1:0] M08_AXI_arsize,
    output wire [2-1:0] M08_AXI_arburst,
    output wire M08_AXI_arvalid,
    input  wire M08_AXI_arready,
    input  wire [4-1:0] M08_AXI_rid,
    input  wire [512-1:0] M08_AXI_rdata,
    input  wire [2-1:0] M08_AXI_rresp,
    input  wire M08_AXI_rlast,
    input  wire M08_AXI_rvalid,
    output wire M08_AXI_rready,

    output wire [648-1:0] L0_REQ_tdata,
    output wire L0_REQ_tvalid,
    input  wire L0_REQ_tready,
    input  wire [528-1:0] L0_RSP_tdata,
    input  wire L0_RSP_tvalid,
    output wire L0_RSP_tready,
    output wire [648-1:0] L1_REQ_tdata,
    output wire L1_REQ_tvalid,
    input  wire L1_REQ_tready,
    input  wire [528-1:0] L1_RSP_tdata,
    input  wire L1_RSP_tvalid,
    output wire L1_RSP_tready,
    output wire [648-1:0] L2_REQ_tdata,
    output wire L2_REQ_tvalid,
    input  wire L2_REQ_tready,
    input  wire [528-1:0] L2_RSP_tdata,
    input  wire L2_RSP_tvalid,
    output wire L2_RSP_tready,
    output wire [648-1:0] L3_REQ_tdata,
    output wire L3_REQ_tvalid,
    input  wire L3_REQ_tready,
    input  wire [528-1:0] L3_RSP_tdata,
    input  wire L3_RSP_tvalid,
    output wire L3_RSP_tready,
    output wire [648-1:0] L4_REQ_tdata,
    output wire L4_REQ_tvalid,
    input  wire L4_REQ_tready,
    input  wire [528-1:0] L4_RSP_tdata,
    input  wire L4_RSP_tvalid,
    output wire L4_RSP_tready,
    output wire [648-1:0] L5_REQ_tdata,
    output wire L5_REQ_tvalid,
    input  wire L5_REQ_tready,
    input  wire [528-1:0] L5_RSP_tdata,
    input  wire L5_RSP_tvalid,
    output wire L5_RSP_tready,

    output wire [31:0] stat_decerr
);
    localparam integer NM   = 6;
    localparam integer NL   = 9;
    localparam integer NK   = 6;
    localparam integer AW   = 43;
    localparam integer MAXW = 512;
    localparam integer MAXID = 4;
    localparam integer FW   = 512;

    localparam integer NSEG = 8;
    localparam [NSEG*AW-1:0]   Q_BASE = {43'h18000010000, 43'h18000000000, 43'h10000010000, 43'h10000000000, 43'h00000010000, 43'h00000000000, 43'h08000010000, 43'h08000000000};
    localparam [NSEG*AW-1:0]   Q_MASK = {8{43'h7FFFFFF0000}};
    localparam [NSEG*3-1:0]    Q_DST  = {3'd4, 3'd4, 3'd3, 3'd3, 3'd2, 3'd2, 3'd1, 3'd0};
    localparam [NSEG*3-1:0]    Q_DPT  = {3'd1, 3'd0, 3'd1, 3'd0, 3'd1, 3'd0, 3'd1, 3'd0};

    wire [NM*MAXID-1:0]    mp_awid, mp_arid, mp_bid, mp_rid;
    wire [NM*AW-1:0]       mp_awaddr, mp_araddr;
    wire [NM*8-1:0]        mp_awlen, mp_arlen;
    wire [NM*3-1:0]        mp_awsize, mp_arsize;
    wire [NM*2-1:0]        mp_awburst, mp_arburst, mp_bresp, mp_rresp;
    wire [NM-1:0]          mp_awvalid, mp_awready, mp_wvalid, mp_wready;
    wire [NM-1:0]          mp_wlast, mp_bvalid, mp_bready;
    wire [NM-1:0]          mp_arvalid, mp_arready, mp_rvalid, mp_rready, mp_rlast;
    wire [NM*MAXW-1:0]     mp_wdata, mp_rdata;
    wire [NM*(MAXW/8)-1:0] mp_wstrb;

    wire [NL*MAXID-1:0]    sp_awid, sp_arid, sp_bid, sp_rid;
    wire [NL*AW-1:0]       sp_awaddr, sp_araddr;
    wire [NL*8-1:0]        sp_awlen, sp_arlen;
    wire [NL*3-1:0]        sp_awsize, sp_arsize;
    wire [NL*2-1:0]        sp_awburst, sp_arburst, sp_bresp, sp_rresp;
    wire [NL-1:0]          sp_awvalid, sp_awready, sp_wvalid, sp_wready;
    wire [NL-1:0]          sp_wlast, sp_bvalid, sp_bready;
    wire [NL-1:0]          sp_arvalid, sp_arready, sp_rvalid, sp_rready, sp_rlast;
    wire [NL*MAXW-1:0]     sp_wdata, sp_rdata;
    wire [NL*(MAXW/8)-1:0] sp_wstrb;

    wire [NK-1:0]      lk_req_valid, lk_req_ready, lk_rsp_valid, lk_rsp_ready;
    wire [642-1:0]  lk_req_pay;
    wire [NK*522-1:0] lk_rsp_pay;

    assign mp_awid[0*4 +: 4] = S00_AXI_awid;
    assign mp_awaddr[0*43 +: 43] = S00_AXI_awaddr;
    assign mp_awlen[0*8 +: 8] = S00_AXI_awlen;
    assign mp_awsize[0*3 +: 3] = S00_AXI_awsize;
    assign mp_awburst[0*2 +: 2] = S00_AXI_awburst;
    assign mp_awvalid[0] = S00_AXI_awvalid;
    assign S00_AXI_awready = mp_awready[0];
    assign mp_wdata[0*512 +: 512] = S00_AXI_wdata;
    assign mp_wstrb[0*64 +: 64] = S00_AXI_wstrb;
    assign mp_wlast[0] = S00_AXI_wlast;
    assign mp_wvalid[0] = S00_AXI_wvalid;
    assign S00_AXI_wready = mp_wready[0];
    assign S00_AXI_bid = mp_bid[0*4 +: 4];
    assign S00_AXI_bresp = mp_bresp[0*2 +: 2];
    assign S00_AXI_bvalid = mp_bvalid[0];
    assign mp_bready[0] = S00_AXI_bready;
    assign mp_arid[0*4 +: 4] = S00_AXI_arid;
    assign mp_araddr[0*43 +: 43] = S00_AXI_araddr;
    assign mp_arlen[0*8 +: 8] = S00_AXI_arlen;
    assign mp_arsize[0*3 +: 3] = S00_AXI_arsize;
    assign mp_arburst[0*2 +: 2] = S00_AXI_arburst;
    assign mp_arvalid[0] = S00_AXI_arvalid;
    assign S00_AXI_arready = mp_arready[0];
    assign S00_AXI_rid = mp_rid[0*4 +: 4];
    assign S00_AXI_rdata = mp_rdata[0*512 +: 512];
    assign S00_AXI_rresp = mp_rresp[0*2 +: 2];
    assign S00_AXI_rlast = mp_rlast[0];
    assign S00_AXI_rvalid = mp_rvalid[0];
    assign mp_rready[0] = S00_AXI_rready;

    assign mp_awid[1*4 +: 4] = S01_AXI_awid;
    assign mp_awaddr[1*43 +: 43] = S01_AXI_awaddr;
    assign mp_awlen[1*8 +: 8] = S01_AXI_awlen;
    assign mp_awsize[1*3 +: 3] = S01_AXI_awsize;
    assign mp_awburst[1*2 +: 2] = S01_AXI_awburst;
    assign mp_awvalid[1] = S01_AXI_awvalid;
    assign S01_AXI_awready = mp_awready[1];
    assign mp_wdata[1*512 +: 512] = S01_AXI_wdata;
    assign mp_wstrb[1*64 +: 64] = S01_AXI_wstrb;
    assign mp_wlast[1] = S01_AXI_wlast;
    assign mp_wvalid[1] = S01_AXI_wvalid;
    assign S01_AXI_wready = mp_wready[1];
    assign S01_AXI_bid = mp_bid[1*4 +: 4];
    assign S01_AXI_bresp = mp_bresp[1*2 +: 2];
    assign S01_AXI_bvalid = mp_bvalid[1];
    assign mp_bready[1] = S01_AXI_bready;
    assign mp_arid[1*4 +: 4] = S01_AXI_arid;
    assign mp_araddr[1*43 +: 43] = S01_AXI_araddr;
    assign mp_arlen[1*8 +: 8] = S01_AXI_arlen;
    assign mp_arsize[1*3 +: 3] = S01_AXI_arsize;
    assign mp_arburst[1*2 +: 2] = S01_AXI_arburst;
    assign mp_arvalid[1] = S01_AXI_arvalid;
    assign S01_AXI_arready = mp_arready[1];
    assign S01_AXI_rid = mp_rid[1*4 +: 4];
    assign S01_AXI_rdata = mp_rdata[1*512 +: 512];
    assign S01_AXI_rresp = mp_rresp[1*2 +: 2];
    assign S01_AXI_rlast = mp_rlast[1];
    assign S01_AXI_rvalid = mp_rvalid[1];
    assign mp_rready[1] = S01_AXI_rready;

    assign mp_awid[2*4 +: 4] = S02_AXI_awid;
    assign mp_awaddr[2*43 +: 43] = S02_AXI_awaddr;
    assign mp_awlen[2*8 +: 8] = S02_AXI_awlen;
    assign mp_awsize[2*3 +: 3] = S02_AXI_awsize;
    assign mp_awburst[2*2 +: 2] = S02_AXI_awburst;
    assign mp_awvalid[2] = S02_AXI_awvalid;
    assign S02_AXI_awready = mp_awready[2];
    assign mp_wdata[2*512 +: 512] = S02_AXI_wdata;
    assign mp_wstrb[2*64 +: 64] = S02_AXI_wstrb;
    assign mp_wlast[2] = S02_AXI_wlast;
    assign mp_wvalid[2] = S02_AXI_wvalid;
    assign S02_AXI_wready = mp_wready[2];
    assign S02_AXI_bid = mp_bid[2*4 +: 4];
    assign S02_AXI_bresp = mp_bresp[2*2 +: 2];
    assign S02_AXI_bvalid = mp_bvalid[2];
    assign mp_bready[2] = S02_AXI_bready;
    assign mp_arid[2*4 +: 4] = S02_AXI_arid;
    assign mp_araddr[2*43 +: 43] = S02_AXI_araddr;
    assign mp_arlen[2*8 +: 8] = S02_AXI_arlen;
    assign mp_arsize[2*3 +: 3] = S02_AXI_arsize;
    assign mp_arburst[2*2 +: 2] = S02_AXI_arburst;
    assign mp_arvalid[2] = S02_AXI_arvalid;
    assign S02_AXI_arready = mp_arready[2];
    assign S02_AXI_rid = mp_rid[2*4 +: 4];
    assign S02_AXI_rdata = mp_rdata[2*512 +: 512];
    assign S02_AXI_rresp = mp_rresp[2*2 +: 2];
    assign S02_AXI_rlast = mp_rlast[2];
    assign S02_AXI_rvalid = mp_rvalid[2];
    assign mp_rready[2] = S02_AXI_rready;

    assign mp_awid[3*4 +: 4] = S03_AXI_awid;
    assign mp_awaddr[3*43 +: 43] = S03_AXI_awaddr;
    assign mp_awlen[3*8 +: 8] = S03_AXI_awlen;
    assign mp_awsize[3*3 +: 3] = S03_AXI_awsize;
    assign mp_awburst[3*2 +: 2] = S03_AXI_awburst;
    assign mp_awvalid[3] = S03_AXI_awvalid;
    assign S03_AXI_awready = mp_awready[3];
    assign mp_wdata[3*512 +: 512] = S03_AXI_wdata;
    assign mp_wstrb[3*64 +: 64] = S03_AXI_wstrb;
    assign mp_wlast[3] = S03_AXI_wlast;
    assign mp_wvalid[3] = S03_AXI_wvalid;
    assign S03_AXI_wready = mp_wready[3];
    assign S03_AXI_bid = mp_bid[3*4 +: 4];
    assign S03_AXI_bresp = mp_bresp[3*2 +: 2];
    assign S03_AXI_bvalid = mp_bvalid[3];
    assign mp_bready[3] = S03_AXI_bready;
    assign mp_arid[3*4 +: 4] = S03_AXI_arid;
    assign mp_araddr[3*43 +: 43] = S03_AXI_araddr;
    assign mp_arlen[3*8 +: 8] = S03_AXI_arlen;
    assign mp_arsize[3*3 +: 3] = S03_AXI_arsize;
    assign mp_arburst[3*2 +: 2] = S03_AXI_arburst;
    assign mp_arvalid[3] = S03_AXI_arvalid;
    assign S03_AXI_arready = mp_arready[3];
    assign S03_AXI_rid = mp_rid[3*4 +: 4];
    assign S03_AXI_rdata = mp_rdata[3*512 +: 512];
    assign S03_AXI_rresp = mp_rresp[3*2 +: 2];
    assign S03_AXI_rlast = mp_rlast[3];
    assign S03_AXI_rvalid = mp_rvalid[3];
    assign mp_rready[3] = S03_AXI_rready;

    assign mp_awid[4*4 +: 4] = S04_AXI_awid;
    assign mp_awaddr[4*43 +: 43] = S04_AXI_awaddr;
    assign mp_awlen[4*8 +: 8] = S04_AXI_awlen;
    assign mp_awsize[4*3 +: 3] = S04_AXI_awsize;
    assign mp_awburst[4*2 +: 2] = S04_AXI_awburst;
    assign mp_awvalid[4] = S04_AXI_awvalid;
    assign S04_AXI_awready = mp_awready[4];
    assign mp_wdata[4*512 +: 512] = S04_AXI_wdata;
    assign mp_wstrb[4*64 +: 64] = S04_AXI_wstrb;
    assign mp_wlast[4] = S04_AXI_wlast;
    assign mp_wvalid[4] = S04_AXI_wvalid;
    assign S04_AXI_wready = mp_wready[4];
    assign S04_AXI_bid = mp_bid[4*4 +: 4];
    assign S04_AXI_bresp = mp_bresp[4*2 +: 2];
    assign S04_AXI_bvalid = mp_bvalid[4];
    assign mp_bready[4] = S04_AXI_bready;
    assign mp_arid[4*4 +: 4] = S04_AXI_arid;
    assign mp_araddr[4*43 +: 43] = S04_AXI_araddr;
    assign mp_arlen[4*8 +: 8] = S04_AXI_arlen;
    assign mp_arsize[4*3 +: 3] = S04_AXI_arsize;
    assign mp_arburst[4*2 +: 2] = S04_AXI_arburst;
    assign mp_arvalid[4] = S04_AXI_arvalid;
    assign S04_AXI_arready = mp_arready[4];
    assign S04_AXI_rid = mp_rid[4*4 +: 4];
    assign S04_AXI_rdata = mp_rdata[4*512 +: 512];
    assign S04_AXI_rresp = mp_rresp[4*2 +: 2];
    assign S04_AXI_rlast = mp_rlast[4];
    assign S04_AXI_rvalid = mp_rvalid[4];
    assign mp_rready[4] = S04_AXI_rready;

    assign mp_awid[5*4 +: 4] = S05_AXI_awid;
    assign mp_awaddr[5*43 +: 43] = S05_AXI_awaddr;
    assign mp_awlen[5*8 +: 8] = S05_AXI_awlen;
    assign mp_awsize[5*3 +: 3] = S05_AXI_awsize;
    assign mp_awburst[5*2 +: 2] = S05_AXI_awburst;
    assign mp_awvalid[5] = S05_AXI_awvalid;
    assign S05_AXI_awready = mp_awready[5];
    assign mp_wdata[5*512 +: 512] = S05_AXI_wdata;
    assign mp_wstrb[5*64 +: 64] = S05_AXI_wstrb;
    assign mp_wlast[5] = S05_AXI_wlast;
    assign mp_wvalid[5] = S05_AXI_wvalid;
    assign S05_AXI_wready = mp_wready[5];
    assign S05_AXI_bid = mp_bid[5*4 +: 4];
    assign S05_AXI_bresp = mp_bresp[5*2 +: 2];
    assign S05_AXI_bvalid = mp_bvalid[5];
    assign mp_bready[5] = S05_AXI_bready;
    assign mp_arid[5*4 +: 4] = S05_AXI_arid;
    assign mp_araddr[5*43 +: 43] = S05_AXI_araddr;
    assign mp_arlen[5*8 +: 8] = S05_AXI_arlen;
    assign mp_arsize[5*3 +: 3] = S05_AXI_arsize;
    assign mp_arburst[5*2 +: 2] = S05_AXI_arburst;
    assign mp_arvalid[5] = S05_AXI_arvalid;
    assign S05_AXI_arready = mp_arready[5];
    assign S05_AXI_rid = mp_rid[5*4 +: 4];
    assign S05_AXI_rdata = mp_rdata[5*512 +: 512];
    assign S05_AXI_rresp = mp_rresp[5*2 +: 2];
    assign S05_AXI_rlast = mp_rlast[5];
    assign S05_AXI_rvalid = mp_rvalid[5];
    assign mp_rready[5] = S05_AXI_rready;

    assign M00_AXI_awid = sp_awid[0*4 +: 4];
    assign M00_AXI_awaddr = sp_awaddr[0*43 +: 43];
    assign M00_AXI_awlen = sp_awlen[0*8 +: 8];
    assign M00_AXI_awsize = sp_awsize[0*3 +: 3];
    assign M00_AXI_awburst = sp_awburst[0*2 +: 2];
    assign M00_AXI_awvalid = sp_awvalid[0];
    assign sp_awready[0] = M00_AXI_awready;
    assign M00_AXI_wdata = sp_wdata[0*512 +: 512];
    assign M00_AXI_wstrb = sp_wstrb[0*64 +: 64];
    assign M00_AXI_wlast = sp_wlast[0];
    assign M00_AXI_wvalid = sp_wvalid[0];
    assign sp_wready[0] = M00_AXI_wready;
    assign sp_bid[0*4 +: 4] = M00_AXI_bid;
    assign sp_bresp[0*2 +: 2] = M00_AXI_bresp;
    assign sp_bvalid[0] = M00_AXI_bvalid;
    assign M00_AXI_bready = sp_bready[0];
    assign M00_AXI_arid = sp_arid[0*4 +: 4];
    assign M00_AXI_araddr = sp_araddr[0*43 +: 43];
    assign M00_AXI_arlen = sp_arlen[0*8 +: 8];
    assign M00_AXI_arsize = sp_arsize[0*3 +: 3];
    assign M00_AXI_arburst = sp_arburst[0*2 +: 2];
    assign M00_AXI_arvalid = sp_arvalid[0];
    assign sp_arready[0] = M00_AXI_arready;
    assign sp_rid[0*4 +: 4] = M00_AXI_rid;
    assign sp_rdata[0*512 +: 512] = M00_AXI_rdata;
    assign sp_rresp[0*2 +: 2] = M00_AXI_rresp;
    assign sp_rlast[0] = M00_AXI_rlast;
    assign sp_rvalid[0] = M00_AXI_rvalid;
    assign M00_AXI_rready = sp_rready[0];

    assign M01_AXI_awid = sp_awid[1*4 +: 4];
    assign M01_AXI_awaddr = sp_awaddr[1*43 +: 43];
    assign M01_AXI_awlen = sp_awlen[1*8 +: 8];
    assign M01_AXI_awsize = sp_awsize[1*3 +: 3];
    assign M01_AXI_awburst = sp_awburst[1*2 +: 2];
    assign M01_AXI_awvalid = sp_awvalid[1];
    assign sp_awready[1] = M01_AXI_awready;
    assign M01_AXI_wdata = sp_wdata[1*512 +: 512];
    assign M01_AXI_wstrb = sp_wstrb[1*64 +: 64];
    assign M01_AXI_wlast = sp_wlast[1];
    assign M01_AXI_wvalid = sp_wvalid[1];
    assign sp_wready[1] = M01_AXI_wready;
    assign sp_bid[1*4 +: 4] = M01_AXI_bid;
    assign sp_bresp[1*2 +: 2] = M01_AXI_bresp;
    assign sp_bvalid[1] = M01_AXI_bvalid;
    assign M01_AXI_bready = sp_bready[1];
    assign M01_AXI_arid = sp_arid[1*4 +: 4];
    assign M01_AXI_araddr = sp_araddr[1*43 +: 43];
    assign M01_AXI_arlen = sp_arlen[1*8 +: 8];
    assign M01_AXI_arsize = sp_arsize[1*3 +: 3];
    assign M01_AXI_arburst = sp_arburst[1*2 +: 2];
    assign M01_AXI_arvalid = sp_arvalid[1];
    assign sp_arready[1] = M01_AXI_arready;
    assign sp_rid[1*4 +: 4] = M01_AXI_rid;
    assign sp_rdata[1*512 +: 512] = M01_AXI_rdata;
    assign sp_rresp[1*2 +: 2] = M01_AXI_rresp;
    assign sp_rlast[1] = M01_AXI_rlast;
    assign sp_rvalid[1] = M01_AXI_rvalid;
    assign M01_AXI_rready = sp_rready[1];

    assign M02_AXI_awid = sp_awid[2*4 +: 4];
    assign M02_AXI_awaddr = sp_awaddr[2*43 +: 43];
    assign M02_AXI_awlen = sp_awlen[2*8 +: 8];
    assign M02_AXI_awsize = sp_awsize[2*3 +: 3];
    assign M02_AXI_awburst = sp_awburst[2*2 +: 2];
    assign M02_AXI_awvalid = sp_awvalid[2];
    assign sp_awready[2] = M02_AXI_awready;
    assign M02_AXI_wdata = sp_wdata[2*512 +: 512];
    assign M02_AXI_wstrb = sp_wstrb[2*64 +: 64];
    assign M02_AXI_wlast = sp_wlast[2];
    assign M02_AXI_wvalid = sp_wvalid[2];
    assign sp_wready[2] = M02_AXI_wready;
    assign sp_bid[2*4 +: 4] = M02_AXI_bid;
    assign sp_bresp[2*2 +: 2] = M02_AXI_bresp;
    assign sp_bvalid[2] = M02_AXI_bvalid;
    assign M02_AXI_bready = sp_bready[2];
    assign M02_AXI_arid = sp_arid[2*4 +: 4];
    assign M02_AXI_araddr = sp_araddr[2*43 +: 43];
    assign M02_AXI_arlen = sp_arlen[2*8 +: 8];
    assign M02_AXI_arsize = sp_arsize[2*3 +: 3];
    assign M02_AXI_arburst = sp_arburst[2*2 +: 2];
    assign M02_AXI_arvalid = sp_arvalid[2];
    assign sp_arready[2] = M02_AXI_arready;
    assign sp_rid[2*4 +: 4] = M02_AXI_rid;
    assign sp_rdata[2*512 +: 512] = M02_AXI_rdata;
    assign sp_rresp[2*2 +: 2] = M02_AXI_rresp;
    assign sp_rlast[2] = M02_AXI_rlast;
    assign sp_rvalid[2] = M02_AXI_rvalid;
    assign M02_AXI_rready = sp_rready[2];

    assign M03_AXI_awid = sp_awid[3*4 +: 4];
    assign M03_AXI_awaddr = sp_awaddr[3*43 +: 43];
    assign M03_AXI_awlen = sp_awlen[3*8 +: 8];
    assign M03_AXI_awsize = sp_awsize[3*3 +: 3];
    assign M03_AXI_awburst = sp_awburst[3*2 +: 2];
    assign M03_AXI_awvalid = sp_awvalid[3];
    assign sp_awready[3] = M03_AXI_awready;
    assign M03_AXI_wdata = sp_wdata[3*512 +: 512];
    assign M03_AXI_wstrb = sp_wstrb[3*64 +: 64];
    assign M03_AXI_wlast = sp_wlast[3];
    assign M03_AXI_wvalid = sp_wvalid[3];
    assign sp_wready[3] = M03_AXI_wready;
    assign sp_bid[3*4 +: 4] = M03_AXI_bid;
    assign sp_bresp[3*2 +: 2] = M03_AXI_bresp;
    assign sp_bvalid[3] = M03_AXI_bvalid;
    assign M03_AXI_bready = sp_bready[3];
    assign M03_AXI_arid = sp_arid[3*4 +: 4];
    assign M03_AXI_araddr = sp_araddr[3*43 +: 43];
    assign M03_AXI_arlen = sp_arlen[3*8 +: 8];
    assign M03_AXI_arsize = sp_arsize[3*3 +: 3];
    assign M03_AXI_arburst = sp_arburst[3*2 +: 2];
    assign M03_AXI_arvalid = sp_arvalid[3];
    assign sp_arready[3] = M03_AXI_arready;
    assign sp_rid[3*4 +: 4] = M03_AXI_rid;
    assign sp_rdata[3*512 +: 512] = M03_AXI_rdata;
    assign sp_rresp[3*2 +: 2] = M03_AXI_rresp;
    assign sp_rlast[3] = M03_AXI_rlast;
    assign sp_rvalid[3] = M03_AXI_rvalid;
    assign M03_AXI_rready = sp_rready[3];

    assign M04_AXI_awid = sp_awid[4*4 +: 4];
    assign M04_AXI_awaddr = sp_awaddr[4*43 +: 43];
    assign M04_AXI_awlen = sp_awlen[4*8 +: 8];
    assign M04_AXI_awsize = sp_awsize[4*3 +: 3];
    assign M04_AXI_awburst = sp_awburst[4*2 +: 2];
    assign M04_AXI_awvalid = sp_awvalid[4];
    assign sp_awready[4] = M04_AXI_awready;
    assign M04_AXI_wdata = sp_wdata[4*512 +: 512];
    assign M04_AXI_wstrb = sp_wstrb[4*64 +: 64];
    assign M04_AXI_wlast = sp_wlast[4];
    assign M04_AXI_wvalid = sp_wvalid[4];
    assign sp_wready[4] = M04_AXI_wready;
    assign sp_bid[4*4 +: 4] = M04_AXI_bid;
    assign sp_bresp[4*2 +: 2] = M04_AXI_bresp;
    assign sp_bvalid[4] = M04_AXI_bvalid;
    assign M04_AXI_bready = sp_bready[4];
    assign M04_AXI_arid = sp_arid[4*4 +: 4];
    assign M04_AXI_araddr = sp_araddr[4*43 +: 43];
    assign M04_AXI_arlen = sp_arlen[4*8 +: 8];
    assign M04_AXI_arsize = sp_arsize[4*3 +: 3];
    assign M04_AXI_arburst = sp_arburst[4*2 +: 2];
    assign M04_AXI_arvalid = sp_arvalid[4];
    assign sp_arready[4] = M04_AXI_arready;
    assign sp_rid[4*4 +: 4] = M04_AXI_rid;
    assign sp_rdata[4*512 +: 512] = M04_AXI_rdata;
    assign sp_rresp[4*2 +: 2] = M04_AXI_rresp;
    assign sp_rlast[4] = M04_AXI_rlast;
    assign sp_rvalid[4] = M04_AXI_rvalid;
    assign M04_AXI_rready = sp_rready[4];

    assign M05_AXI_awid = sp_awid[5*4 +: 4];
    assign M05_AXI_awaddr = sp_awaddr[5*43 +: 43];
    assign M05_AXI_awlen = sp_awlen[5*8 +: 8];
    assign M05_AXI_awsize = sp_awsize[5*3 +: 3];
    assign M05_AXI_awburst = sp_awburst[5*2 +: 2];
    assign M05_AXI_awvalid = sp_awvalid[5];
    assign sp_awready[5] = M05_AXI_awready;
    assign M05_AXI_wdata = sp_wdata[5*512 +: 512];
    assign M05_AXI_wstrb = sp_wstrb[5*64 +: 64];
    assign M05_AXI_wlast = sp_wlast[5];
    assign M05_AXI_wvalid = sp_wvalid[5];
    assign sp_wready[5] = M05_AXI_wready;
    assign sp_bid[5*4 +: 4] = M05_AXI_bid;
    assign sp_bresp[5*2 +: 2] = M05_AXI_bresp;
    assign sp_bvalid[5] = M05_AXI_bvalid;
    assign M05_AXI_bready = sp_bready[5];
    assign M05_AXI_arid = sp_arid[5*4 +: 4];
    assign M05_AXI_araddr = sp_araddr[5*43 +: 43];
    assign M05_AXI_arlen = sp_arlen[5*8 +: 8];
    assign M05_AXI_arsize = sp_arsize[5*3 +: 3];
    assign M05_AXI_arburst = sp_arburst[5*2 +: 2];
    assign M05_AXI_arvalid = sp_arvalid[5];
    assign sp_arready[5] = M05_AXI_arready;
    assign sp_rid[5*4 +: 4] = M05_AXI_rid;
    assign sp_rdata[5*512 +: 512] = M05_AXI_rdata;
    assign sp_rresp[5*2 +: 2] = M05_AXI_rresp;
    assign sp_rlast[5] = M05_AXI_rlast;
    assign sp_rvalid[5] = M05_AXI_rvalid;
    assign M05_AXI_rready = sp_rready[5];

    assign M06_AXI_awid = sp_awid[6*4 +: 4];
    assign M06_AXI_awaddr = sp_awaddr[6*43 +: 43];
    assign M06_AXI_awlen = sp_awlen[6*8 +: 8];
    assign M06_AXI_awsize = sp_awsize[6*3 +: 3];
    assign M06_AXI_awburst = sp_awburst[6*2 +: 2];
    assign M06_AXI_awvalid = sp_awvalid[6];
    assign sp_awready[6] = M06_AXI_awready;
    assign M06_AXI_wdata = sp_wdata[6*512 +: 512];
    assign M06_AXI_wstrb = sp_wstrb[6*64 +: 64];
    assign M06_AXI_wlast = sp_wlast[6];
    assign M06_AXI_wvalid = sp_wvalid[6];
    assign sp_wready[6] = M06_AXI_wready;
    assign sp_bid[6*4 +: 4] = M06_AXI_bid;
    assign sp_bresp[6*2 +: 2] = M06_AXI_bresp;
    assign sp_bvalid[6] = M06_AXI_bvalid;
    assign M06_AXI_bready = sp_bready[6];
    assign M06_AXI_arid = sp_arid[6*4 +: 4];
    assign M06_AXI_araddr = sp_araddr[6*43 +: 43];
    assign M06_AXI_arlen = sp_arlen[6*8 +: 8];
    assign M06_AXI_arsize = sp_arsize[6*3 +: 3];
    assign M06_AXI_arburst = sp_arburst[6*2 +: 2];
    assign M06_AXI_arvalid = sp_arvalid[6];
    assign sp_arready[6] = M06_AXI_arready;
    assign sp_rid[6*4 +: 4] = M06_AXI_rid;
    assign sp_rdata[6*512 +: 512] = M06_AXI_rdata;
    assign sp_rresp[6*2 +: 2] = M06_AXI_rresp;
    assign sp_rlast[6] = M06_AXI_rlast;
    assign sp_rvalid[6] = M06_AXI_rvalid;
    assign M06_AXI_rready = sp_rready[6];

    assign M07_AXI_awid = sp_awid[7*4 +: 4];
    assign M07_AXI_awaddr = sp_awaddr[7*43 +: 43];
    assign M07_AXI_awlen = sp_awlen[7*8 +: 8];
    assign M07_AXI_awsize = sp_awsize[7*3 +: 3];
    assign M07_AXI_awburst = sp_awburst[7*2 +: 2];
    assign M07_AXI_awvalid = sp_awvalid[7];
    assign sp_awready[7] = M07_AXI_awready;
    assign M07_AXI_wdata = sp_wdata[7*512 +: 512];
    assign M07_AXI_wstrb = sp_wstrb[7*64 +: 64];
    assign M07_AXI_wlast = sp_wlast[7];
    assign M07_AXI_wvalid = sp_wvalid[7];
    assign sp_wready[7] = M07_AXI_wready;
    assign sp_bid[7*4 +: 4] = M07_AXI_bid;
    assign sp_bresp[7*2 +: 2] = M07_AXI_bresp;
    assign sp_bvalid[7] = M07_AXI_bvalid;
    assign M07_AXI_bready = sp_bready[7];
    assign M07_AXI_arid = sp_arid[7*4 +: 4];
    assign M07_AXI_araddr = sp_araddr[7*43 +: 43];
    assign M07_AXI_arlen = sp_arlen[7*8 +: 8];
    assign M07_AXI_arsize = sp_arsize[7*3 +: 3];
    assign M07_AXI_arburst = sp_arburst[7*2 +: 2];
    assign M07_AXI_arvalid = sp_arvalid[7];
    assign sp_arready[7] = M07_AXI_arready;
    assign sp_rid[7*4 +: 4] = M07_AXI_rid;
    assign sp_rdata[7*512 +: 512] = M07_AXI_rdata;
    assign sp_rresp[7*2 +: 2] = M07_AXI_rresp;
    assign sp_rlast[7] = M07_AXI_rlast;
    assign sp_rvalid[7] = M07_AXI_rvalid;
    assign M07_AXI_rready = sp_rready[7];

    assign M08_AXI_awid = sp_awid[8*4 +: 4];
    assign M08_AXI_awaddr = sp_awaddr[8*43 +: 43];
    assign M08_AXI_awlen = sp_awlen[8*8 +: 8];
    assign M08_AXI_awsize = sp_awsize[8*3 +: 3];
    assign M08_AXI_awburst = sp_awburst[8*2 +: 2];
    assign M08_AXI_awvalid = sp_awvalid[8];
    assign sp_awready[8] = M08_AXI_awready;
    assign M08_AXI_wdata = sp_wdata[8*512 +: 512];
    assign M08_AXI_wstrb = sp_wstrb[8*64 +: 64];
    assign M08_AXI_wlast = sp_wlast[8];
    assign M08_AXI_wvalid = sp_wvalid[8];
    assign sp_wready[8] = M08_AXI_wready;
    assign sp_bid[8*4 +: 4] = M08_AXI_bid;
    assign sp_bresp[8*2 +: 2] = M08_AXI_bresp;
    assign sp_bvalid[8] = M08_AXI_bvalid;
    assign M08_AXI_bready = sp_bready[8];
    assign M08_AXI_arid = sp_arid[8*4 +: 4];
    assign M08_AXI_araddr = sp_araddr[8*43 +: 43];
    assign M08_AXI_arlen = sp_arlen[8*8 +: 8];
    assign M08_AXI_arsize = sp_arsize[8*3 +: 3];
    assign M08_AXI_arburst = sp_arburst[8*2 +: 2];
    assign M08_AXI_arvalid = sp_arvalid[8];
    assign sp_arready[8] = M08_AXI_arready;
    assign sp_rid[8*4 +: 4] = M08_AXI_rid;
    assign sp_rdata[8*512 +: 512] = M08_AXI_rdata;
    assign sp_rresp[8*2 +: 2] = M08_AXI_rresp;
    assign sp_rlast[8] = M08_AXI_rlast;
    assign sp_rvalid[8] = M08_AXI_rvalid;
    assign M08_AXI_rready = sp_rready[8];

    assign L0_REQ_tdata  = {6'd0, lk_req_pay};
    assign L0_REQ_tvalid = lk_req_valid[0];
    assign lk_req_ready[0] = L0_REQ_tready;
    assign lk_rsp_valid[0] = L0_RSP_tvalid;
    assign L0_RSP_tready = lk_rsp_ready[0];
    assign lk_rsp_pay[0*522 +: 522] = L0_RSP_tdata[522-1:0];
    assign L1_REQ_tdata  = {6'd0, lk_req_pay};
    assign L1_REQ_tvalid = lk_req_valid[1];
    assign lk_req_ready[1] = L1_REQ_tready;
    assign lk_rsp_valid[1] = L1_RSP_tvalid;
    assign L1_RSP_tready = lk_rsp_ready[1];
    assign lk_rsp_pay[1*522 +: 522] = L1_RSP_tdata[522-1:0];
    assign L2_REQ_tdata  = {6'd0, lk_req_pay};
    assign L2_REQ_tvalid = lk_req_valid[2];
    assign lk_req_ready[2] = L2_REQ_tready;
    assign lk_rsp_valid[2] = L2_RSP_tvalid;
    assign L2_RSP_tready = lk_rsp_ready[2];
    assign lk_rsp_pay[2*522 +: 522] = L2_RSP_tdata[522-1:0];
    assign L3_REQ_tdata  = {6'd0, lk_req_pay};
    assign L3_REQ_tvalid = lk_req_valid[3];
    assign lk_req_ready[3] = L3_REQ_tready;
    assign lk_rsp_valid[3] = L3_RSP_tvalid;
    assign L3_RSP_tready = lk_rsp_ready[3];
    assign lk_rsp_pay[3*522 +: 522] = L3_RSP_tdata[522-1:0];
    assign L4_REQ_tdata  = {6'd0, lk_req_pay};
    assign L4_REQ_tvalid = lk_req_valid[4];
    assign lk_req_ready[4] = L4_REQ_tready;
    assign lk_rsp_valid[4] = L4_RSP_tvalid;
    assign L4_RSP_tready = lk_rsp_ready[4];
    assign lk_rsp_pay[4*522 +: 522] = L4_RSP_tdata[522-1:0];
    assign L5_REQ_tdata  = {6'd0, lk_req_pay};
    assign L5_REQ_tvalid = lk_req_valid[5];
    assign lk_req_ready[5] = L5_REQ_tready;
    assign lk_rsp_valid[5] = L5_RSP_tvalid;
    assign L5_RSP_tready = lk_rsp_ready[5];
    assign lk_rsp_pay[5*522 +: 522] = L5_RSP_tdata[522-1:0];

    wire [2:0]   rq_dport;
    wire [1:0]   rq_src;
    wire [3:0]   rq_tag;
    wire         rq_wr, rq_head, rq_last;
    wire [AW-1:0] rq_addr;
    wire [7:0]   rq_len;
    wire [2:0]   rq_size;
    wire [FW-1:0] rq_data;
    wire [FW/8-1:0] rq_strb;

    assign lk_req_pay = {rq_src, rq_dport, rq_tag, rq_wr, rq_head, rq_last,
                        rq_addr, rq_len, rq_size, rq_data, rq_strb};

    wire [NK*2-1:0]  rs_dst;
    wire [NK*4-1:0]  rs_tag;
    wire [NK-1:0]    rs_wr, rs_last;
    wire [NK*2-1:0]  rs_resp;
    wire [NK*FW-1:0] rs_data;

    genvar k;
    generate
    for (k = 0; k < NK; k = k + 1) begin : g_unpack
        assign {rs_dst[k*2 +: 2], rs_tag[k*4 +: 4], rs_wr[k], rs_last[k],
                rs_resp[k*2 +: 2], rs_data[k*FW +: FW]} =
            lk_rsp_pay[k*522 +: 522];
    end
    endgenerate

    sb_stn_root #(.FW(FW), .AW(AW), .MAXW(MAXW), .MAXID(MAXID), .NM(NM),
                  .NL(NL), .NK(NK), .TAGW(4), .DSTW(3), .SRCW(2),
                  .OST(OST), .STORE_FWD(STORE_FWD),
                  .LUT_PER_BRAM(LUT_PER_BRAM), .TIMEOUT(TIMEOUT),
                  .LOC_W(32'h000001FF), .NSEG(NSEG),
                  .SEG_BASE(Q_BASE), .SEG_MASK(Q_MASK),
                  .SEG_DST(Q_DST), .SEG_DPORT(Q_DPT)) u_stn (
        .bus_clk(bus_clk), .bus_rst(bus_rst),
        .clk_ctrl(clk_ctrl), .aresetn_ctrl(aresetn_ctrl),
        .clk_xdma(clk_xdma), .aresetn_xdma(aresetn_xdma),
        .clk_loc(clk_loc), .aresetn_loc(aresetn_loc),
        .mp_awid(mp_awid), .mp_awaddr(mp_awaddr), .mp_awlen(mp_awlen),
        .mp_awsize(mp_awsize), .mp_awburst(mp_awburst),
        .mp_awvalid(mp_awvalid), .mp_awready(mp_awready),
        .mp_wdata(mp_wdata), .mp_wstrb(mp_wstrb), .mp_wlast(mp_wlast),
        .mp_wvalid(mp_wvalid), .mp_wready(mp_wready),
        .mp_bid(mp_bid), .mp_bresp(mp_bresp), .mp_bvalid(mp_bvalid),
        .mp_bready(mp_bready),
        .mp_arid(mp_arid), .mp_araddr(mp_araddr), .mp_arlen(mp_arlen),
        .mp_arsize(mp_arsize), .mp_arburst(mp_arburst),
        .mp_arvalid(mp_arvalid), .mp_arready(mp_arready),
        .mp_rid(mp_rid), .mp_rdata(mp_rdata), .mp_rresp(mp_rresp),
        .mp_rlast(mp_rlast), .mp_rvalid(mp_rvalid), .mp_rready(mp_rready),
        .sp_awid(sp_awid), .sp_awaddr(sp_awaddr), .sp_awlen(sp_awlen),
        .sp_awsize(sp_awsize), .sp_awburst(sp_awburst),
        .sp_awvalid(sp_awvalid), .sp_awready(sp_awready),
        .sp_wdata(sp_wdata), .sp_wstrb(sp_wstrb), .sp_wlast(sp_wlast),
        .sp_wvalid(sp_wvalid), .sp_wready(sp_wready),
        .sp_bid(sp_bid), .sp_bresp(sp_bresp), .sp_bvalid(sp_bvalid),
        .sp_bready(sp_bready),
        .sp_arid(sp_arid), .sp_araddr(sp_araddr), .sp_arlen(sp_arlen),
        .sp_arsize(sp_arsize), .sp_arburst(sp_arburst),
        .sp_arvalid(sp_arvalid), .sp_arready(sp_arready),
        .sp_rid(sp_rid), .sp_rdata(sp_rdata), .sp_rresp(sp_rresp),
        .sp_rlast(sp_rlast), .sp_rvalid(sp_rvalid), .sp_rready(sp_rready),
        .lk_req_valid(lk_req_valid), .lk_req_ready(lk_req_ready),
        .lk_req_dport(rq_dport), .lk_req_src(rq_src), .lk_req_tag(rq_tag),
        .lk_req_wr(rq_wr), .lk_req_head(rq_head), .lk_req_last(rq_last),
        .lk_req_addr(rq_addr), .lk_req_len(rq_len), .lk_req_size(rq_size),
        .lk_req_data(rq_data), .lk_req_strb(rq_strb),
        .lk_rsp_valid(lk_rsp_valid), .lk_rsp_ready(lk_rsp_ready),
        .lk_rsp_dst(rs_dst), .lk_rsp_tag(rs_tag), .lk_rsp_wr(rs_wr),
        .lk_rsp_last(rs_last), .lk_rsp_resp(rs_resp), .lk_rsp_data(rs_data),
        .stat_decerr(stat_decerr)
    );
endmodule

`default_nettype wire
