// MAG with ONE AXI master: stock `mag` plus a per-master AXI->request shim
// feeding mag_dram_port. `mag` is instantiated VERBATIM, nothing is edited.

`default_nettype none

module mag_1m #(
    parameter integer FLIT_WIDTH = 288,
    parameter integer POS_WIDTH  = 4,
    parameter integer DATA_W     = 256,
    parameter integer ADDR_W     = 40,
    parameter integer ID_W       = 4,
    parameter integer MEM_PORTS  = 2,
    parameter integer MEM_X      = 1,
    parameter integer MEM_Y      = 1,
    parameter integer MEM_X1     = 1,
    parameter integer MEM_Y1     = 2,
    parameter integer GRID_LO    = 1,
    parameter integer GRID_HI    = 2,
    parameter integer STAGE_FLITS = 128,
    parameter integer ILINK      = 0,
    parameter integer MESH_ID    = 0,
    parameter integer LINK_W     = 288,
    parameter integer TUSER_W    = 96,
    parameter integer MW         = 512,
    parameter integer STAGE         = 0,
    parameter integer STAGE_BANKS   = 4,
    parameter integer STAGE_ENTRIES = 16384,
    parameter integer STAGE_PIPE    = 1,
    parameter integer STAGE_AT_PORT = 0,
    parameter integer NREQ       = MEM_PORTS + 2 + ((ILINK != 0) ? 1 : 0)
)(
    input  wire clk,
    input  wire resetn,
    input  wire dram_aclk,
    input  wire dram_aresetn,

    // MAG's two AXI slaves pass straight through.
    input  wire [ID_W-1:0]   sm_awid,
    input  wire [ADDR_W-1:0] sm_awaddr,
    input  wire [7:0]        sm_awlen,
    input  wire              sm_awvalid,
    output wire              sm_awready,
    input  wire [DATA_W-1:0] sm_wdata,
    input  wire [DATA_W/8-1:0] sm_wstrb,
    input  wire              sm_wlast,
    input  wire              sm_wvalid,
    output wire              sm_wready,
    output wire [ID_W-1:0]   sm_bid,
    output wire [1:0]        sm_bresp,
    output wire              sm_bvalid,
    input  wire              sm_bready,
    input  wire [ID_W-1:0]   sm_arid,
    input  wire [ADDR_W-1:0] sm_araddr,
    input  wire [7:0]        sm_arlen,
    input  wire              sm_arvalid,
    output wire              sm_arready,
    output wire [ID_W-1:0]   sm_rid,
    output wire [DATA_W-1:0] sm_rdata,
    output wire [1:0]        sm_rresp,
    output wire              sm_rlast,
    output wire              sm_rvalid,
    input  wire              sm_rready,

    input  wire [ID_W-1:0]   sc_awid,
    input  wire [31:0]       sc_awaddr,
    input  wire [7:0]        sc_awlen,
    input  wire              sc_awvalid,
    output wire              sc_awready,
    input  wire [63:0]       sc_wdata,
    input  wire [7:0]        sc_wstrb,
    input  wire              sc_wlast,
    input  wire              sc_wvalid,
    output wire              sc_wready,
    output wire [ID_W-1:0]   sc_bid,
    output wire [1:0]        sc_bresp,
    output wire              sc_bvalid,
    input  wire              sc_bready,
    input  wire [ID_W-1:0]   sc_arid,
    input  wire [31:0]       sc_araddr,
    input  wire [7:0]        sc_arlen,
    input  wire              sc_arvalid,
    output wire              sc_arready,
    output wire [ID_W-1:0]   sc_rid,
    output wire [63:0]       sc_rdata,
    output wire [1:0]        sc_rresp,
    output wire              sc_rlast,
    output wire              sc_rvalid,
    input  wire              sc_rready,

    // NoC
    input  wire [MEM_PORTS*FLIT_WIDTH-1:0] mem_in_data,
    input  wire [MEM_PORTS-1:0]            mem_in_valid,
    output wire [MEM_PORTS-1:0]            mem_in_busy,
    output wire [MEM_PORTS*FLIT_WIDTH-1:0] mem_out_data,
    output wire [MEM_PORTS-1:0]            mem_out_valid,
    input  wire [MEM_PORTS-1:0]            mem_out_busy,
    output wire [15:0]                     mem_rd_count,
    output wire [15:0]                     mem_wr_count,
    output wire                            mv_busy,
    output wire [3:0]                      mv_fault,
    output wire [31:0]                     mv_done,

    // THE POINT: one AXI master, one memory clock.
    output wire [ID_W-1:0]   m_awid,
    output wire [ADDR_W-1:0] m_awaddr,
    output wire [7:0]        m_awlen,
    output wire [2:0]        m_awsize,
    output wire [1:0]        m_awburst,
    output wire              m_awvalid,
    input  wire              m_awready,
    output wire [MW-1:0]     m_wdata,
    output wire [MW/8-1:0]   m_wstrb,
    output wire              m_wlast,
    output wire              m_wvalid,
    input  wire              m_wready,
    input  wire [ID_W-1:0]   m_bid,
    input  wire [1:0]        m_bresp,
    input  wire              m_bvalid,
    output wire              m_bready,
    output wire [ID_W-1:0]   m_arid,
    output wire [ADDR_W-1:0] m_araddr,
    output wire [7:0]        m_arlen,
    output wire [2:0]        m_arsize,
    output wire [1:0]        m_arburst,
    output wire              m_arvalid,
    input  wire              m_arready,
    input  wire [ID_W-1:0]   m_rid,
    input  wire [MW-1:0]     m_rdata,
    input  wire [1:0]        m_rresp,
    input  wire              m_rlast,
    input  wire              m_rvalid,
    output wire              m_rready,

    // Straight through to `mag`; constants at ILINK=0, as there.
    output wire [LINK_W-1:0]  link0_out_tdata,
    output wire [TUSER_W-1:0] link0_out_tuser,
    output wire               link0_out_tlast,
    output wire               link0_out_tvalid,
    input  wire               link0_out_tready,
    input  wire [LINK_W-1:0]  link0_in_tdata,
    input  wire [TUSER_W-1:0] link0_in_tuser,
    input  wire               link0_in_tlast,
    input  wire               link0_in_tvalid,
    output wire               link0_in_tready,
    output wire [LINK_W-1:0]  link1_out_tdata,
    output wire [TUSER_W-1:0] link1_out_tuser,
    output wire               link1_out_tlast,
    output wire               link1_out_tvalid,
    input  wire               link1_out_tready,
    input  wire [LINK_W-1:0]  link1_in_tdata,
    input  wire [TUSER_W-1:0] link1_in_tuser,
    input  wire               link1_in_tlast,
    input  wire               link1_in_tvalid,
    output wire               link1_in_tready
);
    // ---- the stock MAG, verbatim ----------------------------------------
    wire [NREQ*ID_W-1:0]     x_awid,  x_arid,  x_bid,  x_rid;
    wire [NREQ*ADDR_W-1:0]   x_awaddr, x_araddr;
    wire [NREQ*8-1:0]        x_awlen, x_arlen;
    wire [NREQ*3-1:0]        x_awsize, x_arsize;
    wire [NREQ*2-1:0]        x_awburst, x_arburst, x_bresp, x_rresp;
    wire [NREQ-1:0]          x_awvalid, x_awready, x_arvalid, x_arready;
    wire [NREQ*DATA_W-1:0]   x_wdata, x_rdata;
    wire [NREQ*DATA_W/8-1:0] x_wstrb;
    wire [NREQ-1:0]          x_wlast, x_wvalid, x_wready;
    wire [NREQ-1:0]          x_bvalid, x_bready, x_rlast, x_rvalid, x_rready;

    mag #(.FLIT_WIDTH(FLIT_WIDTH), .POS_WIDTH(POS_WIDTH), .DATA_W(DATA_W),
          .MW(MW),
          .ADDR_W(ADDR_W), .ID_W(ID_W), .MEM_PORTS(MEM_PORTS),
          .MEM_X(MEM_X), .MEM_Y(MEM_Y), .MEM_X1(MEM_X1), .MEM_Y1(MEM_Y1),
          .GRID_LO(GRID_LO), .GRID_HI(GRID_HI), .STAGE_FLITS(STAGE_FLITS),
          .ILINK(ILINK), .MESH_ID(MESH_ID), .LINK_W(LINK_W),
          .TUSER_W(TUSER_W), .STAGE(STAGE), .STAGE_BANKS(STAGE_BANKS),
          .STAGE_ENTRIES(STAGE_ENTRIES), .STAGE_PIPE(STAGE_PIPE),
          .STAGE_AT_PORT(STAGE_AT_PORT)) u_mag (
        .clk(clk), .resetn(resetn),
        .sm_awid(sm_awid), .sm_awaddr(sm_awaddr), .sm_awlen(sm_awlen),
        .sm_awvalid(sm_awvalid), .sm_awready(sm_awready),
        .sm_wdata(sm_wdata), .sm_wstrb(sm_wstrb), .sm_wlast(sm_wlast),
        .sm_wvalid(sm_wvalid), .sm_wready(sm_wready),
        .sm_bid(sm_bid), .sm_bresp(sm_bresp), .sm_bvalid(sm_bvalid),
        .sm_bready(sm_bready),
        .sm_arid(sm_arid), .sm_araddr(sm_araddr), .sm_arlen(sm_arlen),
        .sm_arvalid(sm_arvalid), .sm_arready(sm_arready),
        .sm_rid(sm_rid), .sm_rdata(sm_rdata), .sm_rresp(sm_rresp),
        .sm_rlast(sm_rlast), .sm_rvalid(sm_rvalid), .sm_rready(sm_rready),
        .sc_awid(sc_awid), .sc_awaddr(sc_awaddr), .sc_awlen(sc_awlen),
        .sc_awvalid(sc_awvalid), .sc_awready(sc_awready),
        .sc_wdata(sc_wdata), .sc_wstrb(sc_wstrb), .sc_wlast(sc_wlast),
        .sc_wvalid(sc_wvalid), .sc_wready(sc_wready),
        .sc_bid(sc_bid), .sc_bresp(sc_bresp), .sc_bvalid(sc_bvalid),
        .sc_bready(sc_bready),
        .sc_arid(sc_arid), .sc_araddr(sc_araddr), .sc_arlen(sc_arlen),
        .sc_arvalid(sc_arvalid), .sc_arready(sc_arready),
        .sc_rid(sc_rid), .sc_rdata(sc_rdata), .sc_rresp(sc_rresp),
        .sc_rlast(sc_rlast), .sc_rvalid(sc_rvalid), .sc_rready(sc_rready),
        .dram_aclk(dram_aclk), .dram_aresetn(dram_aresetn),
        .dram_awid(m_awid), .dram_awaddr(m_awaddr), .dram_awlen(m_awlen),
        .dram_awsize(m_awsize), .dram_awburst(m_awburst),
        .dram_awvalid(m_awvalid), .dram_awready(m_awready),
        .dram_wdata(m_wdata), .dram_wstrb(m_wstrb), .dram_wlast(m_wlast),
        .dram_wvalid(m_wvalid), .dram_wready(m_wready),
        .dram_bid(m_bid), .dram_bresp(m_bresp), .dram_bvalid(m_bvalid),
        .dram_bready(m_bready),
        .dram_arid(m_arid), .dram_araddr(m_araddr), .dram_arlen(m_arlen),
        .dram_arsize(m_arsize), .dram_arburst(m_arburst),
        .dram_arvalid(m_arvalid), .dram_arready(m_arready),
        .dram_rid(m_rid), .dram_rdata(m_rdata), .dram_rresp(m_rresp),
        .dram_rlast(m_rlast), .dram_rvalid(m_rvalid), .dram_rready(m_rready),
        .mem_in_data(mem_in_data), .mem_in_valid(mem_in_valid),
        .mem_in_busy(mem_in_busy),
        .mem_out_data(mem_out_data), .mem_out_valid(mem_out_valid),
        .mem_out_busy(mem_out_busy),
        .mem_rd_count(mem_rd_count), .mem_wr_count(mem_wr_count),
        .mv_busy(mv_busy), .mv_fault(mv_fault), .mv_done(mv_done),
        .link0_out_tdata(link0_out_tdata), .link0_out_tuser(link0_out_tuser),
        .link0_out_tlast(link0_out_tlast), .link0_out_tvalid(link0_out_tvalid),
        .link0_out_tready(link0_out_tready),
        .link0_in_tdata(link0_in_tdata), .link0_in_tuser(link0_in_tuser),
        .link0_in_tlast(link0_in_tlast), .link0_in_tvalid(link0_in_tvalid),
        .link0_in_tready(link0_in_tready),
        .link1_out_tdata(link1_out_tdata), .link1_out_tuser(link1_out_tuser),
        .link1_out_tlast(link1_out_tlast), .link1_out_tvalid(link1_out_tvalid),
        .link1_out_tready(link1_out_tready),
        .link1_in_tdata(link1_in_tdata), .link1_in_tuser(link1_in_tuser),
        .link1_in_tlast(link1_in_tlast), .link1_in_tvalid(link1_in_tvalid),
        .link1_in_tready(link1_in_tready)
    );

endmodule

`default_nettype wire
