// mm_mesh at MW=512: the e2e that proves MAG's own mag_dram_port carries agent,
// memory-port, mover and upload traffic, not directed bursts.

`default_nettype none

module mm_mesh_1m #(
    parameter integer FW      = 288,
    parameter integer PW      = 4,
    parameter integer DW      = 256,
    parameter integer AW      = 40,
    parameter integer IDW     = 4,
    parameter integer MEMP    = 1,
    parameter integer NCH     = MEMP + 2,
    parameter integer MW      = 512,
    parameter integer MODEL   = 0,
    parameter integer GRID_LO = 1,
    parameter integer GRID_HI = 2
)(
    input  wire clk,
    input  wire rst,
    input  wire dram_aclk,
    input  wire dram_aresetn,

    input  wire [AW-1:0]  sm_awaddr,
    input  wire [7:0]     sm_awlen,
    input  wire           sm_awvalid,
    input  wire [DW-1:0]  sm_wdata,
    input  wire           sm_wlast,
    input  wire           sm_wvalid,
    input  wire [31:0]    sc_awaddr,
    input  wire           sc_awvalid,
    output wire           sc_awready,
    input  wire [63:0]    sc_wdata,
    input  wire           sc_wvalid,
    output wire           sc_wready,
    output wire           sc_bvalid,
    input  wire [31:0]    sc_araddr,
    input  wire           sc_arvalid,
    output wire [63:0]    sc_rdata,
    output wire           sc_rvalid,

    output wire           mv_busy,
    output wire [3:0]     mv_fault,
    output wire [31:0]    mv_done,

    output wire [IDW-1:0] m_awid,
    output wire [AW-1:0]  m_awaddr,
    output wire [7:0]     m_awlen,
    output wire [2:0]     m_awsize,
    output wire [1:0]     m_awburst,
    output wire           m_awvalid,
    input  wire           m_awready,
    output wire [MW-1:0]  m_wdata,
    output wire [MW/8-1:0] m_wstrb,
    output wire           m_wlast,
    output wire           m_wvalid,
    input  wire           m_wready,
    input  wire [IDW-1:0] m_bid,
    input  wire [1:0]     m_bresp,
    input  wire           m_bvalid,
    output wire           m_bready,
    output wire [IDW-1:0] m_arid,
    output wire [AW-1:0]  m_araddr,
    output wire [7:0]     m_arlen,
    output wire [2:0]     m_arsize,
    output wire [1:0]     m_arburst,
    output wire           m_arvalid,
    input  wire           m_arready,
    input  wire [IDW-1:0] m_rid,
    input  wire [MW-1:0]  m_rdata,
    input  wire [1:0]     m_rresp,
    input  wire           m_rlast,
    input  wire           m_rvalid,
    output wire           m_rready,

    input  wire [FW-1:0]  ext_in_data,
    input  wire           ext_in_valid,
    output wire           ext_in_busy,
    output wire [FW-1:0]  ext_out_data,
    output wire           ext_out_valid,
    input  wire           ext_out_busy,
    output wire [47:0]    dbg_cluster,
    output wire [31:0]    dbg_vec_cycles,
    output wire           dbg_vec_fault,
    output wire [31:0]    obs
);
    mm_mesh #(.FW(FW), .PW(PW), .DW(DW), .AW(AW), .IDW(IDW), .MEMP(MEMP),
              .MW(MW),
              .MODEL(MODEL), .GRID_LO(GRID_LO), .GRID_HI(GRID_HI)) u_mesh (
        .clk(clk), .mat_clk(clk), .vec_clk(clk), .rst(rst),
        .sm_awaddr(sm_awaddr), .sm_awlen(sm_awlen), .sm_awvalid(sm_awvalid),
        .sm_wdata(sm_wdata), .sm_wlast(sm_wlast), .sm_wvalid(sm_wvalid),
        .sc_awaddr(sc_awaddr), .sc_awvalid(sc_awvalid), .sc_awready(sc_awready),
        .sc_wdata(sc_wdata), .sc_wvalid(sc_wvalid), .sc_wready(sc_wready),
        .sc_bvalid(sc_bvalid), .sc_araddr(sc_araddr), .sc_arvalid(sc_arvalid),
        .sc_rdata(sc_rdata), .sc_rvalid(sc_rvalid),
        .mv_busy(mv_busy), .mv_fault(mv_fault), .mv_done(mv_done),
        .dram_aclk(dram_aclk), .dram_aresetn(dram_aresetn),
        .dram_awid(m_awid), .dram_awaddr(m_awaddr), .dram_awlen(m_awlen),
        .dram_awsize(m_awsize), .dram_awburst(m_awburst),
        .dram_awvalid(m_awvalid), .dram_awready(m_awready),
        .dram_wdata(m_wdata), .dram_wstrb(m_wstrb), .dram_wlast(m_wlast),
        .dram_wvalid(m_wvalid), .dram_wready(m_wready),
        .dram_bid(m_bid), .dram_bresp(m_bresp), .dram_bvalid(m_bvalid),
        .dram_bready(m_bready),
        .dram_arid(m_arid), .dram_araddr(m_araddr), .dram_arlen(m_arlen),
        .dram_arsize(m_arsize), .dram_arburst(m_arburst),
        .dram_arvalid(m_arvalid), .dram_arready(m_arready),
        .dram_rid(m_rid), .dram_rdata(m_rdata), .dram_rresp(m_rresp),
        .dram_rlast(m_rlast), .dram_rvalid(m_rvalid), .dram_rready(m_rready),
        .ext_in_data(ext_in_data), .ext_in_valid(ext_in_valid),
        .ext_in_busy(ext_in_busy),
        .ext_out_data(ext_out_data), .ext_out_valid(ext_out_valid),
        .ext_out_busy(ext_out_busy),
        .dbg_cluster(dbg_cluster), .dbg_vec_cycles(dbg_vec_cycles),
        .dbg_vec_fault(dbg_vec_fault), .obs(obs)
    );

endmodule

`default_nettype wire
