// card_v9_1n -- GENERATED by scripts/py/gen_card.py from scripts/tcl/v9/00_config.tcl.
// Do not edit by hand.
//
// Die modules: ktpu_ship_2x1_4c2v_1m_nol2_pump; compute dies [0].
// Config overrides: none
// Clocks are ports. `rstn` is the control wizard's lock; every sysnode
// domain is held by lock_all, the AND of rstn and the mesh wizards' locks.

`default_nettype none

// 1 = behavioural DSPs; xsim.py and vlt.py define it.
`ifndef MX_MODEL
`define MX_MODEL 1
`endif

module card_v9_1n #(
    parameter integer DRAM_WORDS = 65536,   // 512-bit words per channel
    parameter integer LOCK_CYC   = 64     // clk_ctrl cycles a LOAD holds the lock low
)(
    input  wire clk_ctrl,              // clk_wiz_ctrl out1: station port 3, the wizards
    input  wire clk_xdma,              // xdma_0/axi_aclk: managers 1 and 2
    input  wire [3:0] bus_clk,         // clk_wiz_ctrl out2..5; JTAG on bus_clk[1]
    input  wire [3:0] sys_clk,         // mesh wizard out4: node, Xache partition, ports 0/1
    input  wire [3:0] noc_clk,         // mesh wizard out1
    input  wire [3:0] mat2x_clk,       // mesh wizard out2 (mat 1x through ktpu_div2)
    input  wire [3:0] vec_clk,         // mesh wizard out3
    input  wire [3:0] ddr_clk,         // MIG ui_clk: Xache home, station port 2
    input  wire rstn,

    // manager 0: jtag_axi, 64-bit, on bus_clk[1]
    input  wire [3:0] h0_awid,
    input  wire [42:0] h0_awaddr,
    input  wire [7:0] h0_awlen,
    input  wire [2:0] h0_awsize,
    input  wire [1:0] h0_awburst,
    input  wire h0_awvalid,
    output wire h0_awready,
    input  wire [63:0] h0_wdata,
    input  wire [7:0] h0_wstrb,
    input  wire h0_wlast,
    input  wire h0_wvalid,
    output wire h0_wready,
    output wire [3:0] h0_bid,
    output wire [1:0] h0_bresp,
    output wire h0_bvalid,
    input  wire h0_bready,
    input  wire [3:0] h0_arid,
    input  wire [42:0] h0_araddr,
    input  wire [7:0] h0_arlen,
    input  wire [2:0] h0_arsize,
    input  wire [1:0] h0_arburst,
    input  wire h0_arvalid,
    output wire h0_arready,
    output wire [3:0] h0_rid,
    output wire [63:0] h0_rdata,
    output wire [1:0] h0_rresp,
    output wire h0_rlast,
    output wire h0_rvalid,
    input  wire h0_rready,

    // manager 1: XDMA M_AXI, 512-bit, on clk_xdma
    input  wire [3:0] h1_awid,
    input  wire [42:0] h1_awaddr,
    input  wire [7:0] h1_awlen,
    input  wire [2:0] h1_awsize,
    input  wire [1:0] h1_awburst,
    input  wire h1_awvalid,
    output wire h1_awready,
    input  wire [511:0] h1_wdata,
    input  wire [63:0] h1_wstrb,
    input  wire h1_wlast,
    input  wire h1_wvalid,
    output wire h1_wready,
    output wire [3:0] h1_bid,
    output wire [1:0] h1_bresp,
    output wire h1_bvalid,
    input  wire h1_bready,
    input  wire [3:0] h1_arid,
    input  wire [42:0] h1_araddr,
    input  wire [7:0] h1_arlen,
    input  wire [2:0] h1_arsize,
    input  wire [1:0] h1_arburst,
    input  wire h1_arvalid,
    output wire h1_arready,
    output wire [3:0] h1_rid,
    output wire [511:0] h1_rdata,
    output wire [1:0] h1_rresp,
    output wire h1_rlast,
    output wire h1_rvalid,
    input  wire h1_rready,

    // manager 2: XDMA M_AXI_LITE, 32-bit, on clk_xdma
    input  wire [42:0] h2_awaddr,
    input  wire h2_awvalid,
    output wire h2_awready,
    input  wire [31:0] h2_wdata,
    input  wire [3:0] h2_wstrb,
    input  wire h2_wvalid,
    output wire h2_wready,
    output wire [1:0] h2_bresp,
    output wire h2_bvalid,
    input  wire h2_bready,
    input  wire [42:0] h2_araddr,
    input  wire h2_arvalid,
    output wire h2_arready,
    output wire [31:0] h2_rdata,
    output wire [1:0] h2_rresp,
    output wire h2_rvalid,
    input  wire h2_rready,

    // the mesh wizards as applied: CLKOUT3..0 divides, M, D, lock
    output wire [4*32-1:0] wiz_div,
    output wire [4*8-1:0]  wiz_mult,
    output wire [4*8-1:0]  wiz_divclk,
    output wire [3:0]      wiz_locked,

    // DRAM backdoors, channel h = Xache home h
    input  wire [3:0]       bd_we,
    input  wire [4*16-1:0]  bd_addr,
    input  wire [4*512-1:0] bd_wdata,
    output wire [4*512-1:0] bd_rdata,

    output wire [31:0] stat_decerr,
    output wire [3:0]  sys_rstn         // each die's sysnode reset
);

    // ---- resets: one per clock (20_clocks.tcl at PER_DIE_CLK 1) -------
    wire rstn_ctrl, rstn_xdma;
    wire [3:0] rstn_bus, rstn_sys, rstn_ddr;
    wire lock_all = rstn & (&wiz_locked);
    kh_rst_sync u_rs_ctrl (.clk(clk_ctrl), .arstn(rstn), .rstn(rstn_ctrl));
    kh_rst_sync u_rs_xdma (.clk(clk_xdma), .arstn(rstn), .rstn(rstn_xdma));
    assign sys_rstn = rstn_sys;
    genvar gi;
    generate for (gi = 0; gi < 4; gi = gi + 1) begin : g_rs
        kh_rst_sync u_bus (.clk(bus_clk[gi]), .arstn(rstn), .rstn(rstn_bus[gi]));
        kh_rst_sync u_sys (.clk(sys_clk[gi]), .arstn(lock_all), .rstn(rstn_sys[gi]));
        kh_rst_sync u_ddr (.clk(ddr_clk[gi]), .arstn(rstn), .rstn(rstn_ddr[gi]));
    end endgenerate

    // ---- the station map (v8/50_addr_lit.tcl) ---------------------------
    localparam [16*43-1:0] SEG_BASE  = 688'h0000126000000000c00000000041800040000000000000012400000000080000000004100003000000000000001220000000004000000000408000200000000000000120000000000000000000040000010000000000;
    localparam [16*43-1:0] SEG_MASK  = 688'hffffffe0001fffffc00003ffffff800070000000000ffffffe0001fffffc00003ffffff800070000000000ffffffe0001fffffc00003ffffff800070000000000ffffffe0001fffffc00003ffffff800070000000000;
    localparam [16*43-1:0] SEG_XLT   = 688'h0000126000000000c00000000041800000000000000000012400000000080000000004100000000000000000001220000000004000000000408000000000000000000120000000000000000000040000000000000000;
    localparam [16*2-1:0]  SEG_DST   = 32'hffaa5500;
    localparam [16*2-1:0]  SEG_DPORT = 32'he4e4e4e4;

    wire [3:0] M00_awid;
    wire [42:0] M00_awaddr;
    wire [7:0] M00_awlen;
    wire [2:0] M00_awsize;
    wire [1:0] M00_awburst;
    wire M00_awvalid;
    wire M00_awready;
    wire [255:0] M00_wdata;
    wire [31:0] M00_wstrb;
    wire M00_wlast;
    wire M00_wvalid;
    wire M00_wready;
    wire [3:0] M00_bid;
    wire [1:0] M00_bresp;
    wire M00_bvalid;
    wire M00_bready;
    wire [3:0] M00_arid;
    wire [42:0] M00_araddr;
    wire [7:0] M00_arlen;
    wire [2:0] M00_arsize;
    wire [1:0] M00_arburst;
    wire M00_arvalid;
    wire M00_arready;
    wire [3:0] M00_rid;
    wire [255:0] M00_rdata;
    wire [1:0] M00_rresp;
    wire M00_rlast;
    wire M00_rvalid;
    wire M00_rready;
    wire [3:0] M01_awid;
    wire [42:0] M01_awaddr;
    wire [7:0] M01_awlen;
    wire [2:0] M01_awsize;
    wire [1:0] M01_awburst;
    wire M01_awvalid;
    wire M01_awready;
    wire [31:0] M01_wdata;
    wire [3:0] M01_wstrb;
    wire M01_wlast;
    wire M01_wvalid;
    wire M01_wready;
    wire [3:0] M01_bid;
    wire [1:0] M01_bresp;
    wire M01_bvalid;
    wire M01_bready;
    wire [3:0] M01_arid;
    wire [42:0] M01_araddr;
    wire [7:0] M01_arlen;
    wire [2:0] M01_arsize;
    wire [1:0] M01_arburst;
    wire M01_arvalid;
    wire M01_arready;
    wire [3:0] M01_rid;
    wire [31:0] M01_rdata;
    wire [1:0] M01_rresp;
    wire M01_rlast;
    wire M01_rvalid;
    wire M01_rready;
    wire [42:0] M02_awaddr;
    wire M02_awvalid;
    wire M02_awready;
    wire [31:0] M02_wdata;
    wire [3:0] M02_wstrb;
    wire M02_wvalid;
    wire M02_wready;
    wire [1:0] M02_bresp;
    wire M02_bvalid;
    wire M02_bready;
    wire [42:0] M02_araddr;
    wire M02_arvalid;
    wire M02_arready;
    wire [31:0] M02_rdata;
    wire [1:0] M02_rresp;
    wire M02_rvalid;
    wire M02_rready;
    wire [42:0] M03_awaddr;
    wire M03_awvalid;
    wire M03_awready;
    wire [31:0] M03_wdata;
    wire [3:0] M03_wstrb;
    wire M03_wvalid;
    wire M03_wready;
    wire [1:0] M03_bresp;
    wire M03_bvalid;
    wire M03_bready;
    wire [42:0] M03_araddr;
    wire M03_arvalid;
    wire M03_arready;
    wire [31:0] M03_rdata;
    wire [1:0] M03_rresp;
    wire M03_rvalid;
    wire M03_rready;
    wire [3:0] M04_awid;
    wire [42:0] M04_awaddr;
    wire [7:0] M04_awlen;
    wire [2:0] M04_awsize;
    wire [1:0] M04_awburst;
    wire M04_awvalid;
    wire M04_awready;
    wire [255:0] M04_wdata;
    wire [31:0] M04_wstrb;
    wire M04_wlast;
    wire M04_wvalid;
    wire M04_wready;
    wire [3:0] M04_bid;
    wire [1:0] M04_bresp;
    wire M04_bvalid;
    wire M04_bready;
    wire [3:0] M04_arid;
    wire [42:0] M04_araddr;
    wire [7:0] M04_arlen;
    wire [2:0] M04_arsize;
    wire [1:0] M04_arburst;
    wire M04_arvalid;
    wire M04_arready;
    wire [3:0] M04_rid;
    wire [255:0] M04_rdata;
    wire [1:0] M04_rresp;
    wire M04_rlast;
    wire M04_rvalid;
    wire M04_rready;
    wire [3:0] M05_awid;
    wire [42:0] M05_awaddr;
    wire [7:0] M05_awlen;
    wire [2:0] M05_awsize;
    wire [1:0] M05_awburst;
    wire M05_awvalid;
    wire M05_awready;
    wire [31:0] M05_wdata;
    wire [3:0] M05_wstrb;
    wire M05_wlast;
    wire M05_wvalid;
    wire M05_wready;
    wire [3:0] M05_bid;
    wire [1:0] M05_bresp;
    wire M05_bvalid;
    wire M05_bready;
    wire [3:0] M05_arid;
    wire [42:0] M05_araddr;
    wire [7:0] M05_arlen;
    wire [2:0] M05_arsize;
    wire [1:0] M05_arburst;
    wire M05_arvalid;
    wire M05_arready;
    wire [3:0] M05_rid;
    wire [31:0] M05_rdata;
    wire [1:0] M05_rresp;
    wire M05_rlast;
    wire M05_rvalid;
    wire M05_rready;
    wire [42:0] M06_awaddr;
    wire M06_awvalid;
    wire M06_awready;
    wire [31:0] M06_wdata;
    wire [3:0] M06_wstrb;
    wire M06_wvalid;
    wire M06_wready;
    wire [1:0] M06_bresp;
    wire M06_bvalid;
    wire M06_bready;
    wire [42:0] M06_araddr;
    wire M06_arvalid;
    wire M06_arready;
    wire [31:0] M06_rdata;
    wire [1:0] M06_rresp;
    wire M06_rvalid;
    wire M06_rready;
    wire [42:0] M07_awaddr;
    wire M07_awvalid;
    wire M07_awready;
    wire [31:0] M07_wdata;
    wire [3:0] M07_wstrb;
    wire M07_wvalid;
    wire M07_wready;
    wire [1:0] M07_bresp;
    wire M07_bvalid;
    wire M07_bready;
    wire [42:0] M07_araddr;
    wire M07_arvalid;
    wire M07_arready;
    wire [31:0] M07_rdata;
    wire [1:0] M07_rresp;
    wire M07_rvalid;
    wire M07_rready;
    wire [3:0] M08_awid;
    wire [42:0] M08_awaddr;
    wire [7:0] M08_awlen;
    wire [2:0] M08_awsize;
    wire [1:0] M08_awburst;
    wire M08_awvalid;
    wire M08_awready;
    wire [255:0] M08_wdata;
    wire [31:0] M08_wstrb;
    wire M08_wlast;
    wire M08_wvalid;
    wire M08_wready;
    wire [3:0] M08_bid;
    wire [1:0] M08_bresp;
    wire M08_bvalid;
    wire M08_bready;
    wire [3:0] M08_arid;
    wire [42:0] M08_araddr;
    wire [7:0] M08_arlen;
    wire [2:0] M08_arsize;
    wire [1:0] M08_arburst;
    wire M08_arvalid;
    wire M08_arready;
    wire [3:0] M08_rid;
    wire [255:0] M08_rdata;
    wire [1:0] M08_rresp;
    wire M08_rlast;
    wire M08_rvalid;
    wire M08_rready;
    wire [3:0] M09_awid;
    wire [42:0] M09_awaddr;
    wire [7:0] M09_awlen;
    wire [2:0] M09_awsize;
    wire [1:0] M09_awburst;
    wire M09_awvalid;
    wire M09_awready;
    wire [31:0] M09_wdata;
    wire [3:0] M09_wstrb;
    wire M09_wlast;
    wire M09_wvalid;
    wire M09_wready;
    wire [3:0] M09_bid;
    wire [1:0] M09_bresp;
    wire M09_bvalid;
    wire M09_bready;
    wire [3:0] M09_arid;
    wire [42:0] M09_araddr;
    wire [7:0] M09_arlen;
    wire [2:0] M09_arsize;
    wire [1:0] M09_arburst;
    wire M09_arvalid;
    wire M09_arready;
    wire [3:0] M09_rid;
    wire [31:0] M09_rdata;
    wire [1:0] M09_rresp;
    wire M09_rlast;
    wire M09_rvalid;
    wire M09_rready;
    wire [42:0] M10_awaddr;
    wire M10_awvalid;
    wire M10_awready;
    wire [31:0] M10_wdata;
    wire [3:0] M10_wstrb;
    wire M10_wvalid;
    wire M10_wready;
    wire [1:0] M10_bresp;
    wire M10_bvalid;
    wire M10_bready;
    wire [42:0] M10_araddr;
    wire M10_arvalid;
    wire M10_arready;
    wire [31:0] M10_rdata;
    wire [1:0] M10_rresp;
    wire M10_rvalid;
    wire M10_rready;
    wire [42:0] M11_awaddr;
    wire M11_awvalid;
    wire M11_awready;
    wire [31:0] M11_wdata;
    wire [3:0] M11_wstrb;
    wire M11_wvalid;
    wire M11_wready;
    wire [1:0] M11_bresp;
    wire M11_bvalid;
    wire M11_bready;
    wire [42:0] M11_araddr;
    wire M11_arvalid;
    wire M11_arready;
    wire [31:0] M11_rdata;
    wire [1:0] M11_rresp;
    wire M11_rvalid;
    wire M11_rready;
    wire [3:0] M12_awid;
    wire [42:0] M12_awaddr;
    wire [7:0] M12_awlen;
    wire [2:0] M12_awsize;
    wire [1:0] M12_awburst;
    wire M12_awvalid;
    wire M12_awready;
    wire [255:0] M12_wdata;
    wire [31:0] M12_wstrb;
    wire M12_wlast;
    wire M12_wvalid;
    wire M12_wready;
    wire [3:0] M12_bid;
    wire [1:0] M12_bresp;
    wire M12_bvalid;
    wire M12_bready;
    wire [3:0] M12_arid;
    wire [42:0] M12_araddr;
    wire [7:0] M12_arlen;
    wire [2:0] M12_arsize;
    wire [1:0] M12_arburst;
    wire M12_arvalid;
    wire M12_arready;
    wire [3:0] M12_rid;
    wire [255:0] M12_rdata;
    wire [1:0] M12_rresp;
    wire M12_rlast;
    wire M12_rvalid;
    wire M12_rready;
    wire [3:0] M13_awid;
    wire [42:0] M13_awaddr;
    wire [7:0] M13_awlen;
    wire [2:0] M13_awsize;
    wire [1:0] M13_awburst;
    wire M13_awvalid;
    wire M13_awready;
    wire [31:0] M13_wdata;
    wire [3:0] M13_wstrb;
    wire M13_wlast;
    wire M13_wvalid;
    wire M13_wready;
    wire [3:0] M13_bid;
    wire [1:0] M13_bresp;
    wire M13_bvalid;
    wire M13_bready;
    wire [3:0] M13_arid;
    wire [42:0] M13_araddr;
    wire [7:0] M13_arlen;
    wire [2:0] M13_arsize;
    wire [1:0] M13_arburst;
    wire M13_arvalid;
    wire M13_arready;
    wire [3:0] M13_rid;
    wire [31:0] M13_rdata;
    wire [1:0] M13_rresp;
    wire M13_rlast;
    wire M13_rvalid;
    wire M13_rready;
    wire [42:0] M14_awaddr;
    wire M14_awvalid;
    wire M14_awready;
    wire [31:0] M14_wdata;
    wire [3:0] M14_wstrb;
    wire M14_wvalid;
    wire M14_wready;
    wire [1:0] M14_bresp;
    wire M14_bvalid;
    wire M14_bready;
    wire [42:0] M14_araddr;
    wire M14_arvalid;
    wire M14_arready;
    wire [31:0] M14_rdata;
    wire [1:0] M14_rresp;
    wire M14_rvalid;
    wire M14_rready;
    wire [42:0] M15_awaddr;
    wire M15_awvalid;
    wire M15_awready;
    wire [31:0] M15_wdata;
    wire [3:0] M15_wstrb;
    wire M15_wvalid;
    wire M15_wready;
    wire [1:0] M15_bresp;
    wire M15_bvalid;
    wire M15_bready;
    wire [42:0] M15_araddr;
    wire M15_arvalid;
    wire M15_arready;
    wire [31:0] M15_rdata;
    wire [1:0] M15_rresp;
    wire M15_rvalid;
    wire M15_rready;

    sb_bd_line4_jbus #(
        .FW(256), .OST(4), .STORE_FWD(1), .LUT_PER_BRAM(120),
        .LPB1(270), .TIMEOUT(0), .LINK_CDC(1), .LINK_FULL(0),
        .LINK_KTS(0), .MGR0_DOM(1), .CRED(16), .PIPE(4),
        .MREQ0(256), .MRSP0(256), .MMAXB0(0), .MREQ1(64),
        .MRSP1(128), .MMAXB1(0), .MREQ2(16), .MRSP2(16),
        .MMAXB2(1), .SEG_OVERRIDE(1), .SEG_BASE_P(SEG_BASE), .SEG_MASK_P(SEG_MASK),
        .SEG_XLT_P(SEG_XLT), .SEG_DST_P(SEG_DST), .SEG_DPORT_P(SEG_DPORT), .SEG_VLD_P(16'hffff)
    ) u_bus (
        .bus_clk0(bus_clk[0]), .bus_rst0(!rstn_bus[0]), .clk_s0(sys_clk[0]), .aresetn_s0(rstn_sys[0]),
        .clk_ddr0(ddr_clk[0]), .aresetn_ddr0(rstn_ddr[0]), .bus_clk1(bus_clk[1]), .bus_rst1(!rstn_bus[1]),
        .clk_s1(sys_clk[1]), .aresetn_s1(rstn_sys[1]), .clk_ddr1(ddr_clk[1]), .aresetn_ddr1(rstn_ddr[1]),
        .bus_clk2(bus_clk[2]), .bus_rst2(!rstn_bus[2]), .clk_s2(sys_clk[2]), .aresetn_s2(rstn_sys[2]),
        .clk_ddr2(ddr_clk[2]), .aresetn_ddr2(rstn_ddr[2]), .bus_clk3(bus_clk[3]), .bus_rst3(!rstn_bus[3]),
        .clk_s3(sys_clk[3]), .aresetn_s3(rstn_sys[3]), .clk_ddr3(ddr_clk[3]), .aresetn_ddr3(rstn_ddr[3]),
        .clk_ctrl(clk_ctrl), .aresetn_ctrl(rstn_ctrl), .clk_xdma(clk_xdma), .aresetn_xdma(rstn_xdma),
        .S00_AXI_awid(h0_awid), .S00_AXI_awaddr(h0_awaddr), .S00_AXI_awlen(h0_awlen), .S00_AXI_awsize(h0_awsize),
        .S00_AXI_awburst(h0_awburst), .S00_AXI_awvalid(h0_awvalid), .S00_AXI_awready(h0_awready), .S00_AXI_wdata(h0_wdata),
        .S00_AXI_wstrb(h0_wstrb), .S00_AXI_wlast(h0_wlast), .S00_AXI_wvalid(h0_wvalid), .S00_AXI_wready(h0_wready),
        .S00_AXI_bid(h0_bid), .S00_AXI_bresp(h0_bresp), .S00_AXI_bvalid(h0_bvalid), .S00_AXI_bready(h0_bready),
        .S00_AXI_arid(h0_arid), .S00_AXI_araddr(h0_araddr), .S00_AXI_arlen(h0_arlen), .S00_AXI_arsize(h0_arsize),
        .S00_AXI_arburst(h0_arburst), .S00_AXI_arvalid(h0_arvalid), .S00_AXI_arready(h0_arready), .S00_AXI_rid(h0_rid),
        .S00_AXI_rdata(h0_rdata), .S00_AXI_rresp(h0_rresp), .S00_AXI_rlast(h0_rlast), .S00_AXI_rvalid(h0_rvalid),
        .S00_AXI_rready(h0_rready), .S01_AXI_awid(h1_awid), .S01_AXI_awaddr(h1_awaddr), .S01_AXI_awlen(h1_awlen),
        .S01_AXI_awsize(h1_awsize), .S01_AXI_awburst(h1_awburst), .S01_AXI_awvalid(h1_awvalid), .S01_AXI_awready(h1_awready),
        .S01_AXI_wdata(h1_wdata), .S01_AXI_wstrb(h1_wstrb), .S01_AXI_wlast(h1_wlast), .S01_AXI_wvalid(h1_wvalid),
        .S01_AXI_wready(h1_wready), .S01_AXI_bid(h1_bid), .S01_AXI_bresp(h1_bresp), .S01_AXI_bvalid(h1_bvalid),
        .S01_AXI_bready(h1_bready), .S01_AXI_arid(h1_arid), .S01_AXI_araddr(h1_araddr), .S01_AXI_arlen(h1_arlen),
        .S01_AXI_arsize(h1_arsize), .S01_AXI_arburst(h1_arburst), .S01_AXI_arvalid(h1_arvalid), .S01_AXI_arready(h1_arready),
        .S01_AXI_rid(h1_rid), .S01_AXI_rdata(h1_rdata), .S01_AXI_rresp(h1_rresp), .S01_AXI_rlast(h1_rlast),
        .S01_AXI_rvalid(h1_rvalid), .S01_AXI_rready(h1_rready), .S02_AXI_awaddr(h2_awaddr), .S02_AXI_awvalid(h2_awvalid),
        .S02_AXI_awready(h2_awready), .S02_AXI_wdata(h2_wdata), .S02_AXI_wstrb(h2_wstrb), .S02_AXI_wvalid(h2_wvalid),
        .S02_AXI_wready(h2_wready), .S02_AXI_bresp(h2_bresp), .S02_AXI_bvalid(h2_bvalid), .S02_AXI_bready(h2_bready),
        .S02_AXI_araddr(h2_araddr), .S02_AXI_arvalid(h2_arvalid), .S02_AXI_arready(h2_arready), .S02_AXI_rdata(h2_rdata),
        .S02_AXI_rresp(h2_rresp), .S02_AXI_rvalid(h2_rvalid), .S02_AXI_rready(h2_rready), .M00_AXI_awid(M00_awid),
        .M00_AXI_awaddr(M00_awaddr), .M00_AXI_awlen(M00_awlen), .M00_AXI_awsize(M00_awsize), .M00_AXI_awburst(M00_awburst),
        .M00_AXI_awvalid(M00_awvalid), .M00_AXI_awready(M00_awready), .M00_AXI_wdata(M00_wdata), .M00_AXI_wstrb(M00_wstrb),
        .M00_AXI_wlast(M00_wlast), .M00_AXI_wvalid(M00_wvalid), .M00_AXI_wready(M00_wready), .M00_AXI_bid(M00_bid),
        .M00_AXI_bresp(M00_bresp), .M00_AXI_bvalid(M00_bvalid), .M00_AXI_bready(M00_bready), .M00_AXI_arid(M00_arid),
        .M00_AXI_araddr(M00_araddr), .M00_AXI_arlen(M00_arlen), .M00_AXI_arsize(M00_arsize), .M00_AXI_arburst(M00_arburst),
        .M00_AXI_arvalid(M00_arvalid), .M00_AXI_arready(M00_arready), .M00_AXI_rid(M00_rid), .M00_AXI_rdata(M00_rdata),
        .M00_AXI_rresp(M00_rresp), .M00_AXI_rlast(M00_rlast), .M00_AXI_rvalid(M00_rvalid), .M00_AXI_rready(M00_rready),
        .M01_AXI_awid(M01_awid), .M01_AXI_awaddr(M01_awaddr), .M01_AXI_awlen(M01_awlen), .M01_AXI_awsize(M01_awsize),
        .M01_AXI_awburst(M01_awburst), .M01_AXI_awvalid(M01_awvalid), .M01_AXI_awready(M01_awready), .M01_AXI_wdata(M01_wdata),
        .M01_AXI_wstrb(M01_wstrb), .M01_AXI_wlast(M01_wlast), .M01_AXI_wvalid(M01_wvalid), .M01_AXI_wready(M01_wready),
        .M01_AXI_bid(M01_bid), .M01_AXI_bresp(M01_bresp), .M01_AXI_bvalid(M01_bvalid), .M01_AXI_bready(M01_bready),
        .M01_AXI_arid(M01_arid), .M01_AXI_araddr(M01_araddr), .M01_AXI_arlen(M01_arlen), .M01_AXI_arsize(M01_arsize),
        .M01_AXI_arburst(M01_arburst), .M01_AXI_arvalid(M01_arvalid), .M01_AXI_arready(M01_arready), .M01_AXI_rid(M01_rid),
        .M01_AXI_rdata(M01_rdata), .M01_AXI_rresp(M01_rresp), .M01_AXI_rlast(M01_rlast), .M01_AXI_rvalid(M01_rvalid),
        .M01_AXI_rready(M01_rready), .M02_AXI_awaddr(M02_awaddr), .M02_AXI_awvalid(M02_awvalid), .M02_AXI_awready(M02_awready),
        .M02_AXI_wdata(M02_wdata), .M02_AXI_wstrb(M02_wstrb), .M02_AXI_wvalid(M02_wvalid), .M02_AXI_wready(M02_wready),
        .M02_AXI_bresp(M02_bresp), .M02_AXI_bvalid(M02_bvalid), .M02_AXI_bready(M02_bready), .M02_AXI_araddr(M02_araddr),
        .M02_AXI_arvalid(M02_arvalid), .M02_AXI_arready(M02_arready), .M02_AXI_rdata(M02_rdata), .M02_AXI_rresp(M02_rresp),
        .M02_AXI_rvalid(M02_rvalid), .M02_AXI_rready(M02_rready), .M03_AXI_awaddr(M03_awaddr), .M03_AXI_awvalid(M03_awvalid),
        .M03_AXI_awready(M03_awready), .M03_AXI_wdata(M03_wdata), .M03_AXI_wstrb(M03_wstrb), .M03_AXI_wvalid(M03_wvalid),
        .M03_AXI_wready(M03_wready), .M03_AXI_bresp(M03_bresp), .M03_AXI_bvalid(M03_bvalid), .M03_AXI_bready(M03_bready),
        .M03_AXI_araddr(M03_araddr), .M03_AXI_arvalid(M03_arvalid), .M03_AXI_arready(M03_arready), .M03_AXI_rdata(M03_rdata),
        .M03_AXI_rresp(M03_rresp), .M03_AXI_rvalid(M03_rvalid), .M03_AXI_rready(M03_rready), .M04_AXI_awid(M04_awid),
        .M04_AXI_awaddr(M04_awaddr), .M04_AXI_awlen(M04_awlen), .M04_AXI_awsize(M04_awsize), .M04_AXI_awburst(M04_awburst),
        .M04_AXI_awvalid(M04_awvalid), .M04_AXI_awready(M04_awready), .M04_AXI_wdata(M04_wdata), .M04_AXI_wstrb(M04_wstrb),
        .M04_AXI_wlast(M04_wlast), .M04_AXI_wvalid(M04_wvalid), .M04_AXI_wready(M04_wready), .M04_AXI_bid(M04_bid),
        .M04_AXI_bresp(M04_bresp), .M04_AXI_bvalid(M04_bvalid), .M04_AXI_bready(M04_bready), .M04_AXI_arid(M04_arid),
        .M04_AXI_araddr(M04_araddr), .M04_AXI_arlen(M04_arlen), .M04_AXI_arsize(M04_arsize), .M04_AXI_arburst(M04_arburst),
        .M04_AXI_arvalid(M04_arvalid), .M04_AXI_arready(M04_arready), .M04_AXI_rid(M04_rid), .M04_AXI_rdata(M04_rdata),
        .M04_AXI_rresp(M04_rresp), .M04_AXI_rlast(M04_rlast), .M04_AXI_rvalid(M04_rvalid), .M04_AXI_rready(M04_rready),
        .M05_AXI_awid(M05_awid), .M05_AXI_awaddr(M05_awaddr), .M05_AXI_awlen(M05_awlen), .M05_AXI_awsize(M05_awsize),
        .M05_AXI_awburst(M05_awburst), .M05_AXI_awvalid(M05_awvalid), .M05_AXI_awready(M05_awready), .M05_AXI_wdata(M05_wdata),
        .M05_AXI_wstrb(M05_wstrb), .M05_AXI_wlast(M05_wlast), .M05_AXI_wvalid(M05_wvalid), .M05_AXI_wready(M05_wready),
        .M05_AXI_bid(M05_bid), .M05_AXI_bresp(M05_bresp), .M05_AXI_bvalid(M05_bvalid), .M05_AXI_bready(M05_bready),
        .M05_AXI_arid(M05_arid), .M05_AXI_araddr(M05_araddr), .M05_AXI_arlen(M05_arlen), .M05_AXI_arsize(M05_arsize),
        .M05_AXI_arburst(M05_arburst), .M05_AXI_arvalid(M05_arvalid), .M05_AXI_arready(M05_arready), .M05_AXI_rid(M05_rid),
        .M05_AXI_rdata(M05_rdata), .M05_AXI_rresp(M05_rresp), .M05_AXI_rlast(M05_rlast), .M05_AXI_rvalid(M05_rvalid),
        .M05_AXI_rready(M05_rready), .M06_AXI_awaddr(M06_awaddr), .M06_AXI_awvalid(M06_awvalid), .M06_AXI_awready(M06_awready),
        .M06_AXI_wdata(M06_wdata), .M06_AXI_wstrb(M06_wstrb), .M06_AXI_wvalid(M06_wvalid), .M06_AXI_wready(M06_wready),
        .M06_AXI_bresp(M06_bresp), .M06_AXI_bvalid(M06_bvalid), .M06_AXI_bready(M06_bready), .M06_AXI_araddr(M06_araddr),
        .M06_AXI_arvalid(M06_arvalid), .M06_AXI_arready(M06_arready), .M06_AXI_rdata(M06_rdata), .M06_AXI_rresp(M06_rresp),
        .M06_AXI_rvalid(M06_rvalid), .M06_AXI_rready(M06_rready), .M07_AXI_awaddr(M07_awaddr), .M07_AXI_awvalid(M07_awvalid),
        .M07_AXI_awready(M07_awready), .M07_AXI_wdata(M07_wdata), .M07_AXI_wstrb(M07_wstrb), .M07_AXI_wvalid(M07_wvalid),
        .M07_AXI_wready(M07_wready), .M07_AXI_bresp(M07_bresp), .M07_AXI_bvalid(M07_bvalid), .M07_AXI_bready(M07_bready),
        .M07_AXI_araddr(M07_araddr), .M07_AXI_arvalid(M07_arvalid), .M07_AXI_arready(M07_arready), .M07_AXI_rdata(M07_rdata),
        .M07_AXI_rresp(M07_rresp), .M07_AXI_rvalid(M07_rvalid), .M07_AXI_rready(M07_rready), .M08_AXI_awid(M08_awid),
        .M08_AXI_awaddr(M08_awaddr), .M08_AXI_awlen(M08_awlen), .M08_AXI_awsize(M08_awsize), .M08_AXI_awburst(M08_awburst),
        .M08_AXI_awvalid(M08_awvalid), .M08_AXI_awready(M08_awready), .M08_AXI_wdata(M08_wdata), .M08_AXI_wstrb(M08_wstrb),
        .M08_AXI_wlast(M08_wlast), .M08_AXI_wvalid(M08_wvalid), .M08_AXI_wready(M08_wready), .M08_AXI_bid(M08_bid),
        .M08_AXI_bresp(M08_bresp), .M08_AXI_bvalid(M08_bvalid), .M08_AXI_bready(M08_bready), .M08_AXI_arid(M08_arid),
        .M08_AXI_araddr(M08_araddr), .M08_AXI_arlen(M08_arlen), .M08_AXI_arsize(M08_arsize), .M08_AXI_arburst(M08_arburst),
        .M08_AXI_arvalid(M08_arvalid), .M08_AXI_arready(M08_arready), .M08_AXI_rid(M08_rid), .M08_AXI_rdata(M08_rdata),
        .M08_AXI_rresp(M08_rresp), .M08_AXI_rlast(M08_rlast), .M08_AXI_rvalid(M08_rvalid), .M08_AXI_rready(M08_rready),
        .M09_AXI_awid(M09_awid), .M09_AXI_awaddr(M09_awaddr), .M09_AXI_awlen(M09_awlen), .M09_AXI_awsize(M09_awsize),
        .M09_AXI_awburst(M09_awburst), .M09_AXI_awvalid(M09_awvalid), .M09_AXI_awready(M09_awready), .M09_AXI_wdata(M09_wdata),
        .M09_AXI_wstrb(M09_wstrb), .M09_AXI_wlast(M09_wlast), .M09_AXI_wvalid(M09_wvalid), .M09_AXI_wready(M09_wready),
        .M09_AXI_bid(M09_bid), .M09_AXI_bresp(M09_bresp), .M09_AXI_bvalid(M09_bvalid), .M09_AXI_bready(M09_bready),
        .M09_AXI_arid(M09_arid), .M09_AXI_araddr(M09_araddr), .M09_AXI_arlen(M09_arlen), .M09_AXI_arsize(M09_arsize),
        .M09_AXI_arburst(M09_arburst), .M09_AXI_arvalid(M09_arvalid), .M09_AXI_arready(M09_arready), .M09_AXI_rid(M09_rid),
        .M09_AXI_rdata(M09_rdata), .M09_AXI_rresp(M09_rresp), .M09_AXI_rlast(M09_rlast), .M09_AXI_rvalid(M09_rvalid),
        .M09_AXI_rready(M09_rready), .M10_AXI_awaddr(M10_awaddr), .M10_AXI_awvalid(M10_awvalid), .M10_AXI_awready(M10_awready),
        .M10_AXI_wdata(M10_wdata), .M10_AXI_wstrb(M10_wstrb), .M10_AXI_wvalid(M10_wvalid), .M10_AXI_wready(M10_wready),
        .M10_AXI_bresp(M10_bresp), .M10_AXI_bvalid(M10_bvalid), .M10_AXI_bready(M10_bready), .M10_AXI_araddr(M10_araddr),
        .M10_AXI_arvalid(M10_arvalid), .M10_AXI_arready(M10_arready), .M10_AXI_rdata(M10_rdata), .M10_AXI_rresp(M10_rresp),
        .M10_AXI_rvalid(M10_rvalid), .M10_AXI_rready(M10_rready), .M11_AXI_awaddr(M11_awaddr), .M11_AXI_awvalid(M11_awvalid),
        .M11_AXI_awready(M11_awready), .M11_AXI_wdata(M11_wdata), .M11_AXI_wstrb(M11_wstrb), .M11_AXI_wvalid(M11_wvalid),
        .M11_AXI_wready(M11_wready), .M11_AXI_bresp(M11_bresp), .M11_AXI_bvalid(M11_bvalid), .M11_AXI_bready(M11_bready),
        .M11_AXI_araddr(M11_araddr), .M11_AXI_arvalid(M11_arvalid), .M11_AXI_arready(M11_arready), .M11_AXI_rdata(M11_rdata),
        .M11_AXI_rresp(M11_rresp), .M11_AXI_rvalid(M11_rvalid), .M11_AXI_rready(M11_rready), .M12_AXI_awid(M12_awid),
        .M12_AXI_awaddr(M12_awaddr), .M12_AXI_awlen(M12_awlen), .M12_AXI_awsize(M12_awsize), .M12_AXI_awburst(M12_awburst),
        .M12_AXI_awvalid(M12_awvalid), .M12_AXI_awready(M12_awready), .M12_AXI_wdata(M12_wdata), .M12_AXI_wstrb(M12_wstrb),
        .M12_AXI_wlast(M12_wlast), .M12_AXI_wvalid(M12_wvalid), .M12_AXI_wready(M12_wready), .M12_AXI_bid(M12_bid),
        .M12_AXI_bresp(M12_bresp), .M12_AXI_bvalid(M12_bvalid), .M12_AXI_bready(M12_bready), .M12_AXI_arid(M12_arid),
        .M12_AXI_araddr(M12_araddr), .M12_AXI_arlen(M12_arlen), .M12_AXI_arsize(M12_arsize), .M12_AXI_arburst(M12_arburst),
        .M12_AXI_arvalid(M12_arvalid), .M12_AXI_arready(M12_arready), .M12_AXI_rid(M12_rid), .M12_AXI_rdata(M12_rdata),
        .M12_AXI_rresp(M12_rresp), .M12_AXI_rlast(M12_rlast), .M12_AXI_rvalid(M12_rvalid), .M12_AXI_rready(M12_rready),
        .M13_AXI_awid(M13_awid), .M13_AXI_awaddr(M13_awaddr), .M13_AXI_awlen(M13_awlen), .M13_AXI_awsize(M13_awsize),
        .M13_AXI_awburst(M13_awburst), .M13_AXI_awvalid(M13_awvalid), .M13_AXI_awready(M13_awready), .M13_AXI_wdata(M13_wdata),
        .M13_AXI_wstrb(M13_wstrb), .M13_AXI_wlast(M13_wlast), .M13_AXI_wvalid(M13_wvalid), .M13_AXI_wready(M13_wready),
        .M13_AXI_bid(M13_bid), .M13_AXI_bresp(M13_bresp), .M13_AXI_bvalid(M13_bvalid), .M13_AXI_bready(M13_bready),
        .M13_AXI_arid(M13_arid), .M13_AXI_araddr(M13_araddr), .M13_AXI_arlen(M13_arlen), .M13_AXI_arsize(M13_arsize),
        .M13_AXI_arburst(M13_arburst), .M13_AXI_arvalid(M13_arvalid), .M13_AXI_arready(M13_arready), .M13_AXI_rid(M13_rid),
        .M13_AXI_rdata(M13_rdata), .M13_AXI_rresp(M13_rresp), .M13_AXI_rlast(M13_rlast), .M13_AXI_rvalid(M13_rvalid),
        .M13_AXI_rready(M13_rready), .M14_AXI_awaddr(M14_awaddr), .M14_AXI_awvalid(M14_awvalid), .M14_AXI_awready(M14_awready),
        .M14_AXI_wdata(M14_wdata), .M14_AXI_wstrb(M14_wstrb), .M14_AXI_wvalid(M14_wvalid), .M14_AXI_wready(M14_wready),
        .M14_AXI_bresp(M14_bresp), .M14_AXI_bvalid(M14_bvalid), .M14_AXI_bready(M14_bready), .M14_AXI_araddr(M14_araddr),
        .M14_AXI_arvalid(M14_arvalid), .M14_AXI_arready(M14_arready), .M14_AXI_rdata(M14_rdata), .M14_AXI_rresp(M14_rresp),
        .M14_AXI_rvalid(M14_rvalid), .M14_AXI_rready(M14_rready), .M15_AXI_awaddr(M15_awaddr), .M15_AXI_awvalid(M15_awvalid),
        .M15_AXI_awready(M15_awready), .M15_AXI_wdata(M15_wdata), .M15_AXI_wstrb(M15_wstrb), .M15_AXI_wvalid(M15_wvalid),
        .M15_AXI_wready(M15_wready), .M15_AXI_bresp(M15_bresp), .M15_AXI_bvalid(M15_bvalid), .M15_AXI_bready(M15_bready),
        .M15_AXI_araddr(M15_araddr), .M15_AXI_arvalid(M15_arvalid), .M15_AXI_arready(M15_arready), .M15_AXI_rdata(M15_rdata),
        .M15_AXI_rresp(M15_rresp), .M15_AXI_rvalid(M15_rvalid), .M15_AXI_rready(M15_rready), .stat_decerr(stat_decerr)
    );

    // ==== die 0 ====

    wire [3:0] c0_awid;
    wire [31:0] c0_awaddr;
    wire [7:0] c0_awlen;
    wire [2:0] c0_awsize;
    wire [1:0] c0_awburst;
    wire c0_awvalid;
    wire c0_awready;
    wire [63:0] c0_wdata;
    wire [7:0] c0_wstrb;
    wire c0_wlast;
    wire c0_wvalid;
    wire c0_wready;
    wire [3:0] c0_bid;
    wire [1:0] c0_bresp;
    wire c0_bvalid;
    wire c0_bready;
    wire [3:0] c0_arid;
    wire [31:0] c0_araddr;
    wire [7:0] c0_arlen;
    wire [2:0] c0_arsize;
    wire [1:0] c0_arburst;
    wire c0_arvalid;
    wire c0_arready;
    wire [3:0] c0_rid;
    wire [63:0] c0_rdata;
    wire [1:0] c0_rresp;
    wire c0_rlast;
    wire c0_rvalid;
    wire c0_rready;
    wire [3:0] x0_awid;
    wire [39:0] x0_awaddr;
    wire [7:0] x0_awlen;
    wire [2:0] x0_awsize;
    wire [1:0] x0_awburst;
    wire x0_awvalid;
    wire x0_awready;
    wire [511:0] x0_wdata;
    wire [63:0] x0_wstrb;
    wire x0_wlast;
    wire x0_wvalid;
    wire x0_wready;
    wire [3:0] x0_bid;
    wire [1:0] x0_bresp;
    wire x0_bvalid;
    wire x0_bready;
    wire [3:0] x0_arid;
    wire [39:0] x0_araddr;
    wire [7:0] x0_arlen;
    wire [2:0] x0_arsize;
    wire [1:0] x0_arburst;
    wire x0_arvalid;
    wire x0_arready;
    wire [3:0] x0_rid;
    wire [511:0] x0_rdata;
    wire [1:0] x0_rresp;
    wire x0_rlast;
    wire x0_rvalid;
    wire x0_rready;
    // the BD's axi_dwidth_converter SI 32 -> MI 64, on the sysnode clock
    axi_up32to64 #(.AW(32), .IDW(4)) u_dwc0 (.clk(sys_clk[0]), .resetn(rstn_sys[0]),
        .s_awid(M01_awid), .s_awaddr(M01_awaddr[31:0]), .s_awlen(M01_awlen), .s_awsize(M01_awsize),
        .s_awburst(M01_awburst), .s_awvalid(M01_awvalid), .s_awready(M01_awready), .s_wdata(M01_wdata),
        .s_wstrb(M01_wstrb), .s_wlast(M01_wlast), .s_wvalid(M01_wvalid), .s_wready(M01_wready),
        .s_bid(M01_bid), .s_bresp(M01_bresp), .s_bvalid(M01_bvalid), .s_bready(M01_bready),
        .s_arid(M01_arid), .s_araddr(M01_araddr[31:0]), .s_arlen(M01_arlen), .s_arsize(M01_arsize),
        .s_arburst(M01_arburst), .s_arvalid(M01_arvalid), .s_arready(M01_arready), .s_rid(M01_rid),
        .s_rdata(M01_rdata), .s_rresp(M01_rresp), .s_rlast(M01_rlast), .s_rvalid(M01_rvalid),
        .s_rready(M01_rready), .m_awid(c0_awid), .m_awaddr(c0_awaddr), .m_awlen(c0_awlen),
        .m_awsize(c0_awsize), .m_awburst(c0_awburst), .m_awvalid(c0_awvalid), .m_awready(c0_awready),
        .m_wdata(c0_wdata), .m_wstrb(c0_wstrb), .m_wlast(c0_wlast), .m_wvalid(c0_wvalid),
        .m_wready(c0_wready), .m_bid(c0_bid), .m_bresp(c0_bresp), .m_bvalid(c0_bvalid),
        .m_bready(c0_bready), .m_arid(c0_arid), .m_araddr(c0_araddr), .m_arlen(c0_arlen),
        .m_arsize(c0_arsize), .m_arburst(c0_arburst), .m_arvalid(c0_arvalid), .m_arready(c0_arready),
        .m_rid(c0_rid), .m_rdata(c0_rdata), .m_rresp(c0_rresp), .m_rlast(c0_rlast),
        .m_rvalid(c0_rvalid), .m_rready(c0_rready)
    );
    // matmul 1x from the 2x, cleared by NOT(lock)
    wire l0_LINK0_OUT_valid, l0_LINK0_OUT_vc, l0_LINK0_OUT_last;
    wire [287:0] l0_LINK0_OUT_flit;
    wire l0_LINK0_OUT_crd_valid, l0_LINK0_OUT_crd_vc;
    wire [3:0] l0_LINK0_OUT_crd_n;
    wire l0_LINK0_IN_valid, l0_LINK0_IN_vc, l0_LINK0_IN_last;
    wire [287:0] l0_LINK0_IN_flit;
    wire l0_LINK0_IN_crd_valid, l0_LINK0_IN_crd_vc;
    wire [3:0] l0_LINK0_IN_crd_n;
    wire l0_LINK1_OUT_valid, l0_LINK1_OUT_vc, l0_LINK1_OUT_last;
    wire [287:0] l0_LINK1_OUT_flit;
    wire l0_LINK1_OUT_crd_valid, l0_LINK1_OUT_crd_vc;
    wire [3:0] l0_LINK1_OUT_crd_n;
    wire l0_LINK1_IN_valid, l0_LINK1_IN_vc, l0_LINK1_IN_last;
    wire [287:0] l0_LINK1_IN_flit;
    wire l0_LINK1_IN_crd_valid, l0_LINK1_IN_crd_vc;
    wire [3:0] l0_LINK1_IN_crd_n;
    wire mat_clk0;
    ktpu_div2 u_div2_0 (.clk2x(mat2x_clk[0]), .clr(!wiz_locked[0]), .clk1x(mat_clk0));
    wire [63:0] hs_rdata0;
    wire hs_cwe0;
    wire [7:0] hs_c0;
    ktpu_ship_2x1_4c2v_1m_nol2_pump #(
        .MESH_ID(0), .L2_MAG_BANKS(4), .L2_MAG_ENTRIES(16384), .DRAM_CDC(0),
        .DRAM_AR_MAX(16), .GA(512), .GB(512), .TILES(4096),
        .TILE_PRIM("ultra"), .VEC_PRIM("block"), .MAG_CDC(1), .UNIT_CDC(1),
        .MODEL(`MX_MODEL)
    ) u_mesh0 (
        .axi_aclk(sys_clk[0]), .axi_aresetn(rstn_sys[0]), .dram_aclk(sys_clk[0]), .dram_aresetn(rstn_sys[0]),
        .noc_clk(noc_clk[0]), .vec_clk(vec_clk[0]), .mat_clk(mat_clk0), .mat_clk2x(mat2x_clk[0]),
        .hs_addr(32'd0), .hs_wr(1'b0), .hs_wdata(64'd0), .hs_wstrb(8'd0),
        .hs_rd(1'b0), .hs_rdata(hs_rdata0), .hs_console_we(hs_cwe0), .hs_console(hs_c0),
        .S_AXI_MEM_awid(M00_awid), .S_AXI_MEM_awaddr(M00_awaddr[39:0]), .S_AXI_MEM_awlen(M00_awlen), .S_AXI_MEM_awvalid(M00_awvalid),
        .S_AXI_MEM_awready(M00_awready), .S_AXI_MEM_wdata(M00_wdata), .S_AXI_MEM_wstrb(M00_wstrb), .S_AXI_MEM_wlast(M00_wlast),
        .S_AXI_MEM_wvalid(M00_wvalid), .S_AXI_MEM_wready(M00_wready), .S_AXI_MEM_bid(M00_bid), .S_AXI_MEM_bresp(M00_bresp),
        .S_AXI_MEM_bvalid(M00_bvalid), .S_AXI_MEM_bready(M00_bready), .S_AXI_MEM_arid(M00_arid), .S_AXI_MEM_araddr(M00_araddr[39:0]),
        .S_AXI_MEM_arlen(M00_arlen), .S_AXI_MEM_arvalid(M00_arvalid), .S_AXI_MEM_arready(M00_arready), .S_AXI_MEM_rid(M00_rid),
        .S_AXI_MEM_rdata(M00_rdata), .S_AXI_MEM_rresp(M00_rresp), .S_AXI_MEM_rlast(M00_rlast), .S_AXI_MEM_rvalid(M00_rvalid),
        .S_AXI_MEM_rready(M00_rready), .S_AXI_CTRL_awid(c0_awid), .S_AXI_CTRL_awaddr(c0_awaddr), .S_AXI_CTRL_awlen(c0_awlen),
        .S_AXI_CTRL_awvalid(c0_awvalid), .S_AXI_CTRL_awready(c0_awready), .S_AXI_CTRL_wdata(c0_wdata), .S_AXI_CTRL_wstrb(c0_wstrb),
        .S_AXI_CTRL_wlast(c0_wlast), .S_AXI_CTRL_wvalid(c0_wvalid), .S_AXI_CTRL_wready(c0_wready), .S_AXI_CTRL_bid(c0_bid),
        .S_AXI_CTRL_bresp(c0_bresp), .S_AXI_CTRL_bvalid(c0_bvalid), .S_AXI_CTRL_bready(c0_bready), .S_AXI_CTRL_arid(c0_arid),
        .S_AXI_CTRL_araddr(c0_araddr), .S_AXI_CTRL_arlen(c0_arlen), .S_AXI_CTRL_arvalid(c0_arvalid), .S_AXI_CTRL_arready(c0_arready),
        .S_AXI_CTRL_rid(c0_rid), .S_AXI_CTRL_rdata(c0_rdata), .S_AXI_CTRL_rresp(c0_rresp), .S_AXI_CTRL_rlast(c0_rlast),
        .S_AXI_CTRL_rvalid(c0_rvalid), .S_AXI_CTRL_rready(c0_rready), .M_AXI_DRAM_awid(x0_awid), .M_AXI_DRAM_awaddr(x0_awaddr),
        .M_AXI_DRAM_awlen(x0_awlen), .M_AXI_DRAM_awsize(x0_awsize), .M_AXI_DRAM_awburst(x0_awburst), .M_AXI_DRAM_awvalid(x0_awvalid),
        .M_AXI_DRAM_awready(x0_awready), .M_AXI_DRAM_wdata(x0_wdata), .M_AXI_DRAM_wstrb(x0_wstrb), .M_AXI_DRAM_wlast(x0_wlast),
        .M_AXI_DRAM_wvalid(x0_wvalid), .M_AXI_DRAM_wready(x0_wready), .M_AXI_DRAM_bid(x0_bid), .M_AXI_DRAM_bresp(x0_bresp),
        .M_AXI_DRAM_bvalid(x0_bvalid), .M_AXI_DRAM_bready(x0_bready), .M_AXI_DRAM_arid(x0_arid), .M_AXI_DRAM_araddr(x0_araddr),
        .M_AXI_DRAM_arlen(x0_arlen), .M_AXI_DRAM_arsize(x0_arsize), .M_AXI_DRAM_arburst(x0_arburst), .M_AXI_DRAM_arvalid(x0_arvalid),
        .M_AXI_DRAM_arready(x0_arready), .M_AXI_DRAM_rid(x0_rid), .M_AXI_DRAM_rdata(x0_rdata), .M_AXI_DRAM_rresp(x0_rresp),
        .M_AXI_DRAM_rlast(x0_rlast), .M_AXI_DRAM_rvalid(x0_rvalid), .M_AXI_DRAM_rready(x0_rready), .LINK0_OUT_valid(l0_LINK0_OUT_valid),
        .LINK0_IN_valid(l0_LINK0_IN_valid), .LINK0_OUT_vc(l0_LINK0_OUT_vc), .LINK0_IN_vc(l0_LINK0_IN_vc), .LINK0_OUT_last(l0_LINK0_OUT_last),
        .LINK0_IN_last(l0_LINK0_IN_last), .LINK0_OUT_flit(l0_LINK0_OUT_flit), .LINK0_IN_flit(l0_LINK0_IN_flit), .LINK0_OUT_crd_valid(l0_LINK0_OUT_crd_valid),
        .LINK0_IN_crd_valid(l0_LINK0_IN_crd_valid), .LINK0_OUT_crd_vc(l0_LINK0_OUT_crd_vc), .LINK0_IN_crd_vc(l0_LINK0_IN_crd_vc), .LINK0_OUT_crd_n(l0_LINK0_OUT_crd_n),
        .LINK0_IN_crd_n(l0_LINK0_IN_crd_n), .LINK1_OUT_valid(l0_LINK1_OUT_valid), .LINK1_IN_valid(l0_LINK1_IN_valid), .LINK1_OUT_vc(l0_LINK1_OUT_vc),
        .LINK1_IN_vc(l0_LINK1_IN_vc), .LINK1_OUT_last(l0_LINK1_OUT_last), .LINK1_IN_last(l0_LINK1_IN_last), .LINK1_OUT_flit(l0_LINK1_OUT_flit),
        .LINK1_IN_flit(l0_LINK1_IN_flit), .LINK1_OUT_crd_valid(l0_LINK1_OUT_crd_valid), .LINK1_IN_crd_valid(l0_LINK1_IN_crd_valid), .LINK1_OUT_crd_vc(l0_LINK1_OUT_crd_vc),
        .LINK1_IN_crd_vc(l0_LINK1_IN_crd_vc), .LINK1_OUT_crd_n(l0_LINK1_OUT_crd_n), .LINK1_IN_crd_n(l0_LINK1_IN_crd_n)
    );

    axil_ram #(.AW(43), .WORDS(256)) u_ddrctl0 (.clk(ddr_clk[0]), .resetn(rstn_ddr[0]),
        .s_awaddr(M02_awaddr), .s_awvalid(M02_awvalid), .s_awready(M02_awready), .s_wdata(M02_wdata),
        .s_wstrb(M02_wstrb), .s_wvalid(M02_wvalid), .s_wready(M02_wready), .s_bresp(M02_bresp),
        .s_bvalid(M02_bvalid), .s_bready(M02_bready), .s_araddr(M02_araddr), .s_arvalid(M02_arvalid),
        .s_arready(M02_arready), .s_rdata(M02_rdata), .s_rresp(M02_rresp), .s_rvalid(M02_rvalid),
        .s_rready(M02_rready)
    );
    clk_wiz_model #(.AW(43), .D(4), .M(48), .DIV0({8'd4, 8'd4, 8'd2, 8'd4}),
                    .LOCK_CYC(LOCK_CYC)) u_wiz0 (.clk(clk_ctrl), .resetn(rstn_ctrl),
        .s_awaddr(M03_awaddr), .s_awvalid(M03_awvalid), .s_awready(M03_awready), .s_wdata(M03_wdata),
        .s_wstrb(M03_wstrb), .s_wvalid(M03_wvalid), .s_wready(M03_wready), .s_bresp(M03_bresp),
        .s_bvalid(M03_bvalid), .s_bready(M03_bready), .s_araddr(M03_araddr), .s_arvalid(M03_arvalid),
        .s_arready(M03_arready), .s_rdata(M03_rdata), .s_rresp(M03_rresp), .s_rvalid(M03_rvalid),
        .s_rready(M03_rready), .locked(wiz_locked[0]), .divclk(wiz_divclk[0*8 +: 8]), .mult(wiz_mult[0*8 +: 8]),
        .div(wiz_div[0*32 +: 32])
    );

    // ==== die 1 ====

    wire [3:0] c1_awid;
    wire [31:0] c1_awaddr;
    wire [7:0] c1_awlen;
    wire [2:0] c1_awsize;
    wire [1:0] c1_awburst;
    wire c1_awvalid;
    wire c1_awready;
    wire [63:0] c1_wdata;
    wire [7:0] c1_wstrb;
    wire c1_wlast;
    wire c1_wvalid;
    wire c1_wready;
    wire [3:0] c1_bid;
    wire [1:0] c1_bresp;
    wire c1_bvalid;
    wire c1_bready;
    wire [3:0] c1_arid;
    wire [31:0] c1_araddr;
    wire [7:0] c1_arlen;
    wire [2:0] c1_arsize;
    wire [1:0] c1_arburst;
    wire c1_arvalid;
    wire c1_arready;
    wire [3:0] c1_rid;
    wire [63:0] c1_rdata;
    wire [1:0] c1_rresp;
    wire c1_rlast;
    wire c1_rvalid;
    wire c1_rready;
    wire [3:0] x1_awid;
    wire [39:0] x1_awaddr;
    wire [7:0] x1_awlen;
    wire [2:0] x1_awsize;
    wire [1:0] x1_awburst;
    wire x1_awvalid;
    wire x1_awready;
    wire [511:0] x1_wdata;
    wire [63:0] x1_wstrb;
    wire x1_wlast;
    wire x1_wvalid;
    wire x1_wready;
    wire [3:0] x1_bid;
    wire [1:0] x1_bresp;
    wire x1_bvalid;
    wire x1_bready;
    wire [3:0] x1_arid;
    wire [39:0] x1_araddr;
    wire [7:0] x1_arlen;
    wire [2:0] x1_arsize;
    wire [1:0] x1_arburst;
    wire x1_arvalid;
    wire x1_arready;
    wire [3:0] x1_rid;
    wire [511:0] x1_rdata;
    wire [1:0] x1_rresp;
    wire x1_rlast;
    wire x1_rvalid;
    wire x1_rready;
    // the BD's axi_dwidth_converter SI 32 -> MI 64, on the sysnode clock
    axi_up32to64 #(.AW(32), .IDW(4)) u_dwc1 (.clk(sys_clk[1]), .resetn(rstn_sys[1]),
        .s_awid(M05_awid), .s_awaddr(M05_awaddr[31:0]), .s_awlen(M05_awlen), .s_awsize(M05_awsize),
        .s_awburst(M05_awburst), .s_awvalid(M05_awvalid), .s_awready(M05_awready), .s_wdata(M05_wdata),
        .s_wstrb(M05_wstrb), .s_wlast(M05_wlast), .s_wvalid(M05_wvalid), .s_wready(M05_wready),
        .s_bid(M05_bid), .s_bresp(M05_bresp), .s_bvalid(M05_bvalid), .s_bready(M05_bready),
        .s_arid(M05_arid), .s_araddr(M05_araddr[31:0]), .s_arlen(M05_arlen), .s_arsize(M05_arsize),
        .s_arburst(M05_arburst), .s_arvalid(M05_arvalid), .s_arready(M05_arready), .s_rid(M05_rid),
        .s_rdata(M05_rdata), .s_rresp(M05_rresp), .s_rlast(M05_rlast), .s_rvalid(M05_rvalid),
        .s_rready(M05_rready), .m_awid(c1_awid), .m_awaddr(c1_awaddr), .m_awlen(c1_awlen),
        .m_awsize(c1_awsize), .m_awburst(c1_awburst), .m_awvalid(c1_awvalid), .m_awready(c1_awready),
        .m_wdata(c1_wdata), .m_wstrb(c1_wstrb), .m_wlast(c1_wlast), .m_wvalid(c1_wvalid),
        .m_wready(c1_wready), .m_bid(c1_bid), .m_bresp(c1_bresp), .m_bvalid(c1_bvalid),
        .m_bready(c1_bready), .m_arid(c1_arid), .m_araddr(c1_araddr), .m_arlen(c1_arlen),
        .m_arsize(c1_arsize), .m_arburst(c1_arburst), .m_arvalid(c1_arvalid), .m_arready(c1_arready),
        .m_rid(c1_rid), .m_rdata(c1_rdata), .m_rresp(c1_rresp), .m_rlast(c1_rlast),
        .m_rvalid(c1_rvalid), .m_rready(c1_rready)
    );
    // no node: RAMs behind both windows, the Xache master idle
    axi_ram #(.DATA_W(256), .ADDR_W(16), .ID_W(4), .WORDS(512), .PORTS(1)) u_nomem1 (
        .clk(sys_clk[1]), .resetn(rstn_sys[1]),
        .s_awid(M04_awid), .s_awaddr(M04_awaddr[15:0]), .s_awlen(M04_awlen), .s_awsize(M04_awsize),
        .s_awburst(M04_awburst), .s_awvalid(M04_awvalid), .s_awready(M04_awready), .s_wdata(M04_wdata),
        .s_wstrb(M04_wstrb), .s_wlast(M04_wlast), .s_wvalid(M04_wvalid), .s_wready(M04_wready),
        .s_bid(M04_bid), .s_bresp(M04_bresp), .s_bvalid(M04_bvalid), .s_bready(M04_bready),
        .s_arid(M04_arid), .s_araddr(M04_araddr[15:0]), .s_arlen(M04_arlen), .s_arsize(M04_arsize),
        .s_arburst(M04_arburst), .s_arvalid(M04_arvalid), .s_arready(M04_arready), .s_rid(M04_rid),
        .s_rdata(M04_rdata), .s_rresp(M04_rresp), .s_rlast(M04_rlast), .s_rvalid(M04_rvalid),
        .s_rready(M04_rready), .bd_we(1'b0), .bd_addr(16'd0), .bd_wdata(256'd0),
        .bd_rdata()
    );
    axi_ram #(.DATA_W(64), .ADDR_W(16), .ID_W(4), .WORDS(512), .PORTS(1)) u_noctl1 (
        .clk(sys_clk[1]), .resetn(rstn_sys[1]),
        .s_awid(c1_awid), .s_awaddr(c1_awaddr[15:0]), .s_awlen(c1_awlen), .s_awsize(c1_awsize),
        .s_awburst(c1_awburst), .s_awvalid(c1_awvalid), .s_awready(c1_awready), .s_wdata(c1_wdata),
        .s_wstrb(c1_wstrb), .s_wlast(c1_wlast), .s_wvalid(c1_wvalid), .s_wready(c1_wready),
        .s_bid(c1_bid), .s_bresp(c1_bresp), .s_bvalid(c1_bvalid), .s_bready(c1_bready),
        .s_arid(c1_arid), .s_araddr(c1_araddr[15:0]), .s_arlen(c1_arlen), .s_arsize(c1_arsize),
        .s_arburst(c1_arburst), .s_arvalid(c1_arvalid), .s_arready(c1_arready), .s_rid(c1_rid),
        .s_rdata(c1_rdata), .s_rresp(c1_rresp), .s_rlast(c1_rlast), .s_rvalid(c1_rvalid),
        .s_rready(c1_rready), .bd_we(1'b0), .bd_addr(16'd0), .bd_wdata(64'd0),
        .bd_rdata()
    );
    assign x1_awid = 0;
    assign x1_awaddr = 0;
    assign x1_awlen = 0;
    assign x1_awsize = 0;
    assign x1_awburst = 0;
    assign x1_awvalid = 0;
    assign x1_wdata = 0;
    assign x1_wstrb = 0;
    assign x1_wlast = 0;
    assign x1_wvalid = 0;
    assign x1_bready = 0;
    assign x1_arid = 0;
    assign x1_araddr = 0;
    assign x1_arlen = 0;
    assign x1_arsize = 0;
    assign x1_arburst = 0;
    assign x1_arvalid = 0;
    assign x1_rready = 0;

    axil_ram #(.AW(43), .WORDS(256)) u_ddrctl1 (.clk(ddr_clk[1]), .resetn(rstn_ddr[1]),
        .s_awaddr(M06_awaddr), .s_awvalid(M06_awvalid), .s_awready(M06_awready), .s_wdata(M06_wdata),
        .s_wstrb(M06_wstrb), .s_wvalid(M06_wvalid), .s_wready(M06_wready), .s_bresp(M06_bresp),
        .s_bvalid(M06_bvalid), .s_bready(M06_bready), .s_araddr(M06_araddr), .s_arvalid(M06_arvalid),
        .s_arready(M06_arready), .s_rdata(M06_rdata), .s_rresp(M06_rresp), .s_rvalid(M06_rvalid),
        .s_rready(M06_rready)
    );
    clk_wiz_model #(.AW(43), .D(4), .M(48), .DIV0({8'd4, 8'd4, 8'd2, 8'd4}),
                    .LOCK_CYC(LOCK_CYC)) u_wiz1 (.clk(clk_ctrl), .resetn(rstn_ctrl),
        .s_awaddr(M07_awaddr), .s_awvalid(M07_awvalid), .s_awready(M07_awready), .s_wdata(M07_wdata),
        .s_wstrb(M07_wstrb), .s_wvalid(M07_wvalid), .s_wready(M07_wready), .s_bresp(M07_bresp),
        .s_bvalid(M07_bvalid), .s_bready(M07_bready), .s_araddr(M07_araddr), .s_arvalid(M07_arvalid),
        .s_arready(M07_arready), .s_rdata(M07_rdata), .s_rresp(M07_rresp), .s_rvalid(M07_rvalid),
        .s_rready(M07_rready), .locked(wiz_locked[1]), .divclk(wiz_divclk[1*8 +: 8]), .mult(wiz_mult[1*8 +: 8]),
        .div(wiz_div[1*32 +: 32])
    );

    // ==== die 2 ====

    wire [3:0] c2_awid;
    wire [31:0] c2_awaddr;
    wire [7:0] c2_awlen;
    wire [2:0] c2_awsize;
    wire [1:0] c2_awburst;
    wire c2_awvalid;
    wire c2_awready;
    wire [63:0] c2_wdata;
    wire [7:0] c2_wstrb;
    wire c2_wlast;
    wire c2_wvalid;
    wire c2_wready;
    wire [3:0] c2_bid;
    wire [1:0] c2_bresp;
    wire c2_bvalid;
    wire c2_bready;
    wire [3:0] c2_arid;
    wire [31:0] c2_araddr;
    wire [7:0] c2_arlen;
    wire [2:0] c2_arsize;
    wire [1:0] c2_arburst;
    wire c2_arvalid;
    wire c2_arready;
    wire [3:0] c2_rid;
    wire [63:0] c2_rdata;
    wire [1:0] c2_rresp;
    wire c2_rlast;
    wire c2_rvalid;
    wire c2_rready;
    wire [3:0] x2_awid;
    wire [39:0] x2_awaddr;
    wire [7:0] x2_awlen;
    wire [2:0] x2_awsize;
    wire [1:0] x2_awburst;
    wire x2_awvalid;
    wire x2_awready;
    wire [511:0] x2_wdata;
    wire [63:0] x2_wstrb;
    wire x2_wlast;
    wire x2_wvalid;
    wire x2_wready;
    wire [3:0] x2_bid;
    wire [1:0] x2_bresp;
    wire x2_bvalid;
    wire x2_bready;
    wire [3:0] x2_arid;
    wire [39:0] x2_araddr;
    wire [7:0] x2_arlen;
    wire [2:0] x2_arsize;
    wire [1:0] x2_arburst;
    wire x2_arvalid;
    wire x2_arready;
    wire [3:0] x2_rid;
    wire [511:0] x2_rdata;
    wire [1:0] x2_rresp;
    wire x2_rlast;
    wire x2_rvalid;
    wire x2_rready;
    // the BD's axi_dwidth_converter SI 32 -> MI 64, on the sysnode clock
    axi_up32to64 #(.AW(32), .IDW(4)) u_dwc2 (.clk(sys_clk[2]), .resetn(rstn_sys[2]),
        .s_awid(M09_awid), .s_awaddr(M09_awaddr[31:0]), .s_awlen(M09_awlen), .s_awsize(M09_awsize),
        .s_awburst(M09_awburst), .s_awvalid(M09_awvalid), .s_awready(M09_awready), .s_wdata(M09_wdata),
        .s_wstrb(M09_wstrb), .s_wlast(M09_wlast), .s_wvalid(M09_wvalid), .s_wready(M09_wready),
        .s_bid(M09_bid), .s_bresp(M09_bresp), .s_bvalid(M09_bvalid), .s_bready(M09_bready),
        .s_arid(M09_arid), .s_araddr(M09_araddr[31:0]), .s_arlen(M09_arlen), .s_arsize(M09_arsize),
        .s_arburst(M09_arburst), .s_arvalid(M09_arvalid), .s_arready(M09_arready), .s_rid(M09_rid),
        .s_rdata(M09_rdata), .s_rresp(M09_rresp), .s_rlast(M09_rlast), .s_rvalid(M09_rvalid),
        .s_rready(M09_rready), .m_awid(c2_awid), .m_awaddr(c2_awaddr), .m_awlen(c2_awlen),
        .m_awsize(c2_awsize), .m_awburst(c2_awburst), .m_awvalid(c2_awvalid), .m_awready(c2_awready),
        .m_wdata(c2_wdata), .m_wstrb(c2_wstrb), .m_wlast(c2_wlast), .m_wvalid(c2_wvalid),
        .m_wready(c2_wready), .m_bid(c2_bid), .m_bresp(c2_bresp), .m_bvalid(c2_bvalid),
        .m_bready(c2_bready), .m_arid(c2_arid), .m_araddr(c2_araddr), .m_arlen(c2_arlen),
        .m_arsize(c2_arsize), .m_arburst(c2_arburst), .m_arvalid(c2_arvalid), .m_arready(c2_arready),
        .m_rid(c2_rid), .m_rdata(c2_rdata), .m_rresp(c2_rresp), .m_rlast(c2_rlast),
        .m_rvalid(c2_rvalid), .m_rready(c2_rready)
    );
    // no node: RAMs behind both windows, the Xache master idle
    axi_ram #(.DATA_W(256), .ADDR_W(16), .ID_W(4), .WORDS(512), .PORTS(1)) u_nomem2 (
        .clk(sys_clk[2]), .resetn(rstn_sys[2]),
        .s_awid(M08_awid), .s_awaddr(M08_awaddr[15:0]), .s_awlen(M08_awlen), .s_awsize(M08_awsize),
        .s_awburst(M08_awburst), .s_awvalid(M08_awvalid), .s_awready(M08_awready), .s_wdata(M08_wdata),
        .s_wstrb(M08_wstrb), .s_wlast(M08_wlast), .s_wvalid(M08_wvalid), .s_wready(M08_wready),
        .s_bid(M08_bid), .s_bresp(M08_bresp), .s_bvalid(M08_bvalid), .s_bready(M08_bready),
        .s_arid(M08_arid), .s_araddr(M08_araddr[15:0]), .s_arlen(M08_arlen), .s_arsize(M08_arsize),
        .s_arburst(M08_arburst), .s_arvalid(M08_arvalid), .s_arready(M08_arready), .s_rid(M08_rid),
        .s_rdata(M08_rdata), .s_rresp(M08_rresp), .s_rlast(M08_rlast), .s_rvalid(M08_rvalid),
        .s_rready(M08_rready), .bd_we(1'b0), .bd_addr(16'd0), .bd_wdata(256'd0),
        .bd_rdata()
    );
    axi_ram #(.DATA_W(64), .ADDR_W(16), .ID_W(4), .WORDS(512), .PORTS(1)) u_noctl2 (
        .clk(sys_clk[2]), .resetn(rstn_sys[2]),
        .s_awid(c2_awid), .s_awaddr(c2_awaddr[15:0]), .s_awlen(c2_awlen), .s_awsize(c2_awsize),
        .s_awburst(c2_awburst), .s_awvalid(c2_awvalid), .s_awready(c2_awready), .s_wdata(c2_wdata),
        .s_wstrb(c2_wstrb), .s_wlast(c2_wlast), .s_wvalid(c2_wvalid), .s_wready(c2_wready),
        .s_bid(c2_bid), .s_bresp(c2_bresp), .s_bvalid(c2_bvalid), .s_bready(c2_bready),
        .s_arid(c2_arid), .s_araddr(c2_araddr[15:0]), .s_arlen(c2_arlen), .s_arsize(c2_arsize),
        .s_arburst(c2_arburst), .s_arvalid(c2_arvalid), .s_arready(c2_arready), .s_rid(c2_rid),
        .s_rdata(c2_rdata), .s_rresp(c2_rresp), .s_rlast(c2_rlast), .s_rvalid(c2_rvalid),
        .s_rready(c2_rready), .bd_we(1'b0), .bd_addr(16'd0), .bd_wdata(64'd0),
        .bd_rdata()
    );
    assign x2_awid = 0;
    assign x2_awaddr = 0;
    assign x2_awlen = 0;
    assign x2_awsize = 0;
    assign x2_awburst = 0;
    assign x2_awvalid = 0;
    assign x2_wdata = 0;
    assign x2_wstrb = 0;
    assign x2_wlast = 0;
    assign x2_wvalid = 0;
    assign x2_bready = 0;
    assign x2_arid = 0;
    assign x2_araddr = 0;
    assign x2_arlen = 0;
    assign x2_arsize = 0;
    assign x2_arburst = 0;
    assign x2_arvalid = 0;
    assign x2_rready = 0;

    axil_ram #(.AW(43), .WORDS(256)) u_ddrctl2 (.clk(ddr_clk[2]), .resetn(rstn_ddr[2]),
        .s_awaddr(M10_awaddr), .s_awvalid(M10_awvalid), .s_awready(M10_awready), .s_wdata(M10_wdata),
        .s_wstrb(M10_wstrb), .s_wvalid(M10_wvalid), .s_wready(M10_wready), .s_bresp(M10_bresp),
        .s_bvalid(M10_bvalid), .s_bready(M10_bready), .s_araddr(M10_araddr), .s_arvalid(M10_arvalid),
        .s_arready(M10_arready), .s_rdata(M10_rdata), .s_rresp(M10_rresp), .s_rvalid(M10_rvalid),
        .s_rready(M10_rready)
    );
    clk_wiz_model #(.AW(43), .D(4), .M(48), .DIV0({8'd4, 8'd4, 8'd2, 8'd4}),
                    .LOCK_CYC(LOCK_CYC)) u_wiz2 (.clk(clk_ctrl), .resetn(rstn_ctrl),
        .s_awaddr(M11_awaddr), .s_awvalid(M11_awvalid), .s_awready(M11_awready), .s_wdata(M11_wdata),
        .s_wstrb(M11_wstrb), .s_wvalid(M11_wvalid), .s_wready(M11_wready), .s_bresp(M11_bresp),
        .s_bvalid(M11_bvalid), .s_bready(M11_bready), .s_araddr(M11_araddr), .s_arvalid(M11_arvalid),
        .s_arready(M11_arready), .s_rdata(M11_rdata), .s_rresp(M11_rresp), .s_rvalid(M11_rvalid),
        .s_rready(M11_rready), .locked(wiz_locked[2]), .divclk(wiz_divclk[2*8 +: 8]), .mult(wiz_mult[2*8 +: 8]),
        .div(wiz_div[2*32 +: 32])
    );

    // ==== die 3 ====

    wire [3:0] c3_awid;
    wire [31:0] c3_awaddr;
    wire [7:0] c3_awlen;
    wire [2:0] c3_awsize;
    wire [1:0] c3_awburst;
    wire c3_awvalid;
    wire c3_awready;
    wire [63:0] c3_wdata;
    wire [7:0] c3_wstrb;
    wire c3_wlast;
    wire c3_wvalid;
    wire c3_wready;
    wire [3:0] c3_bid;
    wire [1:0] c3_bresp;
    wire c3_bvalid;
    wire c3_bready;
    wire [3:0] c3_arid;
    wire [31:0] c3_araddr;
    wire [7:0] c3_arlen;
    wire [2:0] c3_arsize;
    wire [1:0] c3_arburst;
    wire c3_arvalid;
    wire c3_arready;
    wire [3:0] c3_rid;
    wire [63:0] c3_rdata;
    wire [1:0] c3_rresp;
    wire c3_rlast;
    wire c3_rvalid;
    wire c3_rready;
    wire [3:0] x3_awid;
    wire [39:0] x3_awaddr;
    wire [7:0] x3_awlen;
    wire [2:0] x3_awsize;
    wire [1:0] x3_awburst;
    wire x3_awvalid;
    wire x3_awready;
    wire [511:0] x3_wdata;
    wire [63:0] x3_wstrb;
    wire x3_wlast;
    wire x3_wvalid;
    wire x3_wready;
    wire [3:0] x3_bid;
    wire [1:0] x3_bresp;
    wire x3_bvalid;
    wire x3_bready;
    wire [3:0] x3_arid;
    wire [39:0] x3_araddr;
    wire [7:0] x3_arlen;
    wire [2:0] x3_arsize;
    wire [1:0] x3_arburst;
    wire x3_arvalid;
    wire x3_arready;
    wire [3:0] x3_rid;
    wire [511:0] x3_rdata;
    wire [1:0] x3_rresp;
    wire x3_rlast;
    wire x3_rvalid;
    wire x3_rready;
    // the BD's axi_dwidth_converter SI 32 -> MI 64, on the sysnode clock
    axi_up32to64 #(.AW(32), .IDW(4)) u_dwc3 (.clk(sys_clk[3]), .resetn(rstn_sys[3]),
        .s_awid(M13_awid), .s_awaddr(M13_awaddr[31:0]), .s_awlen(M13_awlen), .s_awsize(M13_awsize),
        .s_awburst(M13_awburst), .s_awvalid(M13_awvalid), .s_awready(M13_awready), .s_wdata(M13_wdata),
        .s_wstrb(M13_wstrb), .s_wlast(M13_wlast), .s_wvalid(M13_wvalid), .s_wready(M13_wready),
        .s_bid(M13_bid), .s_bresp(M13_bresp), .s_bvalid(M13_bvalid), .s_bready(M13_bready),
        .s_arid(M13_arid), .s_araddr(M13_araddr[31:0]), .s_arlen(M13_arlen), .s_arsize(M13_arsize),
        .s_arburst(M13_arburst), .s_arvalid(M13_arvalid), .s_arready(M13_arready), .s_rid(M13_rid),
        .s_rdata(M13_rdata), .s_rresp(M13_rresp), .s_rlast(M13_rlast), .s_rvalid(M13_rvalid),
        .s_rready(M13_rready), .m_awid(c3_awid), .m_awaddr(c3_awaddr), .m_awlen(c3_awlen),
        .m_awsize(c3_awsize), .m_awburst(c3_awburst), .m_awvalid(c3_awvalid), .m_awready(c3_awready),
        .m_wdata(c3_wdata), .m_wstrb(c3_wstrb), .m_wlast(c3_wlast), .m_wvalid(c3_wvalid),
        .m_wready(c3_wready), .m_bid(c3_bid), .m_bresp(c3_bresp), .m_bvalid(c3_bvalid),
        .m_bready(c3_bready), .m_arid(c3_arid), .m_araddr(c3_araddr), .m_arlen(c3_arlen),
        .m_arsize(c3_arsize), .m_arburst(c3_arburst), .m_arvalid(c3_arvalid), .m_arready(c3_arready),
        .m_rid(c3_rid), .m_rdata(c3_rdata), .m_rresp(c3_rresp), .m_rlast(c3_rlast),
        .m_rvalid(c3_rvalid), .m_rready(c3_rready)
    );
    // no node: RAMs behind both windows, the Xache master idle
    axi_ram #(.DATA_W(256), .ADDR_W(16), .ID_W(4), .WORDS(512), .PORTS(1)) u_nomem3 (
        .clk(sys_clk[3]), .resetn(rstn_sys[3]),
        .s_awid(M12_awid), .s_awaddr(M12_awaddr[15:0]), .s_awlen(M12_awlen), .s_awsize(M12_awsize),
        .s_awburst(M12_awburst), .s_awvalid(M12_awvalid), .s_awready(M12_awready), .s_wdata(M12_wdata),
        .s_wstrb(M12_wstrb), .s_wlast(M12_wlast), .s_wvalid(M12_wvalid), .s_wready(M12_wready),
        .s_bid(M12_bid), .s_bresp(M12_bresp), .s_bvalid(M12_bvalid), .s_bready(M12_bready),
        .s_arid(M12_arid), .s_araddr(M12_araddr[15:0]), .s_arlen(M12_arlen), .s_arsize(M12_arsize),
        .s_arburst(M12_arburst), .s_arvalid(M12_arvalid), .s_arready(M12_arready), .s_rid(M12_rid),
        .s_rdata(M12_rdata), .s_rresp(M12_rresp), .s_rlast(M12_rlast), .s_rvalid(M12_rvalid),
        .s_rready(M12_rready), .bd_we(1'b0), .bd_addr(16'd0), .bd_wdata(256'd0),
        .bd_rdata()
    );
    axi_ram #(.DATA_W(64), .ADDR_W(16), .ID_W(4), .WORDS(512), .PORTS(1)) u_noctl3 (
        .clk(sys_clk[3]), .resetn(rstn_sys[3]),
        .s_awid(c3_awid), .s_awaddr(c3_awaddr[15:0]), .s_awlen(c3_awlen), .s_awsize(c3_awsize),
        .s_awburst(c3_awburst), .s_awvalid(c3_awvalid), .s_awready(c3_awready), .s_wdata(c3_wdata),
        .s_wstrb(c3_wstrb), .s_wlast(c3_wlast), .s_wvalid(c3_wvalid), .s_wready(c3_wready),
        .s_bid(c3_bid), .s_bresp(c3_bresp), .s_bvalid(c3_bvalid), .s_bready(c3_bready),
        .s_arid(c3_arid), .s_araddr(c3_araddr[15:0]), .s_arlen(c3_arlen), .s_arsize(c3_arsize),
        .s_arburst(c3_arburst), .s_arvalid(c3_arvalid), .s_arready(c3_arready), .s_rid(c3_rid),
        .s_rdata(c3_rdata), .s_rresp(c3_rresp), .s_rlast(c3_rlast), .s_rvalid(c3_rvalid),
        .s_rready(c3_rready), .bd_we(1'b0), .bd_addr(16'd0), .bd_wdata(64'd0),
        .bd_rdata()
    );
    assign x3_awid = 0;
    assign x3_awaddr = 0;
    assign x3_awlen = 0;
    assign x3_awsize = 0;
    assign x3_awburst = 0;
    assign x3_awvalid = 0;
    assign x3_wdata = 0;
    assign x3_wstrb = 0;
    assign x3_wlast = 0;
    assign x3_wvalid = 0;
    assign x3_bready = 0;
    assign x3_arid = 0;
    assign x3_araddr = 0;
    assign x3_arlen = 0;
    assign x3_arsize = 0;
    assign x3_arburst = 0;
    assign x3_arvalid = 0;
    assign x3_rready = 0;

    axil_ram #(.AW(43), .WORDS(256)) u_ddrctl3 (.clk(ddr_clk[3]), .resetn(rstn_ddr[3]),
        .s_awaddr(M14_awaddr), .s_awvalid(M14_awvalid), .s_awready(M14_awready), .s_wdata(M14_wdata),
        .s_wstrb(M14_wstrb), .s_wvalid(M14_wvalid), .s_wready(M14_wready), .s_bresp(M14_bresp),
        .s_bvalid(M14_bvalid), .s_bready(M14_bready), .s_araddr(M14_araddr), .s_arvalid(M14_arvalid),
        .s_arready(M14_arready), .s_rdata(M14_rdata), .s_rresp(M14_rresp), .s_rvalid(M14_rvalid),
        .s_rready(M14_rready)
    );
    clk_wiz_model #(.AW(43), .D(4), .M(48), .DIV0({8'd4, 8'd4, 8'd2, 8'd4}),
                    .LOCK_CYC(LOCK_CYC)) u_wiz3 (.clk(clk_ctrl), .resetn(rstn_ctrl),
        .s_awaddr(M15_awaddr), .s_awvalid(M15_awvalid), .s_awready(M15_awready), .s_wdata(M15_wdata),
        .s_wstrb(M15_wstrb), .s_wvalid(M15_wvalid), .s_wready(M15_wready), .s_bresp(M15_bresp),
        .s_bvalid(M15_bvalid), .s_bready(M15_bready), .s_araddr(M15_araddr), .s_arvalid(M15_arvalid),
        .s_arready(M15_arready), .s_rdata(M15_rdata), .s_rresp(M15_rresp), .s_rvalid(M15_rvalid),
        .s_rready(M15_rready), .locked(wiz_locked[3]), .divclk(wiz_divclk[3*8 +: 8]), .mult(wiz_mult[3*8 +: 8]),
        .div(wiz_div[3*32 +: 32])
    );

    // ---- interlink (30_meshes.tcl): one kts_pipe_bd per hop and direction
    assign l0_LINK0_IN_valid = 1'b0;
    assign l0_LINK0_IN_vc = 1'b0;
    assign l0_LINK0_IN_last = 1'b0;
    assign l0_LINK0_IN_flit = 288'd0;
    assign l0_LINK0_OUT_crd_valid = 1'b0;
    assign l0_LINK0_OUT_crd_vc = 1'b0;
    assign l0_LINK0_OUT_crd_n = 4'd0;
    assign l0_LINK1_IN_valid = 1'b0;
    assign l0_LINK1_IN_vc = 1'b0;
    assign l0_LINK1_IN_last = 1'b0;
    assign l0_LINK1_IN_flit = 288'd0;
    assign l0_LINK1_OUT_crd_valid = 1'b0;
    assign l0_LINK1_OUT_crd_vc = 1'b0;
    assign l0_LINK1_OUT_crd_n = 4'd0;

    // ---- the Xache (35_xache.tcl): master m = die m, home h = channel h
    wire [5:0] d0_awid;
    wire [39:0] d0_awaddr;
    wire [7:0] d0_awlen;
    wire [2:0] d0_awsize;
    wire [1:0] d0_awburst;
    wire d0_awvalid;
    wire d0_awready;
    wire [511:0] d0_wdata;
    wire [63:0] d0_wstrb;
    wire d0_wlast;
    wire d0_wvalid;
    wire d0_wready;
    wire [5:0] d0_bid;
    wire [1:0] d0_bresp;
    wire d0_bvalid;
    wire d0_bready;
    wire [5:0] d0_arid;
    wire [39:0] d0_araddr;
    wire [7:0] d0_arlen;
    wire [2:0] d0_arsize;
    wire [1:0] d0_arburst;
    wire d0_arvalid;
    wire d0_arready;
    wire [5:0] d0_rid;
    wire [511:0] d0_rdata;
    wire [1:0] d0_rresp;
    wire d0_rlast;
    wire d0_rvalid;
    wire d0_rready;
    wire [5:0] d1_awid;
    wire [39:0] d1_awaddr;
    wire [7:0] d1_awlen;
    wire [2:0] d1_awsize;
    wire [1:0] d1_awburst;
    wire d1_awvalid;
    wire d1_awready;
    wire [511:0] d1_wdata;
    wire [63:0] d1_wstrb;
    wire d1_wlast;
    wire d1_wvalid;
    wire d1_wready;
    wire [5:0] d1_bid;
    wire [1:0] d1_bresp;
    wire d1_bvalid;
    wire d1_bready;
    wire [5:0] d1_arid;
    wire [39:0] d1_araddr;
    wire [7:0] d1_arlen;
    wire [2:0] d1_arsize;
    wire [1:0] d1_arburst;
    wire d1_arvalid;
    wire d1_arready;
    wire [5:0] d1_rid;
    wire [511:0] d1_rdata;
    wire [1:0] d1_rresp;
    wire d1_rlast;
    wire d1_rvalid;
    wire d1_rready;
    wire [5:0] d2_awid;
    wire [39:0] d2_awaddr;
    wire [7:0] d2_awlen;
    wire [2:0] d2_awsize;
    wire [1:0] d2_awburst;
    wire d2_awvalid;
    wire d2_awready;
    wire [511:0] d2_wdata;
    wire [63:0] d2_wstrb;
    wire d2_wlast;
    wire d2_wvalid;
    wire d2_wready;
    wire [5:0] d2_bid;
    wire [1:0] d2_bresp;
    wire d2_bvalid;
    wire d2_bready;
    wire [5:0] d2_arid;
    wire [39:0] d2_araddr;
    wire [7:0] d2_arlen;
    wire [2:0] d2_arsize;
    wire [1:0] d2_arburst;
    wire d2_arvalid;
    wire d2_arready;
    wire [5:0] d2_rid;
    wire [511:0] d2_rdata;
    wire [1:0] d2_rresp;
    wire d2_rlast;
    wire d2_rvalid;
    wire d2_rready;
    wire [5:0] d3_awid;
    wire [39:0] d3_awaddr;
    wire [7:0] d3_awlen;
    wire [2:0] d3_awsize;
    wire [1:0] d3_awburst;
    wire d3_awvalid;
    wire d3_awready;
    wire [511:0] d3_wdata;
    wire [63:0] d3_wstrb;
    wire d3_wlast;
    wire d3_wvalid;
    wire d3_wready;
    wire [5:0] d3_bid;
    wire [1:0] d3_bresp;
    wire d3_bvalid;
    wire d3_bready;
    wire [5:0] d3_arid;
    wire [39:0] d3_araddr;
    wire [7:0] d3_arlen;
    wire [2:0] d3_arsize;
    wire [1:0] d3_arburst;
    wire d3_arvalid;
    wire d3_arready;
    wire [5:0] d3_rid;
    wire [511:0] d3_rdata;
    wire [1:0] d3_rresp;
    wire d3_rlast;
    wire d3_rvalid;
    wire d3_rready;
    kx_pbd_4x4 #(
        .SETS(16384), .SET_W(14), .K(2),
        .RAM_STYLE("ultra"), .BANKS(4), .CDC_DEPTH(16),
        .RD_OUTQ(4), .WR_OUTQ(4), .RB_BEATS(16),
        .HOP_DEPTH(16), .HOP_RXREG(0), .BND_TRUNK(1),
        .PCLK(1), .NSWAP(18), .MEM_TRUNK("distributed"),
        .MEM_RB("distributed"), .MEM_HRD("distributed"), .MEM_HWR("distributed"),
        .SWAP_A(256'h00000000000000000000000000001f1e1d1c1b1a191817161514131211100f0e), .SWAP_B(256'h000000000000000000000000000021201f1e1d1c1b1a19181716151413121110)
    ) u_xache (
        .p_clk0(sys_clk[0]), .d_rstn0(rstn_sys[0]), .h_clk0(ddr_clk[0]), .h_rstn0(rstn_ddr[0]),
        .S00_AXI_awid(x0_awid), .S00_AXI_awaddr(x0_awaddr), .S00_AXI_awlen(x0_awlen), .S00_AXI_awsize(x0_awsize),
        .S00_AXI_awburst(x0_awburst), .S00_AXI_awvalid(x0_awvalid), .S00_AXI_awready(x0_awready), .S00_AXI_wdata(x0_wdata),
        .S00_AXI_wstrb(x0_wstrb), .S00_AXI_wlast(x0_wlast), .S00_AXI_wvalid(x0_wvalid), .S00_AXI_wready(x0_wready),
        .S00_AXI_bid(x0_bid), .S00_AXI_bresp(x0_bresp), .S00_AXI_bvalid(x0_bvalid), .S00_AXI_bready(x0_bready),
        .S00_AXI_arid(x0_arid), .S00_AXI_araddr(x0_araddr), .S00_AXI_arlen(x0_arlen), .S00_AXI_arsize(x0_arsize),
        .S00_AXI_arburst(x0_arburst), .S00_AXI_arvalid(x0_arvalid), .S00_AXI_arready(x0_arready), .S00_AXI_rid(x0_rid),
        .S00_AXI_rdata(x0_rdata), .S00_AXI_rresp(x0_rresp), .S00_AXI_rlast(x0_rlast), .S00_AXI_rvalid(x0_rvalid),
        .S00_AXI_rready(x0_rready), .M00_AXI_awid(d0_awid), .M00_AXI_awaddr(d0_awaddr), .M00_AXI_awlen(d0_awlen),
        .M00_AXI_awsize(d0_awsize), .M00_AXI_awburst(d0_awburst), .M00_AXI_awvalid(d0_awvalid), .M00_AXI_awready(d0_awready),
        .M00_AXI_wdata(d0_wdata), .M00_AXI_wstrb(d0_wstrb), .M00_AXI_wlast(d0_wlast), .M00_AXI_wvalid(d0_wvalid),
        .M00_AXI_wready(d0_wready), .M00_AXI_bid(d0_bid), .M00_AXI_bresp(d0_bresp), .M00_AXI_bvalid(d0_bvalid),
        .M00_AXI_bready(d0_bready), .M00_AXI_arid(d0_arid), .M00_AXI_araddr(d0_araddr), .M00_AXI_arlen(d0_arlen),
        .M00_AXI_arsize(d0_arsize), .M00_AXI_arburst(d0_arburst), .M00_AXI_arvalid(d0_arvalid), .M00_AXI_arready(d0_arready),
        .M00_AXI_rid(d0_rid), .M00_AXI_rdata(d0_rdata), .M00_AXI_rresp(d0_rresp), .M00_AXI_rlast(d0_rlast),
        .M00_AXI_rvalid(d0_rvalid), .M00_AXI_rready(d0_rready), .p_clk1(sys_clk[1]), .d_rstn1(rstn_sys[1]),
        .h_clk1(ddr_clk[1]), .h_rstn1(rstn_ddr[1]), .S01_AXI_awid(x1_awid), .S01_AXI_awaddr(x1_awaddr),
        .S01_AXI_awlen(x1_awlen), .S01_AXI_awsize(x1_awsize), .S01_AXI_awburst(x1_awburst), .S01_AXI_awvalid(x1_awvalid),
        .S01_AXI_awready(x1_awready), .S01_AXI_wdata(x1_wdata), .S01_AXI_wstrb(x1_wstrb), .S01_AXI_wlast(x1_wlast),
        .S01_AXI_wvalid(x1_wvalid), .S01_AXI_wready(x1_wready), .S01_AXI_bid(x1_bid), .S01_AXI_bresp(x1_bresp),
        .S01_AXI_bvalid(x1_bvalid), .S01_AXI_bready(x1_bready), .S01_AXI_arid(x1_arid), .S01_AXI_araddr(x1_araddr),
        .S01_AXI_arlen(x1_arlen), .S01_AXI_arsize(x1_arsize), .S01_AXI_arburst(x1_arburst), .S01_AXI_arvalid(x1_arvalid),
        .S01_AXI_arready(x1_arready), .S01_AXI_rid(x1_rid), .S01_AXI_rdata(x1_rdata), .S01_AXI_rresp(x1_rresp),
        .S01_AXI_rlast(x1_rlast), .S01_AXI_rvalid(x1_rvalid), .S01_AXI_rready(x1_rready), .M01_AXI_awid(d1_awid),
        .M01_AXI_awaddr(d1_awaddr), .M01_AXI_awlen(d1_awlen), .M01_AXI_awsize(d1_awsize), .M01_AXI_awburst(d1_awburst),
        .M01_AXI_awvalid(d1_awvalid), .M01_AXI_awready(d1_awready), .M01_AXI_wdata(d1_wdata), .M01_AXI_wstrb(d1_wstrb),
        .M01_AXI_wlast(d1_wlast), .M01_AXI_wvalid(d1_wvalid), .M01_AXI_wready(d1_wready), .M01_AXI_bid(d1_bid),
        .M01_AXI_bresp(d1_bresp), .M01_AXI_bvalid(d1_bvalid), .M01_AXI_bready(d1_bready), .M01_AXI_arid(d1_arid),
        .M01_AXI_araddr(d1_araddr), .M01_AXI_arlen(d1_arlen), .M01_AXI_arsize(d1_arsize), .M01_AXI_arburst(d1_arburst),
        .M01_AXI_arvalid(d1_arvalid), .M01_AXI_arready(d1_arready), .M01_AXI_rid(d1_rid), .M01_AXI_rdata(d1_rdata),
        .M01_AXI_rresp(d1_rresp), .M01_AXI_rlast(d1_rlast), .M01_AXI_rvalid(d1_rvalid), .M01_AXI_rready(d1_rready),
        .p_clk2(sys_clk[2]), .d_rstn2(rstn_sys[2]), .h_clk2(ddr_clk[2]), .h_rstn2(rstn_ddr[2]),
        .S02_AXI_awid(x2_awid), .S02_AXI_awaddr(x2_awaddr), .S02_AXI_awlen(x2_awlen), .S02_AXI_awsize(x2_awsize),
        .S02_AXI_awburst(x2_awburst), .S02_AXI_awvalid(x2_awvalid), .S02_AXI_awready(x2_awready), .S02_AXI_wdata(x2_wdata),
        .S02_AXI_wstrb(x2_wstrb), .S02_AXI_wlast(x2_wlast), .S02_AXI_wvalid(x2_wvalid), .S02_AXI_wready(x2_wready),
        .S02_AXI_bid(x2_bid), .S02_AXI_bresp(x2_bresp), .S02_AXI_bvalid(x2_bvalid), .S02_AXI_bready(x2_bready),
        .S02_AXI_arid(x2_arid), .S02_AXI_araddr(x2_araddr), .S02_AXI_arlen(x2_arlen), .S02_AXI_arsize(x2_arsize),
        .S02_AXI_arburst(x2_arburst), .S02_AXI_arvalid(x2_arvalid), .S02_AXI_arready(x2_arready), .S02_AXI_rid(x2_rid),
        .S02_AXI_rdata(x2_rdata), .S02_AXI_rresp(x2_rresp), .S02_AXI_rlast(x2_rlast), .S02_AXI_rvalid(x2_rvalid),
        .S02_AXI_rready(x2_rready), .M02_AXI_awid(d2_awid), .M02_AXI_awaddr(d2_awaddr), .M02_AXI_awlen(d2_awlen),
        .M02_AXI_awsize(d2_awsize), .M02_AXI_awburst(d2_awburst), .M02_AXI_awvalid(d2_awvalid), .M02_AXI_awready(d2_awready),
        .M02_AXI_wdata(d2_wdata), .M02_AXI_wstrb(d2_wstrb), .M02_AXI_wlast(d2_wlast), .M02_AXI_wvalid(d2_wvalid),
        .M02_AXI_wready(d2_wready), .M02_AXI_bid(d2_bid), .M02_AXI_bresp(d2_bresp), .M02_AXI_bvalid(d2_bvalid),
        .M02_AXI_bready(d2_bready), .M02_AXI_arid(d2_arid), .M02_AXI_araddr(d2_araddr), .M02_AXI_arlen(d2_arlen),
        .M02_AXI_arsize(d2_arsize), .M02_AXI_arburst(d2_arburst), .M02_AXI_arvalid(d2_arvalid), .M02_AXI_arready(d2_arready),
        .M02_AXI_rid(d2_rid), .M02_AXI_rdata(d2_rdata), .M02_AXI_rresp(d2_rresp), .M02_AXI_rlast(d2_rlast),
        .M02_AXI_rvalid(d2_rvalid), .M02_AXI_rready(d2_rready), .p_clk3(sys_clk[3]), .d_rstn3(rstn_sys[3]),
        .h_clk3(ddr_clk[3]), .h_rstn3(rstn_ddr[3]), .S03_AXI_awid(x3_awid), .S03_AXI_awaddr(x3_awaddr),
        .S03_AXI_awlen(x3_awlen), .S03_AXI_awsize(x3_awsize), .S03_AXI_awburst(x3_awburst), .S03_AXI_awvalid(x3_awvalid),
        .S03_AXI_awready(x3_awready), .S03_AXI_wdata(x3_wdata), .S03_AXI_wstrb(x3_wstrb), .S03_AXI_wlast(x3_wlast),
        .S03_AXI_wvalid(x3_wvalid), .S03_AXI_wready(x3_wready), .S03_AXI_bid(x3_bid), .S03_AXI_bresp(x3_bresp),
        .S03_AXI_bvalid(x3_bvalid), .S03_AXI_bready(x3_bready), .S03_AXI_arid(x3_arid), .S03_AXI_araddr(x3_araddr),
        .S03_AXI_arlen(x3_arlen), .S03_AXI_arsize(x3_arsize), .S03_AXI_arburst(x3_arburst), .S03_AXI_arvalid(x3_arvalid),
        .S03_AXI_arready(x3_arready), .S03_AXI_rid(x3_rid), .S03_AXI_rdata(x3_rdata), .S03_AXI_rresp(x3_rresp),
        .S03_AXI_rlast(x3_rlast), .S03_AXI_rvalid(x3_rvalid), .S03_AXI_rready(x3_rready), .M03_AXI_awid(d3_awid),
        .M03_AXI_awaddr(d3_awaddr), .M03_AXI_awlen(d3_awlen), .M03_AXI_awsize(d3_awsize), .M03_AXI_awburst(d3_awburst),
        .M03_AXI_awvalid(d3_awvalid), .M03_AXI_awready(d3_awready), .M03_AXI_wdata(d3_wdata), .M03_AXI_wstrb(d3_wstrb),
        .M03_AXI_wlast(d3_wlast), .M03_AXI_wvalid(d3_wvalid), .M03_AXI_wready(d3_wready), .M03_AXI_bid(d3_bid),
        .M03_AXI_bresp(d3_bresp), .M03_AXI_bvalid(d3_bvalid), .M03_AXI_bready(d3_bready), .M03_AXI_arid(d3_arid),
        .M03_AXI_araddr(d3_araddr), .M03_AXI_arlen(d3_arlen), .M03_AXI_arsize(d3_arsize), .M03_AXI_arburst(d3_arburst),
        .M03_AXI_arvalid(d3_arvalid), .M03_AXI_arready(d3_arready), .M03_AXI_rid(d3_rid), .M03_AXI_rdata(d3_rdata),
        .M03_AXI_rresp(d3_rresp), .M03_AXI_rlast(d3_rlast), .M03_AXI_rvalid(d3_rvalid), .M03_AXI_rready(d3_rready)
    );

    // ---- DRAM: one axi_ram per channel on its ui clock
    axi_ram #(.DATA_W(512), .ADDR_W(40), .ID_W(6), .WORDS(DRAM_WORDS), .PORTS(1)) u_dram0 (
        .clk(ddr_clk[0]), .resetn(rstn_ddr[0]),
        .s_awid(d0_awid), .s_awaddr(d0_awaddr), .s_awlen(d0_awlen), .s_awsize(d0_awsize),
        .s_awburst(d0_awburst), .s_awvalid(d0_awvalid), .s_awready(d0_awready), .s_wdata(d0_wdata),
        .s_wstrb(d0_wstrb), .s_wlast(d0_wlast), .s_wvalid(d0_wvalid), .s_wready(d0_wready),
        .s_bid(d0_bid), .s_bresp(d0_bresp), .s_bvalid(d0_bvalid), .s_bready(d0_bready),
        .s_arid(d0_arid), .s_araddr(d0_araddr), .s_arlen(d0_arlen), .s_arsize(d0_arsize),
        .s_arburst(d0_arburst), .s_arvalid(d0_arvalid), .s_arready(d0_arready), .s_rid(d0_rid),
        .s_rdata(d0_rdata), .s_rresp(d0_rresp), .s_rlast(d0_rlast), .s_rvalid(d0_rvalid),
        .s_rready(d0_rready), .bd_we(bd_we[0]), .bd_addr(bd_addr[0*16 +: 16]), .bd_wdata(bd_wdata[0*512 +: 512]),
        .bd_rdata(bd_rdata[0*512 +: 512])
    );
    axi_ram #(.DATA_W(512), .ADDR_W(40), .ID_W(6), .WORDS(DRAM_WORDS), .PORTS(1)) u_dram1 (
        .clk(ddr_clk[1]), .resetn(rstn_ddr[1]),
        .s_awid(d1_awid), .s_awaddr(d1_awaddr), .s_awlen(d1_awlen), .s_awsize(d1_awsize),
        .s_awburst(d1_awburst), .s_awvalid(d1_awvalid), .s_awready(d1_awready), .s_wdata(d1_wdata),
        .s_wstrb(d1_wstrb), .s_wlast(d1_wlast), .s_wvalid(d1_wvalid), .s_wready(d1_wready),
        .s_bid(d1_bid), .s_bresp(d1_bresp), .s_bvalid(d1_bvalid), .s_bready(d1_bready),
        .s_arid(d1_arid), .s_araddr(d1_araddr), .s_arlen(d1_arlen), .s_arsize(d1_arsize),
        .s_arburst(d1_arburst), .s_arvalid(d1_arvalid), .s_arready(d1_arready), .s_rid(d1_rid),
        .s_rdata(d1_rdata), .s_rresp(d1_rresp), .s_rlast(d1_rlast), .s_rvalid(d1_rvalid),
        .s_rready(d1_rready), .bd_we(bd_we[1]), .bd_addr(bd_addr[1*16 +: 16]), .bd_wdata(bd_wdata[1*512 +: 512]),
        .bd_rdata(bd_rdata[1*512 +: 512])
    );
    axi_ram #(.DATA_W(512), .ADDR_W(40), .ID_W(6), .WORDS(DRAM_WORDS), .PORTS(1)) u_dram2 (
        .clk(ddr_clk[2]), .resetn(rstn_ddr[2]),
        .s_awid(d2_awid), .s_awaddr(d2_awaddr), .s_awlen(d2_awlen), .s_awsize(d2_awsize),
        .s_awburst(d2_awburst), .s_awvalid(d2_awvalid), .s_awready(d2_awready), .s_wdata(d2_wdata),
        .s_wstrb(d2_wstrb), .s_wlast(d2_wlast), .s_wvalid(d2_wvalid), .s_wready(d2_wready),
        .s_bid(d2_bid), .s_bresp(d2_bresp), .s_bvalid(d2_bvalid), .s_bready(d2_bready),
        .s_arid(d2_arid), .s_araddr(d2_araddr), .s_arlen(d2_arlen), .s_arsize(d2_arsize),
        .s_arburst(d2_arburst), .s_arvalid(d2_arvalid), .s_arready(d2_arready), .s_rid(d2_rid),
        .s_rdata(d2_rdata), .s_rresp(d2_rresp), .s_rlast(d2_rlast), .s_rvalid(d2_rvalid),
        .s_rready(d2_rready), .bd_we(bd_we[2]), .bd_addr(bd_addr[2*16 +: 16]), .bd_wdata(bd_wdata[2*512 +: 512]),
        .bd_rdata(bd_rdata[2*512 +: 512])
    );
    axi_ram #(.DATA_W(512), .ADDR_W(40), .ID_W(6), .WORDS(DRAM_WORDS), .PORTS(1)) u_dram3 (
        .clk(ddr_clk[3]), .resetn(rstn_ddr[3]),
        .s_awid(d3_awid), .s_awaddr(d3_awaddr), .s_awlen(d3_awlen), .s_awsize(d3_awsize),
        .s_awburst(d3_awburst), .s_awvalid(d3_awvalid), .s_awready(d3_awready), .s_wdata(d3_wdata),
        .s_wstrb(d3_wstrb), .s_wlast(d3_wlast), .s_wvalid(d3_wvalid), .s_wready(d3_wready),
        .s_bid(d3_bid), .s_bresp(d3_bresp), .s_bvalid(d3_bvalid), .s_bready(d3_bready),
        .s_arid(d3_arid), .s_araddr(d3_araddr), .s_arlen(d3_arlen), .s_arsize(d3_arsize),
        .s_arburst(d3_arburst), .s_arvalid(d3_arvalid), .s_arready(d3_arready), .s_rid(d3_rid),
        .s_rdata(d3_rdata), .s_rresp(d3_rresp), .s_rlast(d3_rlast), .s_rvalid(d3_rvalid),
        .s_rready(d3_rready), .bd_we(bd_we[3]), .bd_addr(bd_addr[3*16 +: 16]), .bd_wdata(bd_wdata[3*512 +: 512]),
        .bd_rdata(bd_rdata[3*512 +: 512])
    );
endmodule

`default_nettype wire
