// sb_bd_link -- GENERATED by scripts/py/gen_station_wrap.py. Do not edit by hand.
//
// One station-to-station crossing as two AXIS interfaces each way. Its own
// block, and NOT in any pblock: the pipeline registers have to be free to place
// across the die, which a station pinned to one SLR cannot allow.

`default_nettype none

module sb_bd_link #(
    parameter integer PIPE = 4,
    parameter integer CRED = 16
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 bus_clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S_REQ:M_REQ:S_RSP:M_RSP, ASSOCIATED_RESET bus_rst" *)
    input  wire bus_clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 bus_rst RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_HIGH" *)
    input  wire bus_rst,

    input  wire [632-1:0] S_REQ_tdata,
    input  wire S_REQ_tvalid,
    output wire S_REQ_tready,
    output wire [632-1:0] M_REQ_tdata,
    output wire M_REQ_tvalid,
    input  wire M_REQ_tready,
    input  wire [528-1:0] S_RSP_tdata,
    input  wire S_RSP_tvalid,
    output wire S_RSP_tready,
    output wire [528-1:0] M_RSP_tdata,
    output wire M_RSP_tvalid,
    input  wire M_RSP_tready
);
    sb_link #(.W(632), .PIPE(PIPE), .CRED(CRED)) u_req (
        .clk(bus_clk), .rst(bus_rst),
        .i_valid(S_REQ_tvalid), .i_ready(S_REQ_tready), .i_data(S_REQ_tdata),
        .o_valid(M_REQ_tvalid), .o_ready(M_REQ_tready), .o_data(M_REQ_tdata));

    sb_link #(.W(528), .PIPE(PIPE), .CRED(CRED)) u_rsp (
        .clk(bus_clk), .rst(bus_rst),
        .i_valid(S_RSP_tvalid), .i_ready(S_RSP_tready), .i_data(S_RSP_tdata),
        .o_valid(M_RSP_tvalid), .o_ready(M_RSP_tready), .o_data(M_RSP_tdata));
endmodule

`default_nettype wire
