// sb_bd_line4 -- GENERATED by scripts/py/gen_station_wrap.py. Do not edit by hand.
//   gen_station_wrap.py --kind line4 --nq 4 --fw 256 --mgr-w 32,512,32 --mgr-lite 2 --loc-lite 2,3 --aw 43 -o src/synth_top/sb_v6_bus.v -m sb_bd_line4
//
// sb_line4 with every port named so a block design infers an interface:
// 3 AXI4 slaves, 16 AXI4 masters (4 per station), FW=256.

`default_nettype none

module sb_bd_line4 #(
    // Flit width is internal, so a block design may retune it without
    // regenerating this file; the AXI port widths below do not follow it.
    parameter integer FW           = 256,
    parameter integer OST          = 4,
    parameter integer STORE_FWD    = 1,
    parameter integer LUT_PER_BRAM = 0,
    parameter integer TIMEOUT      = 0,
    parameter integer LINK_CDC     = 1,
    parameter integer LINK_FULL    = 0,
    parameter integer CRED         = 16,
    parameter integer PIPE         = 4,
    // Per-station overrides; each defaults to the line-wide value above.
    parameter integer OST0 = OST, OST1 = OST, OST2 = OST, OST3 = OST,
    parameter integer SFW0 = STORE_FWD, SFW1 = STORE_FWD,
    parameter integer SFW2 = STORE_FWD, SFW3 = STORE_FWD,
    parameter integer LPB0 = LUT_PER_BRAM, LPB1 = LUT_PER_BRAM,
    parameter integer LPB2 = LUT_PER_BRAM, LPB3 = LUT_PER_BRAM,
    parameter integer TMO0 = TIMEOUT, TMO1 = TIMEOUT,
    parameter integer TMO2 = TIMEOUT, TMO3 = TIMEOUT,
    // Address map, handed to sb_line4. At 0 its uniform 64 KB map applies,
    // which cannot express the mesh's 1 TB S_AXI_MEM window.
    parameter integer DSTW_P       = 2,
    // SIZED literal: `0` types these as a long that cannot hold 688 bits
    // (19-3452), and `{N{1'b0}}` reads its default back quoted (19-594).
    parameter integer SEG_OVERRIDE = 0,
    parameter [16*43-1:0]   SEG_BASE_P  = 688'h0,
    parameter [16*43-1:0]   SEG_MASK_P  = 688'h0,
    parameter [16*43-1:0]   SEG_XLT_P   = 688'h0,
    parameter [16*2-1:0] SEG_DST_P   = 32'h0,
    parameter [16*2-1:0] SEG_DPORT_P = 32'h0,
    parameter [16-1:0]        SEG_VLD_P   = 16'hFFFF
)(
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 bus_clk0 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_RESET bus_rst0" *)
    input  wire bus_clk0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 bus_rst0 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_HIGH" *)
    input  wire bus_rst0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 bus_clk1 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_RESET bus_rst1" *)
    input  wire bus_clk1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 bus_rst1 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_HIGH" *)
    input  wire bus_rst1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 bus_clk2 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_RESET bus_rst2" *)
    input  wire bus_clk2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 bus_rst2 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_HIGH" *)
    input  wire bus_rst2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 bus_clk3 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_RESET bus_rst3" *)
    input  wire bus_clk3,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 bus_rst3 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_HIGH" *)
    input  wire bus_rst3,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_ctrl CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S00_AXI:M03_AXI:M07_AXI:M11_AXI:M15_AXI, ASSOCIATED_RESET aresetn_ctrl" *)
    input  wire clk_ctrl,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_ctrl RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_ctrl,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_xdma CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S01_AXI:S02_AXI, ASSOCIATED_RESET aresetn_xdma" *)
    input  wire clk_xdma,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_xdma RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_xdma,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_s0 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M00_AXI:M01_AXI, ASSOCIATED_RESET aresetn_s0" *)
    input  wire clk_s0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_s0 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_s0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_s1 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M04_AXI:M05_AXI, ASSOCIATED_RESET aresetn_s1" *)
    input  wire clk_s1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_s1 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_s1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_s2 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M08_AXI:M09_AXI, ASSOCIATED_RESET aresetn_s2" *)
    input  wire clk_s2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_s2 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_s2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_s3 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M12_AXI:M13_AXI, ASSOCIATED_RESET aresetn_s3" *)
    input  wire clk_s3,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_s3 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_s3,

    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_ddr0 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M02_AXI, ASSOCIATED_RESET aresetn_ddr0" *)
    input  wire clk_ddr0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_ddr0 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_ddr0,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_ddr1 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M06_AXI, ASSOCIATED_RESET aresetn_ddr1" *)
    input  wire clk_ddr1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_ddr1 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_ddr1,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_ddr2 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M10_AXI, ASSOCIATED_RESET aresetn_ddr2" *)
    input  wire clk_ddr2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_ddr2 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_ddr2,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_ddr3 CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF M14_AXI, ASSOCIATED_RESET aresetn_ddr3" *)
    input  wire clk_ddr3,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn_ddr3 RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire aresetn_ddr3,

    input  wire [4-1:0] S00_AXI_awid,
    input  wire [43-1:0] S00_AXI_awaddr,
    input  wire [8-1:0] S00_AXI_awlen,
    input  wire [3-1:0] S00_AXI_awsize,
    input  wire [2-1:0] S00_AXI_awburst,
    input  wire S00_AXI_awvalid,
    output wire S00_AXI_awready,
    input  wire [32-1:0] S00_AXI_wdata,
    input  wire [4-1:0] S00_AXI_wstrb,
    input  wire S00_AXI_wlast,
    input  wire S00_AXI_wvalid,
    output wire S00_AXI_wready,
    output wire [4-1:0] S00_AXI_bid,
    output wire [2-1:0] S00_AXI_bresp,
    output wire S00_AXI_bvalid,
    input  wire S00_AXI_bready,
    input  wire [4-1:0] S00_AXI_arid,
    input  wire [43-1:0] S00_AXI_araddr,
    input  wire [8-1:0] S00_AXI_arlen,
    input  wire [3-1:0] S00_AXI_arsize,
    input  wire [2-1:0] S00_AXI_arburst,
    input  wire S00_AXI_arvalid,
    output wire S00_AXI_arready,
    output wire [4-1:0] S00_AXI_rid,
    output wire [32-1:0] S00_AXI_rdata,
    output wire [2-1:0] S00_AXI_rresp,
    output wire S00_AXI_rlast,
    output wire S00_AXI_rvalid,
    input  wire S00_AXI_rready,

    input  wire [4-1:0] S01_AXI_awid,
    input  wire [43-1:0] S01_AXI_awaddr,
    input  wire [8-1:0] S01_AXI_awlen,
    input  wire [3-1:0] S01_AXI_awsize,
    input  wire [2-1:0] S01_AXI_awburst,
    input  wire S01_AXI_awvalid,
    output wire S01_AXI_awready,
    input  wire [512-1:0] S01_AXI_wdata,
    input  wire [64-1:0] S01_AXI_wstrb,
    input  wire S01_AXI_wlast,
    input  wire S01_AXI_wvalid,
    output wire S01_AXI_wready,
    output wire [4-1:0] S01_AXI_bid,
    output wire [2-1:0] S01_AXI_bresp,
    output wire S01_AXI_bvalid,
    input  wire S01_AXI_bready,
    input  wire [4-1:0] S01_AXI_arid,
    input  wire [43-1:0] S01_AXI_araddr,
    input  wire [8-1:0] S01_AXI_arlen,
    input  wire [3-1:0] S01_AXI_arsize,
    input  wire [2-1:0] S01_AXI_arburst,
    input  wire S01_AXI_arvalid,
    output wire S01_AXI_arready,
    output wire [4-1:0] S01_AXI_rid,
    output wire [512-1:0] S01_AXI_rdata,
    output wire [2-1:0] S01_AXI_rresp,
    output wire S01_AXI_rlast,
    output wire S01_AXI_rvalid,
    input  wire S01_AXI_rready,

    input  wire [43-1:0] S02_AXI_awaddr,
    input  wire S02_AXI_awvalid,
    output wire S02_AXI_awready,
    input  wire [32-1:0] S02_AXI_wdata,
    input  wire [4-1:0] S02_AXI_wstrb,
    input  wire S02_AXI_wvalid,
    output wire S02_AXI_wready,
    output wire [2-1:0] S02_AXI_bresp,
    output wire S02_AXI_bvalid,
    input  wire S02_AXI_bready,
    input  wire [43-1:0] S02_AXI_araddr,
    input  wire S02_AXI_arvalid,
    output wire S02_AXI_arready,
    output wire [32-1:0] S02_AXI_rdata,
    output wire [2-1:0] S02_AXI_rresp,
    output wire S02_AXI_rvalid,
    input  wire S02_AXI_rready,

    output wire [4-1:0] M00_AXI_awid,
    output wire [43-1:0] M00_AXI_awaddr,
    output wire [8-1:0] M00_AXI_awlen,
    output wire [3-1:0] M00_AXI_awsize,
    output wire [2-1:0] M00_AXI_awburst,
    output wire M00_AXI_awvalid,
    input  wire M00_AXI_awready,
    output wire [256-1:0] M00_AXI_wdata,
    output wire [32-1:0] M00_AXI_wstrb,
    output wire M00_AXI_wlast,
    output wire M00_AXI_wvalid,
    input  wire M00_AXI_wready,
    input  wire [4-1:0] M00_AXI_bid,
    input  wire [2-1:0] M00_AXI_bresp,
    input  wire M00_AXI_bvalid,
    output wire M00_AXI_bready,
    output wire [4-1:0] M00_AXI_arid,
    output wire [43-1:0] M00_AXI_araddr,
    output wire [8-1:0] M00_AXI_arlen,
    output wire [3-1:0] M00_AXI_arsize,
    output wire [2-1:0] M00_AXI_arburst,
    output wire M00_AXI_arvalid,
    input  wire M00_AXI_arready,
    input  wire [4-1:0] M00_AXI_rid,
    input  wire [256-1:0] M00_AXI_rdata,
    input  wire [2-1:0] M00_AXI_rresp,
    input  wire M00_AXI_rlast,
    input  wire M00_AXI_rvalid,
    output wire M00_AXI_rready,

    output wire [4-1:0] M01_AXI_awid,
    output wire [43-1:0] M01_AXI_awaddr,
    output wire [8-1:0] M01_AXI_awlen,
    output wire [3-1:0] M01_AXI_awsize,
    output wire [2-1:0] M01_AXI_awburst,
    output wire M01_AXI_awvalid,
    input  wire M01_AXI_awready,
    output wire [32-1:0] M01_AXI_wdata,
    output wire [4-1:0] M01_AXI_wstrb,
    output wire M01_AXI_wlast,
    output wire M01_AXI_wvalid,
    input  wire M01_AXI_wready,
    input  wire [4-1:0] M01_AXI_bid,
    input  wire [2-1:0] M01_AXI_bresp,
    input  wire M01_AXI_bvalid,
    output wire M01_AXI_bready,
    output wire [4-1:0] M01_AXI_arid,
    output wire [43-1:0] M01_AXI_araddr,
    output wire [8-1:0] M01_AXI_arlen,
    output wire [3-1:0] M01_AXI_arsize,
    output wire [2-1:0] M01_AXI_arburst,
    output wire M01_AXI_arvalid,
    input  wire M01_AXI_arready,
    input  wire [4-1:0] M01_AXI_rid,
    input  wire [32-1:0] M01_AXI_rdata,
    input  wire [2-1:0] M01_AXI_rresp,
    input  wire M01_AXI_rlast,
    input  wire M01_AXI_rvalid,
    output wire M01_AXI_rready,

    output wire [43-1:0] M02_AXI_awaddr,
    output wire M02_AXI_awvalid,
    input  wire M02_AXI_awready,
    output wire [32-1:0] M02_AXI_wdata,
    output wire [4-1:0] M02_AXI_wstrb,
    output wire M02_AXI_wvalid,
    input  wire M02_AXI_wready,
    input  wire [2-1:0] M02_AXI_bresp,
    input  wire M02_AXI_bvalid,
    output wire M02_AXI_bready,
    output wire [43-1:0] M02_AXI_araddr,
    output wire M02_AXI_arvalid,
    input  wire M02_AXI_arready,
    input  wire [32-1:0] M02_AXI_rdata,
    input  wire [2-1:0] M02_AXI_rresp,
    input  wire M02_AXI_rvalid,
    output wire M02_AXI_rready,

    output wire [43-1:0] M03_AXI_awaddr,
    output wire M03_AXI_awvalid,
    input  wire M03_AXI_awready,
    output wire [32-1:0] M03_AXI_wdata,
    output wire [4-1:0] M03_AXI_wstrb,
    output wire M03_AXI_wvalid,
    input  wire M03_AXI_wready,
    input  wire [2-1:0] M03_AXI_bresp,
    input  wire M03_AXI_bvalid,
    output wire M03_AXI_bready,
    output wire [43-1:0] M03_AXI_araddr,
    output wire M03_AXI_arvalid,
    input  wire M03_AXI_arready,
    input  wire [32-1:0] M03_AXI_rdata,
    input  wire [2-1:0] M03_AXI_rresp,
    input  wire M03_AXI_rvalid,
    output wire M03_AXI_rready,

    output wire [4-1:0] M04_AXI_awid,
    output wire [43-1:0] M04_AXI_awaddr,
    output wire [8-1:0] M04_AXI_awlen,
    output wire [3-1:0] M04_AXI_awsize,
    output wire [2-1:0] M04_AXI_awburst,
    output wire M04_AXI_awvalid,
    input  wire M04_AXI_awready,
    output wire [256-1:0] M04_AXI_wdata,
    output wire [32-1:0] M04_AXI_wstrb,
    output wire M04_AXI_wlast,
    output wire M04_AXI_wvalid,
    input  wire M04_AXI_wready,
    input  wire [4-1:0] M04_AXI_bid,
    input  wire [2-1:0] M04_AXI_bresp,
    input  wire M04_AXI_bvalid,
    output wire M04_AXI_bready,
    output wire [4-1:0] M04_AXI_arid,
    output wire [43-1:0] M04_AXI_araddr,
    output wire [8-1:0] M04_AXI_arlen,
    output wire [3-1:0] M04_AXI_arsize,
    output wire [2-1:0] M04_AXI_arburst,
    output wire M04_AXI_arvalid,
    input  wire M04_AXI_arready,
    input  wire [4-1:0] M04_AXI_rid,
    input  wire [256-1:0] M04_AXI_rdata,
    input  wire [2-1:0] M04_AXI_rresp,
    input  wire M04_AXI_rlast,
    input  wire M04_AXI_rvalid,
    output wire M04_AXI_rready,

    output wire [4-1:0] M05_AXI_awid,
    output wire [43-1:0] M05_AXI_awaddr,
    output wire [8-1:0] M05_AXI_awlen,
    output wire [3-1:0] M05_AXI_awsize,
    output wire [2-1:0] M05_AXI_awburst,
    output wire M05_AXI_awvalid,
    input  wire M05_AXI_awready,
    output wire [32-1:0] M05_AXI_wdata,
    output wire [4-1:0] M05_AXI_wstrb,
    output wire M05_AXI_wlast,
    output wire M05_AXI_wvalid,
    input  wire M05_AXI_wready,
    input  wire [4-1:0] M05_AXI_bid,
    input  wire [2-1:0] M05_AXI_bresp,
    input  wire M05_AXI_bvalid,
    output wire M05_AXI_bready,
    output wire [4-1:0] M05_AXI_arid,
    output wire [43-1:0] M05_AXI_araddr,
    output wire [8-1:0] M05_AXI_arlen,
    output wire [3-1:0] M05_AXI_arsize,
    output wire [2-1:0] M05_AXI_arburst,
    output wire M05_AXI_arvalid,
    input  wire M05_AXI_arready,
    input  wire [4-1:0] M05_AXI_rid,
    input  wire [32-1:0] M05_AXI_rdata,
    input  wire [2-1:0] M05_AXI_rresp,
    input  wire M05_AXI_rlast,
    input  wire M05_AXI_rvalid,
    output wire M05_AXI_rready,

    output wire [43-1:0] M06_AXI_awaddr,
    output wire M06_AXI_awvalid,
    input  wire M06_AXI_awready,
    output wire [32-1:0] M06_AXI_wdata,
    output wire [4-1:0] M06_AXI_wstrb,
    output wire M06_AXI_wvalid,
    input  wire M06_AXI_wready,
    input  wire [2-1:0] M06_AXI_bresp,
    input  wire M06_AXI_bvalid,
    output wire M06_AXI_bready,
    output wire [43-1:0] M06_AXI_araddr,
    output wire M06_AXI_arvalid,
    input  wire M06_AXI_arready,
    input  wire [32-1:0] M06_AXI_rdata,
    input  wire [2-1:0] M06_AXI_rresp,
    input  wire M06_AXI_rvalid,
    output wire M06_AXI_rready,

    output wire [43-1:0] M07_AXI_awaddr,
    output wire M07_AXI_awvalid,
    input  wire M07_AXI_awready,
    output wire [32-1:0] M07_AXI_wdata,
    output wire [4-1:0] M07_AXI_wstrb,
    output wire M07_AXI_wvalid,
    input  wire M07_AXI_wready,
    input  wire [2-1:0] M07_AXI_bresp,
    input  wire M07_AXI_bvalid,
    output wire M07_AXI_bready,
    output wire [43-1:0] M07_AXI_araddr,
    output wire M07_AXI_arvalid,
    input  wire M07_AXI_arready,
    input  wire [32-1:0] M07_AXI_rdata,
    input  wire [2-1:0] M07_AXI_rresp,
    input  wire M07_AXI_rvalid,
    output wire M07_AXI_rready,

    output wire [4-1:0] M08_AXI_awid,
    output wire [43-1:0] M08_AXI_awaddr,
    output wire [8-1:0] M08_AXI_awlen,
    output wire [3-1:0] M08_AXI_awsize,
    output wire [2-1:0] M08_AXI_awburst,
    output wire M08_AXI_awvalid,
    input  wire M08_AXI_awready,
    output wire [256-1:0] M08_AXI_wdata,
    output wire [32-1:0] M08_AXI_wstrb,
    output wire M08_AXI_wlast,
    output wire M08_AXI_wvalid,
    input  wire M08_AXI_wready,
    input  wire [4-1:0] M08_AXI_bid,
    input  wire [2-1:0] M08_AXI_bresp,
    input  wire M08_AXI_bvalid,
    output wire M08_AXI_bready,
    output wire [4-1:0] M08_AXI_arid,
    output wire [43-1:0] M08_AXI_araddr,
    output wire [8-1:0] M08_AXI_arlen,
    output wire [3-1:0] M08_AXI_arsize,
    output wire [2-1:0] M08_AXI_arburst,
    output wire M08_AXI_arvalid,
    input  wire M08_AXI_arready,
    input  wire [4-1:0] M08_AXI_rid,
    input  wire [256-1:0] M08_AXI_rdata,
    input  wire [2-1:0] M08_AXI_rresp,
    input  wire M08_AXI_rlast,
    input  wire M08_AXI_rvalid,
    output wire M08_AXI_rready,

    output wire [4-1:0] M09_AXI_awid,
    output wire [43-1:0] M09_AXI_awaddr,
    output wire [8-1:0] M09_AXI_awlen,
    output wire [3-1:0] M09_AXI_awsize,
    output wire [2-1:0] M09_AXI_awburst,
    output wire M09_AXI_awvalid,
    input  wire M09_AXI_awready,
    output wire [32-1:0] M09_AXI_wdata,
    output wire [4-1:0] M09_AXI_wstrb,
    output wire M09_AXI_wlast,
    output wire M09_AXI_wvalid,
    input  wire M09_AXI_wready,
    input  wire [4-1:0] M09_AXI_bid,
    input  wire [2-1:0] M09_AXI_bresp,
    input  wire M09_AXI_bvalid,
    output wire M09_AXI_bready,
    output wire [4-1:0] M09_AXI_arid,
    output wire [43-1:0] M09_AXI_araddr,
    output wire [8-1:0] M09_AXI_arlen,
    output wire [3-1:0] M09_AXI_arsize,
    output wire [2-1:0] M09_AXI_arburst,
    output wire M09_AXI_arvalid,
    input  wire M09_AXI_arready,
    input  wire [4-1:0] M09_AXI_rid,
    input  wire [32-1:0] M09_AXI_rdata,
    input  wire [2-1:0] M09_AXI_rresp,
    input  wire M09_AXI_rlast,
    input  wire M09_AXI_rvalid,
    output wire M09_AXI_rready,

    output wire [43-1:0] M10_AXI_awaddr,
    output wire M10_AXI_awvalid,
    input  wire M10_AXI_awready,
    output wire [32-1:0] M10_AXI_wdata,
    output wire [4-1:0] M10_AXI_wstrb,
    output wire M10_AXI_wvalid,
    input  wire M10_AXI_wready,
    input  wire [2-1:0] M10_AXI_bresp,
    input  wire M10_AXI_bvalid,
    output wire M10_AXI_bready,
    output wire [43-1:0] M10_AXI_araddr,
    output wire M10_AXI_arvalid,
    input  wire M10_AXI_arready,
    input  wire [32-1:0] M10_AXI_rdata,
    input  wire [2-1:0] M10_AXI_rresp,
    input  wire M10_AXI_rvalid,
    output wire M10_AXI_rready,

    output wire [43-1:0] M11_AXI_awaddr,
    output wire M11_AXI_awvalid,
    input  wire M11_AXI_awready,
    output wire [32-1:0] M11_AXI_wdata,
    output wire [4-1:0] M11_AXI_wstrb,
    output wire M11_AXI_wvalid,
    input  wire M11_AXI_wready,
    input  wire [2-1:0] M11_AXI_bresp,
    input  wire M11_AXI_bvalid,
    output wire M11_AXI_bready,
    output wire [43-1:0] M11_AXI_araddr,
    output wire M11_AXI_arvalid,
    input  wire M11_AXI_arready,
    input  wire [32-1:0] M11_AXI_rdata,
    input  wire [2-1:0] M11_AXI_rresp,
    input  wire M11_AXI_rvalid,
    output wire M11_AXI_rready,

    output wire [4-1:0] M12_AXI_awid,
    output wire [43-1:0] M12_AXI_awaddr,
    output wire [8-1:0] M12_AXI_awlen,
    output wire [3-1:0] M12_AXI_awsize,
    output wire [2-1:0] M12_AXI_awburst,
    output wire M12_AXI_awvalid,
    input  wire M12_AXI_awready,
    output wire [256-1:0] M12_AXI_wdata,
    output wire [32-1:0] M12_AXI_wstrb,
    output wire M12_AXI_wlast,
    output wire M12_AXI_wvalid,
    input  wire M12_AXI_wready,
    input  wire [4-1:0] M12_AXI_bid,
    input  wire [2-1:0] M12_AXI_bresp,
    input  wire M12_AXI_bvalid,
    output wire M12_AXI_bready,
    output wire [4-1:0] M12_AXI_arid,
    output wire [43-1:0] M12_AXI_araddr,
    output wire [8-1:0] M12_AXI_arlen,
    output wire [3-1:0] M12_AXI_arsize,
    output wire [2-1:0] M12_AXI_arburst,
    output wire M12_AXI_arvalid,
    input  wire M12_AXI_arready,
    input  wire [4-1:0] M12_AXI_rid,
    input  wire [256-1:0] M12_AXI_rdata,
    input  wire [2-1:0] M12_AXI_rresp,
    input  wire M12_AXI_rlast,
    input  wire M12_AXI_rvalid,
    output wire M12_AXI_rready,

    output wire [4-1:0] M13_AXI_awid,
    output wire [43-1:0] M13_AXI_awaddr,
    output wire [8-1:0] M13_AXI_awlen,
    output wire [3-1:0] M13_AXI_awsize,
    output wire [2-1:0] M13_AXI_awburst,
    output wire M13_AXI_awvalid,
    input  wire M13_AXI_awready,
    output wire [32-1:0] M13_AXI_wdata,
    output wire [4-1:0] M13_AXI_wstrb,
    output wire M13_AXI_wlast,
    output wire M13_AXI_wvalid,
    input  wire M13_AXI_wready,
    input  wire [4-1:0] M13_AXI_bid,
    input  wire [2-1:0] M13_AXI_bresp,
    input  wire M13_AXI_bvalid,
    output wire M13_AXI_bready,
    output wire [4-1:0] M13_AXI_arid,
    output wire [43-1:0] M13_AXI_araddr,
    output wire [8-1:0] M13_AXI_arlen,
    output wire [3-1:0] M13_AXI_arsize,
    output wire [2-1:0] M13_AXI_arburst,
    output wire M13_AXI_arvalid,
    input  wire M13_AXI_arready,
    input  wire [4-1:0] M13_AXI_rid,
    input  wire [32-1:0] M13_AXI_rdata,
    input  wire [2-1:0] M13_AXI_rresp,
    input  wire M13_AXI_rlast,
    input  wire M13_AXI_rvalid,
    output wire M13_AXI_rready,

    output wire [43-1:0] M14_AXI_awaddr,
    output wire M14_AXI_awvalid,
    input  wire M14_AXI_awready,
    output wire [32-1:0] M14_AXI_wdata,
    output wire [4-1:0] M14_AXI_wstrb,
    output wire M14_AXI_wvalid,
    input  wire M14_AXI_wready,
    input  wire [2-1:0] M14_AXI_bresp,
    input  wire M14_AXI_bvalid,
    output wire M14_AXI_bready,
    output wire [43-1:0] M14_AXI_araddr,
    output wire M14_AXI_arvalid,
    input  wire M14_AXI_arready,
    input  wire [32-1:0] M14_AXI_rdata,
    input  wire [2-1:0] M14_AXI_rresp,
    input  wire M14_AXI_rvalid,
    output wire M14_AXI_rready,

    output wire [43-1:0] M15_AXI_awaddr,
    output wire M15_AXI_awvalid,
    input  wire M15_AXI_awready,
    output wire [32-1:0] M15_AXI_wdata,
    output wire [4-1:0] M15_AXI_wstrb,
    output wire M15_AXI_wvalid,
    input  wire M15_AXI_wready,
    input  wire [2-1:0] M15_AXI_bresp,
    input  wire M15_AXI_bvalid,
    output wire M15_AXI_bready,
    output wire [43-1:0] M15_AXI_araddr,
    output wire M15_AXI_arvalid,
    input  wire M15_AXI_arready,
    input  wire [32-1:0] M15_AXI_rdata,
    input  wire [2-1:0] M15_AXI_rresp,
    input  wire M15_AXI_rvalid,
    output wire M15_AXI_rready,

    output wire [31:0] stat_decerr
);
    localparam integer NM    = 3;
    localparam integer NS    = 16;
    localparam integer AW    = 43;
    localparam integer MAXW  = 512;
    localparam integer MAXID = 4;

    wire [NM*MAXID-1:0]    mp_awid, mp_arid, mp_bid, mp_rid;
    wire [NM*AW-1:0]       mp_awaddr, mp_araddr;
    wire [NM*8-1:0]        mp_awlen, mp_arlen;
    wire [NM*3-1:0]        mp_awsize, mp_arsize;
    wire [NM*2-1:0]        mp_awburst, mp_arburst, mp_bresp, mp_rresp;
    wire [NM-1:0]          mp_awvalid, mp_awready, mp_wvalid, mp_wready;
    wire [NM-1:0]          mp_wlast, mp_bvalid, mp_bready;
    wire [NM-1:0]          mp_arvalid, mp_arready, mp_rvalid, mp_rready, mp_rlast;
    wire [NM*MAXW-1:0]     mp_wdata, mp_rdata;
    wire [NM*(MAXW/8)-1:0] mp_wstrb;

    wire [NS*MAXID-1:0]    sp_awid, sp_arid, sp_bid, sp_rid;
    wire [NS*AW-1:0]       sp_awaddr, sp_araddr;
    wire [NS*8-1:0]        sp_awlen, sp_arlen;
    wire [NS*3-1:0]        sp_awsize, sp_arsize;
    wire [NS*2-1:0]        sp_awburst, sp_arburst, sp_bresp, sp_rresp;
    wire [NS-1:0]          sp_awvalid, sp_awready, sp_wvalid, sp_wready;
    wire [NS-1:0]          sp_wlast, sp_bvalid, sp_bready;
    wire [NS-1:0]          sp_arvalid, sp_arready, sp_rvalid, sp_rready, sp_rlast;
    wire [NS*MAXW-1:0]     sp_wdata, sp_rdata;
    wire [NS*(MAXW/8)-1:0] sp_wstrb;

    assign mp_awid[0*4 +: 4] = S00_AXI_awid;
    assign mp_awaddr[0*43 +: 43] = S00_AXI_awaddr;
    assign mp_awlen[0*8 +: 8] = S00_AXI_awlen;
    assign mp_awsize[0*3 +: 3] = S00_AXI_awsize;
    assign mp_awburst[0*2 +: 2] = S00_AXI_awburst;
    assign mp_awvalid[0] = S00_AXI_awvalid;
    assign S00_AXI_awready = mp_awready[0];
    assign mp_wdata[0*512 +: 32] = S00_AXI_wdata;
    assign mp_wstrb[0*64 +: 4] = S00_AXI_wstrb;
    assign mp_wlast[0] = S00_AXI_wlast;
    assign mp_wvalid[0] = S00_AXI_wvalid;
    assign S00_AXI_wready = mp_wready[0];
    assign S00_AXI_bid = mp_bid[0*4 +: 4];
    assign S00_AXI_bresp = mp_bresp[0*2 +: 2];
    assign S00_AXI_bvalid = mp_bvalid[0];
    assign mp_bready[0] = S00_AXI_bready;
    assign mp_arid[0*4 +: 4] = S00_AXI_arid;
    assign mp_araddr[0*43 +: 43] = S00_AXI_araddr;
    assign mp_arlen[0*8 +: 8] = S00_AXI_arlen;
    assign mp_arsize[0*3 +: 3] = S00_AXI_arsize;
    assign mp_arburst[0*2 +: 2] = S00_AXI_arburst;
    assign mp_arvalid[0] = S00_AXI_arvalid;
    assign S00_AXI_arready = mp_arready[0];
    assign S00_AXI_rid = mp_rid[0*4 +: 4];
    assign S00_AXI_rdata = mp_rdata[0*512 +: 32];
    assign S00_AXI_rresp = mp_rresp[0*2 +: 2];
    assign S00_AXI_rlast = mp_rlast[0];
    assign S00_AXI_rvalid = mp_rvalid[0];
    assign mp_rready[0] = S00_AXI_rready;

    assign mp_awid[1*4 +: 4] = S01_AXI_awid;
    assign mp_awaddr[1*43 +: 43] = S01_AXI_awaddr;
    assign mp_awlen[1*8 +: 8] = S01_AXI_awlen;
    assign mp_awsize[1*3 +: 3] = S01_AXI_awsize;
    assign mp_awburst[1*2 +: 2] = S01_AXI_awburst;
    assign mp_awvalid[1] = S01_AXI_awvalid;
    assign S01_AXI_awready = mp_awready[1];
    assign mp_wdata[1*512 +: 512] = S01_AXI_wdata;
    assign mp_wstrb[1*64 +: 64] = S01_AXI_wstrb;
    assign mp_wlast[1] = S01_AXI_wlast;
    assign mp_wvalid[1] = S01_AXI_wvalid;
    assign S01_AXI_wready = mp_wready[1];
    assign S01_AXI_bid = mp_bid[1*4 +: 4];
    assign S01_AXI_bresp = mp_bresp[1*2 +: 2];
    assign S01_AXI_bvalid = mp_bvalid[1];
    assign mp_bready[1] = S01_AXI_bready;
    assign mp_arid[1*4 +: 4] = S01_AXI_arid;
    assign mp_araddr[1*43 +: 43] = S01_AXI_araddr;
    assign mp_arlen[1*8 +: 8] = S01_AXI_arlen;
    assign mp_arsize[1*3 +: 3] = S01_AXI_arsize;
    assign mp_arburst[1*2 +: 2] = S01_AXI_arburst;
    assign mp_arvalid[1] = S01_AXI_arvalid;
    assign S01_AXI_arready = mp_arready[1];
    assign S01_AXI_rid = mp_rid[1*4 +: 4];
    assign S01_AXI_rdata = mp_rdata[1*512 +: 512];
    assign S01_AXI_rresp = mp_rresp[1*2 +: 2];
    assign S01_AXI_rlast = mp_rlast[1];
    assign S01_AXI_rvalid = mp_rvalid[1];
    assign mp_rready[1] = S01_AXI_rready;

    assign mp_awid[2*4 +: 4] = 4'd0;
    assign mp_awaddr[2*43 +: 43] = S02_AXI_awaddr;
    assign mp_awlen[2*8 +: 8] = 8'd0;
    assign mp_awsize[2*3 +: 3] = 3'd2;
    assign mp_awburst[2*2 +: 2] = 2'b01;
    assign mp_awvalid[2] = S02_AXI_awvalid;
    assign S02_AXI_awready = mp_awready[2];
    assign mp_wdata[2*512 +: 32] = S02_AXI_wdata;
    assign mp_wstrb[2*64 +: 4] = S02_AXI_wstrb;
    assign mp_wlast[2] = 1'b1;
    assign mp_wvalid[2] = S02_AXI_wvalid;
    assign S02_AXI_wready = mp_wready[2];
    assign S02_AXI_bresp = mp_bresp[2*2 +: 2];
    assign S02_AXI_bvalid = mp_bvalid[2];
    assign mp_bready[2] = S02_AXI_bready;
    assign mp_arid[2*4 +: 4] = 4'd0;
    assign mp_araddr[2*43 +: 43] = S02_AXI_araddr;
    assign mp_arlen[2*8 +: 8] = 8'd0;
    assign mp_arsize[2*3 +: 3] = 3'd2;
    assign mp_arburst[2*2 +: 2] = 2'b01;
    assign mp_arvalid[2] = S02_AXI_arvalid;
    assign S02_AXI_arready = mp_arready[2];
    assign S02_AXI_rdata = mp_rdata[2*512 +: 32];
    assign S02_AXI_rresp = mp_rresp[2*2 +: 2];
    assign S02_AXI_rvalid = mp_rvalid[2];
    assign mp_rready[2] = S02_AXI_rready;

    assign M00_AXI_awid = sp_awid[0*4 +: 4];
    assign M00_AXI_awaddr = sp_awaddr[0*43 +: 43];
    assign M00_AXI_awlen = sp_awlen[0*8 +: 8];
    assign M00_AXI_awsize = sp_awsize[0*3 +: 3];
    assign M00_AXI_awburst = sp_awburst[0*2 +: 2];
    assign M00_AXI_awvalid = sp_awvalid[0];
    assign sp_awready[0] = M00_AXI_awready;
    assign M00_AXI_wdata = sp_wdata[0*512 +: 256];
    assign M00_AXI_wstrb = sp_wstrb[0*64 +: 32];
    assign M00_AXI_wlast = sp_wlast[0];
    assign M00_AXI_wvalid = sp_wvalid[0];
    assign sp_wready[0] = M00_AXI_wready;
    assign sp_bid[0*4 +: 4] = M00_AXI_bid;
    assign sp_bresp[0*2 +: 2] = M00_AXI_bresp;
    assign sp_bvalid[0] = M00_AXI_bvalid;
    assign M00_AXI_bready = sp_bready[0];
    assign M00_AXI_arid = sp_arid[0*4 +: 4];
    assign M00_AXI_araddr = sp_araddr[0*43 +: 43];
    assign M00_AXI_arlen = sp_arlen[0*8 +: 8];
    assign M00_AXI_arsize = sp_arsize[0*3 +: 3];
    assign M00_AXI_arburst = sp_arburst[0*2 +: 2];
    assign M00_AXI_arvalid = sp_arvalid[0];
    assign sp_arready[0] = M00_AXI_arready;
    assign sp_rid[0*4 +: 4] = M00_AXI_rid;
    assign sp_rdata[0*512 +: 256] = M00_AXI_rdata;
    assign sp_rresp[0*2 +: 2] = M00_AXI_rresp;
    assign sp_rlast[0] = M00_AXI_rlast;
    assign sp_rvalid[0] = M00_AXI_rvalid;
    assign M00_AXI_rready = sp_rready[0];

    assign M01_AXI_awid = sp_awid[1*4 +: 4];
    assign M01_AXI_awaddr = sp_awaddr[1*43 +: 43];
    assign M01_AXI_awlen = sp_awlen[1*8 +: 8];
    assign M01_AXI_awsize = sp_awsize[1*3 +: 3];
    assign M01_AXI_awburst = sp_awburst[1*2 +: 2];
    assign M01_AXI_awvalid = sp_awvalid[1];
    assign sp_awready[1] = M01_AXI_awready;
    assign M01_AXI_wdata = sp_wdata[1*512 +: 32];
    assign M01_AXI_wstrb = sp_wstrb[1*64 +: 4];
    assign M01_AXI_wlast = sp_wlast[1];
    assign M01_AXI_wvalid = sp_wvalid[1];
    assign sp_wready[1] = M01_AXI_wready;
    assign sp_bid[1*4 +: 4] = M01_AXI_bid;
    assign sp_bresp[1*2 +: 2] = M01_AXI_bresp;
    assign sp_bvalid[1] = M01_AXI_bvalid;
    assign M01_AXI_bready = sp_bready[1];
    assign M01_AXI_arid = sp_arid[1*4 +: 4];
    assign M01_AXI_araddr = sp_araddr[1*43 +: 43];
    assign M01_AXI_arlen = sp_arlen[1*8 +: 8];
    assign M01_AXI_arsize = sp_arsize[1*3 +: 3];
    assign M01_AXI_arburst = sp_arburst[1*2 +: 2];
    assign M01_AXI_arvalid = sp_arvalid[1];
    assign sp_arready[1] = M01_AXI_arready;
    assign sp_rid[1*4 +: 4] = M01_AXI_rid;
    assign sp_rdata[1*512 +: 32] = M01_AXI_rdata;
    assign sp_rresp[1*2 +: 2] = M01_AXI_rresp;
    assign sp_rlast[1] = M01_AXI_rlast;
    assign sp_rvalid[1] = M01_AXI_rvalid;
    assign M01_AXI_rready = sp_rready[1];

    assign M02_AXI_awaddr = sp_awaddr[2*43 +: 43];
    assign M02_AXI_awvalid = sp_awvalid[2];
    assign sp_awready[2] = M02_AXI_awready;
    assign M02_AXI_wdata = sp_wdata[2*512 +: 32];
    assign M02_AXI_wstrb = sp_wstrb[2*64 +: 4];
    assign M02_AXI_wvalid = sp_wvalid[2];
    assign sp_wready[2] = M02_AXI_wready;
    assign sp_bid[2*4 +: 4] = 4'd0;
    assign sp_bresp[2*2 +: 2] = M02_AXI_bresp;
    assign sp_bvalid[2] = M02_AXI_bvalid;
    assign M02_AXI_bready = sp_bready[2];
    assign M02_AXI_araddr = sp_araddr[2*43 +: 43];
    assign M02_AXI_arvalid = sp_arvalid[2];
    assign sp_arready[2] = M02_AXI_arready;
    assign sp_rid[2*4 +: 4] = 4'd0;
    assign sp_rdata[2*512 +: 32] = M02_AXI_rdata;
    assign sp_rresp[2*2 +: 2] = M02_AXI_rresp;
    assign sp_rlast[2] = 1'b1;
    assign sp_rvalid[2] = M02_AXI_rvalid;
    assign M02_AXI_rready = sp_rready[2];

    assign M03_AXI_awaddr = sp_awaddr[3*43 +: 43];
    assign M03_AXI_awvalid = sp_awvalid[3];
    assign sp_awready[3] = M03_AXI_awready;
    assign M03_AXI_wdata = sp_wdata[3*512 +: 32];
    assign M03_AXI_wstrb = sp_wstrb[3*64 +: 4];
    assign M03_AXI_wvalid = sp_wvalid[3];
    assign sp_wready[3] = M03_AXI_wready;
    assign sp_bid[3*4 +: 4] = 4'd0;
    assign sp_bresp[3*2 +: 2] = M03_AXI_bresp;
    assign sp_bvalid[3] = M03_AXI_bvalid;
    assign M03_AXI_bready = sp_bready[3];
    assign M03_AXI_araddr = sp_araddr[3*43 +: 43];
    assign M03_AXI_arvalid = sp_arvalid[3];
    assign sp_arready[3] = M03_AXI_arready;
    assign sp_rid[3*4 +: 4] = 4'd0;
    assign sp_rdata[3*512 +: 32] = M03_AXI_rdata;
    assign sp_rresp[3*2 +: 2] = M03_AXI_rresp;
    assign sp_rlast[3] = 1'b1;
    assign sp_rvalid[3] = M03_AXI_rvalid;
    assign M03_AXI_rready = sp_rready[3];

    assign M04_AXI_awid = sp_awid[4*4 +: 4];
    assign M04_AXI_awaddr = sp_awaddr[4*43 +: 43];
    assign M04_AXI_awlen = sp_awlen[4*8 +: 8];
    assign M04_AXI_awsize = sp_awsize[4*3 +: 3];
    assign M04_AXI_awburst = sp_awburst[4*2 +: 2];
    assign M04_AXI_awvalid = sp_awvalid[4];
    assign sp_awready[4] = M04_AXI_awready;
    assign M04_AXI_wdata = sp_wdata[4*512 +: 256];
    assign M04_AXI_wstrb = sp_wstrb[4*64 +: 32];
    assign M04_AXI_wlast = sp_wlast[4];
    assign M04_AXI_wvalid = sp_wvalid[4];
    assign sp_wready[4] = M04_AXI_wready;
    assign sp_bid[4*4 +: 4] = M04_AXI_bid;
    assign sp_bresp[4*2 +: 2] = M04_AXI_bresp;
    assign sp_bvalid[4] = M04_AXI_bvalid;
    assign M04_AXI_bready = sp_bready[4];
    assign M04_AXI_arid = sp_arid[4*4 +: 4];
    assign M04_AXI_araddr = sp_araddr[4*43 +: 43];
    assign M04_AXI_arlen = sp_arlen[4*8 +: 8];
    assign M04_AXI_arsize = sp_arsize[4*3 +: 3];
    assign M04_AXI_arburst = sp_arburst[4*2 +: 2];
    assign M04_AXI_arvalid = sp_arvalid[4];
    assign sp_arready[4] = M04_AXI_arready;
    assign sp_rid[4*4 +: 4] = M04_AXI_rid;
    assign sp_rdata[4*512 +: 256] = M04_AXI_rdata;
    assign sp_rresp[4*2 +: 2] = M04_AXI_rresp;
    assign sp_rlast[4] = M04_AXI_rlast;
    assign sp_rvalid[4] = M04_AXI_rvalid;
    assign M04_AXI_rready = sp_rready[4];

    assign M05_AXI_awid = sp_awid[5*4 +: 4];
    assign M05_AXI_awaddr = sp_awaddr[5*43 +: 43];
    assign M05_AXI_awlen = sp_awlen[5*8 +: 8];
    assign M05_AXI_awsize = sp_awsize[5*3 +: 3];
    assign M05_AXI_awburst = sp_awburst[5*2 +: 2];
    assign M05_AXI_awvalid = sp_awvalid[5];
    assign sp_awready[5] = M05_AXI_awready;
    assign M05_AXI_wdata = sp_wdata[5*512 +: 32];
    assign M05_AXI_wstrb = sp_wstrb[5*64 +: 4];
    assign M05_AXI_wlast = sp_wlast[5];
    assign M05_AXI_wvalid = sp_wvalid[5];
    assign sp_wready[5] = M05_AXI_wready;
    assign sp_bid[5*4 +: 4] = M05_AXI_bid;
    assign sp_bresp[5*2 +: 2] = M05_AXI_bresp;
    assign sp_bvalid[5] = M05_AXI_bvalid;
    assign M05_AXI_bready = sp_bready[5];
    assign M05_AXI_arid = sp_arid[5*4 +: 4];
    assign M05_AXI_araddr = sp_araddr[5*43 +: 43];
    assign M05_AXI_arlen = sp_arlen[5*8 +: 8];
    assign M05_AXI_arsize = sp_arsize[5*3 +: 3];
    assign M05_AXI_arburst = sp_arburst[5*2 +: 2];
    assign M05_AXI_arvalid = sp_arvalid[5];
    assign sp_arready[5] = M05_AXI_arready;
    assign sp_rid[5*4 +: 4] = M05_AXI_rid;
    assign sp_rdata[5*512 +: 32] = M05_AXI_rdata;
    assign sp_rresp[5*2 +: 2] = M05_AXI_rresp;
    assign sp_rlast[5] = M05_AXI_rlast;
    assign sp_rvalid[5] = M05_AXI_rvalid;
    assign M05_AXI_rready = sp_rready[5];

    assign M06_AXI_awaddr = sp_awaddr[6*43 +: 43];
    assign M06_AXI_awvalid = sp_awvalid[6];
    assign sp_awready[6] = M06_AXI_awready;
    assign M06_AXI_wdata = sp_wdata[6*512 +: 32];
    assign M06_AXI_wstrb = sp_wstrb[6*64 +: 4];
    assign M06_AXI_wvalid = sp_wvalid[6];
    assign sp_wready[6] = M06_AXI_wready;
    assign sp_bid[6*4 +: 4] = 4'd0;
    assign sp_bresp[6*2 +: 2] = M06_AXI_bresp;
    assign sp_bvalid[6] = M06_AXI_bvalid;
    assign M06_AXI_bready = sp_bready[6];
    assign M06_AXI_araddr = sp_araddr[6*43 +: 43];
    assign M06_AXI_arvalid = sp_arvalid[6];
    assign sp_arready[6] = M06_AXI_arready;
    assign sp_rid[6*4 +: 4] = 4'd0;
    assign sp_rdata[6*512 +: 32] = M06_AXI_rdata;
    assign sp_rresp[6*2 +: 2] = M06_AXI_rresp;
    assign sp_rlast[6] = 1'b1;
    assign sp_rvalid[6] = M06_AXI_rvalid;
    assign M06_AXI_rready = sp_rready[6];

    assign M07_AXI_awaddr = sp_awaddr[7*43 +: 43];
    assign M07_AXI_awvalid = sp_awvalid[7];
    assign sp_awready[7] = M07_AXI_awready;
    assign M07_AXI_wdata = sp_wdata[7*512 +: 32];
    assign M07_AXI_wstrb = sp_wstrb[7*64 +: 4];
    assign M07_AXI_wvalid = sp_wvalid[7];
    assign sp_wready[7] = M07_AXI_wready;
    assign sp_bid[7*4 +: 4] = 4'd0;
    assign sp_bresp[7*2 +: 2] = M07_AXI_bresp;
    assign sp_bvalid[7] = M07_AXI_bvalid;
    assign M07_AXI_bready = sp_bready[7];
    assign M07_AXI_araddr = sp_araddr[7*43 +: 43];
    assign M07_AXI_arvalid = sp_arvalid[7];
    assign sp_arready[7] = M07_AXI_arready;
    assign sp_rid[7*4 +: 4] = 4'd0;
    assign sp_rdata[7*512 +: 32] = M07_AXI_rdata;
    assign sp_rresp[7*2 +: 2] = M07_AXI_rresp;
    assign sp_rlast[7] = 1'b1;
    assign sp_rvalid[7] = M07_AXI_rvalid;
    assign M07_AXI_rready = sp_rready[7];

    assign M08_AXI_awid = sp_awid[8*4 +: 4];
    assign M08_AXI_awaddr = sp_awaddr[8*43 +: 43];
    assign M08_AXI_awlen = sp_awlen[8*8 +: 8];
    assign M08_AXI_awsize = sp_awsize[8*3 +: 3];
    assign M08_AXI_awburst = sp_awburst[8*2 +: 2];
    assign M08_AXI_awvalid = sp_awvalid[8];
    assign sp_awready[8] = M08_AXI_awready;
    assign M08_AXI_wdata = sp_wdata[8*512 +: 256];
    assign M08_AXI_wstrb = sp_wstrb[8*64 +: 32];
    assign M08_AXI_wlast = sp_wlast[8];
    assign M08_AXI_wvalid = sp_wvalid[8];
    assign sp_wready[8] = M08_AXI_wready;
    assign sp_bid[8*4 +: 4] = M08_AXI_bid;
    assign sp_bresp[8*2 +: 2] = M08_AXI_bresp;
    assign sp_bvalid[8] = M08_AXI_bvalid;
    assign M08_AXI_bready = sp_bready[8];
    assign M08_AXI_arid = sp_arid[8*4 +: 4];
    assign M08_AXI_araddr = sp_araddr[8*43 +: 43];
    assign M08_AXI_arlen = sp_arlen[8*8 +: 8];
    assign M08_AXI_arsize = sp_arsize[8*3 +: 3];
    assign M08_AXI_arburst = sp_arburst[8*2 +: 2];
    assign M08_AXI_arvalid = sp_arvalid[8];
    assign sp_arready[8] = M08_AXI_arready;
    assign sp_rid[8*4 +: 4] = M08_AXI_rid;
    assign sp_rdata[8*512 +: 256] = M08_AXI_rdata;
    assign sp_rresp[8*2 +: 2] = M08_AXI_rresp;
    assign sp_rlast[8] = M08_AXI_rlast;
    assign sp_rvalid[8] = M08_AXI_rvalid;
    assign M08_AXI_rready = sp_rready[8];

    assign M09_AXI_awid = sp_awid[9*4 +: 4];
    assign M09_AXI_awaddr = sp_awaddr[9*43 +: 43];
    assign M09_AXI_awlen = sp_awlen[9*8 +: 8];
    assign M09_AXI_awsize = sp_awsize[9*3 +: 3];
    assign M09_AXI_awburst = sp_awburst[9*2 +: 2];
    assign M09_AXI_awvalid = sp_awvalid[9];
    assign sp_awready[9] = M09_AXI_awready;
    assign M09_AXI_wdata = sp_wdata[9*512 +: 32];
    assign M09_AXI_wstrb = sp_wstrb[9*64 +: 4];
    assign M09_AXI_wlast = sp_wlast[9];
    assign M09_AXI_wvalid = sp_wvalid[9];
    assign sp_wready[9] = M09_AXI_wready;
    assign sp_bid[9*4 +: 4] = M09_AXI_bid;
    assign sp_bresp[9*2 +: 2] = M09_AXI_bresp;
    assign sp_bvalid[9] = M09_AXI_bvalid;
    assign M09_AXI_bready = sp_bready[9];
    assign M09_AXI_arid = sp_arid[9*4 +: 4];
    assign M09_AXI_araddr = sp_araddr[9*43 +: 43];
    assign M09_AXI_arlen = sp_arlen[9*8 +: 8];
    assign M09_AXI_arsize = sp_arsize[9*3 +: 3];
    assign M09_AXI_arburst = sp_arburst[9*2 +: 2];
    assign M09_AXI_arvalid = sp_arvalid[9];
    assign sp_arready[9] = M09_AXI_arready;
    assign sp_rid[9*4 +: 4] = M09_AXI_rid;
    assign sp_rdata[9*512 +: 32] = M09_AXI_rdata;
    assign sp_rresp[9*2 +: 2] = M09_AXI_rresp;
    assign sp_rlast[9] = M09_AXI_rlast;
    assign sp_rvalid[9] = M09_AXI_rvalid;
    assign M09_AXI_rready = sp_rready[9];

    assign M10_AXI_awaddr = sp_awaddr[10*43 +: 43];
    assign M10_AXI_awvalid = sp_awvalid[10];
    assign sp_awready[10] = M10_AXI_awready;
    assign M10_AXI_wdata = sp_wdata[10*512 +: 32];
    assign M10_AXI_wstrb = sp_wstrb[10*64 +: 4];
    assign M10_AXI_wvalid = sp_wvalid[10];
    assign sp_wready[10] = M10_AXI_wready;
    assign sp_bid[10*4 +: 4] = 4'd0;
    assign sp_bresp[10*2 +: 2] = M10_AXI_bresp;
    assign sp_bvalid[10] = M10_AXI_bvalid;
    assign M10_AXI_bready = sp_bready[10];
    assign M10_AXI_araddr = sp_araddr[10*43 +: 43];
    assign M10_AXI_arvalid = sp_arvalid[10];
    assign sp_arready[10] = M10_AXI_arready;
    assign sp_rid[10*4 +: 4] = 4'd0;
    assign sp_rdata[10*512 +: 32] = M10_AXI_rdata;
    assign sp_rresp[10*2 +: 2] = M10_AXI_rresp;
    assign sp_rlast[10] = 1'b1;
    assign sp_rvalid[10] = M10_AXI_rvalid;
    assign M10_AXI_rready = sp_rready[10];

    assign M11_AXI_awaddr = sp_awaddr[11*43 +: 43];
    assign M11_AXI_awvalid = sp_awvalid[11];
    assign sp_awready[11] = M11_AXI_awready;
    assign M11_AXI_wdata = sp_wdata[11*512 +: 32];
    assign M11_AXI_wstrb = sp_wstrb[11*64 +: 4];
    assign M11_AXI_wvalid = sp_wvalid[11];
    assign sp_wready[11] = M11_AXI_wready;
    assign sp_bid[11*4 +: 4] = 4'd0;
    assign sp_bresp[11*2 +: 2] = M11_AXI_bresp;
    assign sp_bvalid[11] = M11_AXI_bvalid;
    assign M11_AXI_bready = sp_bready[11];
    assign M11_AXI_araddr = sp_araddr[11*43 +: 43];
    assign M11_AXI_arvalid = sp_arvalid[11];
    assign sp_arready[11] = M11_AXI_arready;
    assign sp_rid[11*4 +: 4] = 4'd0;
    assign sp_rdata[11*512 +: 32] = M11_AXI_rdata;
    assign sp_rresp[11*2 +: 2] = M11_AXI_rresp;
    assign sp_rlast[11] = 1'b1;
    assign sp_rvalid[11] = M11_AXI_rvalid;
    assign M11_AXI_rready = sp_rready[11];

    assign M12_AXI_awid = sp_awid[12*4 +: 4];
    assign M12_AXI_awaddr = sp_awaddr[12*43 +: 43];
    assign M12_AXI_awlen = sp_awlen[12*8 +: 8];
    assign M12_AXI_awsize = sp_awsize[12*3 +: 3];
    assign M12_AXI_awburst = sp_awburst[12*2 +: 2];
    assign M12_AXI_awvalid = sp_awvalid[12];
    assign sp_awready[12] = M12_AXI_awready;
    assign M12_AXI_wdata = sp_wdata[12*512 +: 256];
    assign M12_AXI_wstrb = sp_wstrb[12*64 +: 32];
    assign M12_AXI_wlast = sp_wlast[12];
    assign M12_AXI_wvalid = sp_wvalid[12];
    assign sp_wready[12] = M12_AXI_wready;
    assign sp_bid[12*4 +: 4] = M12_AXI_bid;
    assign sp_bresp[12*2 +: 2] = M12_AXI_bresp;
    assign sp_bvalid[12] = M12_AXI_bvalid;
    assign M12_AXI_bready = sp_bready[12];
    assign M12_AXI_arid = sp_arid[12*4 +: 4];
    assign M12_AXI_araddr = sp_araddr[12*43 +: 43];
    assign M12_AXI_arlen = sp_arlen[12*8 +: 8];
    assign M12_AXI_arsize = sp_arsize[12*3 +: 3];
    assign M12_AXI_arburst = sp_arburst[12*2 +: 2];
    assign M12_AXI_arvalid = sp_arvalid[12];
    assign sp_arready[12] = M12_AXI_arready;
    assign sp_rid[12*4 +: 4] = M12_AXI_rid;
    assign sp_rdata[12*512 +: 256] = M12_AXI_rdata;
    assign sp_rresp[12*2 +: 2] = M12_AXI_rresp;
    assign sp_rlast[12] = M12_AXI_rlast;
    assign sp_rvalid[12] = M12_AXI_rvalid;
    assign M12_AXI_rready = sp_rready[12];

    assign M13_AXI_awid = sp_awid[13*4 +: 4];
    assign M13_AXI_awaddr = sp_awaddr[13*43 +: 43];
    assign M13_AXI_awlen = sp_awlen[13*8 +: 8];
    assign M13_AXI_awsize = sp_awsize[13*3 +: 3];
    assign M13_AXI_awburst = sp_awburst[13*2 +: 2];
    assign M13_AXI_awvalid = sp_awvalid[13];
    assign sp_awready[13] = M13_AXI_awready;
    assign M13_AXI_wdata = sp_wdata[13*512 +: 32];
    assign M13_AXI_wstrb = sp_wstrb[13*64 +: 4];
    assign M13_AXI_wlast = sp_wlast[13];
    assign M13_AXI_wvalid = sp_wvalid[13];
    assign sp_wready[13] = M13_AXI_wready;
    assign sp_bid[13*4 +: 4] = M13_AXI_bid;
    assign sp_bresp[13*2 +: 2] = M13_AXI_bresp;
    assign sp_bvalid[13] = M13_AXI_bvalid;
    assign M13_AXI_bready = sp_bready[13];
    assign M13_AXI_arid = sp_arid[13*4 +: 4];
    assign M13_AXI_araddr = sp_araddr[13*43 +: 43];
    assign M13_AXI_arlen = sp_arlen[13*8 +: 8];
    assign M13_AXI_arsize = sp_arsize[13*3 +: 3];
    assign M13_AXI_arburst = sp_arburst[13*2 +: 2];
    assign M13_AXI_arvalid = sp_arvalid[13];
    assign sp_arready[13] = M13_AXI_arready;
    assign sp_rid[13*4 +: 4] = M13_AXI_rid;
    assign sp_rdata[13*512 +: 32] = M13_AXI_rdata;
    assign sp_rresp[13*2 +: 2] = M13_AXI_rresp;
    assign sp_rlast[13] = M13_AXI_rlast;
    assign sp_rvalid[13] = M13_AXI_rvalid;
    assign M13_AXI_rready = sp_rready[13];

    assign M14_AXI_awaddr = sp_awaddr[14*43 +: 43];
    assign M14_AXI_awvalid = sp_awvalid[14];
    assign sp_awready[14] = M14_AXI_awready;
    assign M14_AXI_wdata = sp_wdata[14*512 +: 32];
    assign M14_AXI_wstrb = sp_wstrb[14*64 +: 4];
    assign M14_AXI_wvalid = sp_wvalid[14];
    assign sp_wready[14] = M14_AXI_wready;
    assign sp_bid[14*4 +: 4] = 4'd0;
    assign sp_bresp[14*2 +: 2] = M14_AXI_bresp;
    assign sp_bvalid[14] = M14_AXI_bvalid;
    assign M14_AXI_bready = sp_bready[14];
    assign M14_AXI_araddr = sp_araddr[14*43 +: 43];
    assign M14_AXI_arvalid = sp_arvalid[14];
    assign sp_arready[14] = M14_AXI_arready;
    assign sp_rid[14*4 +: 4] = 4'd0;
    assign sp_rdata[14*512 +: 32] = M14_AXI_rdata;
    assign sp_rresp[14*2 +: 2] = M14_AXI_rresp;
    assign sp_rlast[14] = 1'b1;
    assign sp_rvalid[14] = M14_AXI_rvalid;
    assign M14_AXI_rready = sp_rready[14];

    assign M15_AXI_awaddr = sp_awaddr[15*43 +: 43];
    assign M15_AXI_awvalid = sp_awvalid[15];
    assign sp_awready[15] = M15_AXI_awready;
    assign M15_AXI_wdata = sp_wdata[15*512 +: 32];
    assign M15_AXI_wstrb = sp_wstrb[15*64 +: 4];
    assign M15_AXI_wvalid = sp_wvalid[15];
    assign sp_wready[15] = M15_AXI_wready;
    assign sp_bid[15*4 +: 4] = 4'd0;
    assign sp_bresp[15*2 +: 2] = M15_AXI_bresp;
    assign sp_bvalid[15] = M15_AXI_bvalid;
    assign M15_AXI_bready = sp_bready[15];
    assign M15_AXI_araddr = sp_araddr[15*43 +: 43];
    assign M15_AXI_arvalid = sp_arvalid[15];
    assign sp_arready[15] = M15_AXI_arready;
    assign sp_rid[15*4 +: 4] = 4'd0;
    assign sp_rdata[15*512 +: 32] = M15_AXI_rdata;
    assign sp_rresp[15*2 +: 2] = M15_AXI_rresp;
    assign sp_rlast[15] = 1'b1;
    assign sp_rvalid[15] = M15_AXI_rvalid;
    assign M15_AXI_rready = sp_rready[15];

    sb_line4 #(.FW(FW), .AW(AW), .MAXW(MAXW), .MAXID(MAXID), .NM(NM),
               .NQ(4), .PORTW(2), .TAGW(4), .OST(OST),
               .STORE_FWD(STORE_FWD), .LUT_PER_BRAM(LUT_PER_BRAM),
               .TIMEOUT(TIMEOUT), .PIPE(PIPE), .CRED(CRED),
               .LINK_CDC(LINK_CDC), .LINK_FULL(LINK_FULL),
               .OST0(OST0), .OST1(OST1), .OST2(OST2), .OST3(OST3),
               .SFW0(SFW0), .SFW1(SFW1), .SFW2(SFW2), .SFW3(SFW3),
               .LPB0(LPB0), .LPB1(LPB1), .LPB2(LPB2), .LPB3(LPB3),
               .TMO0(TMO0), .TMO1(TMO1), .TMO2(TMO2), .TMO3(TMO3),
               .DSTW_P(DSTW_P), .SEG_OVERRIDE(SEG_OVERRIDE),
               .SEG_BASE_P(SEG_BASE_P), .SEG_MASK_P(SEG_MASK_P),
               .SEG_XLT_P(SEG_XLT_P), .SEG_DST_P(SEG_DST_P),
               .SEG_DPORT_P(SEG_DPORT_P), .SEG_VLD_P(SEG_VLD_P)) u_line (
        .bus_clk0(bus_clk0), .bus_rst0(bus_rst0),
        .bus_clk1(bus_clk1), .bus_rst1(bus_rst1),
        .bus_clk2(bus_clk2), .bus_rst2(bus_rst2),
        .bus_clk3(bus_clk3), .bus_rst3(bus_rst3),
        .clk_ctrl(clk_ctrl), .aresetn_ctrl(aresetn_ctrl),
        .clk_xdma(clk_xdma), .aresetn_xdma(aresetn_xdma),
        .clk_s0(clk_s0), .aresetn_s0(aresetn_s0),
        .clk_s1(clk_s1), .aresetn_s1(aresetn_s1),
        .clk_s2(clk_s2), .aresetn_s2(aresetn_s2),
        .clk_s3(clk_s3), .aresetn_s3(aresetn_s3),
        .clk_ddr0(clk_ddr0), .aresetn_ddr0(aresetn_ddr0),
        .clk_ddr1(clk_ddr1), .aresetn_ddr1(aresetn_ddr1),
        .clk_ddr2(clk_ddr2), .aresetn_ddr2(aresetn_ddr2),
        .clk_ddr3(clk_ddr3), .aresetn_ddr3(aresetn_ddr3),
        .mp_awid(mp_awid), .mp_awaddr(mp_awaddr), .mp_awlen(mp_awlen),
        .mp_awsize(mp_awsize), .mp_awburst(mp_awburst),
        .mp_awvalid(mp_awvalid), .mp_awready(mp_awready),
        .mp_wdata(mp_wdata), .mp_wstrb(mp_wstrb), .mp_wlast(mp_wlast),
        .mp_wvalid(mp_wvalid), .mp_wready(mp_wready),
        .mp_bid(mp_bid), .mp_bresp(mp_bresp), .mp_bvalid(mp_bvalid),
        .mp_bready(mp_bready),
        .mp_arid(mp_arid), .mp_araddr(mp_araddr), .mp_arlen(mp_arlen),
        .mp_arsize(mp_arsize), .mp_arburst(mp_arburst),
        .mp_arvalid(mp_arvalid), .mp_arready(mp_arready),
        .mp_rid(mp_rid), .mp_rdata(mp_rdata), .mp_rresp(mp_rresp),
        .mp_rlast(mp_rlast), .mp_rvalid(mp_rvalid), .mp_rready(mp_rready),
        .sp_awid(sp_awid), .sp_awaddr(sp_awaddr), .sp_awlen(sp_awlen),
        .sp_awsize(sp_awsize), .sp_awburst(sp_awburst),
        .sp_awvalid(sp_awvalid), .sp_awready(sp_awready),
        .sp_wdata(sp_wdata), .sp_wstrb(sp_wstrb), .sp_wlast(sp_wlast),
        .sp_wvalid(sp_wvalid), .sp_wready(sp_wready),
        .sp_bid(sp_bid), .sp_bresp(sp_bresp), .sp_bvalid(sp_bvalid),
        .sp_bready(sp_bready),
        .sp_arid(sp_arid), .sp_araddr(sp_araddr), .sp_arlen(sp_arlen),
        .sp_arsize(sp_arsize), .sp_arburst(sp_arburst),
        .sp_arvalid(sp_arvalid), .sp_arready(sp_arready),
        .sp_rid(sp_rid), .sp_rdata(sp_rdata), .sp_rresp(sp_rresp),
        .sp_rlast(sp_rlast), .sp_rvalid(sp_rvalid), .sp_rready(sp_rready),
        .stat_decerr(stat_decerr)
    );
endmodule

`default_nettype wire
